src/objects/Account_Team__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team</relationshipLabel>
        <relationshipName>Account_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>客户小组</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Account Team No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/AddAccountTeamUpdateAccountShareTest.cls
@istest(seealldata=true)
public class AddAccountTeamUpdateAccountShareTest {
    public static testmethod void testAddAccountTeamUpdateAccountShare() {
    
        List<User> u = [select id from User where IsActive = true limit 2];
        Account a = [select id from Account limit 1];
        Account_Team__c at = new Account_Team__c(); 
        at.Team_Member__c = u[0].id;
        at.Account__c = a.id;
        Account_Team__c at1 = new Account_Team__c(); 
        at1.Team_Member__c = u[1].id;
        at1.Account__c = a.id;

        insert at;
        insert at1;
    }
}