src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IPMS_BUs__c</fullName>
        <label>IPMS BU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Distributor</fullName>
        <active>true</active>
        <label>Distributor</label>
    </recordTypes>
    <recordTypes>
        <fullName>End_User</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reseller</fullName>
        <active>true</active>
        <label>Reseller</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>IPMS_BU__c</fullName>
        <label>IPMS BU</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEC</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>WW</fullName>
                </value>
                <value>
                    <fullName>SEA</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>PS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/IPMSAccountUpdateBUCon.cls
public class IPMSAccountUpdateBUCon {
    public static void updateIPMSBU(List<Account> accList){
        if(null != accList && accList.size()>0){
            Set<Id> userId = new Set<Id>();
            for(Account acc:accList){
                userId.add(acc.OwnerId);
            }
            List<User> userList = [SELECT Id,IPMS_BU__c FROM User WHERE Id in:userId];
            List<RecordType> rtList = [SELECT Id,DeveloperName FROM RecordType WHERE SobjectType = 'Account'];
            Map<Id,User> userMap = new Map<Id,User>(userList);
            Map<Id,RecordType> rtMap =  new Map<Id,RecordType>(rtList);
            Set<String> strSet = new Set<String>{'Distributor','Reseller','End_User'};
                for(Account acc:accList){      
                    if(strSet.contains(rtMap.get(acc.RecordTypeId).DeveloperName)){
                        acc.IPMS_BUs__c = userMap.get(acc.OwnerId).IPMS_BU__c;
                    }
                  }
              }
         }
    }