src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SU__c</fullName>
        <label>SU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACQ</fullName>
                </value>
                <value>
                    <fullName>CME</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>FSI</fullName>
                </value>
                <value>
                    <fullName>GPC</fullName>
                </value>
                <value>
                    <fullName>GpComm</fullName>
                </value>
                <value>
                    <fullName>H3C</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Non-Named</fullName>
                </value>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>Utility</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>CME-MTUM</fullName>
                </value>
                <value>
                    <fullName>CME-Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Team__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only</fullName>
                    <default>true</default>
                    <label>Read Only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team</relationshipLabel>
        <relationshipName>Account_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only</fullName>
                    <default>true</default>
                    <label>Read Only</label>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>客户小组</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Account Team No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <label>Opportunity ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source_Leads_ID__c</fullName>
        <label>Source Leads ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Hardware</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>HW Sales</description>
        <label>Hardware</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/UpdateH3COpportunityIDTest.cls
@istest(seealldata=false)
public class UpdateH3COpportunityIDTest {
    /**public static testmethod void testUpdateH3COpportunityID() {
    
        List<User> u = [select id from User where IsActive = true and profile.name <> 'System Administrator' limit 2];
        Id rtoid = [select id from recordType where name = 'Hardware' and SobjectType = 'opportunity' limit 1].id;
        Id rtaid = [select id from recordType where name = 'Customer' and SobjectType = 'account' limit 1].id;
        
        Account a = new Account();
        a.SU__c = 'ACQ';
        a.recordTypeId = rtaid;
        a.name = 'test';
        insert a;
        
        Account_Team__c at = new Account_Team__c();
        at.Account__c = a.id;
        at.Team_Member__c = u[0].id;
        at.Account_Access__c = 'Read Only';
        at.Opportunity_Access__c = 'Read Only';
        insert at;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = a.id;
        opp.ownerId = u[0].id;
        opp.Name = 'test';
        opp.StageName = '01 - Understand Customer';
        opp.CloseDate = date.today();
        opp.recordtypeId = rtoid;
        insert opp;
        Opportunity opptest = [select id,Opportunity_ID__c from Opportunity where id = :opp.id];
        String tmp = '';
        String count = String.valueof(Integer.valueof(opptest.Opportunity_ID__c.right(4)) + 1);
        if(count.length() == 1){
            tmp = '000'+count;
        }else if(count.length() == 2){
            tmp = '00'+count;
        }else if(count.length() == 3){
            tmp = '0'+count;
        }else{
            tmp = count;
        }
        opptest.Opportunity_ID__c =opptest.Opportunity_ID__c.substring(0, opptest.Opportunity_ID__c.length() - 4) + tmp ;       
        update opptest;
        
        Opportunity opp1 = new Opportunity();
        opp1.AccountId = a.id;
        opp1.ownerId = u[0].id;
        opp1.Name = 'test';
        opp1.StageName = '01 - Understand Customer';
        opp1.CloseDate = date.today();
        opp1.Source_Leads_ID__c = null;
        opp1.Opportunity_ID__c = 'H3C-201601010001';
        insert opp1;
    }*/
}