src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Legacy-Backlog</fullName>
                </value>
                <value>
                    <fullName>Requested by Sales</fullName>
                </value>
                <value>
                    <fullName>Requested by Marketing</fullName>
                </value>
                <value>
                    <fullName>Converted from Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>UL @ibreakingpoint 20151027</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Qualifier__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Lead Qualifier</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <description>UL @ibreakingpoint 20151112 for Report, 18 changed</description>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
                <value>
                    <fullName>Reassign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prointerest_Quntity__c</fullName>
        <label>Prointerest_Quntity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timeframe_to_Buy__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Timeframe to Buy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;1 week</fullName>
                </value>
                <value>
                    <fullName>&lt;1 month</fullName>
                </value>
                <value>
                    <fullName>1-3 month</fullName>
                </value>
                <value>
                    <fullName>4-6 month</fullName>
                </value>
                <value>
                    <fullName>7-9month</fullName>
                </value>
                <value>
                    <fullName>10-12month</fullName>
                </value>
                <value>
                    <fullName>&gt;12month</fullName>
                </value>
                <value>
                    <fullName>Unclear</fullName>
                </value>
                <value>
                    <fullName>No Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/LeadUpdateTest.cls
@istest(seealldata=true)
public class LeadUpdateTest {
    public static testmethod void testLeadUpdate1() { 
        
        account acc = new account();
        acc.name = 'BP-test';
        acc.Data_Source__c = 'Converted from Marketing';
        insert acc;

        lead ld = new lead();
        ld.Account__c = acc.id;
        ld.Company = 'BP'; 
        ld.LastName= 'Bay';
        ld.Phone = '13911111234';
        ld.Lead_Qualifier__c='123456@qq.com';
        ld.Timeframe_to_Buy__c = '<1 week';
        ld.Budget__c = 'yes';
        ld.Prointerest_Quntity__c = 1;
        insert ld;
        
        user u = [select id,email from user where IsActive = true limit 1];
        u.email = '123456@qq.com';
        update u;
        
        ld.Lead_Status__c = 'Reject';
        update ld;
    }
    
    public static testmethod void testLeadUpdate2() { 
        
        account acc = new account();
        acc.name = 'BP-test';
        acc.Data_Source__c = 'Converted from Marketing';
        insert acc;

        lead ld = new lead();
        ld.Account__c = acc.id;
        ld.Company = 'BP'; 
        ld.LastName= 'Bay';
        ld.Phone = '13911111234';
        //ld.Lead_Qualifier__c='123456@qq.com';
        ld.Timeframe_to_Buy__c = '<1 week';
        ld.Budget__c = 'yes';
        ld.Prointerest_Quntity__c = 1;
        insert ld;

        ld.Lead_Status__c = 'Reject';
        update ld;
    }
}