src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Alliance_and_Channel_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Alliance and Channel Partner</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Alliance and Channel Partner</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partner</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Account_Role__c</fullName>
        <label>Partner Account Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Implementer</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Outsourcer</fullName>
                </value>
                <value>
                    <fullName>Referral/Agent</fullName>
                </value>
                <value>
                    <fullName>Prime</fullName>
                </value>
                <value>
                    <fullName>Sub</fullName>
                </value>
                <value>
                    <fullName>Co-Seller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alliance Partner</fullName>
                </value>
                <value>
                    <fullName>Channel Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account record type = Partner</description>
        <label>Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Alliance and Channel Partner</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sourced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sourced</label>
        <type>Checkbox</type>
    </fields>
    <label>业务机会合作伙伴</label>
    <nameField>
        <displayFormat>ACP-{000000}</displayFormat>
        <label>A&amp;C Partner No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Location__c.object
<CustomObject>
    <label>地区</label>
    <nameField>
        <label>Locator ID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/AddAllianceChannelPartnerControllerTest.cls
@istest(seealldata=true)
public class AddAllianceChannelPartnerControllerTest {
    public static testmethod void testAddAllianceChannelPartnerController01() {      
        account a = [select id from account limit 1];
        Location__c l = [select id,name from Location__c limit 1];
        Opportunity o = [select id from Opportunity limit 1];
        PageReference aa = Page.AddAllianceAndChannelPartner;
        Test.setCurrentPage(aa);
        String str = '(channelPartnerClass:[BusinessRelationship=business Relationship, PartnerNm=BP test, channelPartner=Alliance_and_Channel_Partner__c:{Opportunity__c=006N00000076wUCIAY, Partner_Type__c=Alliance Partner, Primary__c=true, Sourced__c=true, Partner__c=001N000000ZM7IbIAL, Partner_Account_Role__c=Implementer})';
        Apexpages.currentpage().getparameters().put('oppId' , o.id);
        Apexpages.currentpage().getparameters().put('ptype' , 'Alliance Partner');
        Apexpages.currentpage().getparameters().put('local' , l.name);
        Apexpages.currentpage().getparameters().put('actId' , a.id);
        Apexpages.currentpage().getparameters().put('br' , 'test');
        Apexpages.currentpage().getparameters().put('pl' , str);
        //Apexpages.currentpage().getparameters().put('logicNum' , '0');
        string actIdStr = '{'+a.id+'}';
        Apexpages.currentpage().getparameters().put('actIdStr' ,actIdStr);

        Alliance_and_Channel_Partner__c acp = new Alliance_and_Channel_Partner__c();
        acp.Location__c = l.id;
        acp.Opportunity__c = o.id;
        acp.Partner__c = a.id;
        
        AddAllianceAndChannelPartnerController aaacpc = new AddAllianceAndChannelPartnerController(new ApexPages.StandardController(acp));
        AddAllianceAndChannelPartnerController.channelPartnerClass accc = new AddAllianceAndChannelPartnerController.channelPartnerClass();
        aaacpc.partnerList.add(accc);
    }
    
    public static testmethod void testAddAllianceChannelPartnerController02() {      
        account a = [select id from account where recordType.name = 'partner' limit 1];
        Location__c l = [select id,name from Location__c limit 1];
        Opportunity o = [select id from Opportunity limit 1];
        PageReference aa = Page.AddAllianceAndChannelPartner;
        Test.setCurrentPage(aa);
        String str = '(channelPartnerClass:[BusinessRelationship=business Relationship, PartnerNm=BP test, channelPartner=Alliance_and_Channel_Partner__c:{Opportunity__c=006N00000076wUCIAY, Partner_Type__c=Alliance Partner, Partner__c=001N000000ZM7IbIAL, Partner_Account_Role__c=Influencer, Primary__c=true, Sourced__c=true}, logicNum=0, partnerLocation=testWang],';
        Apexpages.currentpage().getparameters().put('oppId' , o.id);
        Apexpages.currentpage().getparameters().put('ptype' , 'Alliance Partner');
        Apexpages.currentpage().getparameters().put('local' , l.name);
        Apexpages.currentpage().getparameters().put('actId' , a.id);
        Apexpages.currentpage().getparameters().put('br' , 'test');
        Apexpages.currentpage().getparameters().put('pl' , str);
        Apexpages.currentpage().getparameters().put('logicNum' , '0');
        string actIdStr = '{'+a.id+'}';
        Apexpages.currentpage().getparameters().put('actIdStr' ,actIdStr);

        Alliance_and_Channel_Partner__c acp = new Alliance_and_Channel_Partner__c();
        acp.Location__c = l.id;
        acp.Opportunity__c = o.id;
        acp.Partner__c = a.id;
        
        AddAllianceAndChannelPartnerController aaacpc = new AddAllianceAndChannelPartnerController(new ApexPages.StandardController(acp));
        AddAllianceAndChannelPartnerController.channelPartnerClass accc = new AddAllianceAndChannelPartnerController.channelPartnerClass();
        accc.channelPartner.Partner__c = a.id;
        accc.channelPartner.Partner_Account_Role__c = 'Influencer';
        accc.channelPartner.Partner_Type__c = 'Alliance Partner';
        aaacpc.partnerList.add(accc);
        aaacpc.save();
        aaacpc.ShowLookup();
        aaacpc.Cancel();
        
    }
}