src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Team__c.object
<CustomObject>
    <fields>
        <fullName>Account_Access__c</fullName>
        <label>Account Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only</fullName>
                    <default>true</default>
                    <label>Read Only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team</relationshipLabel>
        <relationshipName>Account_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Access__c</fullName>
        <label>Opportunity Access</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Read Only</fullName>
                    <default>true</default>
                    <label>Read Only</label>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>客户小组</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Account Team No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Source_Leads_ID__c</fullName>
        <label>Source Leads ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/OwnerContainsAccountTeamTest.cls
@istest(seealldata=true)
public class OwnerContainsAccountTeamTest {
    public static testmethod void testOwnerContainsAccountTeam1() {
    
        List<User> u = [select id from User where IsActive = true and profile.name <> 'System Administrator' limit 2];
        List<account> acc = [select id from account limit 1];
        
        Account_Team__c at = new Account_Team__c();
        at.Account__c = acc[0].id;
        at.Team_Member__c = u[0].id;
        at.Account_Access__c = 'Read Only';
        at.Opportunity_Access__c = 'Read Only';
        insert at;
        
        Opportunity opp = new Opportunity();
        //opp.AccountId = acc[0].id;
        opp.ownerId = u[0].id;
        opp.Name = 'test';
        opp.StageName = '01 - Understand Customer';
        opp.CloseDate = date.today();
        opp.Source_Leads_ID__c = null;
        insert opp;

    }
}