src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>CSC_FST_Service_Request</fullName>
        <active>true</active>
        <businessProcess>CSC %26 FST Service Request</businessProcess>
        <label>05-CSC &amp; FST Service Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Choose_Address__c</fullName>
        <label>Choose Address</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>User Entry</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Same business day</fullName>
                </value>
                <value>
                    <fullName>Next business day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Priority__c</fullName>
        <label>Delivery Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>50-SBD</fullName>
                </value>
                <value>
                    <fullName>94-SBD</fullName>
                </value>
                <value>
                    <fullName>95-NBD</fullName>
                </value>
                <value>
                    <fullName>96-NBD</fullName>
                </value>
                <value>
                    <fullName>97-Trade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IGSO_City__c</fullName>
        <label>IGSO_City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IGSO_Line1__c</fullName>
        <label>IGSO_Line1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IGSO_Line2__c</fullName>
        <label>IGSO_Line2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IGSO_State_Province__c</fullName>
        <label>IGSO_State_Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IGSO_Zip_Postal_Code__c</fullName>
        <label>IGSO_Zip_Postal_Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Reason__c</fullName>
        <label>Order Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>615-Customer Self Repair</fullName>
                </value>
                <value>
                    <fullName>5AU-Service Advanced Exchange</fullName>
                </value>
                <value>
                    <fullName>575-DRP when SAP R/3&amp;APO Down</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Condition__c</fullName>
        <label>Shipping Condition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EX-Same Business day</fullName>
                </value>
                <value>
                    <fullName>02-Next Business day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <label>Work Order Name</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>OrderToWorkOrder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_GSEM_GetCasesByQueueNameTest.cls
@isTest
private class CSC_GSEM_GetCasesByQueueNameTest {

    //输入
    public class Appinput{
        public String queueName;
    }

    private static List<RecordType> rtList = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Case' AND DeveloperName = 'CSC_FST_Service_Request']; 
    
    static testMethod void testMethod1() {
        Appinput input = new Appinput();
        input.queueName = 'CNA-PR-SCM_ISSG_SERVER';
        
        Account a = TestUtil.getAccount('中国移动'); 
        system.debug('aaaaaaaa:' + a.Id);
        Contact cc = TestUtil.getContact('test',a.Id);
        system.debug('ccccccc:' + cc.Id);
        Entitlement e = TestUtil.getInsertEntitlement(a.Id);
        system.debug('eeeeeee:' + e.Id);
        Case caseInfo = TestUtil.getCase(a.Id,cc.Id,e.Id,userInfo.getUserId());
        //TestUtil.GetPartsOrder(caseInfo.Id,e.Id,a.Id,cc.Id);
        //TestUtil.getTask(caseInfo.Id);

        Workorder w = ElevationToHPEComponentTest.GetWorkOrder(caseInfo.Id);
        Order__c o = getOrder(w.Id);
        //getPart(o.Id);

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(input);
        System.debug('reqJson = ' + reqJson);
        req.requestBody = Blob.valueof(reqJson);
        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/GetCasesByQueueName/';  
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        test.startTest(); 
        CSC_GSEM_GetCasesByQueueName.doPost();
        test.stopTest();
    }

    public static Order__c getOrder(String wId){
        Order__c o = new Order__c();
        o.Work_Order_Name__c = wId;
        o.Order_Reason__c = '615-Customer Self Repair';
        o.Delivery_Priority__c = '50-SBD';
        o.Shipping_Condition__c = '02-Next Business day';
        o.Choose_Address__c = 'Customer';
        o.Order_Number__c = '63984759575';
        o.IGSO_Line1__c = 'shanghai';
        o.IGSO_Line2__c = 'zhejiang';
        o.IGSO_City__c = 'shanghai';
        o.IGSO_State_Province__c = 'zhemnt';
        o.IGSO_Zip_Postal_Code__c = '2000001';
        insert o;
    
        return o;    
      }
}