src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>New_Account_Name__c</fullName>
        <label>New Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <label>Scenario</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Create Opportunity Account in SFDC</fullName>
                </value>
                <value>
                    <fullName>Create Order Account in CRS</fullName>
                </value>
                <value>
                    <fullName>Create Account in both SFDC and CRS</fullName>
                </value>
                <value>
                    <fullName>Create Marketing Account</fullName>
                </value>
                <value>
                    <fullName>Create Upfront Account</fullName>
                </value>
                <value>
                    <fullName>Create ROP Account</fullName>
                </value>
                <value>
                    <fullName>Update Account Name</fullName>
                </value>
                <value>
                    <fullName>Update Account Address</fullName>
                </value>
                <value>
                    <fullName>Update Account Attributes</fullName>
                </value>
                <value>
                    <fullName>Merge Accounts</fullName>
                </value>
                <value>
                    <fullName>Transfer Account</fullName>
                </value>
                <value>
                    <fullName>Request One Time Order</fullName>
                </value>
                <value>
                    <fullName>Add/Update Sales</fullName>
                </value>
                <value>
                    <fullName>SCP Access</fullName>
                </value>
                <value>
                    <fullName>Partner Related</fullName>
                </value>
                <value>
                    <fullName>Have Problem Accessing SFDC</fullName>
                </value>
                <value>
                    <fullName>Create a New User</fullName>
                </value>
                <value>
                    <fullName>Deactive User</fullName>
                </value>
                <value>
                    <fullName>Change Role</fullName>
                </value>
                <value>
                    <fullName>Add/Change Sales Territory</fullName>
                </value>
                <value>
                    <fullName>Batch Update</fullName>
                </value>
                <value>
                    <fullName>Claim Request</fullName>
                </value>
                <value>
                    <fullName>Query Request</fullName>
                </value>
                <value>
                    <fullName>Bidding</fullName>
                </value>
                <value>
                    <fullName>Other Issues</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/RewriteCaseNewEditTest.cls
@istest
public class RewriteCaseNewEditTest {
    public static testmethod void testRewriteCaseNewEdit() {
        String rtid = [select id from recordtype where sobjecttype = 'Case' and name != '01-Account Request' limit 1].id;
        Case cs1 = new Case(Subject = 'test1' , recordtypeid = rtid, Reason = 'Customer - Create a new account', New_Account_Name__c = '1', 
        Scenario__c = 'Create Opportunity Account in SFDC');
        insert cs1;
        RewriteCaseNewEdit cscon1 = new RewriteCaseNewEdit(new ApexPages.StandardController(cs1));
        cscon1.whetherrror = true;
        cscon1.blnwhetheracctrqstrt = true;
        cscon1.accnameAddError = 'Required';
        cscon1.newaccnameAddError = 'Required';
        cscon1.newaccengnameAddError = 'Required';
        cscon1.l1accAddError = 'Required';
        cscon1.l1engaccAddError = 'Required';
        cscon1.suAddError = 'Required';
        cscon1.dtaAddError = 'Required';
        cscon1.industryAddError = 'Required';
        cscon1.subindustryAddError = 'Required';
        cscon1.provinceAddError = 'Required';
        cscon1.cityAddError = 'Required';
        cscon1.billstreetAddError = 'Required';
        cscon1.billzipposcodeAddError = 'Required';
        cscon1.team1AddError = 'Required';
        cscon1.team2AddError = 'Required';
        cscon1.team3AddError = 'Required';
        cscon1.team4AddError = 'Required';
        cscon1.team5AddError = 'Required';
        cscon1.descriptionAddError = 'Required';
        cscon1.firstnameError = 'Required';
        cscon1.lastnameError = 'Required';
        cscon1.phoneError = 'Required';
        cscon1.saveAllrecord();   
        cscon1.whetherrror = true;
        cscon1.accnameAddError = 'Blank';
        cscon1.newaccnameAddError = 'Blank';
        cscon1.newaccengnameAddError = 'Blank';
        cscon1.l1accAddError = 'Blank';
        cscon1.l1engaccAddError = 'Blank';
        cscon1.suAddError = 'Blank';
        cscon1.dtaAddError = 'Blank';
        cscon1.industryAddError = 'Blank';
        cscon1.subindustryAddError = 'Blank';
        cscon1.provinceAddError = 'Blank';
        cscon1.cityAddError = 'Blank';
        cscon1.billstreetAddError = 'Blank';
        cscon1.billzipposcodeAddError = 'Blank';
        cscon1.team1AddError = 'Blank';
        cscon1.team2AddError = 'Blank';
        cscon1.team3AddError = 'Blank';
        cscon1.team4AddError = 'Blank';
        cscon1.team5AddError = 'Blank';
        cscon1.descriptionAddError = 'Blank';
        cscon1.saveAllrecord();   
        //
        Case cs2 = new Case(Subject = 'test2' , recordtypeid = rtid);
        insert cs2;
        RewriteCaseNewEdit cscon2 = new RewriteCaseNewEdit(new ApexPages.StandardController(cs2));
        Attachment attachtest1 = new Attachment();    
        attachtest1.Name='testattach1';
        Blob testattachbody1 = Blob.valueOf('testattachbody1');
        attachtest1.body = testattachbody1;
        attachtest1.parentId = cs2.id;
        Attachment attachtest2 = cscon2.athmt;
        cscon2.athmt = attachtest1;
        cscon2.athmtls.add(attachtest1);
        cscon2.saveAllrecord();       
    }    
}