src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Legacy-Backlog</fullName>
                </value>
                <value>
                    <fullName>Requested by Sales</fullName>
                </value>
                <value>
                    <fullName>Requested by Marketing</fullName>
                </value>
                <value>
                    <fullName>Converted from Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L1_Account__c</fullName>
        <label>L1 Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L1_English_Account__c</fullName>
        <label>L1 English Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDM_ID__c</fullName>
        <externalId>true</externalId>
        <label>MDM ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SU__c</fullName>
        <label>SU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACQ</fullName>
                </value>
                <value>
                    <fullName>CME</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>FSI</fullName>
                </value>
                <value>
                    <fullName>GPC</fullName>
                </value>
                <value>
                    <fullName>GpComm</fullName>
                </value>
                <value>
                    <fullName>H3C</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Non-Named</fullName>
                </value>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>Utility</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>CME-MTUM</fullName>
                </value>
                <value>
                    <fullName>CME-Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Function__c</fullName>
        <label>Job Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Decision Office</fullName>
                </value>
                <value>
                    <fullName>Finance &amp; Procurement</fullName>
                </value>
                <value>
                    <fullName>IT department</fullName>
                </value>
                <value>
                    <fullName>Line of Business</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Level__c</fullName>
        <label>Job Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>C Level</fullName>
                </value>
                <value>
                    <fullName>Executive</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>L1_Account__c</fullName>
        <label>L1 Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>L1_English_Account__c</fullName>
        <label>L1 English Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Account_English_Name__c</fullName>
        <label>New Account English Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Account_Name__c</fullName>
        <label>New Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <label>Scenario</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Create Opportunity Account in SFDC</fullName>
                </value>
                <value>
                    <fullName>Create Order Account in CRS</fullName>
                </value>
                <value>
                    <fullName>Create Account in both SFDC and CRS</fullName>
                </value>
                <value>
                    <fullName>Create Marketing Account</fullName>
                </value>
                <value>
                    <fullName>Create Upfront Account</fullName>
                </value>
                <value>
                    <fullName>Create ROP Account</fullName>
                </value>
                <value>
                    <fullName>Update Account Name</fullName>
                </value>
                <value>
                    <fullName>Update Account Address</fullName>
                </value>
                <value>
                    <fullName>Update Account Attributes</fullName>
                </value>
                <value>
                    <fullName>Merge Accounts</fullName>
                </value>
                <value>
                    <fullName>Transfer Account</fullName>
                </value>
                <value>
                    <fullName>Request One Time Order</fullName>
                </value>
                <value>
                    <fullName>Add/Update Sales</fullName>
                </value>
                <value>
                    <fullName>SCP Access</fullName>
                </value>
                <value>
                    <fullName>Partner Related</fullName>
                </value>
                <value>
                    <fullName>Have Problem Accessing SFDC</fullName>
                </value>
                <value>
                    <fullName>Create a New User</fullName>
                </value>
                <value>
                    <fullName>Deactive User</fullName>
                </value>
                <value>
                    <fullName>Change Role</fullName>
                </value>
                <value>
                    <fullName>Add/Change Sales Territory</fullName>
                </value>
                <value>
                    <fullName>Batch Update</fullName>
                </value>
                <value>
                    <fullName>Claim Request</fullName>
                </value>
                <value>
                    <fullName>Query Request</fullName>
                </value>
                <value>
                    <fullName>Bidding</fullName>
                </value>
                <value>
                    <fullName>Other Issues</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TAT_Reason__c</fullName>
        <label>TAT Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account blocked by RPL</fullName>
                </value>
                <value>
                    <fullName>Case logged outside of business hours</fullName>
                </value>
                <value>
                    <fullName>Case misrouted due to requestor</fullName>
                </value>
                <value>
                    <fullName>Case re-opened</fullName>
                </value>
                <value>
                    <fullName>Case logged</fullName>
                </value>
                <value>
                    <fullName>Data flow issue- D&amp;B to MDM/MDCP</fullName>
                </value>
                <value>
                    <fullName>Delay in feedback by Approver</fullName>
                </value>
                <value>
                    <fullName>Delay in feedback by Requestor</fullName>
                </value>
                <value>
                    <fullName>Multiple Account request in single case</fullName>
                </value>
                <value>
                    <fullName>System downtime- MDM/MDCP</fullName>
                </value>
                <value>
                    <fullName>System downtime- SFDC</fullName>
                </value>
                <value>
                    <fullName>System issue</fullName>
                </value>
                <value>
                    <fullName>PRL blocked</fullName>
                </value>
                <value>
                    <fullName>Late reply by requestor</fullName>
                </value>
                <value>
                    <fullName>Late reply by approver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Member_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases_Team_Member_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases_Team_Member_2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member 3</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases_Team_Member_3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member 4</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases_Team_Member_4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member 5</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases_Team_Member_5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member_6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member 6</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WeChat__c</fullName>
        <label>WeChat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/GenerateAccountControllerTest.cls
@istest(seealldata=true)
public class GenerateAccountControllerTest {
    public static testmethod void testGenerateAccountController001() {
        Test.startTest();
        case c = CreateCase();
        c.Reason = 'Customer - Create a new account';
        c.Scenario__c = 'Create Opportunity Account in SFDC';
        update c;
        GenerateAccountController.GenerateAccountController(c.id);
        /*
        account acc = new account();
        acc.name = 'test0001';
        acc.MDM_ID__c = 'MDM-100000001';
        insert acc;
        c.AccountId = acc.id;
        update c;
        GenerateAccountController.GenerateAccountController(c.id);
        
        account ac = [select id from account where id = :c.AccountId];
        ac.MDM_ID__c = '';
        update ac;
        GenerateAccountController.GenerateAccountController(c.id);
        */
        Test.stopTest();
    }

    public static testmethod void testGenerateAccountController001_1() {
        Test.startTest();
        case c = CreateCase();
        c.Reason = 'Customer - Create a new account';
        c.Scenario__c = 'Create Opportunity Account in SFDC';
        update c;
        /*
        GenerateAccountController.GenerateAccountController(c.id);
        */
        account acc = new account();
        acc.name = 'test0001';
        acc.MDM_ID__c = 'MDM-100000001';
        insert acc;
        c.AccountId = acc.id;
        update c;
        GenerateAccountController.GenerateAccountController(c.id);
        /*
        account ac = [select id from account where id = :c.AccountId];
        ac.MDM_ID__c = '';
        update ac;
        GenerateAccountController.GenerateAccountController(c.id);
        */
        Test.stopTest();
    }

    public static testmethod void testGenerateAccountController001_2() {
        Test.startTest();
        case c = CreateCase();
        c.Reason = 'Customer - Create a new account';
        c.Scenario__c = 'Create Opportunity Account in SFDC';
        update c;
        
        //GenerateAccountController.GenerateAccountController(c.id);
        
        account acc = new account();
        acc.name = 'test0001';
        acc.MDM_ID__c = 'MDM-100000001';
        insert acc;
        c.AccountId = acc.id;
        update c;
        /*
        GenerateAccountController.GenerateAccountController(c.id);
        */
        account ac = [select id from account where id = :c.AccountId];
        ac.MDM_ID__c = '';
        update ac;
        GenerateAccountController.GenerateAccountController(c.id);
        
        Test.stopTest();
    }

    public static testmethod void testGenerateAccountController002() {
        Test.startTest();
        case c = CreateCase();
        c.Reason = 'Customer - Create a new account';
        c.Scenario__c = 'Create Marketing Account';
        update c;
        GenerateAccountController.GenerateAccountController(c.id);
        
        account acc = new account();
        acc.name = 'test0001';
        acc.MDM_ID__c = 'MDM-100000001';
        insert acc;
        c.AccountId = acc.id;
        update c;
        GenerateAccountController.GenerateAccountController(c.id);
        
        account ac = [select id from account where id = :c.AccountId];
        ac.MDM_ID__c = '';
        update ac;
        GenerateAccountController.GenerateAccountController(c.id);
        Test.stopTest();
    }
    public static testmethod void testGenerateAccountController003() {
        Test.startTest();
        case c = CreateCase();
        c.Reason = 'Customer - Update an existing account';
        c.Scenario__c = 'Update Account Name';
        account acc = new account();
        acc.name = 'test0001';
        acc.MDM_ID__c = 'MDM-100000001';
        insert acc;
        c.AccountId = acc.id;
        update c;
        GenerateAccountController.GenerateAccountController(c.id);
        account ac = [select id from account where id = :c.AccountId];
        ac.MDM_ID__c = '';
        update ac;
        GenerateAccountController.GenerateAccountController(c.id);
        Test.stopTest();
    }
    public static testmethod void testGenerateAccountController004() {
        Test.startTest();
        case c = CreateCase();
        c.Reason = 'Customer - Update an existing account';
        c.Scenario__c = 'Transfer Account';
        account acc = new account();
        acc.name = 'test0001';
        acc.MDM_ID__c = 'MDM-100000001';
        insert acc;
        c.AccountId = acc.id;
        update c;
        GenerateAccountController.GenerateAccountController(c.id);
        account ac = [select id from account where id = :c.AccountId];
        ac.MDM_ID__c = '';
        update ac;
        GenerateAccountController.GenerateAccountController(c.id);
        Test.stopTest();
    }
    public static testmethod void testGenerateAccountController005() {
        Test.startTest();
        case c = CreateCase();
        c.Reason = 'Customer - Update an existing account';
        c.Scenario__c = 'Request One Time Order';
        account acc = new account();
        acc.name = 'test0001';
        acc.MDM_ID__c = 'MDM-100000001';
        insert acc;
        c.AccountId = acc.id;
        update c;
        GenerateAccountController.GenerateAccountController(c.id);
        account ac = [select id from account where id = :c.AccountId];
        ac.MDM_ID__c = '';
        update ac;
        GenerateAccountController.GenerateAccountController(c.id);
        Test.stopTest();
    }
    public static testmethod void testGenerateAccountController006() {
        Test.startTest();
        case c = CreateCase();
        c.Reason = 'Customer - Update an existing account';
        c.Scenario__c = 'Update Account Address';
        account acc = new account();
        acc.name = 'test0001';
        acc.MDM_ID__c = 'MDM-100000001';
        insert acc;
        c.AccountId = acc.id;
        update c;
        GenerateAccountController.GenerateAccountController(c.id);
        account ac = [select id from account where id = :c.AccountId];
        ac.MDM_ID__c = '';
        update ac;
        GenerateAccountController.GenerateAccountController(c.id);
        Test.stopTest();
    }
    public static testmethod void testGenerateAccountController007() {
        Test.startTest();
        list<Case> c70 = [select id from Case where Reason = 'SCP Admin Support' limit 1];
        if(c70.size() > 0){
            GenerateAccountController.GenerateAccountController(c70[0].id);
        }
        Test.stopTest();
    }
    public static testmethod void testGenerateAccountController008() {
        Test.startTest();
        case c = CreateCase();
        c.Reason = 'Customer - Create a new account';
        c.Scenario__c = 'Create Opportunity Account in SFDC';
        update c;
        List<account> a80 = [select id,name from account where MDM_ID__c != '' and MDM_ID__c != null and Data_Source__c = 'Requested by Marketing' limit 1];
        a80[0].name = c.New_Account_Name__c;
        update a80;
        if(a80.size() > 0){
            GenerateAccountController.GenerateAccountController(c.id);
        }
        Test.stopTest();
    }
    
    public static testmethod case CreateCase(){
        Entitlement e = [select id from Entitlement where name = '01-Account Request Entitlement Process'];
        case c = new case();
        c.status = 'New';
        c.TAT_Reason__c = 'Case logged';
        c.Entitlement = e;
        c.Last_Name__c = 'test';
        c.First_Name__c = 'wang';
        c.Title__c = 'test';
        c.Job_Function__c = 'test';
        c.Job_Level__c = 'test';
        c.Phone__c = '12345678901';
        c.Email__c = '123456@qq.com';
        c.WeChat__c = '1234567';
        c.New_Account_Name__c = 'testGenerateAccount';
        id uid =[select id from user where name = 'Work Flow Adimin' limit 1].id;
        if(uid != null){
            c.Team_Member_1__c = uid;
            c.Team_Member_2__c = uid;
            c.Team_Member_3__c = uid;
            c.Team_Member_4__c = uid;
            c.Team_Member_5__c = uid;
            c.Team_Member_6__c = uid;
        }
        c.New_Account_English_Name__c = 'TEST16021703';
        c.L1_Account__c = '2';
        c.L1_English_Account__c = '2';
        c.SU__c = 'CME';
        c.DTA__c = 'CME';
        c.Province__c = 'Beijing';
        c.City__c = 'Beijing';
        c.Industry__c='公共事业';
        c.Sub_Industry__c='UT-斯达康';
        c.Billing_Zip_Postal_Code__c='100103';
        c.Billing_State_Province__c='beijing';
        c.Billing_City__c='beijing';
        c.Billing_Street__c='chaoyang';
        c.Recordtypeid = '01228000000PMiNAAW'; //01-Account Request add by Lily 2018-4-8
        insert c;
        return c;
    }
}