src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CSC_Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oversea_Country__c</fullName>
        <label>Oversea Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Countrys</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Regions</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Distributor</fullName>
        <active>true</active>
        <label>Distributor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/globalValueSets/Countrys.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>East Timor</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Laos</fullName>
    </customValue>
    <customValue>
        <fullName>Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Maldives</fullName>
    </customValue>
    <customValue>
        <fullName>Myanmar</fullName>
    </customValue>
    <customValue>
        <fullName>Nepal</fullName>
    </customValue>
    <customValue>
        <fullName>Pakistan</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
    </customValue>
    <customValue>
        <fullName>Sri Lanka</fullName>
    </customValue>
    <customValue>
        <fullName>Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Vietnam</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Iceland</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <customValue>
        <fullName>Malta</fullName>
    </customValue>
    <customValue>
        <fullName>South Asia</fullName>
        <isActive>false</isActive>
        <label>South Asia</label>
    </customValue>
    <masterLabel>Countrys</masterLabel>
</GlobalValueSet>

H3CIPMSJAVA-20180830/src/globalValueSets/Regions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>South East Asia</fullName>
        <default>true</default>
        <label>South East Asia</label>
    </customValue>
    <customValue>
        <fullName>Northeast Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Middle Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>South Asia</fullName>
    </customValue>
    <customValue>
        <fullName>West EU</fullName>
    </customValue>
    <customValue>
        <fullName>East EU</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

H3CIPMSJAVA-20180830/src/classes/IPMSAccountUpdateBUConTest.cls
@isTest
public class IPMSAccountUpdateBUConTest {
    @isTest
    static void IPMSAccUpBUConTestMethod(){
        RecordType rt = [SELECT Id FROM RecordType WHERE sobjectType = 'Account' AND DeveloperName = 'Distributor'];
        Account acc = new Account();
        acc.RecordTypeId = rt.Id;
        acc.Name = 'testAccount';
        acc.CSC_Country__c = 'China';
        acc.Region__c = 'South Asia';
        acc.Oversea_Country__c = 'Bangladesh';
        insert acc;
        
    }
}