src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AMID__c</fullName>
        <externalId>true</externalId>
        <label>AMID2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name_Latin_Capture__c</fullName>
        <label>Account Name Latin Capture</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDCP_Business_Relationship_ID__c</fullName>
        <label>MDCP Business Relationship ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDCP_Site_ID__c</fullName>
        <label>MDCP Site ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDCP_Site_Instance_ID__c</fullName>
        <label>MDCP Site Instance ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Alliance_and_Channel_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Alliance and Channel Partner</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partner</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account record type = Partner</description>
        <label>Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Alliance and Channel Partner</relationshipLabel>
        <relationshipName>Alliance_and_Channel_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>业务机会合作伙伴</label>
    <nameField>
        <displayFormat>ACP-{000000}</displayFormat>
        <label>A&amp;C Partner No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Engagement__c</fullName>
        <label>Customer Engagement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>End User Sales</fullName>
                </value>
                <value>
                    <fullName>Alliance</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fulfillment__c</fullName>
        <label>Fulfillment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Customer_Engagement__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>HP Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Channel Fulfilled</fullName>
                </value>
                <value>
                    <fullName>VSI Fulfilled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <label>Opportunity ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <formula>Opportunity.Opportunity_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/EmailNoticetoHPFS.cls
global class EmailNoticetoHPFS {
    /**webservice static String SendOppEmail(Id oppid) {
        Map<String , String> currencycontysymbol = new Map<String , String>{
            'CNY' => '￥',
            'AUD' => 'AUD',
            'CLP' => 'CLP',
            'COP' => 'COP',
            'EUR' => 'EUR',
            'GBP' => 'GBP',
            'JPY' => 'JPY',
            'KZT' => 'KZT',
            'SGD' => 'SGD',
            'USD' => '$',
            'VND' => 'VND'
        };
        
        List<Messaging.Singleemailmessage> listSingleEmailMessages = new List<Messaging.Singleemailmessage>();
        List<Messaging.SendEmailResult> listEmailResult = null;
        List<Alliance_and_Channel_Partner__c> partnerls = new List<Alliance_and_Channel_Partner__c>(); 
        String patrname = '';
        String errmessage = '';
        Opportunity opp = [select id,currencyisocode, Opportunity_ID__c,Accountid,ownerid, name,CloseDate, StageName, ForecastCategoryName, Amount, Description, Customer_Engagement__c, Fulfillment__c 
        from opportunity
        where id = :oppid];
        String oppclosedate = String.valueof(opp.CloseDate);
        String oppamount = currencycontysymbol.get(opp.currencyisocode) + String.valueof(opp.amount);
        partnerls = [select id, Partner__r.Name, Opportunity__c from Alliance_and_Channel_Partner__c where Opportunity__c = :oppid];
        if(partnerls.size() == 1) {
            patrname = partnerls[0].Partner__r.Name;       
        }
        else if(partnerls.size() > 1) {
            for(Integer inpatrnum = 0 ; inpatrnum < partnerls.size() - 1 ; inpatrnum++) {
                patrname = patrname + partnerls[inpatrnum].Partner__r.Name + ',';    
            }
            patrname = patrname + partnerls[partnerls.size() - 1].Partner__r.Name; 
        }
        Account acc = [select id, name, Account_Name_Latin_Capture__c, BillingAddress,BillingCity, BillingCountry, BillingPostalCode, BillingState, 
        BillingStreet, MDCP_Site_ID__c, MDCP_Site_Instance_ID__c, MDCP_Business_Relationship_ID__c,AMID__c from Account where id = :opp.Accountid];
        String accaddress = acc.BillingCity + acc.BillingCountry + acc.BillingPostalCode + acc.BillingState + acc.BillingStreet;
        User ur = [select id, name, Email, Phone, MobilePhone from user where id = :opp.ownerid];
        List<Opportunitylineitem> opltls = new List<Opportunitylineitem>();
        opltls = [select id, product2.name,currencyisocode, quantity, UnitPrice, Subtotal, ServiceDate from opportunitylineitem where opportunityid = :oppid];
        //EmailBody Replace variable in Html Map
        Map<String, String> rplcbdhtmlvrbmap = new Map<String, String>{
            '{!oppownername}' => ur.name,
            '{!accname}' =>acc.name,
            '{!accltname}' =>acc.Account_Name_Latin_Capture__c ,
            '{!accadress}' =>accaddress,
            '{!mdcpid}' =>acc.MDCP_Site_ID__c,
            '{!mdcpinstanceid}' => acc.MDCP_Site_Instance_ID__c,
            '{!mdcprelationid}' => acc.MDCP_Business_Relationship_ID__c,
            '{!accamid}' =>acc.AMID__c,
            '{!uremail}' =>ur.email,
            '{!urphone}' =>ur.phone,
            '{!urmobile}' =>ur.MobilePhone,
            '{!oppid}' =>opp.Opportunity_ID__c,
            '{!oppname}' =>opp.name,
            '{!oppstage}' =>opp.stagename,
            '{!oppfrcategory}' =>opp.ForecastCategoryName,
            '{!oppclosedate}' =>oppclosedate,
            '{!oppamount}' =>oppamount,
            '{!oppdescription}' =>opp.description,
            '{!oppengage}' =>opp.Customer_Engagement__c,
            '{!oppfulfilment}' =>opp.Fulfillment__c,
            '{!opppartnername}' =>patrname           
        }; 
        system.debug('billaddress--' + accaddress);
        system.debug('--?--' + oppamount);
        //Send Email
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] {'hpfs.salesoperations@hpe.com'});
        String sbjt = 'H3C - HPEFS Engagement has been triggered by ' + ur.name;
        mail.setsubject(sbjt);
        EmailTemplate emailTemplate = [SELECT Id, Subject, HtmlValue, Body FROM EmailTemplate WHERE Name = 'Opportunity HPFS Engaged'];   
        String htmlbd = emailTemplate.HtmlValue;
        for(String htmlvrb : rplcbdhtmlvrbmap.keyset()) {
            htmlbd = htmlbd.replace(htmlvrb, (rplcbdhtmlvrbmap.get(htmlvrb) == null) ? '' : rplcbdhtmlvrbmap.get(htmlvrb));    
        }
        if(opltls.size() > 0) {
            for(Opportunitylineitem olyinfo : opltls) {
                htmlbd = htmlbd + '<td colspan="4" height="18" width="360" class="tableborder">' + olyinfo.product2.name + '</td>' + 
                         '<td width="124" class="tableborder">' + olyinfo.quantity + '</td>' +
                         '<td colspan="2" width="160" class="tableborder">' + currencycontysymbol.get(olyinfo.currencyisocode) + olyinfo.unitprice + '</td>' +
                         '<td colspan="2" width="146" class="tableborder">' + currencycontysymbol.get(olyinfo.currencyisocode) + olyinfo.subtotal + '</td>' +
                         '<td colspan="3" width="216" class="tableborder">' + String.valueof(olyinfo.ServiceDate) + '</td>' +
                         '</tr> ';    
            }
        }
        htmlbd = htmlbd + '</table></html>';
        mail.sethtmlbody(htmlbd);
        String analyzestr = mail.gethtmlbody();
        system.debug('--currency?--' + analyzestr.substring(analyzestr.indexof('Close Date:') , analyzestr.indexof('Opportunity Update:')));
        mail.setSaveAsActivity(false);
        //mail.setPlainTextBody(bd);
        listSingleEmailMessages.add(mail);
        listEmailResult = Messaging.sendEmail(listSingleEmailMessages);
        return errmessage;
    }*/
    
}