src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CSC_Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>Shanxi</fullName>
                </value>
                <value>
                    <fullName>Shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ASCEngineer__c.object
<CustomObject>
    <description>ASC工程师信息(合作伙伴用户添加)</description>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work_Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>ASCEngineers</relationshipLabel>
        <relationshipName>ASCEngineers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>engineerIDNo__c</fullName>
        <label>engineerIDNo</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>engineerPhone__c</fullName>
        <description>engineerPhone</description>
        <label>engineerPhone</label>
        <type>Phone</type>
    </fields>
    <label>ASCEngineer</label>
    <nameField>
        <label>ASCEngineer Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_PN__c</fullName>
        <label>Product Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Product_Line__c</fullName>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/DeliveryPartPN__c.object
<CustomObject>
    <description>出库件PN号管理</description>
    <fields>
        <fullName>PNType__c</fullName>
        <label>PNType</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>DeliveryPartPN</label>
    <nameField>
        <label>partPN</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/DeliveryParts__c.object
<CustomObject>
    <fields>
        <fullName>DeliveryPartPN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DeliveryPartPN</label>
        <referenceTo>DeliveryPartPN__c</referenceTo>
        <relationshipLabel>DeliveryParts</relationshipLabel>
        <relationshipName>DeliveryParts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isDOA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDOA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isInstallPart__c</fullName>
        <defaultValue>false</defaultValue>
        <description>上门工程师是否安装该备件</description>
        <label>isInstallPart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>workorder__c</fullName>
        <label>workorder</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>DeliveryParts</relationshipLabel>
        <relationshipName>DeliveryPartsWorkorder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DeliveryParts</label>
    <nameField>
        <label>DeliveryPartSN</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/EngineerOnSiteInfo__c.object
<CustomObject>
    <fields>
        <fullName>ASCEngineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ASCEngineer</label>
        <referenceTo>ASCEngineer__c</referenceTo>
        <relationshipLabel>EngineerOnSiteInfo</relationshipLabel>
        <relationshipName>EngineerOnSiteInfoASCEngineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EngineerPhone__c</fullName>
        <formula>ASCEngineer__r.engineerPhone__c</formula>
        <label>EngineerPhone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>workorder__c</fullName>
        <label>workorder</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>EngineerOnSiteInfo</relationshipLabel>
        <relationshipName>EngineerOnSiteInfoworkorder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EngineerOnSiteInfo</label>
    <nameField>
        <displayFormat>EOS-{000000000}</displayFormat>
        <label>OnSiteNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <label>Work Order Name</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>OrderToWorkOrder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Parts_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Parts Order</relationshipLabel>
        <relationshipName>Parts_Order</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X_Failure_Cd__c</fullName>
        <description>72=Unused;
74=Verified Failure;
55=Used + not consumed;
PD=Used + not consumed;
MS=Miss shipment;
WP=Used + not consumed;</description>
        <inlineHelpText>72=Unused;
74=Verified Failure;
55=Used + not consumed;
PD=Used + not consumed;
MS=Miss shipment;
WP=Used + not consumed;</inlineHelpText>
        <label>X Failure Cd</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>55 - DOA/DFS</fullName>
                </value>
                <value>
                    <fullName>74 - Verified Failure</fullName>
                </value>
                <value>
                    <fullName>PD - Physically Damaged</fullName>
                </value>
                <value>
                    <fullName>WP - Wrong Part in Box</fullName>
                </value>
                <value>
                    <fullName>72 - Unused</fullName>
                </value>
                <value>
                    <fullName>MS - Miss Shipment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_QA__c.object
<CustomObject>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Process QA</relationshipLabel>
        <relationshipName>Process_QA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process QA</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>ProcessQAId</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_Product_Line__c</fullName>
        <formula>Case.CSC_Product_Line__c</formula>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <formula>Case.CSC_SN__c</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <label>Requested Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requested_Guaranteed_Date__c</fullName>
        <label>Requested Guaranteed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Enroute_Date__c</fullName>
        <label>WorkOrder Enroute Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Fixed_Date__c</fullName>
        <label>WorkOrder Onsite Repair Fixed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Start_Date__c</fullName>
        <label>WorkOrder Onsite Repair Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_SA_QueryCaseSyncTest.cls
@isTest
public class CSC_SA_QueryCaseSyncTest {
    
    public testMethod static void testCSC_SA_QueryCaseSync(){

        Case cas = GetCase();
        
        WorkOrder wo = new WorkOrder();
        wo.CaseId = cas.Id;
        wo.CurrencyIsoCode = 'CNY';
        wo.Requested_Guaranteed_Date__c = Datetime.now();
        wo.Requested_Date__c = Datetime.now();
        wo.Subcase_Enroute_Date__c = Datetime.now();
        wo.Subcase_Onsite_Start_Date__c = Datetime.now().addDays(1);
        wo.Subcase_Onsite_Fixed_Date__c = Datetime.now().addDays(2);
        insert wo;
        
        Process_QA__c pqa = new Process_QA__c();
        pqa.WorkOrder__c = wo.Id;
        insert pqa;
        
        Order__c order = new Order__c();
        order.CurrencyIsoCode = 'CNY';
        order.Work_Order_Name__c = wo.Id;
        insert order;

        DeliveryPartPN__c dpn = new DeliveryPartPN__c();
        dpn.Name = 'testdpn';
        dpn.CurrencyIsoCode = '';
        dpn.PNType__c = 'test';
        insert dpn;

        DeliveryParts__c dp = new DeliveryParts__c();
        dp.workorder__c = wo.Id;
        dp.Name = 'xxx';
        dp.isInstallPart__c = true;
        dp.isDOA__c = false;
        dp.DeliveryPartPN__c = dpn.Id;
        insert dp;

        DeliveryParts__c dp1 = new DeliveryParts__c();
        dp1.workorder__c = wo.Id;
        dp1.Name = 'xxs';
        dp1.isInstallPart__c = false;
        dp1.isDOA__c = false;
        dp1.DeliveryPartPN__c = dpn.Id;
        insert dp1;

        Parts_Order__c po = new Parts_Order__c();
        po.Name = 'poTest';
        po.X_Failure_Cd__c = '55';
        po.Order__c = order.Id;
        insert po;
        
        ASCEngineer__c engineer = new ASCEngineer__c();
        engineer.CurrencyIsoCode = 'CNY';
        engineer.Work_Order__c = wo.Id;
        engineer.engineerIDNo__c = '511423198601040051';
        engineer.engineerPhone__c='13422223333';
        insert engineer;

        EngineerOnSiteInfo__c eoi = new EngineerOnSiteInfo__c();
        eoi.ASCEngineer__c = engineer.Id;
        eoi.workorder__c = wo.Id;
        insert eoi;
        
        CSC_SA_QueryCaseSync.InterfaceQueryCase content = new CSC_SA_QueryCaseSync.InterfaceQueryCase();
        content.vendorTaskID = wo.Id;

        wo.Status = 'Closed';
        update wo;
        
        Test.startTest();
        CSC_SA_QueryCaseSync.AppInput syncCase = new CSC_SA_QueryCaseSync.AppInput();
        syncCase.content = content;
        
        System.assertEquals('0', CSC_SA_QueryCaseSync.doPost(syncCase).rstCode);
        Test.stopTest();
    }

    public testMethod static void testNoWO(){
        CSC_SA_QueryCaseSync.InterfaceQueryCase content = new CSC_SA_QueryCaseSync.InterfaceQueryCase();
        content.vendorTaskID = 'xxxxxxx';
        
        Test.startTest();
        CSC_SA_QueryCaseSync.AppInput syncCase = new CSC_SA_QueryCaseSync.AppInput();
        syncCase.content = content;
        
        System.assertEquals('-1', CSC_SA_QueryCaseSync.doPost(syncCase).rstCode);
        Test.stopTest();
    }

    public static Account a;
    public static Contact cc;
    public static Case  c;
    public static Entitlement e;

    public Static Case GetCase()
    {
        if(c==null)
        {
            List<RecordType> rtList=[Select Id From RecordType Where Name='05-CSC & FST Service Request'];
        
            c=new Case();
            GetContact();
            // c.CaseNumber = '0034343';
            c.CSC_SN__C='SN';
            c.CSC_PN__C='PN';
            c.CSC_Product_Line__c='TN';
            c.ContactId=cc.Id;
            c.ClosedDate = System.now();
            c.Phone__c='13012345678';
            c.Subject='test';
            GetAccount();
            c.AccountId=a.Id;
            c.CSC_Country__c='China';
            c.Province__c='Beijing';
            c.City__c='北京市';
            c.CSC_Issue__c='CSC_Issue__c';
            c.CSC_Reason__c='Misroute';
            GetEntitlement();
            c.EntitlementId=e.Id;
            c.Job_Function__c='Decision Office';
            c.Job_Level__c='Manager';
            c.Last_Name__c='sb';
            c.First_Name__c='sb';
            c.Title__c='test';
            c.Email__c='123@qq.com';
            c.CSC_OTC__c='05R-Normal Contract';
            c.CSC_Product_Description__c = 'test';
            c.Billing_Street__c = '北京二环';
            c.Province__c = '北京';
            c.City__c = '北京';
            if(rtList.size()>0)
            {
                c.RecordTypeId=rtList[0].Id;
            }
            insert c;    
        }
        return c;
    }
    
    public static Entitlement GetEntitlement()
    {
        if(e==null)
        {
            e=new Entitlement();
            e.Name='Entitlement';
            e.Case_Record_Type__c='01-Account Request';
            GetAccount();
            e.AccountId=a.Id;
            e.SLA_Type__c='NBD';
            e.SLA__c = 'testsss';
            insert e;
        }
        return e;
    }
    
    public static Contact GetContact()
    {
        if(cc==null)
        {
            cc=new Contact();
            cc.LastName='ben';
            GetAccount();
            cc.AccountId=a.Id;
            cc.Email='123@qq.com';
            cc.Job_Level__c='Manager';
            cc.Job_Function__c='Decision Office';
            cc.Phone='13012345678';
            insert cc;
        }
        return cc;
    }
    
    public static Account GetAccount()
    {
        if(a==null)
        {
            a=new Account();
            a.Name='h3c';
            insert a;
        }
        return a;
    }
    
}