src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CSC_Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_District__c</fullName>
        <label>District(del)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_PinCode__c</fullName>
        <label>Pin Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>福建-东山</fullName>
                </value>
                <value>
                    <fullName>福建-福清</fullName>
                </value>
                <value>
                    <fullName>福建-福州</fullName>
                </value>
                <value>
                    <fullName>福建-晋江</fullName>
                </value>
                <value>
                    <fullName>福建-龙岩</fullName>
                </value>
                <value>
                    <fullName>福建-马尾</fullName>
                </value>
                <value>
                    <fullName>福建-南平</fullName>
                </value>
                <value>
                    <fullName>福建-宁德</fullName>
                </value>
                <value>
                    <fullName>福建-莆田</fullName>
                </value>
                <value>
                    <fullName>福建-其它城市</fullName>
                </value>
                <value>
                    <fullName>福建-泉州</fullName>
                </value>
                <value>
                    <fullName>福建-三明</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>Shanxi</fullName>
                </value>
                <value>
                    <fullName>Shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>CSC_FST_Service_Account</fullName>
        <active>true</active>
        <label>CSC &amp; FST Service Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/City__c.object
<CustomObject>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Zip_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>澳门</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>福建-东山</fullName>
                </value>
                <value>
                    <fullName>福建-福清</fullName>
                </value>
                <value>
                    <fullName>福建-福州</fullName>
                </value>
                <value>
                    <fullName>福建-晋江</fullName>
                </value>
                <value>
                    <fullName>福建-龙岩</fullName>
                </value>
                <value>
                    <fullName>福建-马尾</fullName>
                </value>
                <value>
                    <fullName>福建-南平</fullName>
                </value>
                <value>
                    <fullName>福建-宁德</fullName>
                </value>
                <value>
                    <fullName>福建-莆田</fullName>
                </value>
                <value>
                    <fullName>福建-其它城市</fullName>
                </value>
                <value>
                    <fullName>福建-泉州</fullName>
                </value>
                <value>
                    <fullName>福建-三明</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Zip Mapping</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_CustomAccountLookupController.cls
/***********************************************************************
Name: CSC_CustomAccountLookupController
***************************************************
History
--------
VERSION     AUTHOR              DATE            DETAIL
1.0         xuxiangguo          2016-6-08       Created
**************************************************************/
global class CSC_CustomAccountLookupController {

    //客户信息
    public Account account {get;set;} 

    //客户信息检索结果
    public List<Account> results{get;set;} 

    //客户信息条件
    public string searchString{get;set;} 

    //联系人电话号码
    public string strAddress{get;set;} 

    //Account的记录类Id
    public static String ACCOUNT_RECORD_TYPE_ID;
    
    public String strAccountId {get;set;} 

    public String strAccountName {get;set;} 

    public Boolean isSaveSuccess {get;set;}

    public String inputAccountName {get;set;}

    public final static String ERROR_MESSAGE = ' :You must enter a value';

    //取得CSC用的相关的Account的Record Type Id
    static {

        //取得Account的记录类Id
        List<RecordType> accountRtList = [SELECT Id, DeveloperName FROM RecordType 
                    WHERE SobjectType = 'Account' AND DeveloperName = 'CSC_FST_Service_Account'];

        if (accountRtList != null && !accountRtList.isEmpty()) {
            ACCOUNT_RECORD_TYPE_ID = accountRtList[0].Id;
        } else {
            ACCOUNT_RECORD_TYPE_ID = null;
        }
    }

    /**
     方法名: 构造方法CSC_CustomAccountLookupController
     功能说明: 根据检索条件查询客户信息
     参数说明: 无
     返回值: 无
     作者: xuxiangguo
     日期: 2016-6-08
    */
    public CSC_CustomAccountLookupController() {
        account = new Account();
        account.RecordTypeId = ACCOUNT_RECORD_TYPE_ID;
        account.CSC_Country__c = 'China';
        searchString = System.currentPageReference().getParameters().get('lksrch');
        strAddress = '';
    }

    public PageReference search() {
        if ((searchString ==null || ''.equals(searchString.trim()))
            && (strAddress == null || ''.equals(strAddress.trim()))) {
            ApexPages.addMessage(
                    new ApexPages.Message(ApexPages.Severity.WARNING, 'Please enter search condition!'));
            return null;
        }

        runSearch();

        if (results.size() == 0) {
            ApexPages.addMessage(
                    new ApexPages.Message(ApexPages.Severity.INFO, 'No Account record find!'));
        } else if (results.size() > 1000) {
            ApexPages.addMessage(
                    new ApexPages.Message(ApexPages.Severity.WARNING, 'Record size exceeds maximum size of 1000! Please modify search condition and try again.'));
        } else {
            ApexPages.addMessage(
                    new ApexPages.Message(ApexPages.Severity.INFO, 'Search Account information success!'));
        }
        return null;
    }

    private void runSearch() {
        results = performSearch(searchString, strAddress);               
    } 

    private List<Account> performSearch(string searchString, string strAddress) {

        String soql = 'SELECT Id, Name, RecordTypeId, RecordType.Name, CSC_PinCode__c,CSC_Country__c,Province__c,City__c,'
                + 'BillingCountry, BillingState, BillingCity, CSC_District__c, BillingPostalCode, BillingStreet FROM Account '
                + 'Where RecordTypeId = \'' +  ACCOUNT_RECORD_TYPE_ID + '\'';

        if(searchString != '' && searchString != null) {
          soql = soql +  ' AND name LIKE \'%' + searchString +'%\'';
        }

        if(strAddress != '' && strAddress != null) {
          soql = soql +  ' AND BillingStreet LIKE \'%' + strAddress +'%\'';
        }

        return database.query(soql+' limit 999'); 
    }
    
    /**
     方法名: verifyZip
     功能说明: 校验zip信息
     参数说明: 邮编
     返回值: 
     作者: xuxiangguo
     日期: 2016-07-22
    */
    public Pagereference verifyCity(){

        String strCity = account.City__c;

        if (strCity != null && !''.equals(strCity.trim())) {
            try {
                Zip_Mapping__c zipMapping = [SELECT Id, Name, Province__c, City__c FROM Zip_Mapping__c WHERE City__c=:strCity.trim() LIMIT 1];
                if (zipMapping != null) {
                    account.BillingPostalCode = zipMapping.Name;
                }
            } catch (Exception ex){
                account.BillingPostalCode = null;
                System.debug(ex.getMessage());
            }
            
        } else {
            ApexPages.addMessage(
                new ApexPages.Message(ApexPages.Severity.ERROR, Schema.SObjectType.Account.fields.City__c.label + ' :You must enter a value'));
        }

        return null;
    }

    public PageReference saveAccount() {
        try{

            account.Name = inputAccountName;
            Boolean isPassed = true;
            isPassed = checkInputValue();

            if (!isPassed) {
                return null;
            }

            isSaveSuccess = false;
            insert account;
            isSaveSuccess = true;
            strAccountId = account.Id;
            strAccountName = account.Name;
        }catch (Exception ex) {
            ApexPages.addMessage(
                    new ApexPages.Message(ApexPages.Severity.ERROR, 'Create Account Failed!'));
        }
        return null;
    }

    public Boolean checkInputValue (){

        Boolean isPassed = true;

        if (account.Name == null || account.Name.trim() =='') {
            ApexPages.addMessage(
                new ApexPages.Message(ApexPages.Severity.ERROR, Schema.SObjectType.Account.fields.Name.label + ERROR_MESSAGE));
            isPassed = false;
        }

        if (account.CSC_Country__c == null || account.CSC_Country__c.trim() =='') {
            ApexPages.addMessage(
                new ApexPages.Message(ApexPages.Severity.ERROR, Schema.SObjectType.Account.fields.CSC_Country__c.label + ERROR_MESSAGE));
            isPassed = false;
        }

        if (account.Province__c == null || account.Province__c.trim() =='') {
            ApexPages.addMessage(
                new ApexPages.Message(ApexPages.Severity.ERROR, Schema.SObjectType.Account.fields.Province__c.label + ERROR_MESSAGE));
            isPassed = false;
        }

        if (account.City__c == null || account.City__c.trim() =='') {
            ApexPages.addMessage(
                new ApexPages.Message(ApexPages.Severity.ERROR, Schema.SObjectType.Account.fields.City__c.label + ERROR_MESSAGE));
            isPassed = false;
        }

        if (account.BillingPostalCode == null || account.BillingPostalCode.trim() =='') {
            ApexPages.addMessage(
                new ApexPages.Message(ApexPages.Severity.ERROR, 'Zip' + ERROR_MESSAGE));
            isPassed = false;
        }

        if (account.BillingStreet == null || account.BillingStreet.trim() =='') {
            ApexPages.addMessage(
                new ApexPages.Message(ApexPages.Severity.ERROR, 'Address' + ERROR_MESSAGE));
            isPassed = false;
        }

        return isPassed;
    }

    public string getFormTag() {
        return System.currentPageReference().getParameters().get('frm');
    }

    public string getTextBox() {
        return System.currentPageReference().getParameters().get('txt');
    }
}