src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <inlineHelpText>NEC (NEC); 
BR (The Belt and Road);
WW (World Wide);
SEA  (South East Asia);</inlineHelpText>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEC</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>WW</fullName>
                </value>
                <value>
                    <fullName>SEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oversea_Country__c</fullName>
        <label>Oversea Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Countrys</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Regions</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>End_User</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <inlineHelpText>NEC (NEC); 
BR (The Belt and Road);
WW (World Wide);
SEA  (South East Asia);</inlineHelpText>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEC</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>WW</fullName>
                </value>
                <value>
                    <fullName>SEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Countrys</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Regions</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>IPMS_Project</fullName>
        <active>true</active>
        <businessProcess>IPMS</businessProcess>
        <label>IPMS Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RPL_List__c.object
<CustomObject>
    <fields>
        <fullName>Examples__c</fullName>
        <label>Examples</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Keyword1__c</fullName>
        <label>Keyword1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Keyword2__c</fullName>
        <label>Keyword2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RPL List</label>
    <nameField>
        <displayFormat>RPL-{000000000}</displayFormat>
        <label>RPL List No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/globalValueSets/Countrys.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>East Timor</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia</fullName>
    </customValue>
    <customValue>
        <fullName>Laos</fullName>
    </customValue>
    <customValue>
        <fullName>Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Maldives</fullName>
    </customValue>
    <customValue>
        <fullName>Myanmar</fullName>
    </customValue>
    <customValue>
        <fullName>Nepal</fullName>
    </customValue>
    <customValue>
        <fullName>Pakistan</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
    </customValue>
    <customValue>
        <fullName>Sri Lanka</fullName>
    </customValue>
    <customValue>
        <fullName>Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Vietnam</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Iceland</fullName>
    </customValue>
    <customValue>
        <fullName>Israel</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Liechtenstein</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <customValue>
        <fullName>Malta</fullName>
    </customValue>
    <customValue>
        <fullName>Russia</fullName>
    </customValue>
    <masterLabel>Countrys</masterLabel>
</GlobalValueSet>

H3CIPMSJAVA-20180830/src/globalValueSets/Regions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>South East Asia</fullName>
        <default>true</default>
        <label>South East Asia</label>
    </customValue>
    <customValue>
        <fullName>Northeast Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Middle Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>South Asia</fullName>
    </customValue>
    <customValue>
        <fullName>West EU</fullName>
    </customValue>
    <customValue>
        <fullName>East EU</fullName>
    </customValue>
    <customValue>
        <fullName>Oceania</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>Africa</fullName>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

src/classes/Ctrl_Blacklist_Test.cls
@isTest
private class Ctrl_Blacklist_Test {
    static testMethod void testMethod1() {
    	RecordType rt1 = [select id,DeveloperName from RecordType where DeveloperName='End_User' limit 1];
        RecordType rt2 = [select id,DeveloperName from RecordType where DeveloperName='IPMS_Project' limit 1];
       
        Account acc = new Account();
        acc.RecordTypeId = rt1.id;
        acc.Name = 'test00000001';
         acc.Business_Type__c = 'BR';
        acc.Oversea_Country__c = 'Brunei';
        acc.Business_Type__c = 'BR';
        insert acc;
        Opportunity opp = new Opportunity();
        opp.RecordTypeId = rt2.id;
        opp.AccountId = acc.id;
        opp.StageName = 'A: Confirm the project';
        opp.CloseDate = Date.today().addDays(10);
        opp.Name = 'test opp rpllist';
        opp.Region__c = 'East EU';
        opp.Country__c = 'Russia';
        insert opp;
        RPL_List__c rp = new RPL_List__c();
        rp.Examples__c = 'opp rpllist';
        rp.Keyword1__c = 'opp';
        rp.Keyword2__c = 'rpllist';
        insert rp;

        Ctrl_Blacklist.checkBlacklist(opp.id);
        Ctrl_Blacklist.checkCountry(opp.id);
    }
}