src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>福建-东山</fullName>
                </value>
                <value>
                    <fullName>福建-福清</fullName>
                </value>
                <value>
                    <fullName>福建-福州</fullName>
                </value>
                <value>
                    <fullName>福建-晋江</fullName>
                </value>
                <value>
                    <fullName>福建-龙岩</fullName>
                </value>
                <value>
                    <fullName>福建-马尾</fullName>
                </value>
                <value>
                    <fullName>福建-南平</fullName>
                </value>
                <value>
                    <fullName>福建-宁德</fullName>
                </value>
                <value>
                    <fullName>福建-莆田</fullName>
                </value>
                <value>
                    <fullName>福建-其它城市</fullName>
                </value>
                <value>
                    <fullName>福建-泉州</fullName>
                </value>
                <value>
                    <fullName>福建-三明</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>Shanxi</fullName>
                </value>
                <value>
                    <fullName>Shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>CSC_FST_Service_Account</fullName>
        <active>true</active>
        <label>CSC &amp; FST Service Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>重庆市</fullName>
                </value>
                <value>
                    <fullName>重庆市-北碚区</fullName>
                </value>
                <value>
                    <fullName>重庆市-璧山</fullName>
                </value>
                <value>
                    <fullName>重庆市-长寿区</fullName>
                </value>
                <value>
                    <fullName>重庆市-城口县</fullName>
                </value>
                <value>
                    <fullName>重庆市-大足县</fullName>
                </value>
                <value>
                    <fullName>重庆市-垫江县</fullName>
                </value>
                <value>
                    <fullName>重庆市-丰都</fullName>
                </value>
                <value>
                    <fullName>重庆市-奉节</fullName>
                </value>
                <value>
                    <fullName>重庆市-合川市</fullName>
                </value>
                <value>
                    <fullName>重庆市-江北区</fullName>
                </value>
                <value>
                    <fullName>重庆市-江津市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>江苏-常熟</fullName>
                </value>
                <value>
                    <fullName>江苏-常州</fullName>
                </value>
                <value>
                    <fullName>江苏-东台</fullName>
                </value>
                <value>
                    <fullName>江苏-淮安</fullName>
                </value>
                <value>
                    <fullName>江苏-淮阴</fullName>
                </value>
                <value>
                    <fullName>江苏-江阴</fullName>
                </value>
                <value>
                    <fullName>江苏-昆山</fullName>
                </value>
                <value>
                    <fullName>江苏-连云港</fullName>
                </value>
                <value>
                    <fullName>江苏-南京</fullName>
                </value>
                <value>
                    <fullName>江苏-南通</fullName>
                </value>
                <value>
                    <fullName>江苏-邳州</fullName>
                </value>
                <value>
                    <fullName>江苏-苏州</fullName>
                </value>
                <value>
                    <fullName>江苏-太仓</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_NGMS_CM_Update_CaseTest.cls
@isTest
private class CSC_NGMS_CM_Update_CaseTest{

    public class Input{
    
      public  String CaseOrigin;
      public  String CaseID;
      public  String AccountName;
      public  String Province_CN;
      public  String Province_PY;
      public  String City;
      public  String Address;
      public  String ContactMobile;
      public  String ContactName;
      public  String Subject;
    }
    static testMethod void testCM_Update_Case(){

        //创建Account
        Account acc = new Account();
        acc.Name = '测试Account';
        acc.City__c = '安徽-安庆';
        acc.Province__c = 'Anhui';
        acc.BillingStreet = '安徽省-安庆市-1号';
        Insert acc;

        //创建Contact
        Contact cont = new Contact();
        cont.AccountId = acc.Id;
        cont.Phone = '13438940303';
        cont.LastName = 'testName';
        Insert cont;
      
        Case cas = new Case();
        cas.AccountId = acc.Id;
        cas.ContactId = cont.Id;
        //cas.HPE_SubK_ID__c = '000003';
        cas.Subject = 'this is test';
        Insert cas;

        Workorder wk = new Workorder();
        wk.CaseId = cas.Id;
        wk.Subject = 'this is subject for workorder';
        Insert wk;
        Case c = [select CaseNumber,Subject from Case where Id =: cas.Id];
        Account a = [select Name,City__c,Province__c,BillingStreet from Account where Id =:acc.Id];
        Contact con = [select Id,Phone,LastName from Contact where Id =:cont.Id];
        
        Input ipt = new Input();
        ipt.CaseOrigin = 'NGMS-IN';
        ipt.CaseID = c.CaseNumber;
        ipt.AccountName = a.Name;
        ipt.Province_PY = a.Province__c;
        ipt.City = a.City__c;
        ipt.Address = a.BillingStreet;
        ipt.ContactMobile = con.Phone;
        ipt.ContactName = con.LastName;
        ipt.Subject = c.Subject;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(ipt);
        req.requestBody = Blob.valueof(reqJson);
        System.debug(reqJson);
        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/NGMSUpdateCaseStatus/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        CSC_NGMS_CM_Update_Case.CM_Update_Case();
    }
     //Account and contact is null 
    static testMethod void testCM_Update_Case1(){
    
        Case cas = new Case();
        cas.Subject = 'this is test';
        Insert cas;
        Workorder wk = new Workorder();
        wk.CaseId = cas.Id;
        wk.Subject = 'this is subject for workorder';
        Insert wk;
        Case c = [select CaseNumber,Subject from Case where Id =: cas.Id];
        Input ipt1 = new Input();
        ipt1.CaseOrigin = 'NGMS-IN';
        ipt1.CaseID = c.CaseNumber;
        ipt1.Subject = 'xxxxxxxxxxxxxx1';
        ipt1.AccountName = 'Account Name';
        ipt1.Province_PY = '山东';
        ipt1.City = '山东省-济南市';
        ipt1.Address = '山东省-济南市-历城区-0001号';
        ipt1.ContactMobile = '18749483748';
        ipt1.ContactName = 'test class';

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(ipt1);
        req.requestBody = Blob.valueof(reqJson);
        System.debug(reqJson);
        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/NGMSUpdateCaseStatus/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        CSC_NGMS_CM_Update_Case.CM_Update_Case();
    }
    
static testMethod void testgetExistContactAndgetExistAccount(){

    List<RecordType> accountRtList = [SELECT Id, DeveloperName FROM RecordType 
                    WHERE SobjectType = 'Account' AND DeveloperName = 'CSC_FST_Service_Account'];
    String ACCOUNT_RECORDTYPE_ID = accountRtList.isEmpty()? null: accountRtList[0].Id;

    List<RecordType> contactRtList = [SELECT Id, DeveloperName FROM RecordType 
                    WHERE SobjectType = 'Contact' AND DeveloperName = 'CSC_FST_Service_Contact'];
    String CONTACT_RECORDTYPE_ID = contactRtList.isEmpty()? null: contactRtList[0].Id;

    Account acc = new Account();
    acc.Name = 'Account11111';
    acc.City__c = '安徽-安庆';
    acc.Province__c = 'Anhui';
    acc.BillingStreet = '安徽省-安庆市-1号';
    acc.RecordTypeId = ACCOUNT_RECORDTYPE_ID;
    Insert acc;

    //创建Contact
    Contact cont = new Contact();
    cont.AccountId = acc.Id;
    cont.Phone = '13438940303';
    cont.LastName = 'testName';
    cont.RecordTypeId = CONTACT_RECORDTYPE_ID;
    Insert cont;

    Test.startTest();
    CSC_NGMS_CM_Update_Case.getExistAccount(new Account(Name = 'Account11111',City__c = '安徽-安庆',Province__c = 'Anhui',BillingStreet = '安徽省-安庆市-1号',RecordTypeId = ACCOUNT_RECORDTYPE_ID));
    CSC_NGMS_CM_Update_Case.getExistContact(new Contact(Phone = '13438940303',LastName = 'testName',RecordTypeId = CONTACT_RECORDTYPE_ID));
    Test.stopTest();
}

static testMethod void testAccountAndContactisNull(){
    
    List<RecordType> accountRtList = [SELECT Id, DeveloperName FROM RecordType 
                    WHERE SobjectType = 'Account' AND DeveloperName = 'CSC_FST_Service_Account'];
    String ACCOUNT_RECORDTYPE_ID = accountRtList.isEmpty()? null: accountRtList[0].Id;

    List<RecordType> contactRtList = [SELECT Id, DeveloperName FROM RecordType 
                    WHERE SobjectType = 'Contact' AND DeveloperName = 'CSC_FST_Service_Contact'];
    String CONTACT_RECORDTYPE_ID = contactRtList.isEmpty()? null: contactRtList[0].Id;
    
    Test.startTest();
    CSC_NGMS_CM_Update_Case.getExistAccount(new Account(Name = 'Account11111',City__c = '安徽-安庆',Province__c = 'Anhui',BillingStreet = '安徽省-安庆市-1号',RecordTypeId = ACCOUNT_RECORDTYPE_ID));
    CSC_NGMS_CM_Update_Case.getExistContact(new Contact(Phone = '13438940303',LastName = 'testName',RecordTypeId = CONTACT_RECORDTYPE_ID));
    Test.stopTest();
}
}