src/objects/Account_Team__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team</relationshipLabel>
        <relationshipName>Account_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>客户小组</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Account Team No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/DeleteAccountSharewhendltAccTeamTest.cls
@istest(seealldata=true)
public class DeleteAccountSharewhendltAccTeamTest {
    public static testmethod void testDeleteAccountSharewhendltAccTeam() {
        User ur1 = [select id from user where isactive = true limit 1];
        Account acc1 = new Account(name = 'test1');
        insert acc1;
        Account_Team__c acctm1 = new Account_Team__c(Account__c = acc1.id , Team_Member__c = ur1.id);
        insert acctm1;
        AccountShare accsh1 = new AccountShare(AccountId = acc1.id , UserOrGroupId = ur1.id , AccountAccessLevel = 'Read' , OpportunityAccessLevel = 'Read');
        insert accsh1;
        delete acctm1;
    }
}