src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>福建-东山</fullName>
                </value>
                <value>
                    <fullName>福建-福清</fullName>
                </value>
                <value>
                    <fullName>福建-福州</fullName>
                </value>
                <value>
                    <fullName>福建-晋江</fullName>
                </value>
                <value>
                    <fullName>福建-龙岩</fullName>
                </value>
                <value>
                    <fullName>福建-马尾</fullName>
                </value>
                <value>
                    <fullName>福建-南平</fullName>
                </value>
                <value>
                    <fullName>福建-宁德</fullName>
                </value>
                <value>
                    <fullName>福建-莆田</fullName>
                </value>
                <value>
                    <fullName>福建-其它城市</fullName>
                </value>
                <value>
                    <fullName>福建-泉州</fullName>
                </value>
                <value>
                    <fullName>福建-三明</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>Shanxi</fullName>
                </value>
                <value>
                    <fullName>Shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>重庆市</fullName>
                </value>
                <value>
                    <fullName>重庆市-北碚区</fullName>
                </value>
                <value>
                    <fullName>重庆市-璧山</fullName>
                </value>
                <value>
                    <fullName>重庆市-长寿区</fullName>
                </value>
                <value>
                    <fullName>重庆市-城口县</fullName>
                </value>
                <value>
                    <fullName>重庆市-大足县</fullName>
                </value>
                <value>
                    <fullName>重庆市-垫江县</fullName>
                </value>
                <value>
                    <fullName>重庆市-丰都</fullName>
                </value>
                <value>
                    <fullName>重庆市-奉节</fullName>
                </value>
                <value>
                    <fullName>重庆市-合川市</fullName>
                </value>
                <value>
                    <fullName>重庆市-江北区</fullName>
                </value>
                <value>
                    <fullName>重庆市-江津市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HPE_SubK_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>HPE SubK ID</description>
        <label>HPE SubK ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>Shanxi</fullName>
                </value>
                <value>
                    <fullName>Shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/City__c.object
<CustomObject>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>H3C Employee ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_NGMS_CM_Create_WorkOrderTest.cls
@isTest
private class CSC_NGMS_CM_Create_WorkOrderTest{

    public class Input{
       public  String CaseOrigin;  //NGMS-IN
       public  String CaseID;
       public  String EID;    //团队信息（EID）
       public  Decimal Labour_hour;
       public  String Book_Date; //预约上门时间
       public  String Intel_Notes;
       public  List<String> Device;
    }

    static testMethod void CM_Create_WorkOrder(){

        Profile p = [select id from Profile where Name = 'CSC&FST CA'];
        User u = new User();
        u.Alias = 'lixiang';    
        u.ProfileId = p.Id;
        u.Employee_ID__c = '600000';
        u.LastName = 'zhou';
        u.FirstName = 'zhang';
        u.Email = 'zhangfeng@126.com';
        u.Username = 'zhangfeng@126.com';
        u.CommunityNickname = 'lixxxxxxxxxxx';
        u.EmailEncodingKey = 'UTF-8';
        u.TimeZoneSidKey = 'Asia/Shanghai';
        u.LocaleSidKey = 'zh_CN';
        u.LanguageLocaleKey = 'en_US';
        Insert u;

        Account acc = new Account();
        acc.Name = '测试Account';
        acc.City__c = '安徽-安庆';
        acc.Province__c = 'Anhui';
        acc.BillingStreet = '安徽省-安庆市-1号';
        Insert acc;

        //创建Contact
        Contact cont = new Contact();
        cont.AccountId = acc.Id;
        cont.Phone = '13438940303';
        cont.LastName = 'testName';
        Insert cont;

        Case cas = new Case();
        cas.AccountId = acc.Id;
        cas.ContactId = cont.Id;
        cas.HPE_SubK_ID__c = '000003';
        cas.Subject = 'this is test';
        Insert cas;

        Case c = [select Id,CaseNumber from Case where Id =:cas.Id];
        Input ipt = new Input();
        ipt.CaseOrigin = 'NGMS-IN';
        ipt.CaseID = c.CaseNumber;
        ipt.EID = '600000';
        ipt.Labour_hour = 20.0;
        ipt.Intel_Notes = 'this is test notes';
        ipt.Device = new List<String>{'001','002'};
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(ipt);
        req.requestBody = Blob.valueof(reqJson);
        System.debug(reqJson);
        req.requestURI = 'https://hscec--cscdev.cs31.my.salesforce.com/services/apexrest/NGMSCretWorder/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        CSC_NGMS_CM_Create_WorkOrder.CM_Create_WorkOrder();
    }
    
    static testMethod void CM_Create_WorkOrder200(){

        Profile p = [select id from Profile where Name = 'CSC&FST CA'];
        User u = new User();
        u.Alias = 'lixiang';    
        u.ProfileId = p.Id;
        u.Employee_ID__c = '600000';
        u.LastName = 'zhou';
        u.FirstName = 'zhang';
        u.Email = 'zhangfeng@126.com';
        u.Username = 'zhangfeng@126.com';
        u.CommunityNickname = 'lixxxxxxxxxxx';
        u.EmailEncodingKey = 'UTF-8';
        u.TimeZoneSidKey = 'Asia/Shanghai';
        u.LocaleSidKey = 'zh_CN';
        u.LanguageLocaleKey = 'en_US';
        Insert u;

        Account acc = new Account();
        acc.Name = '测试Account';
        acc.City__c = '安徽-安庆';
        acc.Province__c = 'Anhui';
        acc.BillingStreet = '安徽省-安庆市-1号';
        Insert acc;

        //创建Contact
        Contact cont = new Contact();
        cont.AccountId = acc.Id;
        cont.Phone = '13438940303';
        cont.LastName = 'testName';
        Insert cont;

        Case cas = new Case();
        cas.AccountId = acc.Id;
        cas.ContactId = cont.Id;
        cas.HPE_SubK_ID__c = '000003';
        cas.Subject = 'this is test';
        Insert cas;

        Case c = [select Id,CaseNumber from Case where Id =:cas.Id];
        Input ipt = new Input();
        ipt.CaseOrigin = 'NGMS-IN';
        ipt.CaseID = c.CaseNumber;
        ipt.EID = '600000';
        ipt.Labour_hour = 20.0;
        //yyyy-MM-dd HH:mm:ss
        ipt.Book_Date = '2017-03-24 12:24:48';
        ipt.Intel_Notes = 'this is test notes';
        ipt.Device = new List<String>{'001','002'};
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(ipt);
        req.requestBody = Blob.valueof(reqJson);
        System.debug(reqJson);
        req.requestURI = 'https://hscec--cscdev.cs31.my.salesforce.com/services/apexrest/NGMSCretWorder/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        CSC_NGMS_CM_Create_WorkOrder.CM_Create_WorkOrder();
    }

    //test input is null
     static testMethod void CM_Create_WorkOrder1(){

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(null);
        req.requestBody = Blob.valueof(reqJson);
        System.debug(reqJson);
        req.requestURI = 'https://hscec--cscdev.cs31.my.salesforce.com/services/apexrest/NGMSCretWorder/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        CSC_NGMS_CM_Create_WorkOrder.CM_Create_WorkOrder();
    }
    //test EID & CaseId is null
     static testMethod void CM_Create_WorkOrder2(){

        Input ipt = new Input();
        ipt.CaseOrigin = 'NGMS-IN';
        ipt.Labour_hour = 20.0;
        ipt.Intel_Notes = 'this is test notes';
        ipt.Device = new List<String>{'001','002'};
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(ipt);
        req.requestBody = Blob.valueof(reqJson);
        System.debug(reqJson);
        req.requestURI = 'https://hscec--cscdev.cs31.my.salesforce.com/services/apexrest/NGMSCretWorder/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        CSC_NGMS_CM_Create_WorkOrder.CM_Create_WorkOrder();
    }
}