src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Legacy-Backlog</fullName>
                </value>
                <value>
                    <fullName>Requested by Sales</fullName>
                </value>
                <value>
                    <fullName>Requested by Marketing</fullName>
                </value>
                <value>
                    <fullName>Converted from Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>UL @ibreakingpoint 20151027</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/LeadUpdateNewCustomerTest.cls
@istest(seealldata=true)
public class LeadUpdateNewCustomerTest {
    public static testmethod void testLeadUpdateNewCustomer() { 
        
        account acc = new account();
        acc.name = 'BP-test';
        acc.Data_Source__c = 'Converted from Marketing';
        insert acc;
        
        lead ld = new lead();
        ld.Account__c = acc.id;
        ld.Company = 'BP'; 
        ld.LastName= 'Bay';
        ld.Phone = '13911111234';
        insert ld;
        
        lead ld1 = new lead();
        ld1.Account__c = acc.id;
        ld1.Company = 'BP'; 
        ld1.LastName= 'Bay';
        ld1.Phone = '13911111234';
        insert ld1;
        
        ld1.Company = 'BJ';
        update ld1;
    }
}