src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AMID__c</fullName>
        <externalId>true</externalId>
        <label>AMID2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name_Latin_Capture__c</fullName>
        <label>Account Name Latin Capture</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDCP_Business_Relationship_ID__c</fullName>
        <label>MDCP Business Relationship ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDCP_Site_ID__c</fullName>
        <label>MDCP Site ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDCP_Site_Instance_ID__c</fullName>
        <label>MDCP Site Instance ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Engagement__c</fullName>
        <label>Customer Engagement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>End User Sales</fullName>
                </value>
                <value>
                    <fullName>Alliance</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fulfillment__c</fullName>
        <label>Fulfillment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Customer_Engagement__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>HP Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Channel Fulfilled</fullName>
                </value>
                <value>
                    <fullName>VSI Fulfilled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/EmailNoticetoHPFSTest.cls
@istest(seealldata=true)
public class EmailNoticetoHPFSTest {
    /**public static testmethod void testEmailNoticetoHPFS() {
        Account acc1 = new Account(name = 'test1' , Account_Name_Latin_Capture__c = 'testlatin' , BillingCity = 'bj' , BillingCountry = 'china' ,
        BillingPostalCode = '1' , BillingStreet = 'teststreet' , MDCP_Site_ID__c = 'test1' , MDCP_Site_Instance_ID__c = 'test' , 
        MDCP_Business_Relationship_ID__c = 'rr' , AMID__c = 'aa');    
        insert acc1;
        User ur = [select id, name, Email, Phone, MobilePhone from user where isactive = true and profile.name = 'System Administrator' limit 1];
        Opportunity opp1 = new Opportunity(Accountid = acc1.id , ownerid = ur.id , name = 'testopp' , CloseDate = date.today() , 
        StageName = '04B - Propose Solution' , ForecastCategoryName = 'Pipeline' , Amount = 123 , Description = 'test' , Customer_Engagement__c = 'Alliance' , 
        Fulfillment__c = 'Channel Fulfilled', currencyisocode = 'CNY');
        insert opp1;
        Pricebookentry prcbokety = [select id from pricebookentry where isactive=true and currencyisocode = 'CNY' limit 1];
        List<Opportunitylineitem> oltls = new List<Opportunitylineitem>();
        Opportunitylineitem olt1 = new Opportunitylineitem(Pricebookentryid = prcbokety.id , quantity = 12 , UnitPrice = 11 , ServiceDate = date.today() , 
        opportunityid = opp1.id);
        oltls.add(olt1);
        Opportunitylineitem olt2 = new Opportunitylineitem(Pricebookentryid = prcbokety.id , quantity = 13 , UnitPrice = 14 , ServiceDate = date.today() , 
        opportunityid = opp1.id);
        oltls.add(olt2);
        insert oltls;
        EmailNoticetoHPFS.SendOppEmail(opp1.id);
    }*/
}