src/objects/ASCEngineer__c.object
<CustomObject>
    <description>ASC工程师信息(合作伙伴用户添加)</description>
    <fields>
        <fullName>engineerIDNo__c</fullName>
        <label>engineerIDNo</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>engineerPhone__c</fullName>
        <description>engineerPhone</description>
        <label>engineerPhone</label>
        <type>Phone</type>
    </fields>
    <label>ASCEngineer</label>
    <nameField>
        <label>ASCEngineer Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/DeliveryParts__c.object
<CustomObject>
    <fields>
        <fullName>DeliveryPartPN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DeliveryPartPN</label>
        <referenceTo>DeliveryPartPN__c</referenceTo>
        <relationshipLabel>DeliveryParts</relationshipLabel>
        <relationshipName>DeliveryParts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isDOA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDOA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isInstallPart__c</fullName>
        <defaultValue>false</defaultValue>
        <description>上门工程师是否安装该备件</description>
        <label>isInstallPart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>partTypeF__c</fullName>
        <formula>DeliveryPartPN__r.PNType__c</formula>
        <label>partTypeF</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>workorder__c</fullName>
        <label>workorder</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>DeliveryParts</relationshipLabel>
        <relationshipName>DeliveryPartsWorkorder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DeliveryParts</label>
    <nameField>
        <label>DeliveryPartSN</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/EngineerOnSiteInfo__c.object
<CustomObject>
    <fields>
        <fullName>ASCEngineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ASCEngineer</label>
        <referenceTo>ASCEngineer__c</referenceTo>
        <relationshipLabel>EngineerOnSiteInfo</relationshipLabel>
        <relationshipName>EngineerOnSiteInfoASCEngineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EngineerPhone__c</fullName>
        <formula>ASCEngineer__r.engineerPhone__c</formula>
        <label>EngineerPhone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>workorder__c</fullName>
        <label>workorder</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>EngineerOnSiteInfo</relationshipLabel>
        <relationshipName>EngineerOnSiteInfoworkorder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EngineerOnSiteInfo</label>
    <nameField>
        <displayFormat>EOS-{000000000}</displayFormat>
        <label>OnSiteNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <label>Work Order Name</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>OrderToWorkOrder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Parts_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Parts Order</relationshipLabel>
        <relationshipName>Parts_Order</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Removed_Parts_Serial_Number__c</fullName>
        <label>Removed Parts Serial Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Removed_Parts_Status__c</fullName>
        <label>Removed Parts Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Bad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Removed_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Removed Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Removed Parts)</relationshipLabel>
        <relationshipName>Removed_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_QA__c.object
<CustomObject>
    <fields>
        <fullName>QA_Code__c</fullName>
        <label>QA Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>QA_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>0A-See comments</fullName>
                </value>
                <value>
                    <fullName>0B-HP IT system down</fullName>
                </value>
                <value>
                    <fullName>AA-Entitlement Problem</fullName>
                </value>
                <value>
                    <fullName>ZZ-No Issues</fullName>
                </value>
                <value>
                    <fullName>BA-Diag.wrong/incomp</fullName>
                </value>
                <value>
                    <fullName>BH-wrong parts info</fullName>
                </value>
                <value>
                    <fullName>LA-Local issue A</fullName>
                </value>
                <value>
                    <fullName>LB-Local issue B</fullName>
                </value>
                <value>
                    <fullName>PC-Missing part info</fullName>
                </value>
                <value>
                    <fullName>PF-Damaged/DOA</fullName>
                </value>
                <value>
                    <fullName>SC-Addl prob found</fullName>
                </value>
                <value>
                    <fullName>XB-Lack skill/knowledge</fullName>
                </value>
                <value>
                    <fullName>XG-Tool/Manual missing</fullName>
                </value>
                <value>
                    <fullName>XH-Manual/Documentation not read</fullName>
                </value>
                <value>
                    <fullName>XI-CE Assist open with wrong Priority</fullName>
                </value>
                <value>
                    <fullName>XJ-CE was not onsite anymore</fullName>
                </value>
                <value>
                    <fullName>MR-Misrouted Call</fullName>
                </value>
                <value>
                    <fullName>SD-Sys Down Dependency</fullName>
                </value>
                <value>
                    <fullName>D1-IRS Assistance</fullName>
                </value>
                <value>
                    <fullName>D2-Proactive Scan</fullName>
                </value>
                <value>
                    <fullName>D3-FW&amp;SW Patch Analysis</fullName>
                </value>
                <value>
                    <fullName>D4-FW Analysis</fullName>
                </value>
                <value>
                    <fullName>D5-SW Patch Analysis</fullName>
                </value>
                <value>
                    <fullName>D6-Incident Reporting</fullName>
                </value>
                <value>
                    <fullName>Demo Center</fullName>
                </value>
                <value>
                    <fullName>Ink and Media</fullName>
                </value>
                <value>
                    <fullName>Ink Conversion</fullName>
                </value>
                <value>
                    <fullName>Trade Show</fullName>
                </value>
                <value>
                    <fullName>Machine Recertification</fullName>
                </value>
                <value>
                    <fullName>Service Delivery Absorbed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QA_Type__c</fullName>
        <label>QA Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Agent</fullName>
                </value>
                <value>
                    <fullName>CE Assist</fullName>
                </value>
                <value>
                    <fullName>CE QA</fullName>
                </value>
                <value>
                    <fullName>CE SAFE</fullName>
                </value>
                <value>
                    <fullName>Competency Center</fullName>
                </value>
                <value>
                    <fullName>Depot Repair</fullName>
                </value>
                <value>
                    <fullName>Dispatcher/RC</fullName>
                </value>
                <value>
                    <fullName>DOA Fulfillment</fullName>
                </value>
                <value>
                    <fullName>DOA Functional</fullName>
                </value>
                <value>
                    <fullName>Insight RS</fullName>
                </value>
                <value>
                    <fullName>Parts Allocation</fullName>
                </value>
                <value>
                    <fullName>Qualifier/DBD</fullName>
                </value>
                <value>
                    <fullName>Software Support</fullName>
                </value>
                <value>
                    <fullName>Trust Entitlement</fullName>
                </value>
                <value>
                    <fullName>Warranty POP Validation</fullName>
                </value>
                <value>
                    <fullName>GSB-PSP Services QA</fullName>
                </value>
                <value>
                    <fullName>Proactive Care</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Process QA</relationshipLabel>
        <relationshipName>Process_QA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process QA</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>ProcessQAId</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <label>Requested Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requested_Guaranteed_Date__c</fullName>
        <label>Requested Guaranteed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Enroute_Date__c</fullName>
        <label>WorkOrder Enroute Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Fixed_Date__c</fullName>
        <label>WorkOrder Onsite Repair Fixed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Start_Date__c</fullName>
        <label>WorkOrder Onsite Repair Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>isAuthorized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>腾讯查询用，是否已授权</description>
        <label>isOfflineApplyFax</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_SA_QueryCaseSync.cls
/**
 * 客户报修同步查询case
 * 腾讯TC
 * @author xiao-weil
 * @date   2016.11.21
 * https://cs31.salesforce.com/services/apexrest/SFDCQueryCaseSync/
 */
@RestResource(urlMapping='/SFDCQueryCaseSync/*')

global with sharing class CSC_SA_QueryCaseSync{

    //请求参数对象
    global class AppInput{
		public String systemName;
		public CSC_SA_QueryCaseSync.InterfaceQueryCase content;
    }
	global class InterfaceQueryCase{
		public String vendorTaskID;//case ID
	}

    //响应请求参数
    global class AppOut {
        public String rstCode;//0: Success; -1:Error
        public String rstMsg;//error message
        public CSC_SA_QueryCaseSync.SyncQueryCaseRstDetail details;//查询结果
    }

    global class SyncQueryCaseRstDetail {
        public String workOrderId; //厂商的工单ID
		public String caseStatus; //case状态
		public String promiseOnsiteTime; //承诺上门时间
		public String ownerName;//受理人
		//public String customerChangedTime; //客户改约时间
		public String engineerArriveTime; //工程师到达时间
		public String actualRepairTime; //实际维修时间
		public String repairEndTime; //维修完成时间
		public String remark; //厂商特殊字段组合

		public String isAuthorized;//2017-2-21CR 对应  是否已授权
		
		public List<CSC_SA_QueryCaseSync.SyncQueryCaseProcessQA> processQaList;//改约原因信息
		public List<CSC_SA_QueryCaseSync.SyncQueryCaseASCEngineer> ascEngineerList;//派单工程师信息
		public List<CSC_SA_QueryCaseSync.SyncQueryCasePartsSum> partsSumList;//备件情况 工程师上门前获取的备件信息
		public List<CSC_SA_QueryCaseSync.SyncQueryCaseParts> partsList;//实际更换部件
		public List<CSC_SA_QueryCaseSync.SyncQueryCaseParts> doaPartsList;//DOA部件信息
		//
		public List<CSC_SA_QueryCaseSync.SyncQueryCaseParts> changedpartsList;//remove部件信息
    }

	global class SyncQueryCaseProcessQA {
        public String qaCode; //changedReason改约原因
		public String qaDate; //改约时间 1月
    }

	global class SyncQueryCaseASCEngineer {
        public String engineerName; //工程师姓名
		public String engineerPhone; //工程师电话
		public String engineerIDNo; //工程师身份证
    }

	//备件情况 工程师上门前获取的备件信息
	global class SyncQueryCasePartsSum {
		public String PartType; //备件类型
        public String partPN; //原厂备件PN
		public Integer partCount; //数量
    }

	//部件信息
	global class SyncQueryCaseParts {
        public String PartType; //实际备件类型
		public String partPN; //实际备件PN
		public String partSN; //实际备件SN
    }

    @HttpPost
    global static AppOut doPost(CSC_SA_QueryCaseSync.AppInput syncCase) {
        AppOut out = new AppOut();
        out.rstCode='0';
        out.rstMsg='';
        out.details = new CSC_SA_QueryCaseSync.SyncQueryCaseRstDetail();
		out.details.processQaList = new List<CSC_SA_QueryCaseSync.SyncQueryCaseProcessQA>();
		out.details.ascEngineerList = new List<CSC_SA_QueryCaseSync.SyncQueryCaseASCEngineer>();
		out.details.partsList = new List<CSC_SA_QueryCaseSync.SyncQueryCaseParts>();
		out.details.doaPartsList = new List<CSC_SA_QueryCaseSync.SyncQueryCaseParts>();
		out.details.partsSumList = new List<CSC_SA_QueryCaseSync.SyncQueryCasePartsSum>();
        try {
            System.debug('请求参数 ： '+syncCase);
			//根据工单号查询工单信息并构造返回对象中的工单部分
			String workOrderID = syncCase.content.vendorTaskID;
			String queryStr = 'select ID,CaseID,Status,owner.LastName,Requested_Guaranteed_Date__c,Requested_Date__c,Subcase_Enroute_Date__c,Subcase_Onsite_Start_Date__c, ';
			queryStr += 'Subcase_Onsite_Fixed_Date__c,Description,isAuthorized__c ';
			queryStr += 'from WorkOrder Where ID = :workOrderID';
			List<WorkOrder> wos = Database.query(queryStr);
			System.debug('工单信息 ： ' + wos);
			if(wos.size()>0 ){
				WorkOrder wo = wos[0];
				out.details.workOrderId = wo.ID;//工单ID
				out.details.caseStatus = '受理';//已受理报修: 系统单号生成即理解为已经受理 （workorder ID 返回给腾讯）
				out.details.remark = wo.Description;//Remark
				out.details.ownerName = wo.Owner.lastname;
				out.details.promiseOnsiteTime ='';
				//out.details.customerChangedTime ='';
				out.details.engineerArriveTime ='';
				out.details.repairEndTime ='';
				out.details.actualRepairTime ='';
				out.details.isAuthorized = String.valueOf(wo.isAuthorized__c);
				if(wo.Requested_Date__c != null)
					out.details.promiseOnsiteTime = wo.Requested_Date__c.format('yyyy-MM-dd hh:mm:ss');//承诺上门时间
				//if(wo.Requested_Date__c != null)
					//out.details.customerChangedTime = wo.Requested_Date__c.format('yyyy-MM-dd hh:mm:ss');//客户改约时间
				if(wo.Subcase_Enroute_Date__c != null)
					out.details.engineerArriveTime = wo.Subcase_Enroute_Date__c.format('yyyy-MM-dd hh:mm:ss');//工程师到达时间
				if(wo.Subcase_Onsite_Start_Date__c != null)
					out.details.repairEndTime = wo.Subcase_Onsite_Start_Date__c.format('yyyy-MM-dd hh:mm:ss');//实际维修时间
				if(wo.Subcase_Onsite_Fixed_Date__c != null)
					out.details.actualRepairTime = wo.Subcase_Onsite_Fixed_Date__c.format('yyyy-MM-dd hh:mm:ss');//维修完成时间

				//改约原因 [workorder的相关列表process qa的QA code]
				queryStr = 'select QA_Code__c,QA_Type__c from Process_QA__c where WorkOrder__c = :workOrderID';
				List<Process_QA__c> pqas = Database.query(queryStr);
				System.debug('process QA 信息 ： ' + pqas);
				if(pqas.size()>0){
					//获取专供腾讯查看的process QA的自定义设置
					List<String> qATypeList = new List<String> ();
					for (TCprocessQAType__c qAType :[SELECT Name FROM TCprocessQAType__c]) {
						qATypeList.add(qAType.Name);
					}
					for(Process_QA__c pqa : pqas){
						for(String qATypeF:qATypeList){
							if(qATypeF.equals(pqa.QA_Type__c)){
								CSC_SA_QueryCaseSync.SyncQueryCaseProcessQA syncObj= new CSC_SA_QueryCaseSync.SyncQueryCaseProcessQA();
								syncObj.qaCode = pqa.QA_Code__c;
								if(wo.Requested_Date__c != null)
									syncObj.qaDate = wo.Requested_Date__c.format('yyyy-MM-dd hh:mm:ss');
								out.details.processQaList.add(syncObj);
								break;
							}
						}
					}
				}

				//查询工单下备件PN以及数量
				Map<String,CSC_SA_QueryCaseSync.SyncQueryCasePartsSum> countMap = new Map<String,CSC_SA_QueryCaseSync.SyncQueryCasePartsSum>();
				queryStr = 'SELECT DeliveryPartPN__r.name,partTypeF__c FROM DeliveryParts__c where workorder__c = :workOrderID and isInstallPart__c = false and isDOA__c=false';
				List<DeliveryParts__c> tps = Database.query(queryStr);
				System.debug('备件信息(上门前) ： ' + tps);
				for(DeliveryParts__c tp : tps){
					CSC_SA_QueryCaseSync.SyncQueryCasePartsSum tpSync= new CSC_SA_QueryCaseSync.SyncQueryCasePartsSum();
					if(!countMap.containsKey(tp.DeliveryPartPN__r.name)){
						tpSync.partPN = tp.DeliveryPartPN__r.name;
						tpSync.parttype = tp.partTypeF__c;
						tpSync.partCount = 1;
						countMap.put(tp.DeliveryPartPN__r.name,tpSync);
					}else{
						tpSync = countMap.get(tp.DeliveryPartPN__r.name);
						tpSync.partCount++;
					}
				}
				out.details.partsSumList.addall(countMap.values());

				//根据工单查询工单下的实际备件信息 
				queryStr = 'select DeliveryPartPN__r.name,partTypeF__c,Name from DeliveryParts__c Where workorder__c = :workOrderID and isInstallPart__c = true';
				List<DeliveryParts__c> pos = Database.query(queryStr);
				//if(pos.size()>0)
					//out.details.caseStatus = '已派单备件';//已派单备件: 已派备件的返回：目前可以在H3C接到HPE order number 返回后视为已派备件，在phase II能够tracking 备件shipping状态后，请在备件shipping后返回给腾讯已派备件。
				System.debug('备件信息(实际安装) ： ' + pos);
				for(DeliveryParts__c po : pos){
					CSC_SA_QueryCaseSync.SyncQueryCaseParts csPart = new CSC_SA_QueryCaseSync.SyncQueryCaseParts();
					csPart.partPN = po.DeliveryPartPN__r.name;//PN
					csPart.partSN = po.Name;//SN
					csPart.parttype = po.partTypeF__c;
					out.details.partsList.add(csPart);
				}

				//根据工单查询工单下的DOA备件信息 
				queryStr = 'select DeliveryPartPN__r.name,partTypeF__c,Name from DeliveryParts__c Where workorder__c = :workOrderID and isDOA__c = true';
				List<DeliveryParts__c> posDoa = Database.query(queryStr);
				System.debug('备件信息(DOA件) ： ' + posDoa);
				for(DeliveryParts__c po : posDoa){
					CSC_SA_QueryCaseSync.SyncQueryCaseParts csPart = new CSC_SA_QueryCaseSync.SyncQueryCaseParts();
					csPart.partPN = po.DeliveryPartPN__r.name;//PN
					csPart.partSN = po.Name;//SN
					csPart.parttype = po.partTypeF__c;
					out.details.doaPartsList.add(csPart);
				}

				//2018-07-13 add by xutao 
				List<Parts_Order__c> removeParts = [SELECT Id, Removed_Parts__c, 
                        Removed_Parts_Status__c, Removed_Parts_Serial_Number__c
                        FROM Parts_Order__c 
                        WHERE Order__r.Work_Order_Name__c = :workOrderID];
                System.debug('更换下来的配件 ： ' + removeParts);
                try{
					for(Parts_Order__c po : removeParts){
						CSC_SA_QueryCaseSync.SyncQueryCaseParts csPart = new CSC_SA_QueryCaseSync.SyncQueryCaseParts();
						csPart.partPN = po.Removed_Parts__c;//PN
						csPart.partSN = po.Removed_Parts_Serial_Number__c;//SN
						csPart.parttype = po.Removed_Parts_Status__c;
						out.details.changedpartsList.add(csPart);
					}
				}catch(Exception e){
					System.debug('e.getMessage() ：' + e.getMessage());
				}

				//该工程师应为 work order 列表 ASC工程师信息的列表值
				queryStr = 'select ASCEngineer__r.Name,ASCEngineer__r.engineerIDNo__c,ASCEngineer__r.engineerPhone__c from EngineerOnSiteInfo__c where workorder__c = :workOrderID';
				List<EngineerOnSiteInfo__c> ascEngs = Database.query(queryStr);
				System.debug('EngineerOnSiteInfo__c 信息 ： ' + ascEngs);
				if(ascEngs.size()>0)
					out.details.caseStatus = '安排上门';//已安排上门: 约定上门时间确定+上门人原信息已更新
				for(EngineerOnSiteInfo__c ascEng : ascEngs){
					CSC_SA_QueryCaseSync.SyncQueryCaseASCEngineer syncObj= new CSC_SA_QueryCaseSync.SyncQueryCaseASCEngineer();
					syncObj.engineerName = ascEng.ASCEngineer__r.Name;//工程师姓名
					syncObj.engineerPhone = ascEng.ASCEngineer__r.engineerPhone__c;//工程师电话
					syncObj.engineerIDNo = ascEng.ASCEngineer__r.engineerIDNo__c;//工程师身份证
					out.details.ascEngineerList.add(syncObj);
				}

				//case 特殊状态查询
				String woCase = wo.CaseID;
				queryStr = 'select AutoRepairStutas__c from Case where id =: woCase';
				String caseAutoRepairStutas = '';
				List<Case> cas  = Database.query(queryStr);
				for(Case ca : cas){
					caseAutoRepairStutas = ca.AutoRepairStutas__c;
				}
				if(String.isNotBlank(caseAutoRepairStutas))
					out.details.caseStatus = caseAutoRepairStutas;//特殊状态
				if('Closed'.equals(wo.Status))
					out.details.caseStatus = '完成维修';//已完成维修: workorder 关闭视为完成维修

			}else{
				out.rstCode='-1';
				out.rstMsg='不存在的工单ID';
			}
        } catch(Exception e) {
            out.rstCode='-1';
			out.rstMsg='自动报修查询接口发生异常： ' + e.getMessage()+' 行： '+ e.getLineNumber();
			out.details = null;
            System.debug('exception : ' + e.getMessage()+ ', Line Number = ' + e.getLineNumber());  
        }
        return out;
    }
}