src/objects/Business_Center_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Business Center Mapping</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Zip_Postal_Code__c</fullName>
        <defaultValue>&apos;100000&apos;</defaultValue>
        <label>Billing Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Entitle_Guaranteed_DT__c</fullName>
        <label>Entitle Guaranteed D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_Latested_DT__c</fullName>
        <label>Latested D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_Product_Description__c</fullName>
        <label>Product Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Requested_DT__c</fullName>
        <label>Requested D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_Requested_Guaranteed_DT__c</fullName>
        <label>Requested Guaranteed D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Severity__c</fullName>
        <defaultValue>&apos;3-Normal&apos;</defaultValue>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-Critical-Down</fullName>
                </value>
                <value>
                    <fullName>2-Critical-Degraded</fullName>
                </value>
                <value>
                    <fullName>3-Normal</fullName>
                </value>
                <value>
                    <fullName>4-Low Priority</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>重庆市</fullName>
                </value>
                <value>
                    <fullName>重庆市-北碚区</fullName>
                </value>
                <value>
                    <fullName>重庆市-璧山</fullName>
                </value>
                <value>
                    <fullName>重庆市-长寿区</fullName>
                </value>
                <value>
                    <fullName>重庆市-城口县</fullName>
                </value>
                <value>
                    <fullName>重庆市-大足县</fullName>
                </value>
                <value>
                    <fullName>重庆市-垫江县</fullName>
                </value>
                <value>
                    <fullName>重庆市-丰都</fullName>
                </value>
                <value>
                    <fullName>重庆市-奉节</fullName>
                </value>
                <value>
                    <fullName>重庆市-合川市</fullName>
                </value>
                <value>
                    <fullName>重庆市-江北区</fullName>
                </value>
                <value>
                    <fullName>重庆市-江津市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>Shanxi</fullName>
                </value>
                <value>
                    <fullName>Shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA_TYPE__c</fullName>
        <formula>Entitlement.SLA_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLA_TYPE</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>Coverage_Response__c</fullName>
        <description>Entitlement&apos;s Coverage/Response</description>
        <label>Coverage/Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Type__c</fullName>
        <label>SLA Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_Product_Description__c</fullName>
        <formula>Case.CSC_Product_Description__c</formula>
        <label>Product Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <formula>Case.CSC_SN__c</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Severity__c</fullName>
        <description>技术升级 Severity</description>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>江苏-常熟</fullName>
                </value>
                <value>
                    <fullName>江苏-常州</fullName>
                </value>
                <value>
                    <fullName>江苏-东台</fullName>
                </value>
                <value>
                    <fullName>江苏-淮安</fullName>
                </value>
                <value>
                    <fullName>江苏-淮阴</fullName>
                </value>
                <value>
                    <fullName>江苏-江阴</fullName>
                </value>
                <value>
                    <fullName>江苏-昆山</fullName>
                </value>
                <value>
                    <fullName>江苏-连云港</fullName>
                </value>
                <value>
                    <fullName>江苏-南京</fullName>
                </value>
                <value>
                    <fullName>江苏-南通</fullName>
                </value>
                <value>
                    <fullName>江苏-邳州</fullName>
                </value>
                <value>
                    <fullName>江苏-苏州</fullName>
                </value>
                <value>
                    <fullName>江苏-太仓</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA_Type__c</fullName>
        <label>SLA Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_New_WorkOrder_Elevation_Controller.cls
/**
     类名: CSC_New_WorkOrder_Elevation_Controller
     功能说明: 技术升级，创建Record Type是 H3C->ERT 的Wrok Order
     参数说明: 
     返回值: 
     作者: Hunter
     日期: 2016-11-16
*****************************************************************************************
* Edit Date: 2017-03-17 By Chen, Xiaoqian 
* Edit No: ed1
* CSC_New_WorkOrder_Page add action="{!redirect}
* If the work order is "H3C->CoE" go the the CSC_New_WorkOrder_Elevation_Page
***************************************************************************************************/
public class CSC_New_WorkOrder_Elevation_Controller {
        public WorkOrder wo{get;set;}
    public Case myCase{get;set;}
    public string case_id{get;set;}
    public string div_style{get;set;}
    public integer click_count{get;set;}
    public string mobile{get;set;}
    public string recordTypeName{get;set;} //ed1

    /**
     方法名: CSC_New_WorkOrder_Elevation_Controller
     功能说明: 构造函数，根据传递过来的CaseID 和 Work order 的 Record type 构造 Work Order
     参数说明: 
     返回值: 
     作者: Hunter
     日期: 2016-11-15
    */
    public CSC_New_WorkOrder_Elevation_Controller(ApexPages.StandardController controller) {
        click_count=0;
        wo = new WorkOrder();
        wo.OwnerId=userInfo.getUserId();
        Map<string,string> keyToValue=ApexPages.currentPage().getParameters();
        case_id='';
        
        for(string key:keyToValue.keySet())
        {
            if(key.indexOf('Case_lkid')>=0)
            {
                case_id = keyToValue.get(key);
            }
            if(key.indexOf('RecordType')>=0)
            {
                wo.RecordTypeId = keyToValue.get(key);
                RecordType rc=[Select Name From RecordType Where Id=:wo.RecordTypeId];
                recordTypeName = rc.Name;
            }        
        }
        

        system.debug('keyToValue:'+keyToValue);
        system.debug('case_id:'+case_id);
        if(case_id=='')
        {
            div_style='display:none;';
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.severity.ERROR, 'The case message load failed, please do not click continue button waiting the page loaded in record type select page.');
            ApexPages.addMessage(errMsg);
            return;
        }
        myCase=[Select CSC_Requested_DT__c,CSC_Latested_DT__c,CSC_Requested_Guaranteed_DT__c,CSC_Entitle_Guaranteed_DT__c,
            Status,Id,CaseNumber,Subject,AccountId,EntitlementId,Entitlement.SLA_Type__c,Entitlement.Coverage_Response__c,ContactId,Description,Priority,
            CSC_Severity__c,CSC_Product_Description__c,CSC_SN__c,Billing_Street__c,Billing_Zip_Postal_Code__c,City__c,CSC_Country__c,Province__c 
            From Case Where Id=:case_id];
        if(myCase==null || myCase.Id == null)
        {
            div_style='display:none;';
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.severity.ERROR, 'The case message load failed, please provide valid case id.');
            ApexPages.addMessage(errMsg);
            
            return;
        }
        div_style='';
        if(myCase.Status=='Closed')
        {
            div_style='display:none;';
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.severity.ERROR, 'The case is closed,the workorder can not be created.');
            ApexPages.addMessage(errMsg);
            
            return;
        }
        wo.CaseId=case_id;
        List<WorkOrder> woList=[Select Id From WorkOrder Where CaseId=:case_id];
        integer count=woList.size()+1;
        wo.Work_Order_Name__c=myCase.CaseNumber+'-'+string.valueOf(count);
        
        wo.Province__c = myCase.Province__c;
        wo.City__c = myCase.City__c;
        List<Business_Center_Mapping__c> maps = [select Id, Business_Center_Name__c,Province__c from Business_Center_Mapping__c where Province__c =: wo.Province__c];
        if(maps.Size() > 0)
        {
            wo.Business_Center_Name__c = maps[0].Business_Center_Name__c;
        }
        else
        {
            div_style='display:none;';
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.severity.ERROR, 'The province cannot mapping to Business Center, please contact the system administrator');
            ApexPages.addMessage(errMsg);
            return;
        }
        
        wo.Subject= recordTypeName=='H3C->ERT'?'':myCase.Subject;
        wo.AccountId=myCase.AccountId;
        wo.EntitlementId=myCase.EntitlementId;
        if(myCase.EntitlementId != null)
        {
            wo.SLA__c=myCase.Entitlement.Coverage_Response__c;
            wo.SLA_Type__c=myCase.Entitlement.SLA_Type__c;
        }
        wo.ContactId=myCase.ContactId;
        wo.Description=myCase.Description;
        wo.Priority=myCase.Priority;
        
        if(myCase.CSC_Requested_DT__c!=null)
        {
            wo.Requested_Date__c=myCase.CSC_Requested_DT__c;
        }
        else
        {
            wo.Requested_Date__c=system.now();
        }
        wo.Requested_Guaranteed_Date__c=myCase.CSC_Requested_Guaranteed_DT__c;
        user u = [select id,MobilePhone,Phone from user where id != :userinfo.getUserId() limit 1];
        
                System.debug('mp:' + u.MobilePhone);
                System.debug('p:' + u.Phone);
                mobile = Utility.ReturnPhone(u.MobilePhone, u.Phone);
                System.debug('m:' + mobile);
    }

    /**
     方法名: Save
     功能说明: 保存work order 到数据库 并跳转到 work order 详细页
     参数说明: 
     返回值: 
     作者: Hunter
     日期: 2016-11-15
    */
    public PageReference Save()
    {
        try{
            system.debug('wo:'+wo);
            wo.Skill_Category__c='None';
            wo.Skill_Name__c='None';
            wo.Level__c='None';
            //
            //2018-06-08 重新计算 要求workOrder 赋值 依照Case
            myCase = [Select AccountId,EntitlementId,Entitlement.SLA_Type__c,Entitlement.Coverage_Response__c,ContactId,Priority From Case Where Id=:case_id];
            wo.AccountId=myCase.AccountId;
            wo.EntitlementId=myCase.EntitlementId;
            if(myCase.EntitlementId != null)
            {
                wo.SLA__c=myCase.Entitlement.Coverage_Response__c;
                wo.SLA_Type__c=myCase.Entitlement.SLA_Type__c;
            }
            wo.ContactId=myCase.ContactId;
            wo.Priority=myCase.Priority;

            insert wo;
            string url='/'+wo.Id;
            PageReference pageRef = new PageReference(url);
            return pageRef;
        }
        catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
            return null;
        }
    }
    
    /**
     方法名: Cancel
     功能说明: 取消操作，返回case 页面
     参数说明: 
     返回值: 
     作者: Hunter
     日期: 2016-11-15
    */
    public PageReference Cancel()
    {
        string url='/'+case_id;        
        PageReference pageRef = new PageReference(url);
        return pageRef;
    }

}