src/objects/Callout_Failed_Record__c.object
<CustomObject>
    <fields>
        <fullName>Callout_Type__c</fullName>
        <label>Callout Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SendMessage</fullName>
                </value>
                <value>
                    <fullName>ElevationClosure</fullName>
                </value>
                <value>
                    <fullName>CloseSubKCase</fullName>
                </value>
                <value>
                    <fullName>RejectSubKCase</fullName>
                </value>
                <value>
                    <fullName>SubKAddNotesToHPE</fullName>
                </value>
                <value>
                    <fullName>ParklotForCloseCase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Failed_Id__c</fullName>
        <label>Failed Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Failure_Type__c</fullName>
        <description>call out 失败的ReturnError
call out exception包括timeout之类的exception
Resended已经被地方接收，不需要再次接收。</description>
        <label>Failure Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ReturnError</fullName>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sync_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Indicator</label>
        <type>Checkbox</type>
    </fields>
    <label>Callout Failed Record</label>
    <nameField>
        <displayFormat>fal-{00000}</displayFormat>
        <label>Call Out Failed Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_GSEM_UpdateFailedRecordTest.cls
@isTest
private class CSC_GSEM_UpdateFailedRecordTest {
    static testMethod void testAll() {

        CSC_GSEM_UpdateFailedRecord.AppInput input = CSC_GSEM_UpdateFailedRecord.doPost(null);
        System.assertEquals(false, input.Rst);

        Callout_Failed_Record__c cfrc = new Callout_Failed_Record__c();
        cfrc.Failed_Id__c = 'test';
        cfrc.Failure_Type__c = 'Exception';
        cfrc.Callout_Type__c = 'ParklotForCloseCase';
        cfrc.Sync_Indicator__c = false;

        insert cfrc;

        input = CSC_GSEM_UpdateFailedRecord.doPost(new String[]{'test'});
        System.assert(true, input.Rst);

        input = CSC_GSEM_UpdateFailedRecord.doPost(new String[]{'test1'});
        System.assert(true, input.Rst);

    }
}