src/objects/Callout_Failed_Record__c.object
<CustomObject>
    <fields>
        <fullName>Callout_Type__c</fullName>
        <label>Callout Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SendMessage</fullName>
                </value>
                <value>
                    <fullName>ElevationClosure</fullName>
                </value>
                <value>
                    <fullName>CloseSubKCase</fullName>
                </value>
                <value>
                    <fullName>RejectSubKCase</fullName>
                </value>
                <value>
                    <fullName>SubKAddNotesToHPE</fullName>
                </value>
                <value>
                    <fullName>ParklotForCloseCase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Failed_Id__c</fullName>
        <label>Failed Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Indicator</label>
        <type>Checkbox</type>
    </fields>
    <label>Callout Failed Record</label>
    <nameField>
        <displayFormat>fal-{00000}</displayFormat>
        <label>Call Out Failed Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_OTC__c</fullName>
        <label>OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>05R-Normal Contract</fullName>
                    <color>#0B6FCE</color>
                    <label>05R-Normal Contract</label>
                </value>
                <value>
                    <fullName>02N-Warranty Normal</fullName>
                    <color>#78C953</color>
                    <label>02N-Warranty Normal</label>
                </value>
                <value>
                    <fullName>05A-Complmt TAC</fullName>
                    <color>#E27001</color>
                    <label>05A-Complmt TAC</label>
                </value>
                <value>
                    <fullName>05K-Extended Warranty</fullName>
                    <color>#A845DC</color>
                    <label>05K-Extended Warranty</label>
                </value>
                <value>
                    <fullName>05Q-Preventative</fullName>
                    <color>#F3D904</color>
                    <label>05Q-Preventative</label>
                </value>
                <value>
                    <fullName>02G-Sevice Note</fullName>
                    <color>#A53711</color>
                    <label>02G-Sevice Note</label>
                </value>
                <value>
                    <fullName>06J-Intl Gratis</fullName>
                    <color>#66E9BD</color>
                    <label>06J-Intl Gratis</label>
                </value>
                <value>
                    <fullName>00C-Cust Claims Cont</fullName>
                    <color>#0B24BE</color>
                    <label>00C-Cust Claims Cont</label>
                </value>
                <value>
                    <fullName>00W-Cust Claims Warr</fullName>
                    <color>#419249</color>
                    <label>00W-Cust Claims Warr</label>
                </value>
                <value>
                    <fullName>00E-No Entitlement</fullName>
                </value>
                <value>
                    <fullName>01-Trade</fullName>
                    <color>#B6E32E</color>
                    <label>01-Trade</label>
                </value>
                <value>
                    <fullName>06M-Intl re-repair</fullName>
                    <color>#641CCF</color>
                    <label>06M-Intl re-repair</label>
                </value>
                <value>
                    <fullName>05F-Comp Fld Inst</fullName>
                    <color>#F96FB7</color>
                    <label>05F-Comp Fld Inst</label>
                </value>
                <value>
                    <fullName>05S-Compl Site Prep</fullName>
                    <color>#2F5D85</color>
                    <label>05S-Compl Site Prep</label>
                </value>
                <value>
                    <fullName>06F-Intl Field Instl</fullName>
                    <color>#AFCADF</color>
                    <label>06F-Intl Field Instl</label>
                </value>
                <value>
                    <fullName>05P-Contracts: Predictive Support</fullName>
                    <color>#8F6429</color>
                    <label>05P-Contracts: Predictive Support</label>
                </value>
                <value>
                    <fullName>09U-UWD Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Courier Assist</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Sub_code__c</fullName>
        <label>Resolution Sub-code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Code__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HW Issue</fullName>
                </value>
                <value>
                    <fullName>SW Issue</fullName>
                </value>
                <value>
                    <fullName>Firmware/BIOS/Driver updates (except 3Par)</fullName>
                </value>
                <value>
                    <fullName>Implementation/Configuration/Setup questions</fullName>
                </value>
                <value>
                    <fullName>Non-Technical/Presales/Contract Coverage</fullName>
                </value>
                <value>
                    <fullName>Customer self-solved without HP assistance</fullName>
                </value>
                <value>
                    <fullName>Duplicate case logged</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Failed RPL</fullName>
                </value>
                <value>
                    <fullName>Unable to reach customer to begin diagnosis</fullName>
                </value>
                <value>
                    <fullName>Customer unwilling/Unable to perform remote diagnosis and/or implement action plan</fullName>
                </value>
                <value>
                    <fullName>Transferred out of HP EG</fullName>
                </value>
                <value>
                    <fullName>Customer declined billable service</fullName>
                </value>
                <value>
                    <fullName>Reject Subk Subcode</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Type__c</fullName>
        <label>Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-site</fullName>
                </value>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Remote resolve</fullName>
                </value>
                <value>
                    <fullName>Remote Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HPE_EConcierge_ID__c</fullName>
        <description>E-Concierge Id</description>
        <label>HPE EConcierge ID</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/GSEM_Post_Url__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Address__c</fullName>
        <description>relative address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GSEM Post Url</label>
</CustomObject>

src/objects/GSEM_Token__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>access_token1__c</fullName>
        <label>access_token1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>access_token2__c</fullName>
        <label>access token2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>client_id__c</fullName>
        <label>client_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>expires__c</fullName>
        <label>expires</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>issued__c</fullName>
        <label>issued</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>refresh_token__c</fullName>
        <label>refresh_token</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>role__c</fullName>
        <label>role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>token_type__c</fullName>
        <label>token_type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userName__c</fullName>
        <label>userName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GSEM Token</label>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Interface_URL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>GSEM_Service_Client_id__c</fullName>
        <label>GSEM Service Client_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GSEM_Service_Client_secret__c</fullName>
        <label>GSEM Service Client_secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GSEM_Service_Host__c</fullName>
        <description>base host</description>
        <label>GSEM Service Host</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GSEM_Service_Password__c</fullName>
        <label>GSEM Service Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GSEM_Service_UsreName__c</fullName>
        <label>GSEM Service UsreName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Interface URL</label>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSCGSEMEconciergeParklotForCloseCaseTest.cls
@isTest
private class CSCGSEMEconciergeParklotForCloseCaseTest {

    class CSC_GSEM_ParklotCloseMock implements HTTPCalloutMock{
	    public HttpResponse respond(HTTPRequest req){
	    	HttpResponse res = new HTTPResponse();
	    	CSC_GSEM_SubKAddNotesToHPE.AppInput out = new CSC_GSEM_SubKAddNotesToHPE.AppInput(true,'success!');
	    	String response = JSON.serialize(out);
	    	System.debug('response:'+response);
	        res.setHeader('Content-Type', 'application/json');
	        res.setBody(response);
	        res.setStatusCode(200);
	        res.setStatus('OK'); 
	       	return res;
	    }
	}

	class CSC_GSEM_ParklotCloseResponse500ErrorMock implements HTTPCalloutMock{
	    public HttpResponse respond(HTTPRequest req){
	    	HttpResponse res = new HTTPResponse();
	    	CSC_GSEM_SubKAddNotesToHPE.AppInput out = new CSC_GSEM_SubKAddNotesToHPE.AppInput(true,'success!');
	    	String response = JSON.serialize(out);
	    	System.debug('response:'+response);
	        res.setHeader('Content-Type', 'application/json');
	        res.setBody(response);
	        res.setStatusCode(505);
	        res.setStatus('OK'); 
	       	return res;
	    }
	}

	class CSC_GSEM_ParklotCloseJSONErrorMock implements HTTPCalloutMock{
	    public HttpResponse respond(HTTPRequest req){
	    	HttpResponse res = new HTTPResponse();
	        res.setHeader('Content-Type', 'application/json');
	        res.setBody('{"test":}');
	        res.setStatusCode(200);
	        res.setStatus('OK'); 
	       	return res;
	    }
	}

	@TestSetup
	static void setup(){
		GSEM_Post_Url__c  url = new  GSEM_Post_Url__c();
        url.Address__c = '/GsemAgent/SubK/ParklotForCloseCase';
        url.Name = 'ParklotForCloseCase';
        insert url;

        Interface_URL__c inu = new Interface_URL__c();
        inu.GSEM_Service_UsreName__c='test2';
        inu.GSEM_Service_Client_secret__c='TestClientSecret';
        inu.GSEM_Service_Client_id__c='TestClientId';
        inu.GSEM_Service_Password__c='pwd2fortest';
        inu.GSEM_Service_Host__c = 'http://122.225.207.237:8087';
        inu.Name='Interface URL';
        insert inu;

        GSEM_Token__c tokenc = new GSEM_Token__c();
        tokenc.Name = 'using';
        tokenc.token_type__c='bearer';
        tokenc.client_id__c = 'TestClientId';
        tokenc.role__c = 'Test';
        Datetime issued = System.now().addHours(-1);
        tokenc.issued__c = issued;
        tokenc.userName__c='test2';
        tokenc.refresh_token__c='407e91226b33402ca4cf69a9859c6769';
        tokenc.access_token1__c='PLyXCTNNSdGbN-GkGn9TbM9S-5yXM6ngL-HYljZWk8TojItDZfuqFZYLl9W7qfBhYytQD0y1_MvuDlwh4ieXl1tsxojtvBUCfNfNDvehz9UmG5SzEfEzADmHePOVY6_Gb7kJ7fIq6CxfLudUWCLOWCL_PiZy3rHfzxNoatQSyIM5p_nXV14D5NBxqA0mFcrSHin35qPP8e3ZqDM0gYx8vW2ko3iJIoOSkLe2ERt2yPTctivgxtZXL7LF2c1Dn8P';
        tokenc.expires__c = issued.addHours(24);
        tokenc.access_token2__c='K1_9AfZ3YvL9sejM1FEh7Yo8OoY7Gev-LVJCRmZuJx76KfPGm4lrbwUZTIdL3AtZLN1nGBP9IrPNw4ZeUDGZ-XXTYWaa5WgQItC7v_51DUoc';
        insert tokenc;
	}

    static testMethod void testNormal() {
        CSC_GSEM_EconciergeParklotForCloseCase gsem = new CSC_GSEM_EconciergeParklotForCloseCase();
		
        Case c = CSC_GSEM_SubKCreateCase_Test.GetHPECase();

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new CSC_GSEM_ParklotCloseMock());
        CSC_GSEM_Response out = gsem.parklotForCloseCase(c.Id);
        System.assertEquals(true, out.Rst);

        out = gsem.parklotForCloseCase(null);
        System.assertEquals('Empty H3CID!', out.RstMsg);

        out = gsem.parklotForCloseCase('testcaseid');
        System.assertEquals('Case not found!', out.RstMsg);

        Test.setMock(HttpCalloutMock.class, new CSC_GSEM_ParklotCloseResponse500ErrorMock());
        out = gsem.parklotForCloseCase(c.Id);
        System.assertEquals(false, out.Rst);

        Test.setMock(HttpCalloutMock.class, new CSC_GSEM_ParklotCloseJSONErrorMock());
        out = gsem.parklotForCloseCase(c.Id);
        System.assertEquals(false, out.Rst);
        
        Test.stopTest();
    }

    static testMethod void testAbNormal() {
        CSC_GSEM_EconciergeParklotForCloseCase gsem = new CSC_GSEM_EconciergeParklotForCloseCase();
        
        Case c = CSC_GSEM_SubKCreateCase_Test.GetHPECase();
        c.HPE_EConcierge_ID__c = 'test_econcierge_id'; //设置EconciergeId的值
        update c;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new CSC_GSEM_ParklotCloseMock());
        CSC_GSEM_Response out = gsem.parklotForCloseCase(c.Id);
        System.assertEquals(true, out.Rst);

        Test.setMock(HttpCalloutMock.class, new CSC_GSEM_ParklotCloseResponse500ErrorMock());
        out = gsem.parklotForCloseCase(c.Id);
        System.assertEquals(false, out.Rst);

        List<Callout_Failed_Record__c> fails = [SELECT Id, Failed_Id__c,Callout_Type__c 
                                            FROM Callout_Failed_Record__c
                                            WHERE Failed_Id__c=:c.Id
                                            AND Sync_Indicator__c = false];
        System.assertEquals(0, fails.size());
        
        Test.stopTest();
    }

    static testMethod void testNotOTC() {
        CSC_GSEM_EconciergeParklotForCloseCase gsem = new CSC_GSEM_EconciergeParklotForCloseCase();
		
        Case c = CSC_GSEM_SubKCreateCase_Test.GetHPECase();
        c.CSC_OTC__c = '06M-Intl re-repair';
        update c;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new CSC_GSEM_ParklotCloseMock());
        CSC_GSEM_Response out = gsem.parklotForCloseCase(c.Id);
        System.assertEquals('Case is not OTC(05K,05R,02N,02G,00C,00W,00E)! '+ c.CSC_OTC__c, 
        	out.RstMsg);
        
        Test.stopTest();
    }

    static testMethod void testisCaseforEconcierge(){
    	CSC_GSEM_EconciergeParklotForCloseCase gsem = new CSC_GSEM_EconciergeParklotForCloseCase();
		
        Case cas = CSC_GSEM_SubKCreateCase_Test.GetHPECase();
        cas.CSC_Resolution_Type__c = 'Remote Other';
        cas.CSC_Resolution_Code__c ='Void';
        cas.CSC_Resolution_Sub_code__c = 'Test Case';
        update cas;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new CSC_GSEM_ParklotCloseMock());
        CSC_GSEM_Response out = gsem.parklotForCloseCase(cas.Id);
        System.assertEquals('Case Resolution code is not for econcierge.'
                +',CSC_Resolution_Type__c is:'+ cas.CSC_Resolution_Type__c
                +',CSC_Resolution_Code__c is:'+ cas.CSC_Resolution_Code__c
                + ',CSC_Resolution_Sub_code__c is:' + cas.CSC_Resolution_Sub_code__c, 
        	out.RstMsg);
        
        Test.stopTest();
    }
}