src/objects/Callout_Failed_Record__c.object
<CustomObject>
    <fields>
        <fullName>Callout_Type__c</fullName>
        <label>Callout Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SendMessage</fullName>
                </value>
                <value>
                    <fullName>ElevationClosure</fullName>
                </value>
                <value>
                    <fullName>CloseSubKCase</fullName>
                </value>
                <value>
                    <fullName>RejectSubKCase</fullName>
                </value>
                <value>
                    <fullName>SubKAddNotesToHPE</fullName>
                </value>
                <value>
                    <fullName>ParklotForCloseCase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Failed_Id__c</fullName>
        <label>Failed Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Failure_Type__c</fullName>
        <description>call out 失败的ReturnError
call out exception包括timeout之类的exception
Resended已经被地方接收，不需要再次接收。</description>
        <label>Failure Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ReturnError</fullName>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sync_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Indicator</label>
        <type>Checkbox</type>
    </fields>
    <label>Callout Failed Record</label>
    <nameField>
        <displayFormat>fal-{00000}</displayFormat>
        <label>Call Out Failed Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_GSEM_GetBadEconciergeIds_Test.cls
@isTest
private class CSC_GSEM_GetBadEconciergeIds_Test {

    static testMethod void testNormal() {
        CSC_GSEM_GetBadEconciergeIds.AppInput rl = CSC_GSEM_GetBadEconciergeIds.doPost(0);
        System.assertEquals(0, rl.caseIdList.size());

        Case cas = CSC_GSEM_SubKCreateCase_Test.GetHPECase();

        Callout_Failed_Record__c fail = new Callout_Failed_Record__c();
        fail.Failed_Id__c = cas.Id;
        fail.Callout_Type__c = 'ParklotForCloseCase';
        fail.Error_Message__c = 'test';
        fail.Failure_Type__c = 'ReturnError';
        fail.Sync_Indicator__c = false;
        insert fail;

        rl = CSC_GSEM_GetBadEconciergeIds.doPost(0);
        System.assertEquals(1, rl.caseIdList.size());
    }
}