src/objects/Callout_Failed_Record__c.object
<CustomObject>
    <fields>
        <fullName>Failed_Id__c</fullName>
        <label>Failed Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Callout Failed Record</label>
    <nameField>
        <displayFormat>fal-{00000}</displayFormat>
        <label>Call Out Failed Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_PN__c</fullName>
        <label>Product Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Severity__c</fullName>
        <defaultValue>&apos;3-Normal&apos;</defaultValue>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-Critical-Down</fullName>
                </value>
                <value>
                    <fullName>2-Critical-Degraded</fullName>
                </value>
                <value>
                    <fullName>3-Normal</fullName>
                </value>
                <value>
                    <fullName>4-Low Priority</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HPE_SubK_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>HPE SubK ID</description>
        <label>HPE SubK ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <label>Work Order Name</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>OrderToWorkOrder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Parts_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Parts Order</relationshipLabel>
        <relationshipName>Parts_Order</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parts_Serial_Number__c</fullName>
        <label>Parts Serial Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Request Parts)</relationshipLabel>
        <relationshipName>Request_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_QA__c.object
<CustomObject>
    <fields>
        <fullName>QA_Code__c</fullName>
        <label>QA Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>QA_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>0A-See comments</fullName>
                </value>
                <value>
                    <fullName>0B-HP IT system down</fullName>
                </value>
                <value>
                    <fullName>AA-Entitlement Problem</fullName>
                </value>
                <value>
                    <fullName>ZZ-No Issues</fullName>
                </value>
                <value>
                    <fullName>BA-Diag.wrong/incomp</fullName>
                </value>
                <value>
                    <fullName>BH-wrong parts info</fullName>
                </value>
                <value>
                    <fullName>LA-Local issue A</fullName>
                </value>
                <value>
                    <fullName>LB-Local issue B</fullName>
                </value>
                <value>
                    <fullName>PC-Missing part info</fullName>
                </value>
                <value>
                    <fullName>PF-Damaged/DOA</fullName>
                </value>
                <value>
                    <fullName>SC-Addl prob found</fullName>
                </value>
                <value>
                    <fullName>XB-Lack skill/knowledge</fullName>
                </value>
                <value>
                    <fullName>XG-Tool/Manual missing</fullName>
                </value>
                <value>
                    <fullName>XH-Manual/Documentation not read</fullName>
                </value>
                <value>
                    <fullName>XI-CE Assist open with wrong Priority</fullName>
                </value>
                <value>
                    <fullName>XJ-CE was not onsite anymore</fullName>
                </value>
                <value>
                    <fullName>MR-Misrouted Call</fullName>
                </value>
                <value>
                    <fullName>SD-Sys Down Dependency</fullName>
                </value>
                <value>
                    <fullName>D1-IRS Assistance</fullName>
                </value>
                <value>
                    <fullName>D2-Proactive Scan</fullName>
                </value>
                <value>
                    <fullName>D3-FW&amp;SW Patch Analysis</fullName>
                </value>
                <value>
                    <fullName>D4-FW Analysis</fullName>
                </value>
                <value>
                    <fullName>D5-SW Patch Analysis</fullName>
                </value>
                <value>
                    <fullName>D6-Incident Reporting</fullName>
                </value>
                <value>
                    <fullName>Demo Center</fullName>
                </value>
                <value>
                    <fullName>Ink and Media</fullName>
                </value>
                <value>
                    <fullName>Ink Conversion</fullName>
                </value>
                <value>
                    <fullName>Trade Show</fullName>
                </value>
                <value>
                    <fullName>Machine Recertification</fullName>
                </value>
                <value>
                    <fullName>Service Delivery Absorbed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QA_Type__c</fullName>
        <label>QA Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Agent</fullName>
                </value>
                <value>
                    <fullName>CE Assist</fullName>
                </value>
                <value>
                    <fullName>CE QA</fullName>
                </value>
                <value>
                    <fullName>CE SAFE</fullName>
                </value>
                <value>
                    <fullName>Competency Center</fullName>
                </value>
                <value>
                    <fullName>Depot Repair</fullName>
                </value>
                <value>
                    <fullName>Dispatcher/RC</fullName>
                </value>
                <value>
                    <fullName>DOA Fulfillment</fullName>
                </value>
                <value>
                    <fullName>DOA Functional</fullName>
                </value>
                <value>
                    <fullName>Insight RS</fullName>
                </value>
                <value>
                    <fullName>Parts Allocation</fullName>
                </value>
                <value>
                    <fullName>Qualifier/DBD</fullName>
                </value>
                <value>
                    <fullName>Software Support</fullName>
                </value>
                <value>
                    <fullName>Trust Entitlement</fullName>
                </value>
                <value>
                    <fullName>Warranty POP Validation</fullName>
                </value>
                <value>
                    <fullName>GSB-PSP Services QA</fullName>
                </value>
                <value>
                    <fullName>Proactive Care</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Process QA</relationshipLabel>
        <relationshipName>Process_QA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process QA</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>ProcessQAId</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <formula>Case.CSC_SN__c</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Severity__c</fullName>
        <description>技术升级 Severity</description>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Subcase_Repair_Class_Code__c</fullName>
        <label>WorkOrder Repair Class Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DEF</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>DG</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>HM</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IR</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NR</fullName>
                </value>
                <value>
                    <fullName>NS</fullName>
                </value>
                <value>
                    <fullName>NT</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>SV</fullName>
                </value>
                <value>
                    <fullName>SW</fullName>
                </value>
                <value>
                    <fullName>UC</fullName>
                </value>
                <value>
                    <fullName>WK</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>ML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delay_Code__c</fullName>
        <label>Delay Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>CSR</fullName>
        <active>true</active>
        <description>Customer Self Resolve</description>
        <label>CSR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_GSEM_GetClosedCases.cls
/**********************************************************************
 * 
 *
 * @url: /services/apexrest/rest
 * @data:
 *  {
        
    }
*************************************************************************/
@RestResource(urlMapping='/SubK/GetClosedCases')
global with sharing class CSC_GSEM_GetClosedCases {

	global class AppInput extends CSC_GSEM_Response{
		public String Content{set;get;}
    	public AppInput(Boolean b, String msg){
    		super(b,msg);
    	}
    }

    @HttpPost
    global static AppInput doPost(Integer topCount) {
    	//0.查询出错误的caseId列表
    	List<Callout_Failed_Record__c> cfrs = CSC_GSEM_SubK_Common_Function.getFailedCaseIds('CloseSubKCase',topCount);
    	List<String> casIds = new List<String>();
    	for(Callout_Failed_Record__c cfr:cfrs){
    		casIds.add(cfr.Failed_Id__c);
    	}
    	//1.查询出topCount条失败的Case, WorkOrder, PartsOrder
    	List<Case> caslist = CSC_GSEM_SubK_Common_Function.getSubKCaseListByIds(casIds);
    	List<WorkOrder> wods = CSC_GSEM_SubK_Common_Function.getWorkOrdersByCaseIds(casIds);

    	Map<String,List<WorkOrder>> case_wo_map = new Map<String,List<WorkOrder>>();
    	for(Case cas:caslist){
    		List<WorkOrder> wos = case_wo_map.get(cas.Id);
    		if(wos == null){
    			wos = new List<WorkOrder>();
    			case_wo_map.put(cas.Id, wos);
    		}
    		for(WorkOrder wo:wods){
    			if(wo.CaseId == cas.Id){
    				case_wo_map.get(cas.Id).add(wo);
    			}
    		}
    	}

		Set<String> workOrderIds = new Set<String>();
		for(WorkOrder w:wods){
        	workOrderIds.add(w.Id);
        }
    	List<Process_QA__c> pqas =  CSC_GSEM_SubK_Common_Function.getProccessQAListbyWorkId(workOrderIds);
        Map<String,Process_QA__c> pqasMap = new Map<String,Process_QA__c>();
        for(Process_QA__c pqc:pqas){
            pqasMap.put(pqc.WorkOrder__c, pqc);
        }

		//2.查询出topCount条Case下的所有parts,并放到Map中
    	List<Parts_Order__c> paocs = CSC_GSEM_SubK_Common_Function.getPartsOrderByWorkOrderIds(workOrderIds);
    	Map<String,List<Parts_Order__c>> wo_po_map = new Map<String,List<Parts_Order__c>>();
    	for(String woId:workOrderIds){
    		if(wo_po_map.get(woId) == null){
    			wo_po_map.put(woId, new List<Parts_Order__c>());
    		}
    		for(Parts_Order__c po:paocs){
    			if(po.Order__r.Work_Order_Name__r.Id == woId){
	    			wo_po_map.get(woId).add(po);
	    		}
    		}
    	}
    	
    	
    	//3.设置Output对象
    	List<CSC_GSEM_SubKCloseCase.AppOut> outList = new List<CSC_GSEM_SubKCloseCase.AppOut>();
    	
    	CSC_GSEM_SubKCloseCase sc = new CSC_GSEM_SubKCloseCase();

    	for(Case cas:caslist){
			CSC_GSEM_SubKCloseCase.AppOut output = new CSC_GSEM_SubKCloseCase.AppOut();
	    	output.H3CID = cas.Id;

	    	output.HPEID = cas.HPE_SubK_ID__c;

	    	output.RepairLaborType = 'Hardware Repair/Installation';
	    	// output.RepairHours = '';
	    	output.TravelLaborType = 'Travel';
	    	// output.TravelHours='';
	    	output.ProductNumber = cas.CSC_PN__c;
	    	output.SerialNumber = cas.CSC_SN__c;
	        output.CustomerSeverity = cas.CSC_Severity__c;

	    	//2.通过caseId获取Case下所有的partsOrder信息
	    	List<WorkOrder> cws = case_wo_map.get(cas.Id);

	        if(cws.size()>0){
	            WorkOrder oldestWO = sc.minWorkOrder(output,cws);

	            //repair class on the most recent closed onsite workorder
	            output.RepairClass = oldestWO.CSC_Subcase_Repair_Class_Code__c;
	            //delay code on first closed onsite workorder
	            output.DelayCode = oldestWO.Delay_Code__c;
	            //all resolution description from CSR and oniste, the oldest is first
	            output.ResolutionDescription = oldestWO.Resolution__c;

	        	if(cws.size()!=0){
	                //3.获取ProcessQA里列表
	                // List<Process_QA__c> pqas =  CSC_GSEM_SubK_Common_Function.getProccessQAListbyWorkId(workOrderIds);
	                // Map<String,Process_QA__c> pqasMap = new Map<String,Process_QA__c>();
	                // for(Process_QA__c pqc:pqas){
	                //     pqasMap.put(pqc.WorkOrder__c, pqc);
	                // }
	        		List<Parts_Order__c> pocs = new List<Parts_Order__c>();
		        	for(WorkOrder w:cws){
		        		pocs.addAll(wo_po_map.get(w.Id));
		        	}

	    			for(Parts_Order__c poc:pocs){
	    				
	                    Process_QA__c pqc = pqasMap.get(poc.Order__r.Work_Order_Name__r.Id);
	                    if(pqc!=null){
	                        CSC_GSEM_SubKCloseCase.Quality qlt = new CSC_GSEM_SubKCloseCase.Quality();
	        				qlt.QualityCode = pqc.QA_Code__c;
	        				qlt.QualityCodeType = pqc.QA_Type__c;
	                        output.Qualities.add(qlt);
	                    }

	    				CSC_GSEM_SubKCloseCase.RepairPart po = new CSC_GSEM_SubKCloseCase.RepairPart();
	    				po.PartOrderNumber = poc.Name;
	    				// po.LineItemNumber = '';

	    				po.InstalledPartNumber = poc.Request_Parts__r.Name;
	    				po.InstalledPartSerialNumber = poc.Parts_Serial_Number__c;
	    				// po.InstalledPartDescription = poc.Offered_Parts__r.Description__c;
	                    po.InstalledPartDescription = poc.Parts_Description__c;
	    				
	    				// po.SourcedLocation = '';
	    				po.PartUsageCode = poc.Parts_Usage__c;

	    				po.RemovedPartNumber = poc.Removed_Parts__r.Name;
	    				po.RemovedPartSerialNumber = poc.Removed_Parts_Serial_Number__c;
	    				po.RemovedPartDescription = poc.Removed_Parts__r.Description__c;
	    				
	    				po.PartFailureCode= poc.X_Failure_Cd__c;
	    				output.RepairParts.add(po);
	    			}
	    		}
	        } else{
	            System.debug('No WorkOrder Created!');
	        }

	        outList.add(output);
    	}
    	AppInput input = new AppInput(true,'Success!');
    	input.Content = JSON.serialize(outList);
        return input;
    }
}