src/objects/Callout_Failed_Record__c.object
<CustomObject>
    <fields>
        <fullName>Callout_Type__c</fullName>
        <label>Callout Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SendMessage</fullName>
                </value>
                <value>
                    <fullName>ElevationClosure</fullName>
                </value>
                <value>
                    <fullName>CloseSubKCase</fullName>
                </value>
                <value>
                    <fullName>RejectSubKCase</fullName>
                </value>
                <value>
                    <fullName>SubKAddNotesToHPE</fullName>
                </value>
                <value>
                    <fullName>ParklotForCloseCase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Failed_Id__c</fullName>
        <label>Failed Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Indicator</label>
        <type>Checkbox</type>
    </fields>
    <label>Callout Failed Record</label>
    <nameField>
        <displayFormat>fal-{00000}</displayFormat>
        <label>Call Out Failed Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Case_Status__c</fullName>
        <label>HPE Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>RR Closed</fullName>
                </value>
                <value>
                    <fullName>Accept Problem</fullName>
                </value>
                <value>
                    <fullName>Open Requester</fullName>
                </value>
                <value>
                    <fullName>Problem Resolution</fullName>
                </value>
                <value>
                    <fullName>Partner Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HPE_EConcierge_ID__c</fullName>
        <description>E-Concierge Id</description>
        <label>HPE EConcierge ID</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/EConciergeFailedHandler.cls
public without sharing class EConciergeFailedHandler implements Triggers.Handler {

	public void handle() {
		for (Callout_Failed_Record__c cfrc : (List<Callout_Failed_Record__c>)Trigger.new){
			if(cfrc.Callout_Type__c == 'CloseSubKCase'){
				String caseId = cfrc.Failed_Id__c;
				List<Case> cases = [select Id,CSC_Case_Status__c from Case where Id=:caseId];
				if(cases.size()>0){
					Case cas = cases[0];
					if(cas!=null){
						System.debug('CSC_Case_Status__c--'+cas.CSC_Case_Status__c);
						if(String.isNotBlank(cas.CSC_Case_Status__c) 
							&& cas.CSC_Case_Status__c =='REQUEST CLOSURE(CLOSED)'){
							cfrc.Sync_Indicator__c = true;
						}
					}
				}
			}
			if(cfrc.Callout_Type__c == 'ParklotForCloseCase'){
				String caseId = cfrc.Failed_Id__c;
				List<Case> cases = [select Id,HPE_EConcierge_ID__c from Case where Id=:caseId];
				if(cases.size()>0){
					Case cas = cases[0];
					if(cas!=null){
						System.debug('HPE_EConcierge_ID__c--'+cas.HPE_EConcierge_ID__c);
						if(String.isNotBlank(cas.HPE_EConcierge_ID__c)){
							cfrc.Sync_Indicator__c = true;
						}
					}
				}
			}

			if(cfrc.Callout_Type__c == 'SubKAddNotesToHPE'){
				String taskId = cfrc.Failed_Id__c;
				List<Task> tasks = [SELECT Id,CSC_Sync_Status__c FROM Task WHERE Id =:taskId];
				if(tasks.size()>0){
					Task tas = tasks[0];
					if(tas!=null){
						System.debug('CSC_Sync_Status__c--'+tas.CSC_Sync_Status__c);
						if(String.isNotBlank(tas.CSC_Sync_Status__c) 
							&& tas.CSC_Sync_Status__c =='Sent to HPE successful'){
							cfrc.Sync_Indicator__c = true;
						}
					}
				}
			}
		}
	}
    
}