src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Manager_Assistant_Email__c</fullName>
        <label>Campaign Manager Assistant Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Campaign_Owner_Email__c</fullName>
        <label>Campaign Owner Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sub_Work_Group__c</fullName>
        <description>UL @ibreakingpoint 20151125</description>
        <label>Sub Work Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Work_Group__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BCS</fullName>
                </value>
                <value>
                    <fullName>ISS</fullName>
                </value>
                <value>
                    <fullName>SSD</fullName>
                </value>
                <value>
                    <fullName>TSS</fullName>
                </value>
                <value>
                    <fullName>TSC</fullName>
                </value>
                <value>
                    <fullName>FSI</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>Gpcom</fullName>
                </value>
                <value>
                    <fullName>CME</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>Inside</fullName>
                </value>
                <value>
                    <fullName>Cross</fullName>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Bigdata</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Partner lead</fullName>
                </value>
                <value>
                    <fullName>H3C lead</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CampaignUpdateManagerAssistantTest.cls
@istest(seealldata=true)
public class CampaignUpdateManagerAssistantTest {
    public static testmethod void testCampaignUpdateManagerAssistant() {
        try
        {
        string rpt = [Select Id,SobjectType,Name From RecordType Where Name ='Marketing Parent Campaign' and SobjectType = 'Campaign' limit 1].Id;
        //String u1 = [Select id ,email from User where IsActive = true limit 1].id;
        //String email1 = [Select id ,email from User where IsActive = true limit 1].email;
        String u1 = [Select id ,email from User where IsActive = true and  UserPermissionsMarketingUser = true limit 1].id;
        String email1 = [Select id ,email from User where IsActive = true and  UserPermissionsMarketingUser = true limit 1].email;
        Campaign camTest = new Campaign();
        camTest.name = 'test';
        camTest.RecordTypeId = rpt;
        camTest.Sub_Work_Group__c = 'ISS';
        camTest.startDate = Date.today();
        camTest.Campaign_Owner_Email__c = email1;
        camTest.Campaign_Manager_Assistant_Email__c = email1;
        insert camTest;
        }
        catch(Exception ex)
        {
        }
    }
}