src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Manager_Assistant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>UL @ibreakingpoint 20151027</description>
        <label>Campaign Manager Assistant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <description>UL @ibreakingpoint 20151027</description>
        <label>Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Work_Group__c</fullName>
        <description>UL @ibreakingpoint 20151125</description>
        <label>Sub Work Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Work_Group__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BCS</fullName>
                </value>
                <value>
                    <fullName>ISS</fullName>
                </value>
                <value>
                    <fullName>SSD</fullName>
                </value>
                <value>
                    <fullName>TSS</fullName>
                </value>
                <value>
                    <fullName>TSC</fullName>
                </value>
                <value>
                    <fullName>FSI</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>Gpcom</fullName>
                </value>
                <value>
                    <fullName>CME</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>Inside</fullName>
                </value>
                <value>
                    <fullName>Cross</fullName>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Bigdata</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Partner lead</fullName>
                </value>
                <value>
                    <fullName>H3C lead</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>UL @breakingpoint 20151125 changed</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Collateral</fullName>
                </value>
                <value>
                    <fullName>Branding</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Social media</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Virtual event</fullName>
                </value>
                <value>
                    <fullName>Physical event</fullName>
                </value>
                <value>
                    <fullName>Tele-marketing</fullName>
                </value>
                <value>
                    <fullName>Direct mail</fullName>
                </value>
                <value>
                    <fullName>eDM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Campaign_Sub_Work_Group_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Mapping_Value__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Mapping Value</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sub_Work_Group__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Sub Work Group</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Campaign Sub Work Group Mapping</label>
</CustomObject>

src/objects/Latest_Campaign_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Latest Campaign Code for comparison.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Latest Campaign Code</label>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CampaignInsertTest.cls
@isTest
public class CampaignInsertTest {
    static testMethod void InsertTest(){
        string rpt = [Select Id,SobjectType,Name From RecordType Where Name ='Marketing Parent Campaign' and SobjectType = 'Campaign' limit 1].Id;
        string rpt2 = [Select Id,SobjectType,Name From RecordType Where Name ='Marketing Child Campaign' and SobjectType = 'Campaign' limit 1].Id;

        String u1 = [Select id ,name from User where IsActive = true limit 1].id;
        String u2 = [Select id ,name from User where IsActive = true and id != :u1 limit 1].id;
        Latest_Campaign_Code__c lCCode = new Latest_Campaign_Code__c();
        lCCode.Name = 'ISS15Q4';
        lCCode.Code__c = '01';
        insert lCCode;
        
        Campaign_Sub_Work_Group_Mapping__c cSWSetting = new Campaign_Sub_Work_Group_Mapping__c();
        cSWSetting.Name = '001';
        cSWSetting.Sub_Work_Group__c = 'ISS';
        cSWSetting.Mapping_Value__c = 'ISS';
        insert cSWSetting;
        
        Campaign camTest = new Campaign();
        Campaign camTest1 = new Campaign();
        Campaign camInsert = new Campaign();
        Campaign camInsert1 = new Campaign();
        
         
        camTest.name = 'test';
        camTest.RecordTypeId = rpt;
        camTest.Sub_Work_Group__c = 'ISS';
        camTest.startDate = Date.today();
        insert camTest;
        
        camTest1.name = 'test';
        camTest1.RecordTypeId = rpt;
        camTest1.Sub_Work_Group__c = 'Others';
        camTest1.startDate = Date.newinstance(2015, 11, 12);
        insert camTest1;
        //system.debug('RecordTypeId:'+rpt);
        Campaign cammParent = [Select id,name From Campaign Where RecordTypeId = :rpt limit 1];
        
        camInsert.name = 'test';
        camInsert.RecordTypeId = rpt2;
        camInsert.Type__c = 'Advertising';
        camInsert.Parent = cammParent;
        camInsert.startDate = Date.today();
        camInsert.Campaign_Name__c = 'testCamUpdate';
        insert camInsert;
        
        camInsert1.name = 'test';
        camInsert1.RecordTypeId = rpt2;
        camInsert1.Type__c = 'Direct mail';
        camInsert1.Sub_Work_Group__c = 'asdf';
        camInsert1.startDate = Date.today();
        camInsert1.Campaign_Name__c = 'testCamUpdate';
        insert camInsert1; 

    }
     static testMethod void InsertTest1(){
        string rpt = [Select Id,SobjectType,Name From RecordType Where Name ='Marketing Parent Campaign' and SobjectType = 'Campaign' limit 1].Id;
        string rpt2 = [Select Id,SobjectType,Name From RecordType Where Name ='Marketing Child Campaign' and SobjectType = 'Campaign' limit 1].Id;

        String u1 = [Select id ,name from User where IsActive = true limit 1].id;
        String u2 = [Select id ,name from User where IsActive = true and id != :u1 limit 1].id;
        Latest_Campaign_Code__c lCCode = new Latest_Campaign_Code__c();
        lCCode.Name = 'ISS15Q4';
        lCCode.Code__c = '11';
        insert lCCode;
        
        Campaign_Sub_Work_Group_Mapping__c cSWSetting = new Campaign_Sub_Work_Group_Mapping__c();
        cSWSetting.Name = '001';
        cSWSetting.Sub_Work_Group__c = 'ISS';
        cSWSetting.Mapping_Value__c = 'ISS';
        insert cSWSetting;
        
        Campaign camTest = new Campaign();
        Campaign camTest1 = new Campaign();
        Campaign camInsert = new Campaign();
        Campaign camInsert1 = new Campaign();
        
         
        camTest.name = 'test';
        camTest.RecordTypeId = rpt;
        camTest.Sub_Work_Group__c = 'ISS';
        camTest.startDate = Date.today();
        insert camTest;
        
        camTest1.name = 'test';
        camTest1.RecordTypeId = rpt;
        camTest1.Sub_Work_Group__c = 'Others';
        camTest1.startDate = Date.newinstance(2015, 11, 12);
        insert camTest1;
        //system.debug('RecordTypeId:'+rpt);
        Campaign cammParent = [Select id,name From Campaign Where RecordTypeId = :rpt limit 1];
        
        camInsert.name = 'test';
        camInsert.RecordTypeId = rpt2;
        camInsert.Type__c = 'Advertising';
        camInsert.Parent = cammParent;
        camInsert.startDate = Date.today();
        camInsert.Campaign_Name__c = 'testCamUpdate';
        insert camInsert;
        
        camInsert1.name = 'test';
        camInsert1.RecordTypeId = rpt2;
        camInsert1.Type__c = 'Direct mail';
        camInsert1.Sub_Work_Group__c = 'asdf';
        camInsert1.startDate = Date.today();
        camInsert1.Campaign_Name__c = 'testCamUpdate';
        insert camInsert1; 

    }  
    
    static testMethod void UpdateTest(){
        string rpt = [Select Id,SobjectType,Name From RecordType Where Name ='Marketing Parent Campaign' and SobjectType = 'Campaign' limit 1].Id;
        
        String u1 = [Select id ,name from User where IsActive = true limit 1].id;
        String u2 = [Select id ,name from User where IsActive = true and id != :u1 limit 1].id;
        
        Latest_Campaign_Code__c lCCode = new Latest_Campaign_Code__c();
        lCCode.Name = 'ISS';
        lCCode.Code__c = '01';
        insert lCCode;
        
        Campaign_Sub_Work_Group_Mapping__c cSWSetting = new Campaign_Sub_Work_Group_Mapping__c();
        cSWSetting.Name = '001';
        cSWSetting.Sub_Work_Group__c = 'ISS';
        cSWSetting.Mapping_Value__c = 'ISS';
        insert cSWSetting;
        
        Campaign camInsert = new Campaign();
        camInsert.name = 'test';
        camInsert.RecordTypeId = rpt;
        camInsert.Sub_Work_Group__c = 'ISS';
        camInsert.startDate = Date.today();
        camInsert.Campaign_Name__c = 'testCamUpdate';
        
        test.startTest();
        
        insert camInsert;  
        
        Campaign camUpdate = new Campaign();
        camUpdate = [select id, name,Campaign_Name__c from Campaign where Campaign_Name__c ='testCamUpdate' limit 1];
        camUpdate.Campaign_Manager_Assistant__c = u1;
        update camUpdate;
        
        test.stopTest();
    }
}