src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_OPTId__c</fullName>
        <description>外部系统ID（HPE）</description>
        <externalId>true</externalId>
        <label>HPE ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Safari_Status__c</fullName>
        <label>Safari_Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Integration_Status__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Integration Status</relationshipLabel>
        <relationshipName>Integration_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GSEM_Flow2_Code__c</fullName>
        <description>存放SAFARI XML 生成成功或失败代码</description>
        <inlineHelpText>Safari Error
Safari Sent</inlineHelpText>
        <label>GSEM Flow2 Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GSEM_Flow2_Message__c</fullName>
        <description>存放GSEM调用失败时返回的消息</description>
        <label>GSEM Flow2 Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{0000000000}</displayFormat>
        <label>Num</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_GSEM_KillBadCase.cls
/**************************************************************************************************
* Name: CSC_GSEM_KillBadCase
* Object: Case
* Purpose: 
* 
* Return Msg:
*  <Bool,msg>
* Author: Zhou,Xiong
* Create Date: 2016-06-18
***************************************************************************************************/
@RestResource(urlMapping='/KillBadCase/*')
global with sharing class CSC_GSEM_KillBadCase {
    
    //输入
    public class Appinput{
        public String CaseIds; //CaseId can be h3cId or hpeId
    }

    //输出
    global class AppOut {
     
        //true: Success; false:Error
        public Boolean rst;
        public String rstMsg;
    }

    @HttpPost
    global static AppOut doPost() {

        //取得request对象
        RestRequest req = RestContext.request;
        AppInput input = (CSC_GSEM_KillBadCase.AppInput)JSON.deserialize(req.requestBody.tostring(), CSC_GSEM_KillBadCase.AppInput.class);

        List<String> caseList = input.CaseIds.split(';');

        AppOut out = new AppOut();
        out.rst = true;
        out.rstMsg = '';

        try{

            /*List<Case> cases = [SELECT Id,CSC_OPTId__c,Safari_Status__c FROM Case WHERE Id In :caseList or CSC_OPTId__c In :caseList];

            //解锁
            Approval.UnlockResult[] urList = Approval.unlock(cases,false);

            for (Case item : cases){

                item.Safari_Status__c = 'Safari Re-Sent';
            }

            update cases;

            //重新锁数据
            Approval.LockResult[] lrList = Approval.lock(cases, false);*/

            List<Case> cases = [SELECT Id FROM Case WHERE Id In :caseList or CSC_OPTId__c In :caseList];

            Set<Id> ids = new Set<Id>();
            for (Case c : cases){
                ids.add(c.Id);
            }

            List<Integration_Status__c> integrationStatusList = [SELECT GSEM_Flow2_Message__c,GSEM_Flow2_Code__c FROM Integration_Status__c where Case_Name__c in :ids];

            for (Integration_Status__c inter : integrationStatusList){
                inter.GSEM_Flow2_Message__c = '';
                inter.GSEM_Flow2_Code__c = 'Safari Re-Sent';
            }

            update integrationStatusList;
            
        }catch(Exception ex) {
            out.rst = false;
            out.rstMsg = ex.getMessage();
            system.debug('out.rstMsg:' + out.rstMsg);
        }

        return out;
    }
}