src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Closer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Closer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSC_Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSC_Onsite_Fixed_Date__c</fullName>
        <label>Onsite Fixed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_PN__c</fullName>
        <label>Product Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Product_Line__c</fullName>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Report_Closer_Workgroup__c</fullName>
        <label>Closer Workgroup</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Report_ETE_End_Date_to_Open_Date_1__c</fullName>
        <label>ETE_End Date to Open Date 1</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSC_Report_LtzFirst_Onsite_OpenDate__c</fullName>
        <label>Ltz First Onsite Workorder Open Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Courier Assist</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Sub_code__c</fullName>
        <label>Resolution Sub-code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Code__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HW Issue</fullName>
                </value>
                <value>
                    <fullName>SW Issue</fullName>
                </value>
                <value>
                    <fullName>Firmware/BIOS/Driver updates (except 3Par)</fullName>
                </value>
                <value>
                    <fullName>Implementation/Configuration/Setup questions</fullName>
                </value>
                <value>
                    <fullName>Non-Technical/Presales/Contract Coverage</fullName>
                </value>
                <value>
                    <fullName>Customer self-solved without HP assistance</fullName>
                </value>
                <value>
                    <fullName>Duplicate case logged</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Failed RPL</fullName>
                </value>
                <value>
                    <fullName>Unable to reach customer to begin diagnosis</fullName>
                </value>
                <value>
                    <fullName>Customer unwilling/Unable to perform remote diagnosis and/or implement action plan</fullName>
                </value>
                <value>
                    <fullName>Transferred out of HP EG</fullName>
                </value>
                <value>
                    <fullName>Customer declined billable service</fullName>
                </value>
                <value>
                    <fullName>Reject Subk Subcode</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Type__c</fullName>
        <label>Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-site</fullName>
                </value>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Remote resolve</fullName>
                </value>
                <value>
                    <fullName>Remote Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_hpl__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hpl</label>
        <referenceTo>Ref_Value__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases_hpl</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content_Category__c</fullName>
        <label>Content Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>安装问题</fullName>
                </value>
                <value>
                    <fullName>兼容性问题</fullName>
                </value>
                <value>
                    <fullName>配置问题</fullName>
                </value>
                <value>
                    <fullName>固件问题</fullName>
                </value>
                <value>
                    <fullName>驱动问题</fullName>
                </value>
                <value>
                    <fullName>性能问题</fullName>
                </value>
                <value>
                    <fullName>非技术问题</fullName>
                </value>
                <value>
                    <fullName>更换备件</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Content_SubCategory__c</fullName>
        <label>Content SubCategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Content_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OS</fullName>
                </value>
                <value>
                    <fullName>硬件</fullName>
                </value>
                <value>
                    <fullName>选件</fullName>
                </value>
                <value>
                    <fullName>HW</fullName>
                </value>
                <value>
                    <fullName>第三方硬件或软件</fullName>
                </value>
                <value>
                    <fullName>BIOS</fullName>
                </value>
                <value>
                    <fullName>HDM</fullName>
                </value>
                <value>
                    <fullName>阵列卡</fullName>
                </value>
                <value>
                    <fullName>显卡</fullName>
                </value>
                <value>
                    <fullName>CPU</fullName>
                </value>
                <value>
                    <fullName>内存</fullName>
                </value>
                <value>
                    <fullName>硬盘</fullName>
                </value>
                <value>
                    <fullName>网卡</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ToDate_End_Date__c</fullName>
        <label>ToDate_End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ToDate_Open_Date__c</fullName>
        <label>ToDate_Open Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Ref_Value__c.object
<CustomObject>
    <fields>
        <fullName>Hpl__c</fullName>
        <label>Hpl</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Reference Value</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>CSC_Self_Defined_Close_Case_Comments__c</fullName>
        <label>CSC_Self_Defined_Close_Case_ Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Workgroup__c</fullName>
        <label>Workgroup</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WG-CSC_DL_ALPHA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_Networking</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_CA_VA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_Pro1</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_HPSD_Com</fullName>
                </value>
                <value>
                    <fullName>WG-TSCO_DL_ISS_Trade</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_MA_ISSG</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_HPSD CA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_DP_ISS</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_L2_Storage</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_OPS</fullName>
                </value>
                <value>
                    <fullName>WG-H3C_HZ_RD_HW</fullName>
                </value>
                <value>
                    <fullName>WG-H3C_HZ_RD_SW</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_PCI</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_WWXD</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_Value_YIGAO</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_DIGITALCHINA</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_ASIACOM</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_Value_NJSISUO</fullName>
                </value>
                <value>
                    <fullName>WG-GSD_BJ_RASM</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_HPSD_Ent</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_MCRSS</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_Pro2</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_ESupport</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_BCS</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_BLD</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_MA_ADMIN</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_DP_VA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_L2_ISS</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_NJSISUO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_Close_Case_Controller.cls
/***********************************************************************
Name: CSC_Close_Case_Controller
***************************************************
History
--------
VERSION     AUTHOR              DATE            DETAIL
1.0         xuxiangguo          2016-6-15       Created
**************************************************************/
global class CSC_Close_Case_Controller {
    public Case objCase {get;set;}
    public String caseId {get;set;}
    public Boolean isNeedPQRSurvey {get;set;}
    public Boolean isNeedCloseWorkOrder {get;set;}
    public Boolean refresh {get;set;}
    public Boolean isNotOwner {get;set;}

    public String resolutionType {get;set;}
    public String resolutionCode {get;set;}
    public String resolutionSubCode {get;set;}
    public String comments {get;set;}
    public String selfComments {get;set;}

    /**
     方法名: CSC_Close_Case_Controller
     功能说明: 取得关单Case的相关信息
     参数说明: 无
     返回值: 无
     作者: xuxiangguo
     日期: 2016-06-17
    */
    public CSC_Close_Case_Controller(apexpages.standardcontroller stdctlr)
    {
        Controller();
    }
    
    public void Controller() {

        caseId=ApexPages.currentPage().getParameters().get('id'); 

        objCase=[Select CSC_Report_ETE_End_Date_to_Open_Date_1__c, ToDate_Open_Date__c,CSC_Onsite_Fixed_Date__c,CSC_Report_LtzFirst_Onsite_OpenDate__c,Id, 
                ToDate_End_Date__c, CaseNumber, Subject, Owner.Name, Status, CSC_Resolution_Type__c, CSC_PN__c,
                Content_Category__c,Content_SubCategory__c,
                CSC_SN__c,
                CSC_Resolution_Code__c, CSC_Resolution_Sub_code__c, CSC_Comments__c,CSC_Product_Line__c,CSC_hpl__c From Case Where Id=:caseId];
                
        if (!objCase.OwnerId.equals(userInfo.getUserId())) {
            isNotOwner = true;
        } else {
            isNotOwner = false;
        }

        if (objCase.CSC_PN__c != null) {
            isNeedPQRSurvey = CSC_Case_SetData.iSNeedToPQRSurvey(caseId, objCase.CSC_PN__c);
        }

        isNeedCloseWorkOrder = CSC_Case_SetData.isNeedToCloseWorkOrder(caseId);

        User currentActionUser = [SELECT Id,CSC_Self_Defined_Close_Case_Comments__c FROM User WHERE Id =: UserInfo.getUserId()];
        if(currentActionUser != null ){
            selfComments = currentActionUser.CSC_Self_Defined_Close_Case_Comments__c;
        }else{
            selfComments = '';
        }
    }

    /**
     方法名: save
     功能说明: 关闭Case时更新Case相关的信息
     参数说明: 无
     返回值: PageReference null
     作者: xuxiangguo
     日期: 2016-06-17
    */
    public PageReference save(){
        try { 

            //if ('Remote Other'.equals(objCase.CSC_Resolution_Type__c.trim()) && !String.isNotEmpty(objCase.CSC_Comments__c)) {
            //取消Comments as 还原
            //2018-05-28 modify by M-0421 xutao
            //if (!String.isNotEmpty(objCase.CSC_Comments__c)) {
            if ('Remote Other'.equals(objCase.CSC_Resolution_Type__c.trim()) && !String.isNotEmpty(objCase.CSC_Comments__c)) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Comments: You must enter a value'));
                refresh = false;
                return null;
            }

            //add by xutao 2018-06-06 
            String osn = objCase.CSC_SN__c;
            if (String.isNotEmpty(osn) && osn.length() == 20) {

                //Content_Category__c,Content_SubCategory__c,
                // System.debug('asdfghjkl');
                // System.debug(objCase.Content_Category__c);
                // System.debug(objCase.Content_SubCategory__c);
                // System.debug(String.isBlank(objCase.Content_Category__c));
                // System.debug('asdfghjkl');
                // System.debug(String.isBlank(objCase.Content_Category__c) || String.isBlank(objCase.Content_SubCategory__c) && !('更换备件'.equals(objCase.Content_Category__c)||'非技术问题'.equals(objCase.Content_Category__c)));

                //if(!String.isNotEmpty(objCase.Content_Category__c) || !String.isNotEmpty(objCase.Content_SubCategory__c)){
                if(String.isBlank(objCase.Content_Category__c) || String.isBlank(objCase.Content_SubCategory__c) && !('更换备件'.equals(objCase.Content_Category__c)||'非技术问题'.equals(objCase.Content_Category__c))){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Red Brand Server Must Content Category/Content Subcategory is required'));
                    refresh = false;
                    return null;
                }            
            }
            
            if(objCase.CSC_Onsite_Fixed_Date__c!=null)
            {
                objCase.ToDate_End_Date__c=objCase.CSC_Onsite_Fixed_Date__c;
            }
            else
            {
                if(objCase.CSC_Report_LtzFirst_Onsite_OpenDate__c!=null)
                {
                    objCase.ToDate_End_Date__c=objCase.CSC_Report_LtzFirst_Onsite_OpenDate__c;
                }
                else
                {
                    objCase.ToDate_End_Date__c=system.now();
                }
            }

            refresh = true;
            if (objCase.ToDate_Open_Date__c != null && objCase.ToDate_End_Date__c!=null
                && objCase.CSC_Report_LtzFirst_Onsite_OpenDate__c!=null) 
            {
                objCase.CSC_Report_ETE_End_Date_to_Open_Date_1__c=objCase.ToDate_End_Date__c.date().daysBetween(objCase.ToDate_Open_Date__c.date())+1;
                List<Holiday> hList=[Select Id From Holiday Where ACTIVITYDATE<=:objCase.ToDate_End_Date__c.date() And ACTIVITYDATE>=:objCase.CSC_Report_LtzFirst_Onsite_OpenDate__c.date()];
            }
            
            if (objCase.CSC_Product_Line__c != null) {
                List<Ref_Value__c> refValuseList = [SELECT Id from Ref_Value__c where Hpl__c =:objCase.CSC_Product_Line__c];
                if (refValuseList != null && !refValuseList.isEmpty()) {
                    objCase.CSC_hpl__c = refValuseList[0].Id;
                }
            }
           
            objCase.CSC_Resolution_Type__c = resolutionType;
            objCase.CSC_Resolution_Code__c = resolutionCode;
            objCase.CSC_Resolution_Sub_code__c = resolutionSubCode;
            
            objCase.CSC_Comments__c = comments;
            objCase.Status='Closed';
            objCase.CSC_Closer__c=userInfo.getUserId();
            objCase.CSC_Report_Closer_Workgroup__c = [Select Workgroup__c From User Where Id=:UserInfo.getUserId()][0].Workgroup__c;

            update objCase;
            
        } catch(Exception ex) {
            refresh = false;
            system.debug('ex:'+ex);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, ex.getMessage()));
        }

        return null;
    }

}