src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FTP_Link__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>accountName__c</fullName>
        <label>accountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>accountPassword__c</fullName>
        <label>accountPassword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FTP Link</label>
</CustomObject>

src/objects/Integration_Status__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Integration Status</relationshipLabel>
        <relationshipName>Integration_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{0000000000}</displayFormat>
        <label>Num</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_App_GetFtpLinkTest.cls
@isTest
private class CSC_App_GetFtpLinkTest{

    static testMethod void testupdtOrcretBox(){
		Test.startTest();
        //create custom setting
        FTP_Link__c setting = new FTP_Link__c ();
        setting.Name = 'FTP';
        setting.accountName__c = 'sfdc';
        setting.accountPassword__c = 'sfdc';
        setting.password__c = '123';
        Insert setting;

        Case cas = new Case();
        cas.Subject = 'this is test';
        cas.Origin = 'NGMS-TS';
        //6CU724TB39//0010I00001ZEByAQAX
        cas.AccountId = '0010I00001ZEByAQAX';//SGH133X3M7//001p000000GYVLtAAP//0012800000WDBd4AAH
        cas.CSC_SN__c = '6CU724TB39';
        Insert cas;

        Integration_Status__c  ts = new Integration_Status__c ();
        ts.Case_Name__c = cas.Id;
        Insert ts;

        Case c = [select CaseNumber from Case where Id =: cas.Id];

        
        CSC_App_GetFtpLink.updtOrcretBox(c.CaseNumber,180);
        Test.stopTest();
    }
}