src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Case_Service_Category__c</fullName>
        <formula>if(NOT(ispickval(Status,&apos;Closed&apos;)),&apos;&apos;,IF(OR(ISPICKVAL(CSC_Repair_Class_Code__c, &apos;AO&apos;), 
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;AR&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;CA&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;CO&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;IR&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;NT&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;SV&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;SW&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;UC&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;WK&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;SC&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;PO&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;PA&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;PP&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;ML&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;CP&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;AB&apos;),
ISPICKVAL(CSC_Repair_Class_Code__c, &apos;AS&apos;)
),&apos;Corrective&apos;,( IF( TEXT(CSC_Repair_Class_Code__c) = &apos;&apos;, &apos;&apos;, &apos;Non-Corrective&apos;) )))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Service Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HW Delivery</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Advanced Support</fullName>
                </value>
                <value>
                    <fullName>Install</fullName>
                </value>
                <value>
                    <fullName>MC Non-BCS</fullName>
                </value>
                <value>
                    <fullName>MC Datacenter</fullName>
                </value>
                <value>
                    <fullName>Proactive</fullName>
                </value>
                <value>
                    <fullName>Questions</fullName>
                </value>
                <value>
                    <fullName>SW Delivery</fullName>
                </value>
                <value>
                    <fullName>CE Assist</fullName>
                </value>
                <value>
                    <fullName>Depot Repair</fullName>
                </value>
                <value>
                    <fullName>T&amp;M</fullName>
                </value>
                <value>
                    <fullName>MC CTR</fullName>
                </value>
                <value>
                    <fullName>CTR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Onsite_Fixed_Date__c</fullName>
        <label>Onsite Fixed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_Onsite_Stop_Date__c</fullName>
        <label>Onsite Stop Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_PN__c</fullName>
        <label>Product Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Courier Assist</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Sub_code__c</fullName>
        <label>Resolution Sub-code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Code__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HW Issue</fullName>
                </value>
                <value>
                    <fullName>SW Issue</fullName>
                </value>
                <value>
                    <fullName>Firmware/BIOS/Driver updates (except 3Par)</fullName>
                </value>
                <value>
                    <fullName>Implementation/Configuration/Setup questions</fullName>
                </value>
                <value>
                    <fullName>Non-Technical/Presales/Contract Coverage</fullName>
                </value>
                <value>
                    <fullName>Customer self-solved without HP assistance</fullName>
                </value>
                <value>
                    <fullName>Duplicate case logged</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Failed RPL</fullName>
                </value>
                <value>
                    <fullName>Unable to reach customer to begin diagnosis</fullName>
                </value>
                <value>
                    <fullName>Customer unwilling/Unable to perform remote diagnosis and/or implement action plan</fullName>
                </value>
                <value>
                    <fullName>Transferred out of HP EG</fullName>
                </value>
                <value>
                    <fullName>Customer declined billable service</fullName>
                </value>
                <value>
                    <fullName>Reject Subk Subcode</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Type__c</fullName>
        <label>Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-site</fullName>
                </value>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Remote resolve</fullName>
                </value>
                <value>
                    <fullName>Remote Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_Btwn_Rerpr_CSC__c</fullName>
        <label>Days Btwn Rerpr(CSC)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Delivery_Alternative__c</fullName>
        <label>Delivery Alternative</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>600</fullName>
                    <color>#78C953</color>
                    <label>600</label>
                </value>
                <value>
                    <fullName>400</fullName>
                    <color>#A845DC</color>
                    <label>400</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <color>#F3D904</color>
                    <label>300</label>
                </value>
                <value>
                    <fullName>200</fullName>
                    <color>#A53711</color>
                    <label>200</label>
                </value>
                <value>
                    <fullName>0</fullName>
                    <color>#66E9BD</color>
                    <label>0</label>
                </value>
                <value>
                    <fullName>900</fullName>
                </value>
                <value>
                    <fullName>500</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>PreCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CSC_FST_Service_Request</fullName>
        <active>true</active>
        <businessProcess>CSC %26 FST Service Request</businessProcess>
        <label>05-CSC &amp; FST Service Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Job_Error_log__c.object
<CustomObject>
    <description>Error log</description>
    <fields>
        <fullName>Job_Performance_Log__c</fullName>
        <label>Job Performance Log</label>
        <referenceTo>Job_Performance_Log__c</referenceTo>
        <relationshipLabel>Job Error log</relationshipLabel>
        <relationshipName>Job_Error_log_Per_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Error log</label>
    <nameField>
        <label>Error log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Performance_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Start_Time__c</fullName>
        <label>Job Start Time</label>
        <type>Date</type>
    </fields>
    <label>Job Performance Log</label>
    <nameField>
        <label>Job Performance Log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CaseUpdatePrecaseBatchable.cls
global class CaseUpdatePrecaseBatchable implements Database.Batchable<sObject> {
    public String query;
    public Job_Performance_Log__c Jp;
    public List<Job_Error_log__c> Jellist;
    public static ID CASE_RECORDTYPE_ID;
    static {
        for (RecordType item : [SELECT Id, DeveloperName FROM RecordType 
                WHERE SobjectType = 'Case' AND DeveloperName = 'CSC_FST_Service_Request' LIMIT 1]) {
            CASE_RECORDTYPE_ID = item.Id;
        }
    }

    global CaseUpdatePrecaseBatchable() {
        //Insert log information.
        List<Job_Performance_Log__c> JpList = [select id,Job_Start_Time__c,Class_Name__c
                                               from Job_Performance_Log__c
                                               where Job_Start_Time__c = Today and Class_Name__c =: 'Case'];
        if(JpList.size() == 0){
            Job_Performance_Log__c J = Factory.LogCreate('CaseUpdatePrecaseBatchable ' + String.valueOf(System.today()), 0, 
                                                         'Case', 'CaseUpdatePrecaseBatchable.', 
                                                         '');
            Jp                       = j;
        }
        else{
            Jp                       = JpList.get(0);
        }

        Jellist = new list<Job_Error_log__c>();
        //////////////////////////////////////////////////////////////////////////////////
        Datetime filterDT = DateTime.now() - 60;

        if (!System.Test.isRunningTest()) {
            //this.query = 'SELECT Id, Casenumber, Status, Delivery_Alternative__c, CSC_Case_Service_Category__c, CSC_PN__c, CSC_SN__c, ClosedDate, PreCase__c, CSC_Onsite_Fixed_Date__c,CSC_Onsite_Stop_Date__c,CSC_Case_Type__c, CreatedDate, CSC_Resolution_Type__c, CSC_Resolution_Code__c, CSC_Resolution_Sub_code__c FROM Case WHERE Status=\'Closed\' AND Delivery_Alternative__c != \'200\' AND CSC_Resolution_Code__c != \'Void\' AND CSC_Resolution_Code__c != \'Not Resolved\' AND PreCase__c=null AND ClosedDate > ' + filterDT.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
            this.query = 'SELECT Id, Casenumber, Status, Delivery_Alternative__c, CSC_Case_Service_Category__c, CSC_PN__c, CSC_SN__c, ClosedDate, PreCase__c, CSC_Onsite_Fixed_Date__c,CSC_Onsite_Stop_Date__c,CSC_Case_Type__c, CreatedDate, CSC_Resolution_Type__c, CSC_Resolution_Code__c, CSC_Resolution_Sub_code__c, Days_Btwn_Rerpr_CSC__c FROM Case WHERE Status=\'Closed\' AND Delivery_Alternative__c != \'200\' AND CSC_Resolution_Code__c != \'Void\' AND CSC_Resolution_Code__c != \'Not Resolved\' AND ClosedDate > ' + filterDT.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'') +  ' AND RecordTypeId=\'' +  CASE_RECORDTYPE_ID + '\'';
        }
        else {
            this.query = 'SELECT Id, Casenumber, Status, Delivery_Alternative__c, CSC_Case_Service_Category__c, CSC_PN__c, CSC_SN__c, ClosedDate, PreCase__c, CSC_Onsite_Fixed_Date__c,CSC_Onsite_Stop_Date__c,CSC_Case_Type__c, CreatedDate, CSC_Resolution_Type__c, CSC_Resolution_Code__c, CSC_Resolution_Sub_code__c, Days_Btwn_Rerpr_CSC__c FROM Case WHERE Status=\'Closed\' AND Delivery_Alternative__c != \'200\' AND CSC_Resolution_Code__c != \'Void\' AND CSC_Resolution_Code__c != \'Not Resolved\' AND PreCase__c=null AND ClosedDate > ' + filterDT.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'') + ' AND RecordTypeId=\'' +  CASE_RECORDTYPE_ID + '\' ' + ' Order by CreatedDate ASC LIMIT 200';   
        }
        //this.query = 'SELECT Id, Casenumber, Status, Delivery_Alternative__c, CSC_Case_Service_Category__c, CSC_PN__c, CSC_SN__c, ClosedDate, PreCase__c, CSC_Onsite_Fixed_Date__c,CSC_Onsite_Stop_Date__c,CSC_Case_Type__c, CreatedDate FROM Case WHERE Status=\'Closed\'';
System.debug('Query:' + query);
        Factory.ErrorLogCreate(Jellist, Jp.ID, 'CaseUpdatePrecaseBatchable ' + System.today(), 'CaseUpdatePrecaseBatchable','Case', 
                                   '', query, '', '', 'Loop'); 
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {

        List<Job_Error_log__c> Jelist = new List<Job_Error_log__c>();
        List<Case> newCaseList = (List<Case>)scope;
        CSC_Case_SetData.CloseCaseSetValue2WithLog(newCaseList, Jelist, Jp.ID);
        CSC_Case_SetData.CloseCaseSetValue3WithLog(newCaseList, Jelist, Jp.ID);
        
        try {
            Database.SaveResult[] srList = Database.update(newCaseList,False);
            for(Database.SaveResult sr : srList){
                if(Sr.isSuccess() == False){
                    Factory.ErrorLogCreate(Jelist, Jp.ID, 'CaseUpdatePrecaseBatchable' + System.today(), 
                                           'CaseUpdatePrecaseBatchable', 'Case', Sr.getId(), String.valueOf(Sr.getErrors()), 
                                           'DML',  String.valueOf(Sr.getErrors()), 'DML');                   
                }
                else{
                    continue;
                }
            }

            Factory.ErrorLogCreate(Jelist, Jp.ID, 'CaseUpdatePrecaseBatchable' + System.today(), 
                                           'CaseUpdatePrecaseBatchable', 'Case', '', 'SaveResult size:' + srList.size(), 
                                           'DML',  '', 'DML');
        }
        catch (Exception e) {
            Factory.ErrorLogCreate(Jelist, Jp.ID, 'CaseUpdatePrecaseBatchable' + System.today(), 'CaseUpdatePrecaseBatchable','Case', 
                                   e.getStackTraceString(), String.valueOf(e.getMessage()), String.valueOf(e.getLineNumber()), 
                                   String.valueOf(e.getCause()), 'Loop');            
        }

        insert Jelist;
    }

    global void finish(Database.BatchableContext BC) {
        insert Jellist;
        Database.executeBatch(new CSC_UpdateSurveyAnswerBatch(), 200);
    }
}