src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_FTP_End_Date__c</fullName>
        <label>FTP End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSC_FTP_Start_Date__c</fullName>
        <label>FTP Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSC_FTP_URL__c</fullName>
        <label>FTP URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>FTP_Creator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FTP Creator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>case_Ftp_Creator</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Job_Error_log__c.object
<CustomObject>
    <description>Error log</description>
    <fields>
        <fullName>Job_Performance_Log__c</fullName>
        <label>Job Performance Log</label>
        <referenceTo>Job_Performance_Log__c</referenceTo>
        <relationshipLabel>Job Error log</relationshipLabel>
        <relationshipName>Job_Error_log_Per_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Error log</label>
    <nameField>
        <label>Error log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Performance_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Start_Time__c</fullName>
        <label>Job Start Time</label>
        <type>Date</type>
    </fields>
    <label>Job Performance Log</label>
    <nameField>
        <label>Job Performance Log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_RenewFtpLinkAlertMassgeBatch.cls
/***********************************************************************
Name: CSC_RenewFtpLinkAlertMassgeBatch
***************************************************
History
--------
VERSION     AUTHOR              DATE            DETAIL
1.0         xuxiangguo          2016-11-24      Created
**************************************************************/
global class CSC_RenewFtpLinkAlertMassgeBatch implements Database.Batchable<sObject> {
    public String query;
    public Job_Performance_Log__c Jp;
    public List<Job_Error_log__c> JellistError;
    public static final String CASE_STATUS = 'Closed';

    global CSC_RenewFtpLinkAlertMassgeBatch() {
        if (!System.test.isRunningTest()){
            this.query = 'SELECT Id, CaseNumber, Status, CSC_FTP_URL__c, CSC_FTP_Start_Date__c, CSC_FTP_End_Date__c, FTP_Creator__r.name, FTP_Creator__r.Email '
                        + 'FROM Case WHERE Status != \'' +  CASE_STATUS  + '\' AND CSC_FTP_URL__c != null AND CSC_FTP_End_Date__c != null';
        } else{
            this.query = 'SELECT Id, CaseNumber, Status, CSC_FTP_URL__c, CSC_FTP_Start_Date__c, CSC_FTP_End_Date__c,FTP_Creator__r.name, FTP_Creator__r.Email '
                        + 'FROM Case WHERE Status != \'' +  CASE_STATUS  + '\' AND CSC_FTP_URL__c != null AND CSC_FTP_End_Date__c != null limit 200';
        }

        //Insert log information.
        List<Job_Performance_Log__c> JpList = [select id,Job_Start_Time__c,Class_Name__c
                                               from Job_Performance_Log__c
                                               where Job_Start_Time__c = Today and Class_Name__c =: 'FTP'];
        if(JpList.size() == 0){
            Job_Performance_Log__c j = Factory.LogCreate('Renew FTP alert Messge ' + String.valueOf(System.today()), 0, 
                                                         'FTP', 'Send Email to FTP Creator for renew FTP link.', '');
            Jp = j;
        } else{
            Jp = JpList.get(0);
        }
        JellistError = new list<Job_Error_log__c>();
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {

        List<Case> caseList = scope;
        Date currentDay = date.today();
        List<Job_Error_log__c> Jellist    = new List<Job_Error_log__c>();

        try{
            if (caseList != null && !caseList.isEmpty()) {

                for (Case item:caseList) {

                    if (currentDay.daysBetween(item.CSC_FTP_End_Date__c) == 7) {

                        // 定义邮件发送APP
                        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();

                        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

                        // 定义标题
                        String strSubject = 'Case Number: [' + item.CaseNumber + ']' + ' Renew FTP link Alert Message';
                        mail.setSubject(strSubject);

                        // 邮件内容
                        String strCotent = 'Dear ' + item.FTP_Creator__r.name 
                                    + ' \n Case Number: [' + item.CaseNumber + ']' 
                                    + ' \n FTP link: [' + item.CSC_FTP_URL__c + ']' 
                                    + ' \n FTP period of validity: [' + item.CSC_FTP_End_Date__c + ']'
                                    + ' \n The FTP Link will be invalid after 7 days, Please renew FTP Link!';
                                    
                        mail.setPlainTextBody(strCotent);

                        // 收件人
                        List<String> sendEmail = new List<String>();
                        sendEmail.add(item.FTP_Creator__r.Email);
                        mail.setToAddresses(sendEmail);
                        mails.add(mail);

                        // 发邮件
                        Messaging.SendEmailResult[] results = Messaging.sendEmail(mails);
                    }
                }
            }
        } catch (Exception ex){
            System.debug(ex.getMessage() + ';' + ex.getStackTraceString());

            Factory.ErrorLogCreate(Jellist, Jp.ID, 'FTP Alert Message' + System.today(), 'Renew FTP alert Messge','FTP', 
                                   ex.getStackTraceString(), String.valueOf(ex.getMessage()), String.valueOf(ex.getLineNumber()), 
                                   String.valueOf(ex.getCause()), 'Loop');
        }

        if(Jellist.size()>0){
            insert Jellist;
        }
    }

    global void finish(Database.BatchableContext BC) {
    }
}