src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Case_Status__c</fullName>
        <label>HPE Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>RR Closed</fullName>
                </value>
                <value>
                    <fullName>Accept Problem</fullName>
                </value>
                <value>
                    <fullName>Open Requester</fullName>
                </value>
                <value>
                    <fullName>Problem Resolution</fullName>
                </value>
                <value>
                    <fullName>Partner Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_OTC__c</fullName>
        <label>OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>05R-Normal Contract</fullName>
                    <color>#0B6FCE</color>
                    <label>05R-Normal Contract</label>
                </value>
                <value>
                    <fullName>02N-Warranty Normal</fullName>
                    <color>#78C953</color>
                    <label>02N-Warranty Normal</label>
                </value>
                <value>
                    <fullName>05A-Complmt TAC</fullName>
                    <color>#E27001</color>
                    <label>05A-Complmt TAC</label>
                </value>
                <value>
                    <fullName>05K-Extended Warranty</fullName>
                    <color>#A845DC</color>
                    <label>05K-Extended Warranty</label>
                </value>
                <value>
                    <fullName>05Q-Preventative</fullName>
                    <color>#F3D904</color>
                    <label>05Q-Preventative</label>
                </value>
                <value>
                    <fullName>02G-Sevice Note</fullName>
                    <color>#A53711</color>
                    <label>02G-Sevice Note</label>
                </value>
                <value>
                    <fullName>06J-Intl Gratis</fullName>
                    <color>#66E9BD</color>
                    <label>06J-Intl Gratis</label>
                </value>
                <value>
                    <fullName>00C-Cust Claims Cont</fullName>
                    <color>#0B24BE</color>
                    <label>00C-Cust Claims Cont</label>
                </value>
                <value>
                    <fullName>00W-Cust Claims Warr</fullName>
                    <color>#419249</color>
                    <label>00W-Cust Claims Warr</label>
                </value>
                <value>
                    <fullName>00E-No Entitlement</fullName>
                </value>
                <value>
                    <fullName>01-Trade</fullName>
                    <color>#B6E32E</color>
                    <label>01-Trade</label>
                </value>
                <value>
                    <fullName>06M-Intl re-repair</fullName>
                    <color>#641CCF</color>
                    <label>06M-Intl re-repair</label>
                </value>
                <value>
                    <fullName>05F-Comp Fld Inst</fullName>
                    <color>#F96FB7</color>
                    <label>05F-Comp Fld Inst</label>
                </value>
                <value>
                    <fullName>05S-Compl Site Prep</fullName>
                    <color>#2F5D85</color>
                    <label>05S-Compl Site Prep</label>
                </value>
                <value>
                    <fullName>06F-Intl Field Instl</fullName>
                    <color>#AFCADF</color>
                    <label>06F-Intl Field Instl</label>
                </value>
                <value>
                    <fullName>05P-Contracts: Predictive Support</fullName>
                    <color>#8F6429</color>
                    <label>05P-Contracts: Predictive Support</label>
                </value>
                <value>
                    <fullName>09U-UWD Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Product_Line__c</fullName>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Courier Assist</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Sub_code__c</fullName>
        <label>Resolution Sub-code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Code__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HW Issue</fullName>
                </value>
                <value>
                    <fullName>SW Issue</fullName>
                </value>
                <value>
                    <fullName>Firmware/BIOS/Driver updates (except 3Par)</fullName>
                </value>
                <value>
                    <fullName>Implementation/Configuration/Setup questions</fullName>
                </value>
                <value>
                    <fullName>Non-Technical/Presales/Contract Coverage</fullName>
                </value>
                <value>
                    <fullName>Customer self-solved without HP assistance</fullName>
                </value>
                <value>
                    <fullName>Duplicate case logged</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Failed RPL</fullName>
                </value>
                <value>
                    <fullName>Unable to reach customer to begin diagnosis</fullName>
                </value>
                <value>
                    <fullName>Customer unwilling/Unable to perform remote diagnosis and/or implement action plan</fullName>
                </value>
                <value>
                    <fullName>Transferred out of HP EG</fullName>
                </value>
                <value>
                    <fullName>Customer declined billable service</fullName>
                </value>
                <value>
                    <fullName>Reject Subk Subcode</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Type__c</fullName>
        <label>Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-site</fullName>
                </value>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Remote resolve</fullName>
                </value>
                <value>
                    <fullName>Remote Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HPE_SubK_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>HPE SubK ID</description>
        <label>HPE SubK ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/GSEM_Post_Url__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Address__c</fullName>
        <description>relative address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GSEM Post Url</label>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_GSEM_EconciergeParklotForCloseCase.cls
/**********************************************************************
 * 
 * Name: CSC_GSEM_EconciergeParklotForCloseCase
 * Object: string h3cId
 * Purpose: 
 * 	 
 * Return Msg:
 *  <Bool,msg>
 * Author: Chen, Xiaoqian
 * Create Date: 2017-02-06
*************************************************************************/
public with sharing class CSC_GSEM_EconciergeParklotForCloseCase {

    // OTC Type
    private final static String OTC_00W = '00W';
    private final static String OTC_00C = '00C';
    private final static String OTC_00E = '00E';
    private final static String OTC_05R = '05R';
    private final static String OTC_05K = '05K';
    private final static String OTC_02N = '02N';
    private final static String OTC_02G = '02G';
    // Resolution code
    private static String RESOLUTION_CODE = 'Void';
    private static String NOT_RESOLVED = 'Not Resolved';
    
    public class AppOut{
    	public String H3CId{set;get;}
        public String SubKId{set;get;}
    }

    public class AppInput extends CSC_GSEM_Response{
    	public AppInput(Boolean b, String msg){
    		super(b,msg);
    	}
    }

    public AppInput parklotForCloseCase(String h3cId){
    	if(String.isEmpty(h3cId)){
    		return new AppInput(false,'Empty H3CID!');
    	}
    	
    	//1.校验Case是否符合要求
        List<String> sl = new List<String>();
        sl.add(h3cId);
        List<Case> clist = CSC_GSEM_SubK_Common_Function.getEconciergeCaseByIds(sl);
        if(clist==null || clist.size()==0){
            return new AppInput(false,'Case not found!');
        } 
        Case cas = clist.get(0);
        if(cas == null){
            return new AppInput(false,'Case not found!');
        }

        String strOtc = '';

        if(!String.isEmpty(cas.CSC_OTC__c)){
            strOtc = cas.CSC_OTC__c.substring(0,3);
        }

        if (!((OTC_05K.equalsIgnoreCase(strOtc)
            || OTC_05R.equalsIgnoreCase(strOtc)
            || OTC_02N.equalsIgnoreCase(strOtc)
            || OTC_02G.equalsIgnoreCase(strOtc)
            || OTC_00C.equalsIgnoreCase(strOtc)
            || OTC_00W.equalsIgnoreCase(strOtc)
            || OTC_00E.equalsIgnoreCase(strOtc)) 
            )){
            return new AppInput(false,'Case is not OTC(05K,05R,02N,02G,00C,00W,00E)! '+ cas.CSC_OTC__c);
        }

        // 从customer setting中去的红牌产品的product line信息
        Set<String> redProductPlSet = CSC_Case_Send2QueueCheck.RedBrandPLSet;

        if (redProductPlSet !=null && !redProductPlSet.isEmpty()
               &&redProductPlSet.contains(cas.CSC_Product_Line__c)) {
            return new AppInput(false,'Case is not hpe product ! '+ cas.CSC_Product_Line__c);
        }


        if(!CSC_GSEM_SubK_Common_Function.isCaseforEconcierge(cas)){
            return new AppInput(false,'Case Resolution code is not for econcierge.'
                +',CSC_Resolution_Type__c is:'+ cas.CSC_Resolution_Type__c
                +',CSC_Resolution_Code__c is:'+ cas.CSC_Resolution_Code__c
                + ',CSC_Resolution_Sub_code__c is:' + cas.CSC_Resolution_Sub_code__c);
        }
        
        // if(cas.Status == 'Closed'||cas.CSC_Case_Status__c == 'Closed'){
        //     return new AppInput(false,'Case Status is "Closed"!');
        // }

    	//2.设置提交的JSON
    	AppOut output = new AppOut();
    	output.H3CId = h3cId;
        output.SubKId = cas.HPE_SubK_ID__c;
        
	    String postString = JSON.serialize(output);
	    System.debug('Posted String is'+postString);
	    
	    //3.Post 数据到GSEM
	    String resp = '';
	    try{
	    	GSEM_Post_Url__c post = GSEM_Post_Url__c.getValues('ParklotForCloseCase');
		    System.debug(post);
            resp = CSC_GSEM_Connection.Post(postString, post.Address__c);
		    System.debug('Hi,'+resp);
		} catch (CSC_GSEM_Connection.GSEMConnectException ex){
            //处理错误消息，需要重新发送
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'ParklotForCloseCase', ex.getMessage(), true);
        } catch (CalloutException ex){
            //处理错误消息，需要重新发送
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'ParklotForCloseCase', ex.getMessage(), true);
        } catch(Exception ex){
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'ParklotForCloseCase', ex.getMessage(), true);
			return new AppInput(false,ex.getMessage());
		}
	    
	    //4.获取返回值
	    AppInput input = null;
	    try{
			input = (AppInput)JSON.deserialize(resp, AppInput.class);
            if(!input.Rst){
                CSC_GSEM_Connection.LogFailerCall(h3cId, 'ParklotForCloseCase', input.RstMsg, false);
            }
		}catch(Exception ex){
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'ParklotForCloseCase', ex.getMessage(), false);
			return new AppInput(false,ex.getMessage());
		}

    	return input;
    }
}