src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>HPE_SubK_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>HPE SubK ID</description>
        <label>HPE SubK ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Integration_Status__c.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Integration Status</relationshipLabel>
        <relationshipName>Integration_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvokeTime__c</fullName>
        <label>Close Case Invoke Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NGMS_Code__c</fullName>
        <label>NGMS Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NGMS_Type__c</fullName>
        <label>NGMS Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NGMS-TS</fullName>
                </value>
                <value>
                    <fullName>NGMS-IN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{0000000000}</displayFormat>
        <label>Num</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_NGMS_CloseNgmsCaseTest.cls
@isTest
private class CSC_NGMS_CloseNgmsCaseTest{

    public class Input{

            public String CaseOrigin;
            public Integer DurationDays;
    }
    static testMethod void testCloseNgmsCase(){
        Case cas = new Case();
        //cas.HPE_SubK_ID__c = '000003';
        cas.Subject = 'this is test';
        Insert cas;
        Case c = [select Origin from Case where Id =: cas.Id];
        c.Origin = 'NGMS-TS';
        Update c;

        Integration_Status__c is = new Integration_Status__c();
        is.Case_Name__c = cas.Id;
        is.NGMS_Type__c = 'NGMS-TS';
        is.NGMS_Code__c = '1';
        is.InvokeTime__c= System.Now().addDays(-2);
        Insert is;

        Input inp = new Input();
        inp.CaseOrigin = 'NGMS-TS';
        inp.DurationDays = 6;

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(inp);
        req.requestBody = Blob.valueof(reqJson);
        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/CloseNgmsCas/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        CSC_NGMS_CloseNgmsCase.CloseNgmsCase();
    }
    //input is null
    static testMethod void testCloseNgmsCase1(){
       
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(null);
        req.requestBody = Blob.valueof(reqJson);
        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/CloseNgmsCas/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        CSC_NGMS_CloseNgmsCase.CloseNgmsCase();
    }
    //caseid is null
    static testMethod void testCloseNgmsCase2(){
        Input inp = new Input();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(inp);
        req.requestBody = Blob.valueof(reqJson);
        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/CloseNgmsCas/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        CSC_NGMS_CloseNgmsCase.CloseNgmsCase();
    }
}