src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_OTC__c</fullName>
        <label>OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>05R-Normal Contract</fullName>
                    <color>#0B6FCE</color>
                    <label>05R-Normal Contract</label>
                </value>
                <value>
                    <fullName>02N-Warranty Normal</fullName>
                    <color>#78C953</color>
                    <label>02N-Warranty Normal</label>
                </value>
                <value>
                    <fullName>05A-Complmt TAC</fullName>
                    <color>#E27001</color>
                    <label>05A-Complmt TAC</label>
                </value>
                <value>
                    <fullName>05K-Extended Warranty</fullName>
                    <color>#A845DC</color>
                    <label>05K-Extended Warranty</label>
                </value>
                <value>
                    <fullName>05Q-Preventative</fullName>
                    <color>#F3D904</color>
                    <label>05Q-Preventative</label>
                </value>
                <value>
                    <fullName>02G-Sevice Note</fullName>
                    <color>#A53711</color>
                    <label>02G-Sevice Note</label>
                </value>
                <value>
                    <fullName>06J-Intl Gratis</fullName>
                    <color>#66E9BD</color>
                    <label>06J-Intl Gratis</label>
                </value>
                <value>
                    <fullName>00C-Cust Claims Cont</fullName>
                    <color>#0B24BE</color>
                    <label>00C-Cust Claims Cont</label>
                </value>
                <value>
                    <fullName>00W-Cust Claims Warr</fullName>
                    <color>#419249</color>
                    <label>00W-Cust Claims Warr</label>
                </value>
                <value>
                    <fullName>00E-No Entitlement</fullName>
                </value>
                <value>
                    <fullName>01-Trade</fullName>
                    <color>#B6E32E</color>
                    <label>01-Trade</label>
                </value>
                <value>
                    <fullName>06M-Intl re-repair</fullName>
                    <color>#641CCF</color>
                    <label>06M-Intl re-repair</label>
                </value>
                <value>
                    <fullName>05F-Comp Fld Inst</fullName>
                    <color>#F96FB7</color>
                    <label>05F-Comp Fld Inst</label>
                </value>
                <value>
                    <fullName>05S-Compl Site Prep</fullName>
                    <color>#2F5D85</color>
                    <label>05S-Compl Site Prep</label>
                </value>
                <value>
                    <fullName>06F-Intl Field Instl</fullName>
                    <color>#AFCADF</color>
                    <label>06F-Intl Field Instl</label>
                </value>
                <value>
                    <fullName>05P-Contracts: Predictive Support</fullName>
                    <color>#8F6429</color>
                    <label>05P-Contracts: Predictive Support</label>
                </value>
                <value>
                    <fullName>09U-UWD Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DOA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is DOA</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <label>Work Order Name</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>OrderToWorkOrder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Parts_Order__c.object
<CustomObject>
    <fields>
        <fullName>Offered_S_Plant__c</fullName>
        <label>Offered S Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Parts Order</relationshipLabel>
        <relationshipName>Parts_Order</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parts_Description__c</fullName>
        <formula>Request_Parts__r.Description__c</formula>
        <label>Request Parts Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parts_Serial_Number__c</fullName>
        <label>Parts Serial Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parts_Usage__c</fullName>
        <label>Parts Usage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Used/Consumed</fullName>
                </value>
                <value>
                    <fullName>Used Not Consumed</fullName>
                </value>
                <value>
                    <fullName>Unused</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Removed_Parts_Serial_Number__c</fullName>
        <label>Removed Parts Serial Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Removed_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Removed Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Removed Parts)</relationshipLabel>
        <relationshipName>Removed_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Request Parts)</relationshipLabel>
        <relationshipName>Request_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X_Failure_Cd__c</fullName>
        <description>72=Unused;
74=Verified Failure;
55=Used + not consumed;
PD=Used + not consumed;
MS=Miss shipment;
WP=Used + not consumed;</description>
        <inlineHelpText>72=Unused;
74=Verified Failure;
55=Used + not consumed;
PD=Used + not consumed;
MS=Miss shipment;
WP=Used + not consumed;</inlineHelpText>
        <label>X Failure Cd</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>55 - DOA/DFS</fullName>
                </value>
                <value>
                    <fullName>74 - Verified Failure</fullName>
                </value>
                <value>
                    <fullName>PD - Physically Damaged</fullName>
                </value>
                <value>
                    <fullName>WP - Wrong Part in Box</fullName>
                </value>
                <value>
                    <fullName>72 - Unused</fullName>
                </value>
                <value>
                    <fullName>MS - Miss Shipment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_Report_Subcase_DAH__c</fullName>
        <description>Workorder Onsite Stop Date - Workorder Onsite Start Date</description>
        <formula>(Subcase_Onsite_Stop_Date__c - Subcase_Onsite_Start_Date__c)*24</formula>
        <label>WorkOrder DAH</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Start_Date__c</fullName>
        <label>WorkOrder Onsite Repair Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Stop_Date__c</fullName>
        <label>WorkOrder Onsite Repair Stop Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_MaintainReportController.cls
public without sharing class CSC_MaintainReportController {

    public List<Parts_Order__c> PartsOrderList {    get;    set;  }
    public Integer orderNumber {    get;    set;  }
    public Integer workHour{    get;    set;  }
    public Decimal OTHour{    get;    set;  }
    public String serviceTypeString {get;    set;  }
    public List<ServiceType> serviceType {
        get;    
        set{
            serviceType  = new List<ServiceType>();
            ServiceType s1 = new ServiceType();
            s1.stValue = '05R-Normal Contract';
            s1.stDescriptioin = '合同';
            ServiceType s2 = new ServiceType();
            s2.stValue = '02N-Warranty Normal';
            s2.stDescriptioin = '保修';
            ServiceType s3 = new ServiceType();
            s3.stValue = '01-Trade';
            s3.stDescriptioin = '付费';
            ServiceType s4 = new ServiceType();
            s4.stValue = '06J-Intl Gratis';
            s4.stDescriptioin = '内部吸收';
            ServiceType s5 = new ServiceType();
            s5.stValue = 'DOA';
            s5.stDescriptioin = '产品DOA';
            serviceType.add(s1);
            serviceType.add(s2);
            serviceType.add(s3);
            serviceType.add(s4);
            serviceType.add(s5);
        }
    }
    public List<Attachment> attachList{get;set;}
    public List<Attachment> attachClosedList{get;set;}
    public List<ServiceType> partsUsage{
        get;    
        set{
            partsUsage = new List<ServiceType>();
            ServiceType s1 = new ServiceType();
            s1.stValue = '使用';
            s1.stDescriptioin = '使用';
            ServiceType s2 = new ServiceType();
            s2.stValue = '未用';
            s2.stDescriptioin = '未用';
            ServiceType s3 = new ServiceType();
            s3.stValue = 'DOA';
            s3.stDescriptioin = 'DOA';
            partsUsage.add(s1);
            partsUsage.add(s2);
            partsUsage.add(s3);
        }
    }
    public List<SelectOption> partUsageList{
        get;
        set{
            partUsageList = new List<SelectOption>();
            Schema.DescribeFieldResult DisplayTypeDescribe = Schema.sObjectType.Parts_Order__c.fields.Parts_Usage__c;
            List<Schema.PicklistEntry> DisplayTypePickList = DisplayTypeDescribe.getPicklistValues();
            for(Schema.PicklistEntry picklistValue : DisplayTypePickList) {
                partUsageList.add(new selectOption(picklistValue.getValue(),picklistValue.getLabel()));
            }
        }
    }
    
    public CSC_MaintainReportController(ApexPages.StandardController controller) {
         WorkOrder WorkOrderRecord = (WorkOrder ) controller.getRecord();
         Map<Id, Order__c> orderMap =  new Map<Id, Order__c>();
         PartsOrderList = new List<Parts_Order__c>();
         serviceType = new List<serviceType>();
         partsUsage = new List<serviceType>();
         partUsageList = new List<SelectOption>();
         attachList = new List<Attachment>();
         Case caseRecord = new Case();
         serviceTypeString ='';
         try{
             caseRecord = [select id,CSC_OTC__c,DOA__c  from Case where id = :WorkOrderRecord.caseid];
             serviceTypeString = caseRecord.CSC_OTC__c;
             if(caseRecord.DOA__c ==true){
                 serviceTypeString = 'DOA';
             }
             //,Subcase_Onsite_Stop_Date__c,Subcase_Onsite_Start_Date__c
             OTHour = 0; 
             try{
                 BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
                 OTHour =  (WorkOrderRecord.CSC_Report_Subcase_DAH__c *60 - ( BusinessHours.diff(bh.id ,WorkOrderRecord.Subcase_Onsite_Start_Date__c  ,WorkOrderRecord.Subcase_Onsite_Stop_Date__c)/24/1000))/60 ;
                 if(OTHour <0){
                     OTHour = 0;
                 }
             }
             catch(exception eOT){}
             //workHour = (caseRecord.Subcase_Onsite_Stop_Date__c == null? 0 : caseRecord.Subcase_Onsite_Stop_Date__c) - (caseRecord.Subcase_Onsite_Stop_Date__c == null? 0 : caseRecord.Subcase_Onsite_Stop_Date__c);
         } catch(exception e0){system.debug(e0.getmessage());}
         try{
             attachClosedList = [select id from Attachment where ParentId =: WorkOrderRecord.id and ContentType<>'application/pdf' and name like '%ClosedWR%' order by createddate desc];
             attachList = [select id from Attachment where ParentId =: WorkOrderRecord.id and ContentType<>'application/pdf' and name like '%Communication%' order by createddate desc];
         } catch(exception e00){system.debug(e00.getmessage());}
         try{
             orderMap =  new Map<Id, Order__c>([select id from Order__c where Work_Order_Name__c =: WorkOrderRecord.id]);
         }
         catch(exception e1){system.debug(e1.getmessage());}
         if(orderMap.size()>0){         
             try{
                 PartsOrderList = [select id,Parts_Description__c,Request_Parts__c,Parts_Serial_Number__c, Parts_Usage__c ,Removed_Parts_Serial_Number__c , Removed_Parts__c ,X_Failure_Cd__c,Offered_S_Plant__c  from Parts_Order__c where Order__c in : orderMap.keyset()];
                 
                 PartsOrderList = X_Failure_CdExchange(PartsOrderList);
             }
             catch(exception e2){system.debug(e2.getmessage());}
         }
         orderNumber =PartsOrderList.size()+1;
         
    }
    public List<Parts_Order__c> X_Failure_CdExchange(List<Parts_Order__c> PartsOrderList){
        for(Parts_Order__c po1: PartsOrderList){
            if(po1.X_Failure_Cd__c <> null){
                if(po1.X_Failure_Cd__c.indexOf('74')>=0){
                    po1.Parts_Usage__c = '使用';
                }
                else if(po1.X_Failure_Cd__c.indexOf('72')>=0){
                    po1.Parts_Usage__c = '未用';
                }
                else if(po1.X_Failure_Cd__c.indexOf('55')>=0||po1.X_Failure_Cd__c.indexOf('PD')>=0||po1.X_Failure_Cd__c.indexOf('WP')>=0){
                    po1.Parts_Usage__c = 'DOA';
                }
            }else{
                po1.Parts_Usage__c = '';
            }
        }
        return PartsOrderList;
    }
    public class ServiceType{
        public String stDescriptioin{get;set;}
        public String stValue{get;set;}
    }
}