src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>HPE_SubK_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>HPE SubK ID</description>
        <label>HPE SubK ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/CE_Revisit__c.object
<CustomObject>
    <fields>
        <fullName>Enroute_Date__c</fullName>
        <label>Enroute Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Leave_Date__c</fullName>
        <label>Leave Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NGMS_DurationTag__c</fullName>
        <label>NGMS DurationTag</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>true</fullName>
                    <default>true</default>
                    <label>true</label>
                </value>
                <value>
                    <fullName>false</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>CE Revisit</relationshipLabel>
        <relationshipName>CE_Revisit</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CE Revisit</label>
    <nameField>
        <displayFormat>CRN-{YYYYMMDD}-{00000000}</displayFormat>
        <label>CE Revisit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>NGMS_Duration__c</fullName>
        <label>NGMS_Duration</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>true</fullName>
                    <default>true</default>
                    <label>true</label>
                </value>
                <value>
                    <fullName>false</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subcase_Enroute_Date__c</fullName>
        <label>WorkOrder Enroute Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Start_Date__c</fullName>
        <label>WorkOrder Onsite Repair Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Stop_Date__c</fullName>
        <label>WorkOrder Onsite Repair Stop Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_NGMS_SendWorkOrderDurationTest.cls
@isTest
private class CSC_NGMS_SendWorkOrderDurationTest{

    public class Input{

        public String CaseOrigin;
        public String Durationdays;
    }

    static testMethod void testsendWorkOrderDuration(){

        Case cas = new Case();
        //cas.HPE_SubK_ID__c = '000003';
        cas.Subject = 'this is test';
        cas.Status = 'Closed';
        Insert cas;

        Workorder wk = new Workorder();
        wk.CaseId = cas.Id;
        wk.Subject = 'this is subject for workorder';
        wk.Subcase_Enroute_Date__c = System.now().addHours(-7);
        wk.Subcase_Onsite_Start_Date__c = System.now().addHours(-6);
        wk.Subcase_Onsite_Stop_Date__c = System.now().addHours(-4);
        wk.NGMS_Duration__c = 'true';
        Insert wk;

        CE_Revisit__c ce = new CE_Revisit__c();
        ce.NGMS_DurationTag__c  = 'true';
        ce.Enroute_Date__c = System.now().addDays(1).addHours(-4);
        ce.Leave_Date__c = System.now().addDays(1).addHours(-2);
        ce.Work_Order__c = wk.Id;
        Insert ce;

        Case c = [select Id,Status,Origin from Case where Id =: cas.Id];
        c.Origin = 'NGMS-TS';
        Update c;
        Input ipt  = new Input();
        ipt.CaseOrigin = 'NGMS-TS';
        ipt.Durationdays = '5';

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String reqJson = json.serialize(ipt);
        req.requestBody = Blob.valueof(reqJson);
        System.debug(reqJson);
        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/SendWorkOrderDuration/';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        CSC_NGMS_SendWorkOrderDuration.sendWorkOrderDuration();
    }
}