src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>General_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SNR</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipLabel>个案</relationshipLabel>
        <relationshipName>CaseToGeneral_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/General_Product__c.object
<CustomObject>
    <label>General Product</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Parts__c.object
<CustomObject>
    <fields>
        <fullName>Commodity__c</fullName>
        <label>Commodity</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>General_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>General Product</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipName>PartsToGeneral_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support BOM</label>
    <nameField>
        <label>Spare Part No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parts_Order__c.object
<CustomObject>
    <fields>
        <fullName>Offered_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offered Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Offered Parts)</relationshipLabel>
        <relationshipName>Offered_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promised_DT__c</fullName>
        <label>Promised DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Ship_Plant__c</fullName>
        <label>Ship Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Back Ordered</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>POD</fullName>
                </value>
                <value>
                    <fullName>Recommand</fullName>
                    <default>true</default>
                    <label>Recommand</label>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Send Update</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking__c</fullName>
        <label>Tracking</label>
        <type>TextArea</type>
    </fields>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_SPMS_UpdatePartsStatus.cls
/**************************************************************************************************
* Name: CSC_SPMS_UpdatePartsStatus
* Object: Case
* Purpose: 
* 
* Return Msg:
*  <Bool,msg>
* Author: Zhou,Xiong
* Create Date: 2016-11-07
* *************************************************************************************************
* Edit Date: 2016-12-12 By Xiaoqian 
* Edit No: ed1
* 给方法添加异常处理
***************************************************************************************************/
@RestResource(urlMapping='/UpdatePartsStatus/*')
global with sharing class CSC_SPMS_UpdatePartsStatus {

	// 输入
    public class AppInput{
        //public String SALES_ORDER;
        public String action;
        public String partNumber;
        public String plant;
        public String partStatus;
        public String partOderNo;
        public String trackingNumber;//备件接收或归还trackingNumber
        public String trackingDate;//备件接收或归还trackingDate
        //public String TRACKING;
    }

    //输出
    global class AppOut {
        //true: Success; false:Error
        public Boolean rst;
        public String rstMsg;

        public AppOut(){
            this(true,'');
        }
        
        public AppOut(Boolean rst, String rstMsg){
            this.rst = rst;
            this.rstMsg = rstMsg;
        }
    }

    @HttpPost
    global static AppOut doPost() {

    	RestRequest req = RestContext.request;

        //ed1 start
        AppInput input = null;
        
        String reqString = req.requestBody.tostring();
        System.debug('receive requsted string: '+ reqString);

        try{
            input = (CSC_SPMS_UpdatePartsStatus.AppInput)JSON.deserialize(reqString, CSC_SPMS_UpdatePartsStatus.AppInput.class);
        } catch(JSONException e){
            System.debug(e.getMessage());
            return new AppOut(false,e.getMessage());
        }
        //ed1 end
        
        try{

            if(String.isBlank(input.partNumber)){
                return new AppOut(false,'partNumber should not be empty!');
            }

            if(String.isBlank(input.partOderNo)){
                return new AppOut(false,'Part Order number should not be empty!');
            }

        	// 备件号是否存在
            //modify by xutao for spms 20171113
 	       	List<Parts__c> parts = [SELECT Id,Name FROM Parts__c WHERE Name =: input.partNumber 
            AND General_Product__c = NULL ORDER BY Commodity__c DESC NULLS LAST, LastModifiedDate desc];
 	       	if (parts.isEmpty()){
            	return new AppOut(false,'The Parameter of part number is null!');
 	       	}

        	Parts_Order__c partOrder = [SELECT Ship_Plant__c, Name, Status__c, Tracking__c,Offered_Parts__r.Name,Offered_Parts__c 
            FROM Parts_Order__c where Name =: input.partOderNo];

        	partOrder.Offered_Parts__c = parts[0].Id;

        	if (!String.isEmpty(input.partStatus)){
        		partOrder.Status__c = input.partStatus;
        	}
        	
        	if (!String.isEmpty(input.plant)){
        		partOrder.Ship_Plant__c = input.plant;
        	}

        	if (!String.isEmpty(input.trackingNumber)){
        		partOrder.Tracking__c = input.trackingNumber;
        	}

            if (String.isNotBlank(input.trackingDate)){
                partOrder.Promised_DT__c = Datetime.valueOf(input.trackingDate);
            }

            update partOrder;

        }catch(Exception ex) {
            return new AppOut(false,ex.getMessage());
        }

        return new AppOut();

    }
    
}