src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSC_PN__c</fullName>
        <label>Product Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Courier Assist</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Sub_code__c</fullName>
        <label>Resolution Sub-code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Code__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HW Issue</fullName>
                </value>
                <value>
                    <fullName>SW Issue</fullName>
                </value>
                <value>
                    <fullName>Firmware/BIOS/Driver updates (except 3Par)</fullName>
                </value>
                <value>
                    <fullName>Implementation/Configuration/Setup questions</fullName>
                </value>
                <value>
                    <fullName>Non-Technical/Presales/Contract Coverage</fullName>
                </value>
                <value>
                    <fullName>Customer self-solved without HP assistance</fullName>
                </value>
                <value>
                    <fullName>Duplicate case logged</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Failed RPL</fullName>
                </value>
                <value>
                    <fullName>Unable to reach customer to begin diagnosis</fullName>
                </value>
                <value>
                    <fullName>Customer unwilling/Unable to perform remote diagnosis and/or implement action plan</fullName>
                </value>
                <value>
                    <fullName>Transferred out of HP EG</fullName>
                </value>
                <value>
                    <fullName>Customer declined billable service</fullName>
                </value>
                <value>
                    <fullName>Reject Subk Subcode</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Type__c</fullName>
        <label>Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-site</fullName>
                </value>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Remote resolve</fullName>
                </value>
                <value>
                    <fullName>Remote Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Severity__c</fullName>
        <defaultValue>&apos;3-Normal&apos;</defaultValue>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-Critical-Down</fullName>
                </value>
                <value>
                    <fullName>2-Critical-Degraded</fullName>
                </value>
                <value>
                    <fullName>3-Normal</fullName>
                </value>
                <value>
                    <fullName>4-Low Priority</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HPE_SubK_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>HPE SubK ID</description>
        <label>HPE SubK ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subk_CaseOrigin__c</fullName>
        <description>SubK Case Origin</description>
        <label>Subk CaseOrigin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Process_QA__c.object
<CustomObject>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Process QA</relationshipLabel>
        <relationshipName>Process_QA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process QA</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>ProcessQAId</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <formula>Case.CSC_SN__c</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Severity__c</fullName>
        <description>技术升级 Severity</description>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Critical</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Minor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Subcase_Delay_Code__c</fullName>
        <label>WorkOrder Delay Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-Response Met</fullName>
                </value>
                <value>
                    <fullName>1-Returned to office for resource</fullName>
                </value>
                <value>
                    <fullName>2-Parts Issue</fullName>
                </value>
                <value>
                    <fullName>3-No CE Resources Available</fullName>
                </value>
                <value>
                    <fullName>4-CSO sent to wrong CE</fullName>
                </value>
                <value>
                    <fullName>5-Travel Delay</fullName>
                </value>
                <value>
                    <fullName>6-No Trained/Qualified CE Available</fullName>
                </value>
                <value>
                    <fullName>7-Subcase recd Late from Call Center</fullName>
                </value>
                <value>
                    <fullName>8-Customer caused Delay</fullName>
                </value>
                <value>
                    <fullName>9-Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Subcase_Repair_Class_Code__c</fullName>
        <label>WorkOrder Repair Class Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DEF</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>DG</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>HM</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IR</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NR</fullName>
                </value>
                <value>
                    <fullName>NS</fullName>
                </value>
                <value>
                    <fullName>NT</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>SV</fullName>
                </value>
                <value>
                    <fullName>SW</fullName>
                </value>
                <value>
                    <fullName>UC</fullName>
                </value>
                <value>
                    <fullName>WK</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>ML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Resolution_Code__c</fullName>
        <label>Workorder Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Counrier Assist</fullName>
                </value>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subcase_Enroute_Date__c</fullName>
        <label>WorkOrder Enroute Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Start_Date__c</fullName>
        <label>WorkOrder Onsite Repair Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Stop_Date__c</fullName>
        <label>WorkOrder Onsite Repair Stop Date</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>H3C_CoE</fullName>
        <active>true</active>
        <label>H3C-&gt;CoE</label>
    </recordTypes>
    <recordTypes>
        <fullName>H3C_ERT</fullName>
        <active>true</active>
        <label>H3C-&gt;ERT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_GSEM_SubKCloseCase.cls
/**********************************************************************
 * 
 * Name: CSC_GSEM_SubKCloseCase
 * Object: PR
 * Purpose: 
 * SubK flow Transaction Type = PR, Column C green background is List type.
 * Return Msg:
 *  <Bool,msg>
 * Author: Chen, Xiaoqian
 * Create Date: 2017-01-03
*************************************************************************/
public with sharing class CSC_GSEM_SubKCloseCase {

    public String dateFormat = 'yyyy-MM-dd HH:mm:ss';

    // Resolution code
    // private static String RESOLUTION_CODE = 'Void';
    // private static String NOT_RESOLVED = 'Not Resolved';

    private static String H3C_COE = 'H3C->CoE';
    private static String H3C_ERT = 'H3C->ERT';

    /**
	 * 封装post数据
	 */
    public class AppOut{

    	public AppOut(){
    		this.Qualities = new List<Quality>();
    		this.RepairParts = new List<RepairPart>();
    	}

    	public String H3CID{set;get;}

    	public String HPEID{set;get;}

        public String CustomerSeverity{set;get;}

        // The date/ time that work was started on the service request
        public String ServiceStartDateTime { get; set; }

        // The date/ time that work was stopped on the service request
        public String ServiceEndDateTime { get; set; }

        // The date/ time that the unit being repaired was returned to service
        public String SystemFixedDateTime { get; set; }
        // Type of Labor associated with Repair
        public String RepairLaborType { get; set; }
        public String RepairHours { get; set; }

        // Type of Labor associated with Travel
        public String TravelLaborType { get; set; }
        public String TravelHours { get; set; }

        // Model Number of Product being Serviced
        public String ProductNumber { get; set; }

        // Serial Number of Product being Serviced
        public String SerialNumber { get; set; }

        public List<Quality> Qualities { get; set; }
        public List<RepairPart> RepairParts { get; set; }

        // Code indicating type of Repair
        public String RepairClass { get; set; }
        // Code indicating reason for delay
        public String DelayCode { get; set; }
        // Summary of Repair Activities 
        public String ResolutionDescription { get; set; }
    }

    public class Quality
    {
        // Code describing the service provided
        public String QualityCode { get; set; }
        
        // Code type describing the service provided
        public String QualityCodeType { get; set; }
    }

    public class RepairPart
    {
        // Part Order Number
        public String PartOrderNumber { get; set; }
        
        // Line item of the part 
        // public String LineItemNumber { get; set; }
        
        // The part that was installed
        public String InstalledPartNumber { get; set; }
        
        // The serial number of the part that was installed
        public String InstalledPartSerialNumber { get; set; }
        
        // Description of the part that was installed
        public String InstalledPartDescription { get; set; }
        
        // The location from which the part was shipped
        // public String SourcedLocation { get; set; }
        
        // Part consumption code
        public String PartUsageCode { get; set; }
        
        // The part number that was removed
        public String RemovedPartNumber { get; set; }
        
        // The serial number of the part that was removed
        public String RemovedPartSerialNumber { get; set; }
        
        // Description of the part that was removed
        public String RemovedPartDescription { get; set; }

        // Code that indicates the part failure type
        public String PartFailureCode { get; set; }
    }


    public class AppInput extends CSC_GSEM_Response{
    	public AppInput(Boolean b, String msg){
    		super(b,msg);
    	}
    }

    public AppInput closeCase(String h3cId){
    	if(String.isEmpty(h3cId)){
    		return new AppInput(false,'Empty caseId!');
    	}

    	AppOut output = new AppOut();
    	output.H3CID = h3cId;

    	//1.校验Case是否符合要求
    	Case cas = CSC_GSEM_SubK_Common_Function.getSubKCaseById(h3cId);
        if(cas == null){
            return new AppInput(false,'Case not found!');
        }
        // if(cas.IsClosed){
        //     return new AppInput(false,'Case has been closed!');
        // }
        Boolean isNotPhoneAndRejectCase = cas.Subk_CaseOrigin__c.toUpperCase()!='PHONE'
                && cas.CSC_Resolution_Type__c=='Remote Other'
                && cas.CSC_Resolution_Code__c=='Void'
                && cas.CSC_Resolution_Sub_code__c=='Reject Subk Subcode';
    	output.HPEID = cas.HPE_SubK_ID__c;

    	output.RepairLaborType = 'Hardware Repair/Installation';
    	// output.RepairHours = '';
    	output.TravelLaborType = 'Travel';
    	// output.TravelHours='';
    	output.ProductNumber = cas.CSC_PN__c;
    	output.SerialNumber = cas.CSC_SN__c;
        output.CustomerSeverity = cas.CSC_Severity__c;

    	//2.通过caseId获取Case下所有的partsOrder信息
    	Set<String> workOrderIds = new Set<String>();
        List<String> casIds = new List<String>();
        casIds.add(h3cId);
    	List<WorkOrder> ws = CSC_GSEM_SubK_Common_Function.getWorkOrdersByCaseIdsForSubk(casIds);

        if(ws.size()>0){
            WorkOrder oldestWO = minWorkOrder(output,ws);

            // output.ResolutionDescription = oldestWO.Resolution__c;
            output.ResolutionDescription = cas.CSC_Comments__c;

            if(isNotPhoneAndRejectCase){
                //如果是拒绝单子但又不是phone Case，需要设置默认值。
                output.RepairHours = '00:01';
                output.TravelHours = '00:00';
                output.RepairClass = 'IR';
                output.DelayCode = '9';
                output.ResolutionDescription = 'This case has been misrouted to H3C, please contact HPE!';
            }else{
                output.RepairClass = oldestWO.CSC_Subcase_Repair_Class_Code__c;
                output.DelayCode = String.isNotBlank(oldestWO.CSC_Subcase_Delay_Code__c)?oldestWO.CSC_Subcase_Delay_Code__c.substring(0,1):'9';
            
                Long repair = 0, travle = 0;
            	for(WorkOrder wo:ws){
                    if(filterWorkOrder(wo)) continue;

            		workOrderIds.add(wo.Id);

                    if(wo.Subcase_Onsite_Stop_Date__c!=null && wo.Subcase_Onsite_Start_Date__c!=null){
                        repair += (wo.Subcase_Onsite_Stop_Date__c.getTime()-wo.Subcase_Onsite_Start_Date__c.getTime())/1000;
                    }

                    if(wo.Subcase_Onsite_Start_Date__c!=null && wo.Subcase_Enroute_Date__c!=null){
                        travle += (wo.Subcase_Onsite_Start_Date__c.getTime()-wo.Subcase_Enroute_Date__c.getTime())/1000;
                    }

                    String woResolutionDescription = (String.isBlank(wo.Comments__c)?'':wo.Comments__c+' \r\n')
                                    + (String.isBlank(wo.Resolution__c)?'':wo.Resolution__c);

                    output.ResolutionDescription = 
                       String.isBlank(output.ResolutionDescription)
                       ?(woResolutionDescription+' \r\n')
                       :(output.ResolutionDescription+woResolutionDescription+' \r\n');
            	}

                output.RepairHours = ''+CSC_GSEM_SubK_Common_Function.formatSeconds(repair);
                output.TravelHours = ''+CSC_GSEM_SubK_Common_Function.formatSeconds(travle);
            }

        	if(workOrderIds.size()!=0){
                //3.获取ProcessQA里列表
                List<Process_QA__c> pqas =  CSC_GSEM_SubK_Common_Function.getProccessQAListbyWorkId(workOrderIds);
                Map<String,Process_QA__c> pqasMap = new Map<String,Process_QA__c>();
                for(Process_QA__c pqc:pqas){
                    pqasMap.put(pqc.WorkOrder__c, pqc);
                }

    			List<Parts_Order__c> pocs = CSC_GSEM_SubK_Common_Function.getPartsOrderByWorkOrderIds(workOrderIds);
    			for(Parts_Order__c poc:pocs){
    				
                    Process_QA__c pqc = pqasMap.get(poc.Order__r.Work_Order_Name__r.Id);
                    if(pqc!=null){
                        Quality qlt = new Quality();
        				qlt.QualityCode = isNotPhoneAndRejectCase?'0A-See comments':pqc.QA_Code__c;
        				qlt.QualityCodeType = isNotPhoneAndRejectCase?'CE QA':pqc.QA_Type__c;
                        output.Qualities.add(qlt);
                    }else{
                        if(isNotPhoneAndRejectCase){
                            Quality qlt = new Quality();
                            qlt.QualityCode = '0A-See comments';
                            qlt.QualityCodeType = 'CE QA';
                            output.Qualities.add(qlt);
                        }
                    }

    				RepairPart po = new RepairPart();
    				po.PartOrderNumber = poc.Name;
    				// po.LineItemNumber = '';

    				po.InstalledPartNumber = poc.Request_Parts__r.Name;
    				po.InstalledPartSerialNumber = poc.Parts_Serial_Number__c;
    				// po.InstalledPartDescription = poc.Offered_Parts__r.Description__c;
                    po.InstalledPartDescription = poc.Parts_Description__c;
    				
    				// po.SourcedLocation = '';
    				po.PartUsageCode = poc.Parts_Usage__c;

    				po.RemovedPartNumber = poc.Removed_Parts__r.Name;
    				po.RemovedPartSerialNumber = poc.Removed_Parts_Serial_Number__c;
    				po.RemovedPartDescription = poc.Removed_Parts__r.Description__c;
    				
    				po.PartFailureCode= poc.X_Failure_Cd__c;
    				output.RepairParts.add(po);
    			}
    		}
        } else{
            if(isNotPhoneAndRejectCase){
                //如果是拒绝单子但又不是phone Case，需要设置默认值。
                output.RepairHours = '00:01';
                output.TravelHours = '00:00';
                output.RepairClass = 'IR';
                output.DelayCode = '9';
                output.ResolutionDescription = 'This case has been misrouted to H3C, please contact HPE!';
                Quality qlt = new Quality();
                qlt.QualityCode = '0A-See comments';
                qlt.QualityCodeType = 'CE QA';
                output.Qualities.add(qlt);
            }
        }

    	//3.设置提交的JSON
	    String postString = JSON.serialize(output);
	    System.debug('Posted String is'+postString);
	    
	    //4.Post 数据到GSEM
	    String resp = '';
	    try{
	    	GSEM_Post_Url__c post = GSEM_Post_Url__c.getValues('SubKCloseCase');
		    resp = CSC_GSEM_Connection.Post(postString, post.Address__c);
		    System.debug('Hi,'+resp);
		} catch (CSC_GSEM_Connection.GSEMConnectException ex){
            //处理错误消息，需要重新发送
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'CloseSubKCase', ex.getMessage(), true);
        } catch (CalloutException ex){
            //处理错误消息，需要重新发送
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'CloseSubKCase', ex.getMessage(), true);
        } catch (Exception ex){
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'CloseSubKCase', ex.getMessage(), true);
			return new AppInput(false,ex.getMessage());
		}
	    
	    //5.获取返回值
	    AppInput input = null;
	    try{
			input = (AppInput)JSON.deserialize(resp, AppInput.class);
            if(!input.Rst){
                CSC_GSEM_Connection.LogFailerCall(h3cId, 'CloseSubKCase', input.RstMsg, false);
            }
		}catch(Exception ex){
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'CloseSubKCase', ex.getMessage(), false);
			return new AppInput(false,ex.getMessage());
		}

    	return input;
    }

    //获取最早关单的workOrder，并设置几个日期值
    public WorkOrder minWorkOrder(AppOut output,List<WorkOrder> ws){
        WorkOrder minOrder = null;
        
        if(ws == null){return null;}
        if(ws.size()==0){return null;}
        minOrder = ws.get(0);
        DateTime earliestStartDateTime = ws.get(0).Subcase_Onsite_Start_Date__c;
        DateTime lastestEndDateTime = ws.get(0).Subcase_Onsite_Stop_Date__c;
        DateTime lastestFixedDateTime = ws.get(0).Subcase_Onsite_Fixed_Date__c;
        for(WorkOrder wo:ws){
            if(filterWorkOrder(wo)) continue;
            if(wo.Subcase_Close_Date__c.getTime() < minOrder.Subcase_Close_Date__c.getTime()){
                minOrder = wo;
            }
            if(earliestStartDateTime == null){
                earliestStartDateTime = wo.Subcase_Onsite_Start_Date__c;
            }else if(wo.Subcase_Onsite_Start_Date__c!=null){
                if(wo.Subcase_Onsite_Start_Date__c.getTime() < earliestStartDateTime.getTime()){
                    earliestStartDateTime = wo.Subcase_Onsite_Start_Date__c;
                }
            }
            if(lastestEndDateTime == null){
                lastestEndDateTime = wo.Subcase_Onsite_Stop_Date__c;
            } else if(wo.Subcase_Onsite_Stop_Date__c!=null){
                if(wo.Subcase_Onsite_Stop_Date__c.getTime() > lastestEndDateTime.getTime()){
                    lastestEndDateTime = wo.Subcase_Onsite_Stop_Date__c;
                }
            }
            if(lastestFixedDateTime == null){
                lastestFixedDateTime = wo.Subcase_Onsite_Fixed_Date__c;
            } else if(wo.Subcase_Onsite_Fixed_Date__c!=null){
                if(wo.Subcase_Onsite_Fixed_Date__c.getTime() > lastestFixedDateTime.getTime()){
                    lastestFixedDateTime = wo.Subcase_Onsite_Fixed_Date__c;
                }
            }
        }
        // earliest start date/time oniste workorder 
        output.ServiceStartDateTime = earliestStartDateTime.formatGmt(dateFormat);
        //the latest end date/time onsite workorder
        output.ServiceEndDateTime = lastestEndDateTime.formatGmt(dateFormat);
        //the latest fixed time for onsite workorder
        output.SystemFixedDateTime = lastestFixedDateTime.formatGmt(dateFormat);
        return minOrder;
    }

    /**
     * [filterWorkOrder 过滤掉不满足条件的workorder]
     * @param  wo [description]
     * @return    [description]
     */
    public Boolean filterWorkOrder(WorkOrder wo){
        Boolean r = false;
        // 过滤掉不满足条件的workorder
        // if(wo.Resolution_Code__c.equalsIgnoreCase(RESOLUTION_CODE) 
        //     || wo.Resolution_Code__c.equalsIgnoreCase(NOT_RESOLVED)){
        //         r=true;
        // }
        if(wo.Record_Type__c.equalsIgnoreCase(H3C_COE) 
            || wo.Record_Type__c.equalsIgnoreCase(H3C_ERT)){
                r=true;
        }
        return r;
    }
}