src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Resubmit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Resubmit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TAT_Reason__c</fullName>
        <label>TAT Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account blocked by RPL</fullName>
                </value>
                <value>
                    <fullName>Case logged outside of business hours</fullName>
                </value>
                <value>
                    <fullName>Case misrouted due to requestor</fullName>
                </value>
                <value>
                    <fullName>Case re-opened</fullName>
                </value>
                <value>
                    <fullName>Case logged</fullName>
                </value>
                <value>
                    <fullName>Data flow issue- D&amp;B to MDM/MDCP</fullName>
                </value>
                <value>
                    <fullName>Delay in feedback by Approver</fullName>
                </value>
                <value>
                    <fullName>Delay in feedback by Requestor</fullName>
                </value>
                <value>
                    <fullName>Multiple Account request in single case</fullName>
                </value>
                <value>
                    <fullName>System downtime- MDM/MDCP</fullName>
                </value>
                <value>
                    <fullName>System downtime- SFDC</fullName>
                </value>
                <value>
                    <fullName>System issue</fullName>
                </value>
                <value>
                    <fullName>PRL blocked</fullName>
                </value>
                <value>
                    <fullName>Late reply by requestor</fullName>
                </value>
                <value>
                    <fullName>Late reply by approver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CaseUpdateRejectResubmitTest.cls
@istest(seealldata=true)
public class CaseUpdateRejectResubmitTest {
    public static testmethod void testCaseUpdateRejectResubmit() {
        //Entitlement e = [select id from Entitlement where name = '01-Account Request Entitlement Process'];
        //id uid = [select id from user where id != :userinfo.getUserId() and isActive = true limit 1].id;
        //User uid2 = [select id from user where id != :userinfo.getUserId() and isActive = true and id != :uid limit 1];
        //case c;
        //system.runas(uid2) {
        //c = new case();
        //c.status = 'New';
        //c.TAT_Reason__c = 'Case logged';
        //c.Entitlement = e;
        //insert c;
        //CaseShare cs = new CaseShare();
        //cs.caseid = c.id;
        //cs.UserOrGroupId = uid;
        //cs.CaseAccessLevel = 'Read';
        //insert cs;
        //}
        //c.status = 'Rejected';
        //c.Resubmit__c  = false;
        //update c;
        //c.status = 'Work in Progress';
        //c.Resubmit__c  = true;
       //update c;
    }
}