src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Report_CD_1V_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CD 1V case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSC_Report_CD_8_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CD 8 case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSC_Report_LtzFirst_Onsite_OpenDate__c</fullName>
        <label>Ltz First Onsite Workorder Open Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_Report_Part_Number_Counts__c</fullName>
        <label>Part_Number Counts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSC_Report_Part_Number__c</fullName>
        <label>Part Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CSC_Report_QACode__c</fullName>
        <label>QA Code</label>
        <length>75256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Courier Assist</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Sub_code__c</fullName>
        <label>Resolution Sub-code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Code__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HW Issue</fullName>
                </value>
                <value>
                    <fullName>SW Issue</fullName>
                </value>
                <value>
                    <fullName>Firmware/BIOS/Driver updates (except 3Par)</fullName>
                </value>
                <value>
                    <fullName>Implementation/Configuration/Setup questions</fullName>
                </value>
                <value>
                    <fullName>Non-Technical/Presales/Contract Coverage</fullName>
                </value>
                <value>
                    <fullName>Customer self-solved without HP assistance</fullName>
                </value>
                <value>
                    <fullName>Duplicate case logged</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Failed RPL</fullName>
                </value>
                <value>
                    <fullName>Unable to reach customer to begin diagnosis</fullName>
                </value>
                <value>
                    <fullName>Customer unwilling/Unable to perform remote diagnosis and/or implement action plan</fullName>
                </value>
                <value>
                    <fullName>Transferred out of HP EG</fullName>
                </value>
                <value>
                    <fullName>Customer declined billable service</fullName>
                </value>
                <value>
                    <fullName>Reject Subk Subcode</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Type__c</fullName>
        <label>Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-site</fullName>
                </value>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Remote resolve</fullName>
                </value>
                <value>
                    <fullName>Remote Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>CSC_FST_Service_Request</fullName>
        <active>true</active>
        <businessProcess>CSC %26 FST Service Request</businessProcess>
        <label>05-CSC &amp; FST Service Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Job_Error_log__c.object
<CustomObject>
    <description>Error log</description>
    <fields>
        <fullName>Job_Performance_Log__c</fullName>
        <label>Job Performance Log</label>
        <referenceTo>Job_Performance_Log__c</referenceTo>
        <relationshipLabel>Job Error log</relationshipLabel>
        <relationshipName>Job_Error_log_Per_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Error log</label>
    <nameField>
        <label>Error log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Performance_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Start_Time__c</fullName>
        <label>Job Start Time</label>
        <type>Date</type>
    </fields>
    <label>Job Performance Log</label>
    <nameField>
        <label>Job Performance Log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_CaseUpdate1V1B_Batch.cls
global class CSC_CaseUpdate1V1B_Batch implements Database.Batchable<sObject> {
    public String query;
    public Job_Performance_Log__c Jp;
    public List<Job_Error_log__c> Jellist;

    public static ID CASE_RECORDTYPE_ID;
    static {
        for (RecordType item : [SELECT Id, DeveloperName FROM RecordType 
                WHERE SobjectType = 'Case' AND DeveloperName = 'CSC_FST_Service_Request' LIMIT 1]) {
            CASE_RECORDTYPE_ID = item.Id;
        }
    }

    global CSC_CaseUpdate1V1B_Batch() {
        //Insert log information.
        List<Job_Performance_Log__c> JpList = [select id,Job_Start_Time__c,Class_Name__c
                                               from Job_Performance_Log__c
                                               where Job_Start_Time__c = Today and Class_Name__c =: 'Case'];
        if(JpList.size() == 0){
            Job_Performance_Log__c J = Factory.LogCreate('CSC_CaseUpdate1V1B_Batch ' + String.valueOf(System.today()), 0, 
                                                         'Case', 'CSC_CaseUpdate1V1B_Batch.', 
                                                         '');
            Jp                       = j;
        }
        else{
            Jp                       = JpList.get(0);
        }

        Jellist = new list<Job_Error_log__c>();

        Datetime filterDT = DateTime.now() - 60;

        if (!System.Test.isRunningTest()) {
            this.query = 'SELECT Id, caseNumber, CSC_Report_QACode__c, CSC_Report_CD_1V_Case__c, CSC_Report_CD_8_Case__c, CSC_Report_Part_Number__c, CSC_Report_Part_Number_Counts__c, CSC_Report_LtzFirst_Onsite_OpenDate__c, CSC_Resolution_Type__c, CSC_Resolution_Code__c, CSC_Resolution_Sub_code__c, Owner.Id FROM Case WHERE Status=\'Closed\' AND RecordTypeId=\'' +  CASE_RECORDTYPE_ID + '\' AND ClosedDate > ' + filterDT.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');    
        }
        else {
            this.query = 'SELECT Id, caseNumber, CSC_Report_QACode__c, CSC_Report_CD_1V_Case__c, CSC_Report_CD_8_Case__c, CSC_Report_Part_Number__c, CSC_Report_Part_Number_Counts__c, CSC_Report_LtzFirst_Onsite_OpenDate__c, CSC_Resolution_Type__c, CSC_Resolution_Code__c, CSC_Resolution_Sub_code__c, Owner.Id FROM Case WHERE Status=\'Closed\'  AND RecordTypeId=\'' +  CASE_RECORDTYPE_ID + '\'' + ' Order by CreatedDate ASC LIMIT 200';
        }

        Factory.ErrorLogCreate(Jellist, Jp.ID, 'CSC_CaseUpdate1V1B_Batch ' + System.today(), 'CSC_CaseUpdate1V1B_Batch','Case', 
                                   '', query, '', '', 'Loop'); 
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        List<Case> newCaseList = (List<Case>)scope;
        List<Job_Error_log__c> Jelist = new List<Job_Error_log__c>();
        
        CSC_Case_SetData.CloseCaseSetValueWithLog(newCaseList, Jelist, Jp.Id);
        //CSC_Case_SetData.CloseCaseSetValue(newCaseList);
        try {
            Database.SaveResult[] srList = Database.update(newCaseList,False);
            for(Database.SaveResult sr : srList){
                if(Sr.isSuccess() == False){
                    Factory.ErrorLogCreate(Jelist, Jp.ID, 'CSC_CaseUpdate1V1B_Batch' + System.today(), 
                                           'CSC_CaseUpdate1V1B_Batch', 'Case', Sr.getId(), String.valueOf(Sr.getErrors()), 
                                           'DML',  String.valueOf(Sr.getErrors()), 'DML');                   
                }
                else{
                    continue;
                }
            }
            
            Factory.ErrorLogCreate(Jelist, Jp.ID, 'CSC_CaseUpdate1V1B_Batch' + System.today(), 
                                           'CSC_CaseUpdate1V1B_Batch', 'Case', '', 'SaveResult size:' + srList.size(), 
                                           'DML',  '', 'DML');
        }
        catch (Exception e) {
            Factory.ErrorLogCreate(Jelist, Jp.ID, 'CSC_CaseUpdate1V1B_Batch' + System.today(), 'CSC_CaseUpdate1V1B_Batch','Case', 
                                   e.getStackTraceString(), String.valueOf(e.getMessage()), String.valueOf(e.getLineNumber()), 
                                   String.valueOf(e.getCause()), 'Loop');            
        }

        insert Jelist;
    }

    global void finish(Database.BatchableContext BC) {
        
        insert Jellist;
        //Database.executeBatch(new CaseUpdatePrecaseBatchable(), 200);
        CaseFunction C = new CaseFunction();
        String q       = C.ProcessQAQueryValue(); 
        if (!System.Test.isRunningTest()) {
            Database.executeBatch(new ProcessQABatchable(q), 200);
        }
    }
}