src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Latested_DT__c</fullName>
        <label>Latested D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>重庆市</fullName>
                </value>
                <value>
                    <fullName>重庆市-北碚区</fullName>
                </value>
                <value>
                    <fullName>重庆市-璧山</fullName>
                </value>
                <value>
                    <fullName>重庆市-长寿区</fullName>
                </value>
                <value>
                    <fullName>重庆市-城口县</fullName>
                </value>
                <value>
                    <fullName>重庆市-大足县</fullName>
                </value>
                <value>
                    <fullName>重庆市-垫江县</fullName>
                </value>
                <value>
                    <fullName>重庆市-丰都</fullName>
                </value>
                <value>
                    <fullName>重庆市-奉节</fullName>
                </value>
                <value>
                    <fullName>重庆市-合川市</fullName>
                </value>
                <value>
                    <fullName>重庆市-江北区</fullName>
                </value>
                <value>
                    <fullName>重庆市-江津市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>Shanxi</fullName>
                </value>
                <value>
                    <fullName>Shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Dispatch__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DispatchToUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dispatch</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Dispatch No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill_User__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SkillUserToUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Skill User</label>
    <nameField>
        <displayFormat>SU-{00000}</displayFormat>
        <label>Skill User No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Assign_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assign User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WorkOrderToAssignUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>江苏-常熟</fullName>
                </value>
                <value>
                    <fullName>江苏-常州</fullName>
                </value>
                <value>
                    <fullName>江苏-东台</fullName>
                </value>
                <value>
                    <fullName>江苏-淮安</fullName>
                </value>
                <value>
                    <fullName>江苏-淮阴</fullName>
                </value>
                <value>
                    <fullName>江苏-江阴</fullName>
                </value>
                <value>
                    <fullName>江苏-昆山</fullName>
                </value>
                <value>
                    <fullName>江苏-连云港</fullName>
                </value>
                <value>
                    <fullName>江苏-南京</fullName>
                </value>
                <value>
                    <fullName>江苏-南通</fullName>
                </value>
                <value>
                    <fullName>江苏-邳州</fullName>
                </value>
                <value>
                    <fullName>江苏-苏州</fullName>
                </value>
                <value>
                    <fullName>江苏-太仓</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>shanxi</fullName>
                </value>
                <value>
                    <fullName>shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <label>Requested Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Estimated_Task_Duration__c</fullName>
        <label>WorkOrder Estimated Task Duration</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_Dispatch_Controller_Test.cls
@isTest
public class CSC_Dispatch_Controller_Test
{
    // public static testMethod void CSC_Dispatch_Controller_Test1()
    // {
        // CSC_Dispatch_Controller c=new CSC_Dispatch_Controller();
        // c=new CSC_Dispatch_Controller(null);

        // WorkOrder wo=CSC_Assign_Controller_Test.GetWorkOrder();
        // wo.Requested_Date__c=null;
        // wo.Assign_User__c=userInfo.getUserId();
        // wo.Subcase_Estimated_Task_Duration__c=null;
        // wo.Province__c = null;
        // wo.City__c = null;
        // update wo;

        // case ca = CSC_Assign_Controller_Test.GetCase();
        // ca.CSC_Latested_DT__c = system.now();
        // ca.CSC_Case_Type2__c='Repair';
        // update ca;
        // ApexPages.currentPage().getParameters().put('id', wo.Id);
        // c=new CSC_Dispatch_Controller(null);
        
        // ca.CSC_Case_Type2__c='Other';
        // update ca;
        // wo.Case=ca;
        
        // datetime startTime = datetime.newInstance(2010,11,1,15,0,0);
        // datetime endTime = datetime.newInstance(2010,11,1,16,0,0);
        // wo.Requested_Date__c=startTime;
        // update wo;

        // Dispatch__c dp = new Dispatch__c();
        // dp.WorkOrder__c = wo.id;
        // dp.User__c = userInfo.getUserId();
        // dp.StartDateTime__c = startTime;
        // dp.EndDateTime__c = endTime;
        // dp.Status__c = 'Assign';
        // insert dp;

        // test.startTest();
        // ApexPages.currentPage().getParameters().put('id', wo.Id);
        // c=new CSC_Dispatch_Controller(null);
        // c.Close();
        // c.row=0;
        // CSC_Dispatch_Controller.Entity e=new CSC_Dispatch_Controller.Entity();
        // e.uName=UserInfo.GetUserName();
        // e.uId=UserInfo.GetUserId();
        // e.dt=system.today();
        // e.styleList=new List<string>();
        // c.entityInitList.add(e);
        // c.searchType = true;
        // c.Search();
        // c.searchType = false;
        // c.Search();
        // c.Assign();
        // test.stopTest();
    // }
    
//     public static testMethod void CSC_Dispatch_Controller_Test2()
//     {
//         CSC_Assign_Controller_Test.GetCase2();
//         WorkOrder wo=CSC_Assign_Controller_Test.GetWorkOrder();
//         wo.Requested_Date__c=system.now().adddays(1);
//         wo.Assign_User__c=userInfo.getUserId();
//         wo.Subcase_Estimated_Task_Duration__c=100;
//         update wo;
//         test.startTest();
//         ApexPages.currentPage().getParameters().put('id', wo.Id);
//         CSC_Dispatch_Controller c=new CSC_Dispatch_Controller(null);
//         c.Close();
//         c.row=0;
//         CSC_Dispatch_Controller.Entity e=new CSC_Dispatch_Controller.Entity();
//         e.uName=UserInfo.GetUserName();
//         e.uId=UserInfo.GetUserId();
//         e.dt=system.today();
//         e.styleList=new List<string>();
//         e.styleList.add(system.label.Holiday_Style);
//         c.entityInitList.add(e);
//         c.Assign();
        
//         c.searchType=true;
//         c.Search();
//         c.GetEntityByUser(userInfo.getUserId(),system.today().adddays(-1),system.today().adddays(10));
//         test.stopTest();
//     }
    
//     public static testMethod void CSC_Dispatch_Controller_Test3()
//     {
//         User u_CE=[Select Id,City From User Where Profile.Name = 'CSC&FST CE' And IsActive=true limit 1];
//         u_CE.City='北京市';
//         update u_CE;
//         CSC_Assign_Controller_Test.GetCase3();
//         WorkOrder wo=CSC_Assign_Controller_Test.GetWorkOrder();
//         wo.Requested_Date__c=system.now().adddays(1);
//         wo.Assign_User__c=userInfo.getUserId();
//         wo.Subcase_Estimated_Task_Duration__c=100;
//         wo.Skill_Name__c='Windows 2003/2008';
//         wo.Skill_Category__c='Operating system';
//         update wo;
        
//         ProfileSkill ps=new ProfileSkill();
//         ps.Skill_Category__c='Operating system';
//         ps.Name='Windows 2003/2008';
//         insert ps;
        
//         Skill_User__c su=new Skill_User__c();
//         su.Level__c='Advanced';
//         su.Skill__c=ps.Id;
//         su.Skill_Category__c='Operating system';
//         su.User__c=u_CE.Id;
//         insert su;
        
//         List<Dispatch__c> dList=new List<Dispatch__c>();
//         Dispatch__c d=new Dispatch__c();
//         d.StartDateTime__c=system.now().adddays(-1);
//         d.EndDateTime__c=system.now().adddays(1);
//         d.Status__c='Holiday';
//         d.User__c=u_CE.Id;
//         dList.add(d);
        
//         insert dList;
        
//         test.startTest();
//         ApexPages.currentPage().getParameters().put('id', wo.Id);
//         CSC_Dispatch_Controller c=new CSC_Dispatch_Controller(null);
//         c.Close();
//         c.row=0;
//         CSC_Dispatch_Controller.Entity e=new CSC_Dispatch_Controller.Entity();
//         e.uName=UserInfo.GetUserName();
//         e.uId=UserInfo.GetUserId();
//         e.dt=system.today();
//         e.styleList=new List<string>();
//         e.styleList.add(system.label.Holiday_Style);
//         c.entityInitList.add(e);
//         c.Assign();
        
//         c.searchType=true;
//         c.Search();
//         c.GetEntityByUser(userInfo.getUserId(),system.today().adddays(-1),system.today().adddays(10));
        
//         c.wo.City__c='北京市';
//         c.GetAllEntity();
        
//         test.stopTest();
//     }
}