src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_FTP_End_Date__c</fullName>
        <label>FTP End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSC_FTP_Start_Date__c</fullName>
        <label>FTP Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSC_FTP_URL__c</fullName>
        <label>FTP URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>FTP_Creator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FTP Creator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>case_Ftp_Creator</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/RunFTPFunction_Test.cls
@isTest
private class RunFTPFunction_Test {
    static testMethod void testMethod1() {
        Test.startTest();
        Case objCase = TestUtil.getCase();
        objCase.CSC_FTP_URL__c = 'ftp://test.test';
        objCase.CSC_FTP_Start_Date__c = Date.today();
        objCase.CSC_FTP_End_Date__c = Date.today()+7;
        objCase.FTP_Creator__c = TestUtil.getUser().Id;
        objCase.Status = 'Active';
        insert objCase;

        Case caze = [select CaseNumber from case where Id =:objCase.Id];
        RunFTPFunction.RunFTPAlertMessge(String.valueOf(caze.CaseNumber));
        Test.stopTest();
    }
}