src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HW Delivery</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Advanced Support</fullName>
                </value>
                <value>
                    <fullName>Install</fullName>
                </value>
                <value>
                    <fullName>MC Non-BCS</fullName>
                </value>
                <value>
                    <fullName>MC Datacenter</fullName>
                </value>
                <value>
                    <fullName>Proactive</fullName>
                </value>
                <value>
                    <fullName>Questions</fullName>
                </value>
                <value>
                    <fullName>SW Delivery</fullName>
                </value>
                <value>
                    <fullName>CE Assist</fullName>
                </value>
                <value>
                    <fullName>Depot Repair</fullName>
                </value>
                <value>
                    <fullName>T&amp;M</fullName>
                </value>
                <value>
                    <fullName>MC CTR</fullName>
                </value>
                <value>
                    <fullName>CTR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Cause__c</fullName>
        <label>Cause</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSC_Environment__c</fullName>
        <label>Environment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSC_OTC__c</fullName>
        <label>OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>05R-Normal Contract</fullName>
                    <color>#0B6FCE</color>
                    <label>05R-Normal Contract</label>
                </value>
                <value>
                    <fullName>02N-Warranty Normal</fullName>
                    <color>#78C953</color>
                    <label>02N-Warranty Normal</label>
                </value>
                <value>
                    <fullName>05A-Complmt TAC</fullName>
                    <color>#E27001</color>
                    <label>05A-Complmt TAC</label>
                </value>
                <value>
                    <fullName>05K-Extended Warranty</fullName>
                    <color>#A845DC</color>
                    <label>05K-Extended Warranty</label>
                </value>
                <value>
                    <fullName>05Q-Preventative</fullName>
                    <color>#F3D904</color>
                    <label>05Q-Preventative</label>
                </value>
                <value>
                    <fullName>02G-Sevice Note</fullName>
                    <color>#A53711</color>
                    <label>02G-Sevice Note</label>
                </value>
                <value>
                    <fullName>06J-Intl Gratis</fullName>
                    <color>#66E9BD</color>
                    <label>06J-Intl Gratis</label>
                </value>
                <value>
                    <fullName>00C-Cust Claims Cont</fullName>
                    <color>#0B24BE</color>
                    <label>00C-Cust Claims Cont</label>
                </value>
                <value>
                    <fullName>00W-Cust Claims Warr</fullName>
                    <color>#419249</color>
                    <label>00W-Cust Claims Warr</label>
                </value>
                <value>
                    <fullName>00E-No Entitlement</fullName>
                </value>
                <value>
                    <fullName>01-Trade</fullName>
                    <color>#B6E32E</color>
                    <label>01-Trade</label>
                </value>
                <value>
                    <fullName>06M-Intl re-repair</fullName>
                    <color>#641CCF</color>
                    <label>06M-Intl re-repair</label>
                </value>
                <value>
                    <fullName>05F-Comp Fld Inst</fullName>
                    <color>#F96FB7</color>
                    <label>05F-Comp Fld Inst</label>
                </value>
                <value>
                    <fullName>05S-Compl Site Prep</fullName>
                    <color>#2F5D85</color>
                    <label>05S-Compl Site Prep</label>
                </value>
                <value>
                    <fullName>06F-Intl Field Instl</fullName>
                    <color>#AFCADF</color>
                    <label>06F-Intl Field Instl</label>
                </value>
                <value>
                    <fullName>05P-Contracts: Predictive Support</fullName>
                    <color>#8F6429</color>
                    <label>05P-Contracts: Predictive Support</label>
                </value>
                <value>
                    <fullName>09U-UWD Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution__c</fullName>
        <label>Resolution</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_WorkOrder_Test.cls
@isTest
public class CSC_WorkOrder_Test
{
    public static testMethod void CSC_WorkOrder_Test1()
    { 
        Case c=CSC_Assign_Controller_Test.GetCase();
        c.CSC_Environment__c='CSC_Environment__c';
        c.CSC_Cause__c='CSC_Cause__c';
        c.CSC_Resolution__c='DEF';
        c.CSC_OTC__c='05R-Normal Contract';
        c.CSC_Case_Type__c='DEF';
        update c;
        
        WorkOrder wo=CSC_Assign_Controller_Test.GetWorkOrder();
        CSC_Assign_Controller_Test.GetOrder();
        CSC_Assign_Controller_Test.GetParts();
        test.startTest();
        
        CSC_WorkOrder.GetRecordType();
        CSC_WorkOrder.GetHoliday();
        List<Group> dpList=CSC_WorkOrder.GetDpList();
        CSC_WorkOrder.GetDpGroup();
        CSC_WorkOrder.GetUser();
        CSC_WorkOrder.Check_Activity_InDPQ(null);
        List<Task> tList=new List<Task>();
        Task t1=new Task();
        t1.ActivityDate=system.today();
        t1.Action_Type__c='Onsite Action';
        //t1.Action_Type__c='Troubleshooting';
        t1.WhatId=c.Id;
        tList.add(t1);
        
        Task t2=new Task();
        t2.ActivityDate=system.today();
        //t2.Action_Type__c='Onsite Action';
        t2.Action_Type__c='Troubleshooting';
        t2.WhatId=c.Id;
        tList.add(t2);
        
        insert tList;

        if(dpList.size()>0)
        {
            wo.OwnerId=dpList[0].Id;
            wo.status='Closed';
            try
            {
                update wo;
            }
            catch(Exception ex)
            {
            }
        }
        test.stopTest();
    }
    
    
    public static testMethod void CSC_WorkOrder_Test3()
    {
        Case c=CSC_Assign_Controller_Test.GetCase();
        WorkOrder wo=CSC_Assign_Controller_Test.GetWorkOrder();
        test.startTest();
        
        CSC_WorkOrder.GetRecordType();
        CSC_WorkOrder.GetHoliday();
        List<Group> dpList=CSC_WorkOrder.GetDpList();
        CSC_WorkOrder.GetDpGroup();
        CSC_WorkOrder.GetUser();
        CSC_WorkOrder.Check_Activity_InDPQ(null);
        List<Task> tList=new List<Task>();
        Task t1=new Task();
        t1.ActivityDate=system.today();
        t1.Action_Type__c='Onsite Action';
        //t1.Action_Type__c='Troubleshooting';
        t1.WhatId=c.Id;
        tList.add(t1);
        
        Task t2=new Task();
        t2.ActivityDate=system.today();
        //t2.Action_Type__c='Onsite Action';
        t2.Action_Type__c='Troubleshooting';
        t2.WhatId=c.Id;
        tList.add(t2);
        
        insert tList;

        if(dpList.size()>0)
        {
            wo.OwnerId=dpList[0].Id;
            wo.status='Closed';
            try
            {
                update wo;
            }
            catch(Exception e)
            {
            }
        }
        test.stopTest();
    }

}