src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Cause__c</fullName>
        <label>Cause</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSC_Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSC_Environment__c</fullName>
        <label>Environment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSC_Error_Codes__c</fullName>
        <label>Error Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Is_Issue_Intermittent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Issue Intermittent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSC_Issue__c</fullName>
        <label>Issue</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSC_OPTId__c</fullName>
        <description>外部系统ID（HPE）</description>
        <externalId>true</externalId>
        <label>HPE ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Courier Assist</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Sub_code__c</fullName>
        <label>Resolution Sub-code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Code__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HW Issue</fullName>
                </value>
                <value>
                    <fullName>SW Issue</fullName>
                </value>
                <value>
                    <fullName>Firmware/BIOS/Driver updates (except 3Par)</fullName>
                </value>
                <value>
                    <fullName>Implementation/Configuration/Setup questions</fullName>
                </value>
                <value>
                    <fullName>Non-Technical/Presales/Contract Coverage</fullName>
                </value>
                <value>
                    <fullName>Customer self-solved without HP assistance</fullName>
                </value>
                <value>
                    <fullName>Duplicate case logged</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Failed RPL</fullName>
                </value>
                <value>
                    <fullName>Unable to reach customer to begin diagnosis</fullName>
                </value>
                <value>
                    <fullName>Customer unwilling/Unable to perform remote diagnosis and/or implement action plan</fullName>
                </value>
                <value>
                    <fullName>Transferred out of HP EG</fullName>
                </value>
                <value>
                    <fullName>Customer declined billable service</fullName>
                </value>
                <value>
                    <fullName>Reject Subk Subcode</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Type__c</fullName>
        <label>Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-site</fullName>
                </value>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Remote resolve</fullName>
                </value>
                <value>
                    <fullName>Remote Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution__c</fullName>
        <label>Resolution</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/EmailShowCaseInfo.cls
public with sharing class EmailShowCaseInfo {
	public String CaseID {get;set;}

    public EmailShowCaseInfo() {
        
    }

    public Case getCaseInfo() {
    	Case main = new Case();
    	if (CaseID != null && String.isNotBlank(CaseID)) {
    		List<Case> caseList = [SELECT Id, Subject, CSC_OPTId__c, CSC_Comments__c, CSC_Environment__c, CSC_Issue__c,
    				CSC_Error_Codes__c, CSC_Is_Issue_Intermittent__c, CSC_Resolution__c, CSC_Resolution_Code__c, CSC_Resolution_Type__c,
    				CSC_Resolution_Sub_code__c, CSC_Cause__c
    				FROM Case WHERE Id = :CaseID];

    		if (caseList.size() > 0) {
    			main = caseList[0];
    		}
    	}

    	return main;
    }
}