src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HW Delivery</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Advanced Support</fullName>
                </value>
                <value>
                    <fullName>Install</fullName>
                </value>
                <value>
                    <fullName>MC Non-BCS</fullName>
                </value>
                <value>
                    <fullName>MC Datacenter</fullName>
                </value>
                <value>
                    <fullName>Proactive</fullName>
                </value>
                <value>
                    <fullName>Questions</fullName>
                </value>
                <value>
                    <fullName>SW Delivery</fullName>
                </value>
                <value>
                    <fullName>CE Assist</fullName>
                </value>
                <value>
                    <fullName>Depot Repair</fullName>
                </value>
                <value>
                    <fullName>T&amp;M</fullName>
                </value>
                <value>
                    <fullName>MC CTR</fullName>
                </value>
                <value>
                    <fullName>CTR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Contract__c</fullName>
        <label>Contract</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Entitle_Guaranteed_DT__c</fullName>
        <label>Entitle Guaranteed D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_Latested_DT__c</fullName>
        <label>Latested D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_OTC__c</fullName>
        <label>OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>05R-Normal Contract</fullName>
                    <color>#0B6FCE</color>
                    <label>05R-Normal Contract</label>
                </value>
                <value>
                    <fullName>02N-Warranty Normal</fullName>
                    <color>#78C953</color>
                    <label>02N-Warranty Normal</label>
                </value>
                <value>
                    <fullName>05A-Complmt TAC</fullName>
                    <color>#E27001</color>
                    <label>05A-Complmt TAC</label>
                </value>
                <value>
                    <fullName>05K-Extended Warranty</fullName>
                    <color>#A845DC</color>
                    <label>05K-Extended Warranty</label>
                </value>
                <value>
                    <fullName>05Q-Preventative</fullName>
                    <color>#F3D904</color>
                    <label>05Q-Preventative</label>
                </value>
                <value>
                    <fullName>02G-Sevice Note</fullName>
                    <color>#A53711</color>
                    <label>02G-Sevice Note</label>
                </value>
                <value>
                    <fullName>06J-Intl Gratis</fullName>
                    <color>#66E9BD</color>
                    <label>06J-Intl Gratis</label>
                </value>
                <value>
                    <fullName>00C-Cust Claims Cont</fullName>
                    <color>#0B24BE</color>
                    <label>00C-Cust Claims Cont</label>
                </value>
                <value>
                    <fullName>00W-Cust Claims Warr</fullName>
                    <color>#419249</color>
                    <label>00W-Cust Claims Warr</label>
                </value>
                <value>
                    <fullName>00E-No Entitlement</fullName>
                </value>
                <value>
                    <fullName>01-Trade</fullName>
                    <color>#B6E32E</color>
                    <label>01-Trade</label>
                </value>
                <value>
                    <fullName>06M-Intl re-repair</fullName>
                    <color>#641CCF</color>
                    <label>06M-Intl re-repair</label>
                </value>
                <value>
                    <fullName>05F-Comp Fld Inst</fullName>
                    <color>#F96FB7</color>
                    <label>05F-Comp Fld Inst</label>
                </value>
                <value>
                    <fullName>05S-Compl Site Prep</fullName>
                    <color>#2F5D85</color>
                    <label>05S-Compl Site Prep</label>
                </value>
                <value>
                    <fullName>06F-Intl Field Instl</fullName>
                    <color>#AFCADF</color>
                    <label>06F-Intl Field Instl</label>
                </value>
                <value>
                    <fullName>05P-Contracts: Predictive Support</fullName>
                    <color>#8F6429</color>
                    <label>05P-Contracts: Predictive Support</label>
                </value>
                <value>
                    <fullName>09U-UWD Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_PN__c</fullName>
        <label>Product Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Product_Description__c</fullName>
        <label>Product Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Product_Line__c</fullName>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Requested_DT__c</fullName>
        <label>Requested D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_Requested_Guaranteed_DT__c</fullName>
        <label>Requested Guaranteed D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Warranty_Status__c</fullName>
        <label>Warranty Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_hpl__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hpl</label>
        <referenceTo>Ref_Value__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases_hpl</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA_TYPE__c</fullName>
        <formula>Entitlement.SLA_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLA_TYPE</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>Check_Date__c</fullName>
        <description>Entitlement&apos;s check date</description>
        <label>Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Coverage_Response__c</fullName>
        <description>Entitlement&apos;s Coverage/Response</description>
        <label>Coverage/Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entitlement_Status__c</fullName>
        <description>Entitlement&apos;s status</description>
        <label>Entitlement Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entitlement_Warning_Message__c</fullName>
        <label>Entitlement Warning Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PN__c</fullName>
        <description>Product Number</description>
        <label>Product Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <description>Product Description</description>
        <label>Product Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>Product Line</description>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Type__c</fullName>
        <label>SLA Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SN__c</fullName>
        <description>Serial Number</description>
        <label>Serial Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_Product_Description__c</fullName>
        <formula>Case.CSC_Product_Description__c</formula>
        <label>Product Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Product_Line__c</fullName>
        <formula>Case.CSC_Product_Line__c</formula>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <formula>Case.CSC_SN__c</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Type__c</fullName>
        <label>SLA Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_Flow2_EsController.cls
global with sharing class CSC_Flow2_EsController {

    public final static String ENTITLEMENT_NAME = 'CSC_ENTITLEMENT_NAME'; 

    @Future(callout=true)
    public static void getEntitlementInfo(Set<Id> caseIds){

        List<Case> caseList = [SELECT Id,CSC_SN__c,CSC_PN__c,AccountId,CreatedDate,CSC_Contract__c,CSC_Product_Line__c,CSC_Product_Description__c,CSC_Requested_DT__c,CSC_Latested_DT__c,CSC_Entitle_Guaranteed_DT__c,
                                    CSC_Requested_Guaranteed_DT__c,CSC_Case_Type__c,CSC_hpl__c,CSC_OTC__c,CSC_Warranty_Status__c,Origin FROM Case Where Id IN : caseIds];
        
        Date searchDate = Date.today();

        String strGetEntitlementInfo = '';

        List<Entitlement> entitles = new List<Entitlement>();

        // NGMS过来的单子，不需要更改OTC Code
        Map<Id,String> otcMap = new Map<Id,String>();

        for (Case objCase:caseList){

            strGetEntitlementInfo = CSC_SearchEntitlementInfo.getEntitlementInfo(objCase.CSC_SN__c, objCase.CSC_PN__c, searchDate);
            CSC_GetEntitlementInfoResult rtnRsult = (CSC_GetEntitlementInfoResult)JSON.deserialize(strGetEntitlementInfo, CSC_GetEntitlementInfoResult.class);

            system.debug('rtnRsult:' + rtnRsult);
            system.debug('objCase.CSC_SN__c:' + objCase.CSC_SN__c);
            system.debug('objCase.CSC_PN__c:' + objCase.CSC_PN__c);
            
            Entitlement objEntitle = new Entitlement();

            /*objCase.CSC_Contract__c = '';
            objCase.CSC_Product_Line__c = '';
            objCase.CSC_Product_Description__c = '';
            objCase.CSC_Requested_DT__c = null;
            objCase.CSC_Latested_DT__c = null;
            objCase.CSC_Entitle_Guaranteed_DT__c = null;
            objCase.CSC_Requested_Guaranteed_DT__c = null;
            objCase.CSC_Case_Type__c = '';
            objCase.CSC_OTC__c = '';*/

            // NGMS接口过来创建的单子
            if (CSC_GSEM_Common_Function.ORIGIN_TYPE_NGMS_TS.equalsIgnoreCase(objCase.Origin) || 
                CSC_GSEM_Common_Function.ORIGIN_TYPE_NGMS_IN.equalsIgnoreCase(objCase.Origin)){

                otcMap.put(objCase.Id, objCase.CSC_OTC__c);

            }

            system.debug('rtnRsult.resultCode:' + rtnRsult.resultCode);

            if (rtnRsult != null) {

                if ('1'.equals(rtnRsult.resultCode)) {
                    CSC_Case_SetData.setEntitlementInfo(rtnRsult.entitlementInfo, objCase, objEntitle);
                } else {

                    objEntitle.SN__c = objCase.CSC_SN__c;
                    objEntitle.PN__c = objCase.CSC_PN__c;
                    
                    objEntitle.Check_Date__c = searchDate;
                    if ('0'.equals(rtnRsult.resultCode) || '2'.equals(rtnRsult.resultCode) ||
                         '3'.equals(rtnRsult.resultCode) || '5'.equals(rtnRsult.resultCode)) {
                        
                        objEntitle.Entitlement_Status__c = rtnRsult.message;
           
                        if ('3'.equals(rtnRsult.resultCode) || '5'.equals(rtnRsult.resultCode)) {
                            objCase.CSC_OTC__c = '01-Trade';
                        }

                        if (rtnRsult.entitlementInfo != null) {
                            if (rtnRsult.entitlementInfo.productID != null) {
                                objEntitle.PN__c = rtnRsult.entitlementInfo.productID;
                            }
                            
                            if (rtnRsult.entitlementInfo.productLineCode != null) {
                                objEntitle.Product_Line__c = rtnRsult.entitlementInfo.productLineCode;
                            }
                            
                            if (rtnRsult.entitlementInfo.productDescription != null) {
                                objEntitle.Product_Description__c = rtnRsult.entitlementInfo.productDescription;
                            }

                            objEntitle.Entitlement_Warning_Message__c = rtnRsult.entitlementInfo.warningMsg;                            
                        }

                    }else{//多个product list的时候，得手动做查询
                        objEntitle.Entitlement_Status__c = 'There are more than one product, please manually select';
                    }
                }

                objEntitle.Name = ENTITLEMENT_NAME;
                system.debug('objEntitle:' + objEntitle);
                objEntitle.AccountId = objCase.AccountId;
                entitles.add(objEntitle);
            }
        }

        system.debug('entitles:' + entitles);

        if (entitles != null && !entitles.isEmpty()){
            insert entitles;

            for (Case objCase:caseList){

                system.debug('objCase.CSC_SN__c:' + objCase.CSC_SN__c);

                for (Entitlement objEn : entitles){

                    if (objCase.CSC_SN__c.equals(objEn.SN__c)){
                        objCase.EntitlementId = objEn.Id;
                        objCase.CSC_PN__c = objEn.PN__c;
                        objCase.CSC_Product_Line__c = objEn.Product_Line__c;
                        objCase.CSC_Product_Description__c = objEn.Product_Description__c;
                        system.debug('objEn.Id:' + objEn.Id);
                        system.debug('objEn.SN__c:' + objEn.SN__c);
                    }

                }

                // NGMS过来的单子，不需要更改OTC Code
                for(String otcItem:otcMap.keySet()){

                    if (otcItem.equalsIgnoreCase(objCase.Id)){

                        objCase.CSC_OTC__c = otcMap.get(otcItem);
                    }
                }
            }
        }

        update caseList;

        addWorkorderSla(caseList);
    }

    /**
     方法名: addWorkorderSla
     功能说明: NGMS TS或者腾讯创建的case，如果有workorder,更新workorder的SLA__c和SLA_Type__c
     参数说明: caseList
     返回值: 无
     作者: zhouxiong
     日期: 2016-12-22
    */
    public static void addWorkorderSla(List<Case> caseList){

        Set<Id> ids = new Set<Id>();

        //循环caseList,得到case id的数组，用来查询case信息
        for (Case cItem : caseList){

            ids.add(cItem.Id);
        }

        system.debug('ids:' + ids);

        //查询Case信息
        Map<Id,Case> cMap = new Map<Id,Case>([Select Id, EntitlementId, Entitlement.Coverage_Response__c, Entitlement.SLA_Type__c,Origin 
                                              From Case 
                                              Where Id in :ids]);

        List<Workorder> woList = [Select Id,SLA__c,SLA_Type__c,CaseId From workorder Where CaseId in :cMap.keySet()];


        // 已经做了自动Entitlement，而且有workorder的数据，将case的SLA赋值给workorder的SLA
        for (String cItem : cMap.keySet()){

            Case c = cMap.get(cItem);

            for (Workorder wo : woList){

                // TS或者腾讯接口创建的单子
                if ((CSC_GSEM_Common_Function.ORIGIN_TYPE_TC.equalsIgnoreCase(c.Origin) || CSC_GSEM_Common_Function.ORIGIN_TYPE_NGMS_TS.equalsIgnoreCase(c.Origin))
                    && cItem.equalsIgnoreCase(wo.CaseId)){

                    if (c.EntitlementId != null){

                        wo.SLA__c=c.Entitlement.Coverage_Response__c;
                        wo.SLA_Type__c=c.Entitlement.SLA_Type__c;

                    }
                }
            }

        }

        update woList;
    }
}