src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Antifraud_Check_Pass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Antifraud Check Pass</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSC_OTC__c</fullName>
        <label>OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>05R-Normal Contract</fullName>
                    <color>#0B6FCE</color>
                    <label>05R-Normal Contract</label>
                </value>
                <value>
                    <fullName>02N-Warranty Normal</fullName>
                    <color>#78C953</color>
                    <label>02N-Warranty Normal</label>
                </value>
                <value>
                    <fullName>05A-Complmt TAC</fullName>
                    <color>#E27001</color>
                    <label>05A-Complmt TAC</label>
                </value>
                <value>
                    <fullName>05K-Extended Warranty</fullName>
                    <color>#A845DC</color>
                    <label>05K-Extended Warranty</label>
                </value>
                <value>
                    <fullName>05Q-Preventative</fullName>
                    <color>#F3D904</color>
                    <label>05Q-Preventative</label>
                </value>
                <value>
                    <fullName>02G-Sevice Note</fullName>
                    <color>#A53711</color>
                    <label>02G-Sevice Note</label>
                </value>
                <value>
                    <fullName>06J-Intl Gratis</fullName>
                    <color>#66E9BD</color>
                    <label>06J-Intl Gratis</label>
                </value>
                <value>
                    <fullName>00C-Cust Claims Cont</fullName>
                    <color>#0B24BE</color>
                    <label>00C-Cust Claims Cont</label>
                </value>
                <value>
                    <fullName>00W-Cust Claims Warr</fullName>
                    <color>#419249</color>
                    <label>00W-Cust Claims Warr</label>
                </value>
                <value>
                    <fullName>00E-No Entitlement</fullName>
                </value>
                <value>
                    <fullName>01-Trade</fullName>
                    <color>#B6E32E</color>
                    <label>01-Trade</label>
                </value>
                <value>
                    <fullName>06M-Intl re-repair</fullName>
                    <color>#641CCF</color>
                    <label>06M-Intl re-repair</label>
                </value>
                <value>
                    <fullName>05F-Comp Fld Inst</fullName>
                    <color>#F96FB7</color>
                    <label>05F-Comp Fld Inst</label>
                </value>
                <value>
                    <fullName>05S-Compl Site Prep</fullName>
                    <color>#2F5D85</color>
                    <label>05S-Compl Site Prep</label>
                </value>
                <value>
                    <fullName>06F-Intl Field Instl</fullName>
                    <color>#AFCADF</color>
                    <label>06F-Intl Field Instl</label>
                </value>
                <value>
                    <fullName>05P-Contracts: Predictive Support</fullName>
                    <color>#8F6429</color>
                    <label>05P-Contracts: Predictive Support</label>
                </value>
                <value>
                    <fullName>09U-UWD Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Product_Line__c</fullName>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_RPL_AntiFraud_check__c</fullName>
        <formula>AND(OR(ISBLANK( TEXT(CSC_RPL_Status__c)), ISNULL(TEXT(CSC_RPL_Status__c)),ISBLANK(TEXT(AntiFraud_Status__c)), ISNULL(TEXT(AntiFraud_Status__c))), TEXT(CSC_CaseOrQuickLog__c) ==&apos;Normal Case&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RPL AntiFraud check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSC_Repair_Class_Code__c</fullName>
        <label>Repair Class Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DEF</fullName>
                </value>
                <value>
                    <fullName>Account Management Activities</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Courier Assist</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Sub_code__c</fullName>
        <label>Resolution Sub-code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSC_Resolution_Code__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HW Issue</fullName>
                </value>
                <value>
                    <fullName>SW Issue</fullName>
                </value>
                <value>
                    <fullName>Firmware/BIOS/Driver updates (except 3Par)</fullName>
                </value>
                <value>
                    <fullName>Implementation/Configuration/Setup questions</fullName>
                </value>
                <value>
                    <fullName>Non-Technical/Presales/Contract Coverage</fullName>
                </value>
                <value>
                    <fullName>Customer self-solved without HP assistance</fullName>
                </value>
                <value>
                    <fullName>Duplicate case logged</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Failed RPL</fullName>
                </value>
                <value>
                    <fullName>Unable to reach customer to begin diagnosis</fullName>
                </value>
                <value>
                    <fullName>Customer unwilling/Unable to perform remote diagnosis and/or implement action plan</fullName>
                </value>
                <value>
                    <fullName>Transferred out of HP EG</fullName>
                </value>
                <value>
                    <fullName>Customer declined billable service</fullName>
                </value>
                <value>
                    <fullName>Reject Subk Subcode</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Resolution_Type__c</fullName>
        <label>Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On-site</fullName>
                </value>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Remote resolve</fullName>
                </value>
                <value>
                    <fullName>Remote Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phase_II_flag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Phase II flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Integration_Status__c.object
<CustomObject>
    <fields>
        <fullName>Phase_II_Flag__c</fullName>
        <formula>Case_Name__r.Phase_II_flag__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Phase II Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{0000000000}</displayFormat>
        <label>Num</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Parts_Order__c.object
<CustomObject>
    <fields>
        <fullName>Need_Anti_Fake_check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Anti-Fake check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Parts Order</relationshipLabel>
        <relationshipName>Parts_Order</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_Product_Line__c</fullName>
        <formula>Case.CSC_Product_Line__c</formula>
        <label>Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase_II_Flag__c</fullName>
        <formula>Case.Phase_II_flag__c</formula>
        <label>Phase II Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_EBS_SendFinanceMsgTest.cls
@isTest
private class CSC_EBS_SendFinanceMsgTest {
    static testMethod void testMethod1() {
        Test.startTest();
        Account a =TestUtil.getAccount('测试用户');
        Contact c = TestUtil.getContact('测试联系人123',a.Id); //Add by Lily @2017-11-23 for NGMS PQR issue
        Entitlement e = TestUtil.getInsertEntitlement(a.Id);
        Case caze = TestUtil.getCase();
        caze.AccountId = a.Id;//Add by Lily @2017-11-23 for NGMS PQR issue
		caze.ContactId = c.Id;//Add by Lily @2017-11-23 for NGMS PQR issue      
        insert caze;
        //Case c =[Select Id,Status From Case Where Billing_Street__c = '上海市闸北区裕通路100号23F(测试地址)' And Phase_II_flag__c = true][0];
        Integration_Status__c integrationS = TestUtil.getIntegration(caze.Id);
        insert integrationS;
        Workorder w = ElevationToHPEComponentTest.GetWorkOrder(caze.Id);
        Order__c o = EmailHpeConciegeWorkOrderTest.getOrder(w.Id);
        Parts_Order__c po = TestUtil.GetPartsOrder(o);

        po.Need_Anti_Fake_check__c = false;
        update po;

        w.Status = 'Closed';

        update w;

        caze.Status = 'Closed';
        caze.CSC_Resolution_Type__c = 'Remote Other';
        caze.CSC_Resolution_Code__c = 'Void';
        caze.CSC_Resolution_Sub_code__c = 'Test Case';
        Update caze;

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/SendFinanceData/';  
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        CSC_EBS_SendFinanceMsg.doPost();
        Test.stopTest();
    }

    static testMethod void testMethod2() {
        Test.startTest();
        Account a =TestUtil.getAccount('测试用户');
        Contact c = TestUtil.getContact('测试联系人123',a.Id); //Add by Lily @2017-11-23 for NGMS PQR issue
        Entitlement e = TestUtil.getInsertEntitlement(a.Id);
        Case caze = TestUtil.getCase();
        caze.AccountId = a.Id;//Add by Lily @2017-11-23 for NGMS PQR issue
        caze.ContactId = c.Id;//Add by Lily @2017-11-23 for NGMS PQR issue
        caze.CSC_Antifraud_Check_Pass__c = true;
        //caze.CSC_RPL_AntiFraud_check__c = true;
        insert caze;
        //Case c =[Select Id,Status From Case Where Billing_Street__c = '上海市闸北区裕通路100号23F(测试地址)' And Phase_II_flag__c = true][0];
        Integration_Status__c integrationS = TestUtil.getIntegration(caze.Id);
        insert integrationS;
        Workorder w = ElevationToHPEComponentTest.GetWorkOrder(caze.Id);
        Order__c o = EmailHpeConciegeWorkOrderTest.getOrder(w.Id);
        Parts_Order__c po = TestUtil.GetPartsOrder(o);

        po.Need_Anti_Fake_check__c = false;
        update po;

        w.Status = 'Closed';

        update w;

        caze.Status = 'Closed';
        caze.CSC_Product_Line__c = 'CHZ';
        caze.CSC_Resolution_Type__c = 'Remote Other';
        caze.CSC_Resolution_Code__c = 'Void';
        caze.CSC_Resolution_Sub_code__c = 'Test Case';
        
        Update caze;

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/SendFinanceData/';  
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        CSC_EBS_SendFinanceMsg.doPost();
        Test.stopTest();
    }

    static testMethod void testMethod3() {
        Test.startTest();
        Account a =TestUtil.getAccount('测试用户');
        Contact c = TestUtil.getContact('测试联系人123',a.Id); //Add by Lily @2017-11-23 for NGMS PQR issue
        Entitlement e = TestUtil.getInsertEntitlement(a.Id);
        Case caze = TestUtil.getCase();        
		caze.AccountId = a.Id;//Add by Lily @2017-11-23 for NGMS PQR issue
		caze.ContactId = c.Id;//Add by Lily @2017-11-23 for NGMS PQR issue
        caze.CSC_Antifraud_Check_Pass__c = true;
        //caze.CSC_RPL_AntiFraud_check__c = true;
        insert caze;
        //Case c =[Select Id,Status From Case Where Billing_Street__c = '上海市闸北区裕通路100号23F(测试地址)' And Phase_II_flag__c = true][0];
        Integration_Status__c integrationS = TestUtil.getIntegration(caze.Id);
        insert integrationS;
        Workorder w = ElevationToHPEComponentTest.GetWorkOrder(caze.Id);
        Order__c o = EmailHpeConciegeWorkOrderTest.getOrder(w.Id);
        Parts_Order__c po = TestUtil.GetPartsOrder(o);

        po.Need_Anti_Fake_check__c = false;
        update po;

        w.Status = 'Closed';

        update w;

        caze.Status = 'Closed';
        caze.CSC_Product_Line__c = 'NW';
        caze.CSC_Resolution_Type__c = 'Remote Other';
        caze.CSC_Resolution_Code__c = 'Void';
        caze.CSC_Resolution_Sub_code__c = 'Test Case';
        
        Update caze;

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/SendFinanceData/';  
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        CSC_EBS_SendFinanceMsg.doPost();
        Test.stopTest();
    }

    static testMethod void testMethod4() {
        Test.startTest();
        Account a =TestUtil.getAccount('测试用户');
        Contact c = TestUtil.getContact('测试联系人123',a.Id); //Add by Lily @2017-11-23 for NGMS PQR issue
        Entitlement e = TestUtil.getInsertEntitlement(a.Id);
        Case caze = TestUtil.getCase();
        caze.AccountId = a.Id;//Add by Lily @2017-11-23 for NGMS PQR issue
		caze.ContactId = c.Id;//Add by Lily @2017-11-23 for NGMS PQR issue
        caze.CSC_OTC__c = '05S-Compl Site Prep';
        caze.CSC_Repair_Class_Code__c = 'AA';
        caze.CSC_Antifraud_Check_Pass__c = true;
        //caze.CSC_RPL_AntiFraud_check__c = true;
        insert caze;
        //Case c =[Select Id,Status From Case Where Billing_Street__c = '上海市闸北区裕通路100号23F(测试地址)' And Phase_II_flag__c = true][0];
        Integration_Status__c integrationS = TestUtil.getIntegration(caze.Id);
        insert integrationS;
        Workorder w = ElevationToHPEComponentTest.GetWorkOrder(caze.Id);
        Order__c o = EmailHpeConciegeWorkOrderTest.getOrder(w.Id);
        Parts_Order__c po = TestUtil.GetPartsOrder(o);

        po.Need_Anti_Fake_check__c = false;
        update po;

        w.Status = 'Closed';

        update w;

        caze.Status = 'Closed';
        caze.CSC_Product_Line__c = 'NW';
        caze.CSC_Resolution_Type__c = 'Remote Other';
        caze.CSC_Resolution_Code__c = 'Void';
        caze.CSC_Resolution_Sub_code__c = 'Test Case';
        Update caze;

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        req.requestURI = 'https://cs31.salesforce.com/services/apexrest/SendFinanceData/';  
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        CSC_EBS_SendFinanceMsg.doPost();
        Test.stopTest();
    }
}