src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_FTP_End_Date__c</fullName>
        <label>FTP End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSC_FTP_Start_Date__c</fullName>
        <label>FTP Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSC_FTP_URL__c</fullName>
        <label>FTP URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>FTP_Creator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FTP Creator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>case_Ftp_Creator</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FTP_Extend_Period__c</fullName>
        <label>FTP Extend Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_RenewFtpLinkController_Test.cls
@isTest
private class CSC_RenewFtpLinkController_Test {
    static testMethod void testMethod1() {
        Test.startTest();

        Case objCase = TestUtil.getCase();
        objCase.CSC_FTP_URL__c = 'ftp://test.test';
        objCase.CSC_FTP_Start_Date__c = Date.today();
        objCase.CSC_FTP_End_Date__c = Date.today();
        objCase.FTP_Creator__c = TestUtil.getUser().Id;
        objCase.FTP_Extend_Period__c = '60';
       	insert objCase;
    	ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(objCase);
    	ApexPages.currentPage().getParameters().put('id', objCase.Id);
    	CSC_RenewFtpLinkController ftpCont = new CSC_RenewFtpLinkController(sc);
    	ftpCont.renewFtpLink();

        Test.stopTest();
    }

    static testMethod void testMethod2() {
        Test.startTest();

        Case objCase = TestUtil.getCase();
        objCase.CSC_FTP_URL__c = 'ftp://test.test';
        objCase.CSC_FTP_Start_Date__c = Date.today();
        objCase.CSC_FTP_End_Date__c = Date.today();
        objCase.FTP_Creator__c = TestUtil.getUser().Id;
        objCase.FTP_Extend_Period__c = '60';
       	insert objCase;
    	ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(objCase);
    	ApexPages.currentPage().getParameters().put('id', 'test1111');
    	CSC_RenewFtpLinkController ftpCont = new CSC_RenewFtpLinkController(sc);
    	ftpCont.renewFtpLink();

        Test.stopTest();
    }
}