src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Case_Type__c</fullName>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HW Delivery</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Advanced Support</fullName>
                </value>
                <value>
                    <fullName>Install</fullName>
                </value>
                <value>
                    <fullName>MC Non-BCS</fullName>
                </value>
                <value>
                    <fullName>MC Datacenter</fullName>
                </value>
                <value>
                    <fullName>Proactive</fullName>
                </value>
                <value>
                    <fullName>Questions</fullName>
                </value>
                <value>
                    <fullName>SW Delivery</fullName>
                </value>
                <value>
                    <fullName>CE Assist</fullName>
                </value>
                <value>
                    <fullName>Depot Repair</fullName>
                </value>
                <value>
                    <fullName>T&amp;M</fullName>
                </value>
                <value>
                    <fullName>MC CTR</fullName>
                </value>
                <value>
                    <fullName>CTR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_OTC__c</fullName>
        <label>OTC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>05R-Normal Contract</fullName>
                    <color>#0B6FCE</color>
                    <label>05R-Normal Contract</label>
                </value>
                <value>
                    <fullName>02N-Warranty Normal</fullName>
                    <color>#78C953</color>
                    <label>02N-Warranty Normal</label>
                </value>
                <value>
                    <fullName>05A-Complmt TAC</fullName>
                    <color>#E27001</color>
                    <label>05A-Complmt TAC</label>
                </value>
                <value>
                    <fullName>05K-Extended Warranty</fullName>
                    <color>#A845DC</color>
                    <label>05K-Extended Warranty</label>
                </value>
                <value>
                    <fullName>05Q-Preventative</fullName>
                    <color>#F3D904</color>
                    <label>05Q-Preventative</label>
                </value>
                <value>
                    <fullName>02G-Sevice Note</fullName>
                    <color>#A53711</color>
                    <label>02G-Sevice Note</label>
                </value>
                <value>
                    <fullName>06J-Intl Gratis</fullName>
                    <color>#66E9BD</color>
                    <label>06J-Intl Gratis</label>
                </value>
                <value>
                    <fullName>00C-Cust Claims Cont</fullName>
                    <color>#0B24BE</color>
                    <label>00C-Cust Claims Cont</label>
                </value>
                <value>
                    <fullName>00W-Cust Claims Warr</fullName>
                    <color>#419249</color>
                    <label>00W-Cust Claims Warr</label>
                </value>
                <value>
                    <fullName>00E-No Entitlement</fullName>
                </value>
                <value>
                    <fullName>01-Trade</fullName>
                    <color>#B6E32E</color>
                    <label>01-Trade</label>
                </value>
                <value>
                    <fullName>06M-Intl re-repair</fullName>
                    <color>#641CCF</color>
                    <label>06M-Intl re-repair</label>
                </value>
                <value>
                    <fullName>05F-Comp Fld Inst</fullName>
                    <color>#F96FB7</color>
                    <label>05F-Comp Fld Inst</label>
                </value>
                <value>
                    <fullName>05S-Compl Site Prep</fullName>
                    <color>#2F5D85</color>
                    <label>05S-Compl Site Prep</label>
                </value>
                <value>
                    <fullName>06F-Intl Field Instl</fullName>
                    <color>#AFCADF</color>
                    <label>06F-Intl Field Instl</label>
                </value>
                <value>
                    <fullName>05P-Contracts: Predictive Support</fullName>
                    <color>#8F6429</color>
                    <label>05P-Contracts: Predictive Support</label>
                </value>
                <value>
                    <fullName>09U-UWD Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_PN__c</fullName>
        <label>Product Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TAT_Reason__c</fullName>
        <label>TAT Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account blocked by RPL</fullName>
                </value>
                <value>
                    <fullName>Case logged outside of business hours</fullName>
                </value>
                <value>
                    <fullName>Case misrouted due to requestor</fullName>
                </value>
                <value>
                    <fullName>Case re-opened</fullName>
                </value>
                <value>
                    <fullName>Case logged</fullName>
                </value>
                <value>
                    <fullName>Data flow issue- D&amp;B to MDM/MDCP</fullName>
                </value>
                <value>
                    <fullName>Delay in feedback by Approver</fullName>
                </value>
                <value>
                    <fullName>Delay in feedback by Requestor</fullName>
                </value>
                <value>
                    <fullName>Multiple Account request in single case</fullName>
                </value>
                <value>
                    <fullName>System downtime- MDM/MDCP</fullName>
                </value>
                <value>
                    <fullName>System downtime- SFDC</fullName>
                </value>
                <value>
                    <fullName>System issue</fullName>
                </value>
                <value>
                    <fullName>PRL blocked</fullName>
                </value>
                <value>
                    <fullName>Late reply by requestor</fullName>
                </value>
                <value>
                    <fullName>Late reply by approver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account_Request_01</fullName>
        <active>true</active>
        <businessProcess>Account Request</businessProcess>
        <label>01-Account Request</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CaseStatusUpdateCompletionDateTest.cls
@istest(seealldata=true)
public class CaseStatusUpdateCompletionDateTest {
    public static testmethod void testCaseStatusUpdateCompletionDate() { 
        Entitlement e = [select id from Entitlement where name = '01-Account Request Entitlement Process'];
        case c = new case();
        c.RecordTypeId = '01228000000PMiNAAW';//Add by Lily @2017-11-23 for NGMS PQR issue 'Account_Request_01'
        c.status = 'New';
        c.TAT_Reason__c = 'Case logged';
        c.Entitlement = e;
        insert c;
        c.status = 'Closed';
        //add by deloitte start
        c.CSC_OTC__c = '01-Trade';
        c.CSC_Case_Type__c = 'DEF';
        c.CSC_SN__c = 'testSN';
        c.CSC_PN__c = 'testPN';
        //add by deloitte end
        update c;
    }
}