src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SLA_TYPE__c</fullName>
        <formula>Entitlement.SLA_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLA_TYPE</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Process_QA__c.object
<CustomObject>
    <fields>
        <fullName>QA_Code__c</fullName>
        <label>QA Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>QA_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>0A-See comments</fullName>
                </value>
                <value>
                    <fullName>0B-HP IT system down</fullName>
                </value>
                <value>
                    <fullName>AA-Entitlement Problem</fullName>
                </value>
                <value>
                    <fullName>ZZ-No Issues</fullName>
                </value>
                <value>
                    <fullName>BA-Diag.wrong/incomp</fullName>
                </value>
                <value>
                    <fullName>BH-wrong parts info</fullName>
                </value>
                <value>
                    <fullName>LA-Local issue A</fullName>
                </value>
                <value>
                    <fullName>LB-Local issue B</fullName>
                </value>
                <value>
                    <fullName>PC-Missing part info</fullName>
                </value>
                <value>
                    <fullName>PF-Damaged/DOA</fullName>
                </value>
                <value>
                    <fullName>SC-Addl prob found</fullName>
                </value>
                <value>
                    <fullName>XB-Lack skill/knowledge</fullName>
                </value>
                <value>
                    <fullName>XG-Tool/Manual missing</fullName>
                </value>
                <value>
                    <fullName>XH-Manual/Documentation not read</fullName>
                </value>
                <value>
                    <fullName>XI-CE Assist open with wrong Priority</fullName>
                </value>
                <value>
                    <fullName>XJ-CE was not onsite anymore</fullName>
                </value>
                <value>
                    <fullName>MR-Misrouted Call</fullName>
                </value>
                <value>
                    <fullName>SD-Sys Down Dependency</fullName>
                </value>
                <value>
                    <fullName>D1-IRS Assistance</fullName>
                </value>
                <value>
                    <fullName>D2-Proactive Scan</fullName>
                </value>
                <value>
                    <fullName>D3-FW&amp;SW Patch Analysis</fullName>
                </value>
                <value>
                    <fullName>D4-FW Analysis</fullName>
                </value>
                <value>
                    <fullName>D5-SW Patch Analysis</fullName>
                </value>
                <value>
                    <fullName>D6-Incident Reporting</fullName>
                </value>
                <value>
                    <fullName>Demo Center</fullName>
                </value>
                <value>
                    <fullName>Ink and Media</fullName>
                </value>
                <value>
                    <fullName>Ink Conversion</fullName>
                </value>
                <value>
                    <fullName>Trade Show</fullName>
                </value>
                <value>
                    <fullName>Machine Recertification</fullName>
                </value>
                <value>
                    <fullName>Service Delivery Absorbed</fullName>
                </value>
                <value>
                    <fullName>1B-Customer agreed to extended DBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Process QA</relationshipLabel>
        <relationshipName>Process_QA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process QA</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>ProcessQAId</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Process_QA_Is_1B__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Process QA Is 1B</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLA_Type__c</fullName>
        <label>SLA Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/UpateWorkOrderInfor.cls
/**************************************************************************************************
 * Name:UpateWorkOrderInfor
 * Object: WorkOrder
 * Purpose:
 1.Update work orders information by related SLA_Type__c.
 * Author: Wang, Maccus Bo
 * Create Date: 2016-08-12
***************************************************************************************************/
global class UpateWorkOrderInfor implements Database.Batchable<sObject> {
    public String query;

    global UpateWorkOrderInfor() {
        this.query = 'SELECT Id, WorkOrderNumber, Case.SLA_Type__c, SLA_Type__c,Process_QA_Is_1B__c,' +
                    '(SELECT QA_Code__c FROM Process_QA__r) ' +
                    ' FROM WorkOrder WHERE Status=\'Closed\'';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug(query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        
        List<WorkOrder> workOrderList = (List<WorkOrder>)scope;
        System.debug('In the batch:' + workOrderList.size());
        for (WorkOrder item : workOrderList) {
            item.SLA_Type__c = item.Case.SLA_Type__c;
            for (Process_QA__c qa : item.Process_QA__r) {
                if (qa.QA_Code__c == '1B-Customer agreed to extended DBD') {
                    item.Process_QA_Is_1B__c = true;
                    break;
                }
            }
        }

        try {
            update workOrderList;
        }
        catch (Exception ex) {
            System.debug('Error:' + ex.getMessage());
        }
        System.debug('The job run successfully this time.');
    }

    global void finish(Database.BatchableContext BC) {
        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                                 TotalJobItems, CreatedBy.Email
                          FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses              = new String[] {a.CreatedBy.Email};
        mail.setToAddresses(toAddresses);
        mail.setSubject('Case update calucation status is ' + a.Status);
        mail.setPlainTextBody
        ('The batch Apex job processed ' + a.TotalJobItems +
        ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
    }
}