src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_Case_Status__c</fullName>
        <label>HPE Case Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>RR Closed</fullName>
                </value>
                <value>
                    <fullName>Accept Problem</fullName>
                </value>
                <value>
                    <fullName>Open Requester</fullName>
                </value>
                <value>
                    <fullName>Problem Resolution</fullName>
                </value>
                <value>
                    <fullName>Partner Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HPE_SubK_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>HPE SubK ID</description>
        <label>HPE SubK ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/GSEM_Post_Url__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Address__c</fullName>
        <description>relative address</description>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GSEM Post Url</label>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_GSEM_SubKRejectCase.cls
/**********************************************************************
 * 
 * Name: CSC_GSEM_SubKRejectCase
 * Object: string h3cId
 * Purpose: 
 * 	 ->Send PPI ("Partner Reject") to HPE ->HPE Close Case.(H3C cancel)
 * Return Msg:
 *  <Bool,msg>
 * Author: Chen, Xiaoqian
 * Create Date: 2017-01-03
*************************************************************************/
public with sharing class CSC_GSEM_SubKRejectCase {
	
    /**
	 * 封装post数据
	 */
    public class AppOut{
    	public String H3CID{set;get;}
        public String HPEID{set;get;}
        public String RejectReason{set;get;}
    	// public CSC_GSEM_SubKAddNotes.Note ppi;
    }

    public class AppInput extends CSC_GSEM_Response{
    	public AppInput(Boolean b, String msg){
    		super(b,msg);
    	}
    }

    public AppInput rejectCase(String h3cId){
    	if(String.isEmpty(h3cId)){
    		return new AppInput(false,'Empty H3CID!');
    	}
    	// if(String.isEmpty(noteType)){
    	// 	return new AppInput(false,'Empty noteType!');
    	// }
    	// if(String.isEmpty(actionType)){
    	// 	return new AppInput(false,'Empty actionType!');
    	// }
    	// if(String.isEmpty(notes)){
    	// 	return new AppInput(false,'Empty notes!');
    	// }
    	//1.校验Case是否符合要求
        Case cas = CSC_GSEM_SubK_Common_Function.getSubKCaseById(h3cId);
        if(cas == null){
            return new AppInput(false,'Case not found!');
        }
        
        // if(cas.Status == 'Closed'||cas.CSC_Case_Status__c == 'Closed'){
        //     return new AppInput(false,'Case Status is "Closed"!');
        // }

    	//2.设置提交的JSON
    	AppOut output = new AppOut();
    	output.H3CID = h3cId;
        output.HPEID = cas.HPE_SubK_ID__c;
        output.RejectReason = cas.CSC_Comments__c;
        
    	// CSC_GSEM_SubKAddNotes.Note ppi = new CSC_GSEM_SubKAddNotes.Note();
    	// ppi.NOTE_TYPE = noteType;
    	// ppi.ACTION_TYPE = actionType;
    	// ppi.NOTES = notes;
    	// ppi.CREATED = system.now().addHours(8).format('yyyy-MM-dd HH:mm:ss');

    	// output.ppi = ppi;

	    String postString = JSON.serialize(output);
	    System.debug('Posted String is'+postString);
	    
	    //3.Post 数据到GSEM
	    String resp = '';
	    try{
	    	GSEM_Post_Url__c post = GSEM_Post_Url__c.getValues('SubKRejectCase');
		    resp = CSC_GSEM_Connection.Post(postString, post.Address__c);
		    System.debug('Hi,'+resp);
		} catch (CSC_GSEM_Connection.GSEMConnectException ex){
            //处理错误消息，需要重新发送
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'RejectSubKCase', ex.getMessage(), true);
        } catch (CalloutException ex){
            //处理错误消息，需要重新发送
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'RejectSubKCase', ex.getMessage(), true);
        } catch(Exception ex){
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'RejectSubKCase', ex.getMessage(), true);
			return new AppInput(false,ex.getMessage());
		}
	    
	    //4.获取返回值
	    AppInput input = null;
	    try{
			input = (AppInput)JSON.deserialize(resp, AppInput.class);
            if(!input.Rst){
                CSC_GSEM_Connection.LogFailerCall(h3cId, 'RejectSubKCase', input.RstMsg, false);
            }
		}catch(Exception ex){
            CSC_GSEM_Connection.LogFailerCall(h3cId, 'RejectSubKCase', ex.getMessage(), false);
			return new AppInput(false,ex.getMessage());
		}

    	return input;
    }
}