src/objects/Certificate__c.object
<CustomObject>
    <description>上岗证</description>
    <fields>
        <fullName>Delete_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>删除标志，false表示正常，true 表示删除</description>
        <label>Delete Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <description>域账号</description>
        <label>Domain</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ProductLine__c</fullName>
        <description>产品线</description>
        <label>Product Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>上岗证状态</description>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserCode__c</fullName>
        <description>工号</description>
        <label>UserCode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <description>员工姓名</description>
        <label>UserName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Certificate</label>
    <nameField>
        <label>Certificate Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CertificateProductSerise__c.object
<CustomObject>
    <description>必须上岗证的产品系列和产品线</description>
    <fields>
        <fullName>Delete_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>删除标志，false表示正常，true 表示删除</description>
        <label>Delete Status</label>
        <type>Checkbox</type>
    </fields>
    <label>CertificateProductSerise</label>
    <nameField>
        <label>CertificateProductSerise Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/ProductLine__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ProductLine Maping</label>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_Ws_Certificate_Test.cls
@isTest
private class CSC_Ws_Certificate_Test {
    static testMethod void testMethod1() {
    	System.RestContext.request = new RestRequest();       
        RestContext.request.requestBody = Blob.valueof('{"seriesList":[{"name":"WX5500H系列","type":"0"},{"name":"WX3800H系列","type":"1"}],"certList":[{"domainAccount":"y10225","certificates":[{"name":"WX5500H系列上岗证","number1":"H3CPE2018051100013","id":"13","productSeries":"WX5500H系列","type":"C","status":"已完成"},{"name":"WX3800H系列上岗证","number1":"H3CPE2018060600290","id":"290","productSeries":"WX3800H系列","type":"B","status":"学习中"}],"name":"杨银波","email":"yang@h3c.com"},{"domainAccount":"xkf7031","certificates":[{"name":"WX5500H系列上岗证","number1":"H3CPE2018051100013","id":"13","productSeries":"WX5500H系列","type":"C","status":"已完成"},{"name":"WX3800H系列上岗证","number1":"H3CPE2018060600290","id":"290","productSeries":"WX3800H系列","type":"B","status":"学习中"}],"name":"xt","email":"kf.xutao@h3c.com"}]}');
        CSC_Ws_Certificate.creat();
        
    }

    static testMethod void testMethod2() {
    	System.RestContext.request = new RestRequest();       
        RestContext.request.requestBody = Blob.valueof('{1}');
        CSC_Ws_Certificate.creat();
        
    }

    static testMethod void testMethod3() {
    	System.RestContext.request = new RestRequest();       
        RestContext.request.requestBody = Blob.valueof('{"seriesList":[{"name":"WX5500H系列","type":"0"},{"name":"WX3800H系列","type":"1"}],"certList":[]}');
        CSC_Ws_Certificate.creat();
        
    }

    static testMethod void testMethod4() {
        test.startTest();
        Certificate__c cc = new Certificate__c();
                cc.name='WX3800H系列上岗证';
                cc.domain__c='xkf7031';
                cc.email__c='kf.xutao@h3c.com';
                cc.type__c='B';
                cc.status__c='学习中';
                cc.productLine__c='WX3800H系列';
                cc.userCode__c = '7031';
                cc.userName__c = 'xt';
                cc.delete_Status__c = true;
        insert cc;
        CertificateProductSerise__c ins = new CertificateProductSerise__c();
                ins.name = 'WX5500H系列';
                ins.Delete_Status__c = true;
        insert ins;
        System.RestContext.request = new RestRequest();       
        RestContext.request.requestBody = Blob.valueof('{"seriesList":[{"flag":"0","name":"WX5500H系列"},{"flag":"0","name":"WX5500H系列"}],"certList":[{"domainAccount":"xkf7031","code":"7031","certificates":[{"flag":"0","name":"WX5500H系列上岗证","productSeries":"WX5500H系列","type":"C","status":"已完成"},{"flag":"1","name":"WX3800H系列上岗证","productSeries":"WX3800H系列","type":"B","status":"学习中"}],"name":"xt","email":"kf.xutao@h3c.com"}]}');
        CSC_Ws_Certificate.creat();
        test.stopTest();
        
    }
}