src/objects/Job_Error_log__c.object
<CustomObject>
    <description>Error log</description>
    <fields>
        <fullName>Job_Performance_Log__c</fullName>
        <label>Job Performance Log</label>
        <referenceTo>Job_Performance_Log__c</referenceTo>
        <relationshipLabel>Job Error log</relationshipLabel>
        <relationshipName>Job_Error_log_Per_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Error log</label>
    <nameField>
        <label>Error log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Performance_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Start_Time__c</fullName>
        <label>Job Start Time</label>
        <type>Date</type>
    </fields>
    <label>Job Performance Log</label>
    <nameField>
        <label>Job Performance Log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CaseFunction_Test.cls
@istest(seealldata=true)
public class CaseFunction_Test {

    public static testMethod void testMethod1() {

        Test.startTest();
        CaseFunction cf = new CaseFunction();
        cf.QueryValue();
        Test.stopTest();
        
    }

    public static testMethod void testMethod2() {

        Test.startTest();
        CaseFunction cf = new CaseFunction();
        cf.ProcessQAQueryValue();
        Test.stopTest();
        
    }

    public static testMethod void testMethod3() {

        Test.startTest();
        CaseFunction cf = new CaseFunction();
        cf.OrderUpdateQueryValue();
        Test.stopTest();
        
    }

    public static testMethod void testMethod4() {

        Test.startTest();
        CaseFunction cf = new CaseFunction();
        cf.PartsOrderQueryValue();
        Test.stopTest();
        
    }

    public static testMethod void testMethod5() {

        Test.startTest();

        Job_Performance_Log__c Jp;
        List<Job_Error_log__c> Jellist;
        //Insert log information.
        List<Job_Performance_Log__c> JpList = [select id,Job_Start_Time__c,Class_Name__c
                                               from Job_Performance_Log__c
                                               where Job_Start_Time__c = Today and Class_Name__c =: 'Case'];
        if(JpList.size() == 0){
            Job_Performance_Log__c J = Factory.LogCreate('CSC_CaseUpdate1V1B_Batch ' + String.valueOf(System.today()), 0, 
                                                         'Case', 'CSC_CaseUpdate1V1B_Batch.', 
                                                         '');
            Jp                       = j;
        }
        else{
            Jp                       = JpList.get(0);
        }

        Jellist = new list<Job_Error_log__c>();
        CaseFunction Cf                   = new CaseFunction();
        list<Case> Clist                  = database.query(Cf.QueryValue());
        Clist                             = Cf.ReportValue(Clist, Jellist, Jp.ID);

        Test.stopTest();
        
    }
}