src/objects/Job_Error_log__c.object
<CustomObject>
    <description>Error log</description>
    <fields>
        <fullName>Job_Performance_Log__c</fullName>
        <label>Job Performance Log</label>
        <referenceTo>Job_Performance_Log__c</referenceTo>
        <relationshipLabel>Job Error log</relationshipLabel>
        <relationshipName>Job_Error_log_Per_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Error log</label>
    <nameField>
        <label>Error log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Performance_Log__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Number__c</fullName>
        <label>Batch Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Descriptation__c</fullName>
        <label>Job Descriptation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Start_Time__c</fullName>
        <label>Job Start Time</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Result_Descriptation__c</fullName>
        <label>Result Descriptation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Success_Number__c</fullName>
        <label>Success Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job Performance Log</label>
    <nameField>
        <label>Job Performance Log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CaseUpdateBatchableTest.cls
@isTest(SeeAllData = True)
private class CaseUpdateBatchableTest {
    /*
    static testMethod void BatchTest1() {
        Test.startTest();
        CaseFunction C = new CaseFunction();
        String q       = C.QueryValue() + ' where createdby.isactive = True order by id asc limit 200';
        Database.executeBatch(new CaseUpdateBatchable(q), 200);
        Test.stopTest();
    }
    static testMethod void BatchTest2() {
        Test.startTest();
        CaseFunction C = new CaseFunction();
        String q       = C.QueryValue() + ' where createdby.isactive = True order by id desc limit 200';
        Database.executeBatch(new CaseUpdateBatchable(q), 200);
        Test.stopTest();
    }
    static testMethod void BatchTest3() {
        Test.startTest();
        CaseFunction C = new CaseFunction();
        String q       = C.QueryValue() + ' where createdby.isactive = True order by Ownerid asc limit 200';
        Database.executeBatch(new CaseUpdateBatchable(q), 200);
        Test.stopTest();
    }
    static testMethod void BatchTest4() {
        Test.startTest();
        CaseFunction C = new CaseFunction();
        String q       = C.QueryValue() + ' where createdby.isactive = True order by Ownerid desc limit 200';
        Database.executeBatch(new CaseUpdateBatchable(q), 200);
        Test.stopTest();
    }
    static testMethod void BatchTest5() {
        Test.startTest();
        CaseFunction C = new CaseFunction();
        String q       = C.QueryValue() + ' where createdby.isactive = True limit 200';
        Database.executeBatch(new CaseUpdateBatchable(q), 200);
        Test.stopTest();
    }
    static testMethod void BatchTest6() {
        try
        {
        CaseUpdate.CaseUpdate();
        Test.startTest();
        CaseFunction C = new CaseFunction();
        String q       = C.ProcessQAQueryValue() + ' where createdby.isactive = True limit 200';
        Database.executeBatch(new ProcessQABatchable(q), 200);
        Test.stopTest();
        }
        catch(Exception ex)
        {
        
        }
    }
    static testMethod void BatchTest7() {
        Test.startTest();
        CaseFunction C = new CaseFunction();
        String q       = C.OrderUpdateQueryValue() + ' where createdby.isactive = True limit 200';
        Database.executeBatch(new OrderUpdateBatchable(q), 200);
        Test.stopTest();
    }    
    static testMethod void BatchTest8() {
        Test.startTest();
        CaseFunction C = new CaseFunction();
        String q       = C.PartsOrderQueryValue() + ' where createdby.isactive = True limit 200';
        Database.executeBatch(new PartsOrderBatchable(q), 200);
        Test.stopTest();
    }
    static testMethod void LogTest8() {
        Test.startTest();
        Job_Performance_Log__c J = new Job_Performance_Log__c();
        J.Name                   = 'Case report value update ' + String.valueOf(System.today());
        J.Batch_Number__c        = 0;
        J.Class_Name__c          = 'Case';
        J.Job_Descriptation__c   = 'Update case information for case related report.';
        J.Job_Start_Time__c      = System.today();
        J.Result_Descriptation__c= '';
        J.Success_Number__c      = 0;
        insert J;

        List<Job_Error_log__c> Jelist     = new List<Job_Error_log__c>();        
        Factory.ErrorLogCreate(Jelist, J.Id, 'String Name', 'String JobName', 
                                      'String ObjName', 'String Record_ID', 
                                      'String Error_Message', 'String Error_Line_Number', 
                                      'String Error_Cause', 'String Error_Type');
        Test.stopTest();
    }
    */
}