src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>UL @ibreakingpoint 20151027</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timeframe_to_Buy__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Timeframe to Buy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;1 week</fullName>
                </value>
                <value>
                    <fullName>&lt;1 month</fullName>
                </value>
                <value>
                    <fullName>1-3 month</fullName>
                </value>
                <value>
                    <fullName>4-6 month</fullName>
                </value>
                <value>
                    <fullName>7-9month</fullName>
                </value>
                <value>
                    <fullName>10-12month</fullName>
                </value>
                <value>
                    <fullName>&gt;12month</fullName>
                </value>
                <value>
                    <fullName>Unclear</fullName>
                </value>
                <value>
                    <fullName>No Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Product_Interests__c.object
<CustomObject>
    <description>To store the list of product in which lead is interested.
UL@Breakingpoint20151103</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>UL@ibreakingpoint 20151118</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Product Interest</relationshipLabel>
        <relationshipName>Product_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Interest</relationshipLabel>
        <relationshipName>Product_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>感兴趣产品</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Product Interests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/LeadChangeOwnerTest.cls
@istest(seealldata=true)
public class LeadChangeOwnerTest {
    /*public static testmethod void testLeadChangeOwner() {
        String strur = 'Sales%';
        Account acc1 = [select id from account limit 1];
        Product2 pro1 = [select id from product2 limit 1];
        User ur1 = [select id, name, profile.name from user where profile.name = 'System Administrator' and isactive = true limit 1];
        User ur2 = [select id, name, profile.name from user where profile.name like :strur and isactive = true limit 1];
        Group grp = [select id, name from Group where type='Queue' limit 1];
        system.debug('--urid--' + ur2.id);
        Lead ld1 = new Lead(LastName = '11',ownerid = ur1.id , Timeframe_to_Buy__c = '<1 month' , Budget__c = 'Yes' , Account__c = acc1.id,
        Company = '22' , phone = '1');
        Lead ld2 = new Lead(LastName = '11',ownerid = ur1.id , Account__c = acc1.id,Timeframe_to_Buy__c = '<1 month',Budget__c = '',
        Company = '22' , phone = '1');
        Lead ld3 = new Lead(LastName = '11',ownerid = ur1.id , Account__c = acc1.id,Budget__c = '22',
        Company = '22' , phone = '1');
        Lead ld4 = new Lead(LastName = '11',ownerid = ur1.id ,Budget__c = '22',Timeframe_to_Buy__c = '<1 month',
        Company = '22' , phone = '1');
        Lead ld5 = new Lead(LastName = '11',ownerid = ur1.id ,Budget__c = '22',Timeframe_to_Buy__c = '<1 month', Account__c = acc1.id,
        Company = '22' , phone = '1');
        Lead ld6 = new Lead(LastName = '11',ownerid = ur1.id ,Budget__c = '22',Timeframe_to_Buy__c = '<1 month', Account__c = acc1.id,
        Company = '22' , phone = '1');
        Lead ld7 = new Lead(LastName = '11',ownerid = ur1.id ,Budget__c = '22',Timeframe_to_Buy__c = '<1 month', Account__c = acc1.id,
        Company = '22' , phone = '1');
        List<Lead> ldls = new List<Lead>();
        ldls.add(ld1);
        ldls.add(ld2);
        ldls.add(ld3);
        ldls.add(ld4);
        ldls.add(ld5);
        ldls.add(ld6);
        ldls.add(ld7);
        insert ldls;
        Product_Interests__c pi1 = new Product_Interests__c(Lead__c = ld1.id , Product__c = pro1.id , Quantity__c = 2 , Unit_Price__c = 1);
        insert pi1;
        test.starttest();
        PageReference ldmaassign = Page.LeadManualAssignOwner;
        Test.setCurrentPage(ldmaassign);
        ApexPages.currentPage().getParameters().put('ldid' , ld1.id);
        LeadChangeOwner ldcgown1 = new LeadChangeOwner(new ApexPages.StandardController(ld1));
        ldcgown1.owneridjs = ur2.name;
        ldcgown1.saveNewOwner();
        //
        ApexPages.currentPage().getParameters().put('ldid' , ld2.id);
        LeadChangeOwner ldcgown2 = new LeadChangeOwner(new ApexPages.StandardController(ld2));
        ldcgown2.owneridjs = ur2.name;
        ldcgown2.saveNewOwner();
        ldcgown2.cancel();
        //
        ApexPages.currentPage().getParameters().put('ldid' , ld3.id);
        LeadChangeOwner ldcgown3 = new LeadChangeOwner(new ApexPages.StandardController(ld3));
        ldcgown3.owneridjs = ur2.name;
        ldcgown3.saveNewOwner();
        //
        ApexPages.currentPage().getParameters().put('ldid' , ld4.id);
        LeadChangeOwner ldcgown4 = new LeadChangeOwner(new ApexPages.StandardController(ld3));
        ldcgown4.owneridjs = ur2.name;
        ldcgown4.saveNewOwner();
        //
        ApexPages.currentPage().getParameters().put('ldid' , ld5.id);
        LeadChangeOwner ldcgown5 = new LeadChangeOwner(new ApexPages.StandardController(ld5));
        ldcgown5.owneridjs = ur2.name;
        ldcgown5.saveNewOwner();
        //
        ApexPages.currentPage().getParameters().put('ldid' , ld6.id);
        LeadChangeOwner ldcgown6 = new LeadChangeOwner(new ApexPages.StandardController(ld6));
        ldcgown6.owneridjs = ur1.name;
        ldcgown6.saveNewOwner();
        //
        ApexPages.currentPage().getParameters().put('ldid' , ld7.id);
        LeadChangeOwner ldcgown7 = new LeadChangeOwner(new ApexPages.StandardController(ld7));
        ldcgown7.owneridjs = grp.name;
        ldcgown7.saveNewOwner();
        test.stoptest();
    }*/
}