src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Closed_Reason__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Defined Need or Project</fullName>
                </value>
                <value>
                    <fullName>Insufficient Budget</fullName>
                </value>
                <value>
                    <fullName>Missing/Incorrect info</fullName>
                </value>
                <value>
                    <fullName>Contact is not a decision maker</fullName>
                </value>
                <value>
                    <fullName>Inadequate Timeframe</fullName>
                </value>
                <value>
                    <fullName>Duplicate Lead/Oppty</fullName>
                </value>
                <value>
                    <fullName>Unable to Contact</fullName>
                </value>
                <value>
                    <fullName>Created Contact</fullName>
                </value>
                <value>
                    <fullName>Admin Use Only : Lead Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <description>UL @ibreakingpoint 20151112 for Report, 18 changed</description>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
                <value>
                    <fullName>Reassign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/ReasonForLeadClosure.cls
public class ReasonForLeadClosure {
    
    public String leadId;
    public Lead lead;
    public Boolean closePopUp {get; set;}
        
    public Boolean vBoolSave      {get; set;}
    
    public ReasonForLeadClosure(ApexPages.StandardController controller) {
        leadId = ApexPages.currentPage().getParameters().get('id');
        this.lead = (Lead)controller.getRecord();
        // Change Status to "Closed"
        lead.Lead_Status__c = 'Closed';
        //lead.Lead_State__c = 'Accepted';
        vBoolSave      = false;
    }
    
    public void changed()
    {
        if (lead.Closed_Reason__c == '' || lead.Closed_Reason__c == null) 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a reason'));
            vBoolSave= false;
        }
        else
        {
            vBoolSave= true;
        }   
    }

  
    public void updateLeadController() 
    {
        if (lead.Closed_Reason__c == '' || lead.Closed_Reason__c == null) 
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a reason'));
            closePopUp = false;
        }
        else
        {
            closePopUp = true;
            update lead;
        }
    
    }
}