src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Closed_Reason__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Defined Need or Project</fullName>
                </value>
                <value>
                    <fullName>Insufficient Budget</fullName>
                </value>
                <value>
                    <fullName>Missing/Incorrect info</fullName>
                </value>
                <value>
                    <fullName>Contact is not a decision maker</fullName>
                </value>
                <value>
                    <fullName>Inadequate Timeframe</fullName>
                </value>
                <value>
                    <fullName>Duplicate Lead/Oppty</fullName>
                </value>
                <value>
                    <fullName>Unable to Contact</fullName>
                </value>
                <value>
                    <fullName>Created Contact</fullName>
                </value>
                <value>
                    <fullName>Admin Use Only : Lead Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <description>UL @ibreakingpoint 20151112 for Report, 18 changed</description>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
                <value>
                    <fullName>Reassign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/ReasonForLeadClosureTest.cls
@isTest
Private class ReasonForLeadClosureTest {

public static List<lead> LdList;
public static Lead newLead,newLead1;

    public Static void setUpData(){
               
        //Create Test Lead
        newLead = new Lead();
        newLead.LastName = 'Lee';
        newLead.FirstName = 'James';
        newLead.Lead_Status__c = 'Open';
        newLead.Phone = '18101010101';
        newLead.Company = 'BP';
        insert newLead;
        
        newLead1 = new Lead();
        newLead1.LastName = 'Lee';
        newLead1.FirstName = 'James';
        newLead1.Lead_Status__c = 'Open';
        newLead1.Phone = '18101010101';
        newLead1.Company = 'BP';
        newLead1.Lead_Status__c = 'closed';
        newLead1.Closed_Reason__c ='Unable to Contact';
        insert newLead1;
          
    } 
 
    public static testMethod void testReasonForLeadClosure() {
        setUpData();
        ApexPages.StandardController sc = new ApexPages.StandardController(newLead);
        ReasonForLeadClosure rlc = new ReasonForLeadClosure(sc);        
        rlc.changed();
        rlc.updateLeadController();
        
        ApexPages.StandardController sc1 = new ApexPages.StandardController(newLead1);
        ReasonForLeadClosure rlc1 = new ReasonForLeadClosure(sc1);
        
        rlc1.changed();
        rlc1.updateLeadController();
        
    }
}