src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>UL @ibreakingpoint 20151027</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timeframe_to_Buy__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Timeframe to Buy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;1 week</fullName>
                </value>
                <value>
                    <fullName>&lt;1 month</fullName>
                </value>
                <value>
                    <fullName>1-3 month</fullName>
                </value>
                <value>
                    <fullName>4-6 month</fullName>
                </value>
                <value>
                    <fullName>7-9month</fullName>
                </value>
                <value>
                    <fullName>10-12month</fullName>
                </value>
                <value>
                    <fullName>&gt;12month</fullName>
                </value>
                <value>
                    <fullName>Unclear</fullName>
                </value>
                <value>
                    <fullName>No Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Product_Interests__c.object
<CustomObject>
    <description>To store the list of product in which lead is interested.
UL@Breakingpoint20151103</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>UL@ibreakingpoint 20151118</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Product Interest</relationshipLabel>
        <relationshipName>Product_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>感兴趣产品</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Product Interests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/LeadChangeOwner.cls
public class LeadChangeOwner {
    Id ldid = apexpages.currentpage().getparameters().get('ldid');
    public Map<Id, User> urnameidmap {get;set;}
    public String owneridjs {get;set;}
    public Map<Id, String> queuenameidmap {get;set;}
    public Lead ldinfo {get{return [select id,name,owner.profile.name,ownerid,Timeframe_to_Buy__c,Budget__c,Account__c from lead where 
    id = :ldid];}set;}
    
    public Apexpages.StandardController stadrdcon {get;set;}
    public Lead ldtest2 {get;set;}
    
    public LeadChangeOwner(Apexpages.StandardController stadcon) {
        stadrdcon = stadcon; 
        ldtest2 = new Lead();      
    } 
    public PageReference saveNewOwner() {
    
        Lead lstest = (Lead)stadrdcon.getrecord();
        system.debug('-22-' + ldtest2.ownerid);
        
        List<Product_Interests__c> prointrstls = [select id, Lead__c from Product_Interests__c where Lead__c = :ldid];
        urnameidmap = new Map<Id, User>();
        queuenameidmap = new Map<Id, String>();
        for(User ur : [select id, name,profile.name from user where isactive = true]) {
            urnameidmap.put(ur.id, ur);    
        }
        for(Group grp : [select id, name from Group where type='Queue']) {
            queuenameidmap.put(grp.id, grp.name);    
        }
        if(urnameidmap.keyset().contains(ldtest2.ownerid) && urnameidmap.get(ldtest2.ownerid).profile.name.contains('Sales')) {

        system.debug('--info--' + ldinfo.Budget__c);
        if(ldinfo.Budget__c == '' || ldinfo.Budget__c == null) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,system.label.Ld_errormessage);
            ApexPages.addMessage(msg);
            return null;
        }
        if (ldinfo.Timeframe_to_Buy__c == '' || ldinfo.Timeframe_to_Buy__c == null) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,system.label.Ld_errormessage);
            ApexPages.addMessage(msg);
            return null;    
        }
        if (ldinfo.Account__c == null) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,system.label.Ld_errormessage);
            ApexPages.addMessage(msg);
            return null;    
        }
        if(prointrstls.size() > 0) {
            Lead ldnew = ldinfo;
            if(urnameidmap.keyset().contains(ldtest2.ownerid)) {
                ldnew.ownerid = ldtest2.ownerid;    
            }
            else if(queuenameidmap.keyset().contains(ldtest2.ownerid)) {
                ldnew.ownerid = ldtest2.ownerid;        
            }
            update ldnew;
            PageReference pr = new PageReference('/' + ldid);   
            return pr; 
        }
        else {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,system.label.Ld_errormessage);
            ApexPages.addMessage(msg);
            return null;    
        }
        }
        else {
            Lead ldnew = ldinfo;
            if(urnameidmap.keyset().contains(ldtest2.ownerid)) {
                ldnew.ownerid = ldtest2.ownerid;    
            }
            else if(queuenameidmap.keyset().contains(ldtest2.ownerid)) {
                ldnew.ownerid = ldtest2.ownerid;        
            }
            update ldnew;
            PageReference pr = new PageReference('/' + ldid);   
            return pr; 
        }    
    }  
    public PageReference cancel() {
         PageReference pr1 = new PageReference('/' + ldid);   
         return pr1;     
    }
}