src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>UL @ibreakingpoint 20151027</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timeframe_to_Buy__c</fullName>
        <description>UL @ibreakingpoint 20151028</description>
        <label>Timeframe to Buy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;1 week</fullName>
                </value>
                <value>
                    <fullName>&lt;1 month</fullName>
                </value>
                <value>
                    <fullName>1-3 month</fullName>
                </value>
                <value>
                    <fullName>4-6 month</fullName>
                </value>
                <value>
                    <fullName>7-9month</fullName>
                </value>
                <value>
                    <fullName>10-12month</fullName>
                </value>
                <value>
                    <fullName>&gt;12month</fullName>
                </value>
                <value>
                    <fullName>Unclear</fullName>
                </value>
                <value>
                    <fullName>No Plan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Product_Interests__c.object
<CustomObject>
    <description>To store the list of product in which lead is interested.
UL@Breakingpoint20151103</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>UL@ibreakingpoint 20151118</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Product Interest</relationshipLabel>
        <relationshipName>Product_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Interest</relationshipLabel>
        <relationshipName>Product_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>感兴趣产品</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Product Interests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CalculateProintrstQuantityTest.cls
@istest(seealldata=true)
public class CalculateProintrstQuantityTest {
    public static testmethod void testCalculateProintrstQuantity() {
        String strur = 'Sales%';
        List<Product_Interests__c> pils = new List<Product_Interests__c>();
        Account acc1 = [select id from account limit 1];
        Product2 pro1 = [select id from product2 limit 1];
        Lead ld1 = new Lead(LastName = '11', Timeframe_to_Buy__c = '<1 month' , Budget__c = 'Yes' , Account__c = acc1.id,
        Company = '22' , phone = '1');
        insert ld1;
        Product_Interests__c pi1 = new Product_Interests__c(Lead__c = ld1.id , Product__c = pro1.id , Quantity__c = 2 , Unit_Price__c = 1);
        Product_Interests__c pi2 = new Product_Interests__c(Lead__c = ld1.id , Product__c = pro1.id , Quantity__c = 3 , Unit_Price__c = 3);
        pils.add(pi1);
        pils.add(pi2);
        insert pils;
        delete pi1;

    }
}