src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>Order_Case</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <label>Work Order Name</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>OrderToWorkOrder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/OrderUpdateBatchable.cls
/**************************************************************************************************
 * Name:OrderUpdateBatchable
 * Object: Order
 * Purpose:
 1.Update case information in order.
 * Author: Hou, Michael Peng
 * Create Date: 2016-08-02
***************************************************************************************************/
global class OrderUpdateBatchable implements Database.Batchable<sObject> {
    public String query;

    global OrderUpdateBatchable(String q) {
        this.query = q;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        List<Order__c> Olist = (List<Order__c>)scope;
        for(Order__c O : Olist){
            O.Case__c        = O.Work_Order_Name__r.CaseID;
        }
        Update Olist;
    }

    global void finish(Database.BatchableContext BC) {
        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        CaseFunction C = new CaseFunction();
        String q       = C.PartsOrderQueryValue();          
        Database.executeBatch(new PartsOrderBatchable(Q), 200);        
    }
}