src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>IsEmailDpUser__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsEmailDpUser</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <label>Work Order Name</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>OrderToWorkOrder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_HPE_SubCase_ID__c</fullName>
        <externalId>true</externalId>
        <label>HPE WorkOrder ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_GSEM_UpdateOrderNumber.cls
/**************************************************************************************************
* Name: UpdateGSEMStatus
* Object: Case
* Purpose: 
* pasts下orderNumber 的状态
* Return Msg:
*  无
* Create Date: 2016-06-11
***************************************************************************************************/
@RestResource(urlMapping='/UpdateOrderNumber/*')
global with sharing class CSC_GSEM_UpdateOrderNumber {
    //输入
    public class Appinput{
        public String h3cOrderId;
        public String orderNumber;
        public String hpeWorkOrderId;
    }

    //输出
    global class AppOut {
        //true: Success; false:Error
        global Boolean rst;
        global String rstMsg;
    }

    @HttpPost
    global static AppOut doPost() {

        //取得caseId和optId
        RestRequest req = RestContext.request;
        AppInput input = (CSC_GSEM_UpdateOrderNumber.AppInput)JSON.deserialize(req.requestBody.tostring(), CSC_GSEM_UpdateOrderNumber.AppInput.class);
        
        //返回，成功，result返回true,message返回空
        AppOut out = new AppOut();
        String retMsg = '';
        out.rst = true;
        out.rstMsg = '';

        try{

            //IsEmailDpUser__c=true
            Order__c orderInfo = [SELECT Id, IsEmailDpUser__c, Work_Order_Name__c,Order_Number__c FROM Order__c WHERE Id = :input.h3cOrderId];

            orderInfo.IsEmailDpUser__c = true;
            orderInfo.Order_Number__c = input.orderNumber;

            update orderInfo;

            //update workOrder的hpe workOrderId
            WorkOrder workorderInfo = [SELECT Id, CSC_HPE_SubCase_ID__c FROM WorkOrder WHERE Id = :orderInfo.Work_Order_Name__c];

            workorderInfo.CSC_HPE_SubCase_ID__c = input.hpeWorkOrderId;

            update workorderInfo;

        }catch(Exception ex) {
            out.rst = false;
            out.rstMsg = ex.getMessage();
        }

        return out;
    }
}