src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Parts_Request_DT__c</fullName>
        <label>Parts Request DT</label>
        <summarizedField>Parts_Order__c.Parts_Request_DT__c</summarizedField>
        <summaryForeignKey>Parts_Order__c.Order__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Parts__c.object
<CustomObject>
    <fields>
        <fullName>Escalate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalate</label>
        <type>Checkbox</type>
    </fields>
    <label>Support BOM</label>
    <nameField>
        <label>Spare Part No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parts_Order__c.object
<CustomObject>
    <fields>
        <fullName>Escalate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HPE_Order_Num__c</fullName>
        <externalId>true</externalId>
        <label>HPE Order Num</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IGSO_Parts_Number__c</fullName>
        <label>IGSO Parts Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internally_Absorbed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internally Absorbed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offered_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offered Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Offered Parts)</relationshipLabel>
        <relationshipName>Offered_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offered_S_Plant__c</fullName>
        <label>Offered S Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Parts Order</relationshipLabel>
        <relationshipName>Parts_Order</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Origin_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order</relationshipLabel>
        <relationshipName>Origin_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PGI_Date__c</fullName>
        <description>库房发货时间</description>
        <label>PGI Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>POD_DateTime__c</fullName>
        <description>工程师填写备件接收时间</description>
        <label>Part Received Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Part_Return_DT__c</fullName>
        <description>备件返回时间</description>
        <label>Parts Return Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Parts_Description__c</fullName>
        <formula>Request_Parts__r.Description__c</formula>
        <label>Request Parts Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parts_Request_DT__c</fullName>
        <label>Parts Request DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Parts_Serial_Number__c</fullName>
        <label>Parts Serial Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parts_Usage__c</fullName>
        <label>Parts Usage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Used/Consumed</fullName>
                </value>
                <value>
                    <fullName>Used Not Consumed</fullName>
                </value>
                <value>
                    <fullName>Unused</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Promised_DT__c</fullName>
        <label>Promised DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Removed_Parts_Serial_Number__c</fullName>
        <label>Removed Parts Serial Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Removed_Parts_Status__c</fullName>
        <label>Removed Parts Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Bad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Removed_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Removed Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Removed Parts)</relationshipLabel>
        <relationshipName>Removed_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Request Parts)</relationshipLabel>
        <relationshipName>Request_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_S_Plant__c</fullName>
        <label>Request S Plant</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Return_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Return Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_Plant__c</fullName>
        <label>Ship Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Back Ordered</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>POD</fullName>
                </value>
                <value>
                    <fullName>Recommand</fullName>
                    <default>true</default>
                    <label>Recommand</label>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Send Update</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking__c</fullName>
        <label>Tracking</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Use_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X_Failure_Cd__c</fullName>
        <description>72=Unused;
74=Verified Failure;
55=Used + not consumed;
PD=Used + not consumed;
MS=Miss shipment;
WP=Used + not consumed;</description>
        <inlineHelpText>72=Unused;
74=Verified Failure;
55=Used + not consumed;
PD=Used + not consumed;
MS=Miss shipment;
WP=Used + not consumed;</inlineHelpText>
        <label>X Failure Cd</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>55 - DOA/DFS</fullName>
                </value>
                <value>
                    <fullName>74 - Verified Failure</fullName>
                </value>
                <value>
                    <fullName>PD - Physically Damaged</fullName>
                </value>
                <value>
                    <fullName>WP - Wrong Part in Box</fullName>
                </value>
                <value>
                    <fullName>72 - Unused</fullName>
                </value>
                <value>
                    <fullName>MS - Miss Shipment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/EmailConciegeForAddParts.cls
global with sharing class EmailConciegeForAddParts {

    //Order ID
    public String OrderId {get;set;}

    public List<Parts_Order__c> partsList;

    public Map<String, String> partUsageMapping {get;set;}

    public EmailConciegeForAddParts() {
        partUsageMapping = new Map<String, String>();
    }

    public List<Parts_Order__c> getPartsList() {
System.debug('Order ID:' + OrderId);
        if (OrderId != null && String.isNotBlank(OrderId)) {
            partsList = [SELECT Id, Name, Parts_Usage__c, Removed_Parts_Status__c, Parts_Serial_Number__c, 
                            Removed_Parts_Serial_Number__c, Ship_Plant__c, X_Failure_Cd__c, Order__c, 
                            Request_S_Plant__c, Offered_S_Plant__c, Use_Requested__c, Origin_Parts__c, 
                            Offered_Parts__c, Request_Parts__c, Removed_Parts__c, Parts_Request_DT__c, 
                            Promised_DT__c, Parts_Description__c, Tracking__c, Escalate__c, 
                            Status__c, RMA__c, POD_DateTime__c, PGI_Date__c, Internally_Absorbed__c, 
                            Return_Override__c, IGSO_Parts_Number__c, 
                            Part_Return_DT__c, HPE_Order_Num__c, Request_Parts__r.Name
                            FROM Parts_Order__c WHERE Order__c = :OrderId AND Status__c IN ('Recommand', 'Ordered', 'Escalated')];

            for (Parts_Order__c item : partsList) {
                if (item.X_Failure_Cd__c ==  '55') {
                    partUsageMapping.put(item.Id, 'Used & Not Consumed');
                }
                else if (item.X_Failure_Cd__c ==  '74') {
                    partUsageMapping.put(item.Id, 'Used & Consumed');
                }
                else if (item.X_Failure_Cd__c ==  'PD') {
                    partUsageMapping.put(item.Id, 'Used & Not Consumed');
                }
                else if (item.X_Failure_Cd__c ==  'WP') {
                    partUsageMapping.put(item.Id, 'Used & Not Consumed');
                }
                else if (item.X_Failure_Cd__c ==  '72') {
                    partUsageMapping.put(item.Id, 'Unused');
                }
                else {
                    partUsageMapping.put(item.Id, '--None--');
                }
            }

            for (String it : partUsageMapping.keySet()) {
                System.debug('Key:' +  it);
            }
        }
        else {
            partsList = new List<Parts_Order__c>();
        }

        return partsList;
    }
}