src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <label>Work Order Name</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>OrderToWorkOrder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Parts__c.object
<CustomObject>
    <label>Support BOM</label>
    <nameField>
        <label>Spare Part No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parts_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Parts Order</relationshipLabel>
        <relationshipName>Parts_Order</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Removed_Parts_Serial_Number__c</fullName>
        <label>Removed Parts Serial Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Removed_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Removed Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Removed Parts)</relationshipLabel>
        <relationshipName>Removed_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Request Parts)</relationshipLabel>
        <relationshipName>Request_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X_Failure_Cd__c</fullName>
        <description>72=Unused;
74=Verified Failure;
55=Used + not consumed;
PD=Used + not consumed;
MS=Miss shipment;
WP=Used + not consumed;</description>
        <inlineHelpText>72=Unused;
74=Verified Failure;
55=Used + not consumed;
PD=Used + not consumed;
MS=Miss shipment;
WP=Used + not consumed;</inlineHelpText>
        <label>X Failure Cd</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>55 - DOA/DFS</fullName>
                </value>
                <value>
                    <fullName>74 - Verified Failure</fullName>
                </value>
                <value>
                    <fullName>PD - Physically Damaged</fullName>
                </value>
                <value>
                    <fullName>WP - Wrong Part in Box</fullName>
                </value>
                <value>
                    <fullName>72 - Unused</fullName>
                </value>
                <value>
                    <fullName>MS - Miss Shipment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_HPE_SubCase_ID__c</fullName>
        <externalId>true</externalId>
        <label>HPE WorkOrder ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CSC_Subcase_Delay_Code__c</fullName>
        <label>WorkOrder Delay Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-Response Met</fullName>
                </value>
                <value>
                    <fullName>1-Returned to office for resource</fullName>
                </value>
                <value>
                    <fullName>2-Parts Issue</fullName>
                </value>
                <value>
                    <fullName>3-No CE Resources Available</fullName>
                </value>
                <value>
                    <fullName>4-CSO sent to wrong CE</fullName>
                </value>
                <value>
                    <fullName>5-Travel Delay</fullName>
                </value>
                <value>
                    <fullName>6-No Trained/Qualified CE Available</fullName>
                </value>
                <value>
                    <fullName>7-Subcase recd Late from Call Center</fullName>
                </value>
                <value>
                    <fullName>8-Customer caused Delay</fullName>
                </value>
                <value>
                    <fullName>9-Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Subcase_Repair_Class_Code__c</fullName>
        <label>WorkOrder Repair Class Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DEF</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>DG</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>HM</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IR</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NR</fullName>
                </value>
                <value>
                    <fullName>NS</fullName>
                </value>
                <value>
                    <fullName>NT</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>SV</fullName>
                </value>
                <value>
                    <fullName>SW</fullName>
                </value>
                <value>
                    <fullName>UC</fullName>
                </value>
                <value>
                    <fullName>WK</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>ML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cause__c</fullName>
        <label>Cause</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Resolution_Code__c</fullName>
        <label>Workorder Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Counrier Assist</fullName>
                </value>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Sub_Code__c</fullName>
        <label>Workorder Resolution Sub-Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Resolution_Code__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer self-solved without HPE assistance</fullName>
                </value>
                <value>
                    <fullName>Firmware/BIOS/Driver updates(except 3Par)</fullName>
                </value>
                <value>
                    <fullName>HW Issue</fullName>
                </value>
                <value>
                    <fullName>Implementation/Configuration/Setup questions</fullName>
                </value>
                <value>
                    <fullName>Non-Technical/Presales/Contract Coverage</fullName>
                </value>
                <value>
                    <fullName>SW Issue</fullName>
                </value>
                <value>
                    <fullName>Duplicate case logged</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Failed RPL</fullName>
                </value>
                <value>
                    <fullName>Unable to reach customer to begin diagnosis</fullName>
                </value>
                <value>
                    <fullName>Customer unwilling/Unable to perform remote diagnosis and/or implement action plan</fullName>
                </value>
                <value>
                    <fullName>Transferred out of HP EG</fullName>
                </value>
                <value>
                    <fullName>Customer declined billable service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Type__c</fullName>
        <label>Workorder Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Remote Other</fullName>
                </value>
                <value>
                    <fullName>Remote Resolve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/EmailHpeConciegeWorkOrder.cls
global with sharing class EmailHpeConciegeWorkOrder {

    public String CaseID {get;set;}

    public EmailHpeConciegeWorkOrder() {
        
    }

/*
    public List<WorkOrder> getWW() {
    	List<WorkOrder> wwlist = new List<WorkOrder>();
    	return wwlist;
    }
*/

    public List<EmailConciegeWorkOrderWrapper> getEmailConciegeWorkOrderWrapperList() {

        List<EmailConciegeWorkOrderWrapper>  orderWrapperList = new List<EmailConciegeWorkOrderWrapper>();

        if (CaseID != null && String.isNotBlank(CaseID)) {
            Map<Id, EmailConciegeWorkOrderWrapper> workOrderMap = new Map<Id, EmailConciegeWorkOrderWrapper>();
            for (WorkOrder item : [SELECT Id, CSC_HPE_SubCase_ID__c, Resolution_Code__c, 
                            Resolution_Type__c, Resolution_Sub_Code__c, CSC_Subcase_Repair_Class_Code__c, 
                            CSC_Subcase_Delay_Code__c, Cause__c, Resolution__c,
                            Comments__c FROM WorkOrder WHERE CaseId = :CaseID]) {
                EmailConciegeWorkOrderWrapper aWrapper = new EmailConciegeWorkOrderWrapper();
                aWrapper.main = item;
                workOrderMap.put(item.Id, aWrapper);
            }

            for (Parts_Order__c item : [SELECT Id, Request_Parts__r.Name, Order__r.Work_Order_Name__c, X_Failure_Cd__c, Removed_Parts__r.Name, Removed_Parts_Serial_Number__c
                                        FROM Parts_Order__c WHERE Order__r.Work_Order_Name__c IN :workOrderMap.keySet()]) {
                if (workOrderMap.containsKey(item.Order__r.Work_Order_Name__c)) {
                    EmailConciegeWorkOrderWrapper aWrapper = workOrderMap.get(item.Order__r.Work_Order_Name__c);
                    aWrapper.partsList.add(item);
                }
            }

            for (Task item : [SELECT WhatId, Note_type__c,Action_Type__c, Description FROM Task 
	    					WHERE WhatId = :workOrderMap.keySet() AND Action_Type__c IN ('Onsite Action','Plan of Action','Troubleshooting')]) {
            	if (workOrderMap.containsKey(item.WhatId)) {
                    EmailConciegeWorkOrderWrapper aWrapper = workOrderMap.get(item.WhatId);
                    aWrapper.activityList.add(item);
                }
            }

            orderWrapperList.addAll(workOrderMap.values());
        }

        return orderWrapperList;
    }
}