src/objects/Survey_Answers__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>个案</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Case_Survey_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>If_rerender__c</fullName>
        <defaultValue>false</defaultValue>
        <label>If rerender</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Query_Type__c</fullName>
        <formula>TEXT(Survey_Questions__r.Query_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Query_Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Distribute__c</fullName>
        <label>Survey Distribute</label>
        <referenceTo>Survey_Distribute__c</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Distribute_Survey_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_Questions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Questions</label>
        <referenceTo>Survey_Questions__c</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Survey_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Answers</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Distribute__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <summaryFilterItems>
            <field>Survey_Answers__c.If_rerender__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Survey_Answers__c.Survey_Distribute__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>个案</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey Distribute</relationshipLabel>
        <relationshipName>Case_Survey_Distribute</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IfFinished__c</fullName>
        <label>IfFinished</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                    <default>true</default>
                    <label>N</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Query_Type__c</fullName>
        <label>Query Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Survey Distribute</label>
    <nameField>
        <displayFormat>SD-{000000}</displayFormat>
        <label>Survey Distribut名称</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Survey_Questions__c.object
<CustomObject>
    <fields>
        <fullName>Query_Type__c</fullName>
        <label>Query Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PQR</fullName>
                </value>
                <value>
                    <fullName>Outage PQR</fullName>
                </value>
                <value>
                    <fullName>Install PQR</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Install PQR_Phase_I</fullName>
                </value>
                <value>
                    <fullName>Outage PQR_Phase_I</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <description>For Query questions</description>
        <label>Questions</label>
        <type>TextArea</type>
    </fields>
    <label>Survey Questions</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Query Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/EmailHpeConciegePQRComponent.cls
public with sharing class EmailHpeConciegePQRComponent {
	public String CaseID {get;set;}
	public List<Survey_Answers__c> surveyAnwList {get;set;}

    public EmailHpeConciegePQRComponent() {
        
    }

    public Boolean getIsListEmpty() {
    	surveyAnwList = new List<Survey_Answers__c>();
    	surveyAnwList = getSurveyAnwswerList();

    	return surveyAnwList.size() == 0;
    }

    public List<Survey_Answers__c> getSurveyAnwswerList() {
    	List<Survey_Answers__c> ansList = new List<Survey_Answers__c>();

    	if (CaseID != null && String.isNotBlank(CaseID)) {
	    	// 根据case查到该case的survey信息
	        Map<Id,Survey_Distribute__c> surveyDistributeMap = new Map<Id,Survey_Distribute__c>([SELECT IfFinished__c, Query_Type__c, Id, Case__c FROM Survey_Distribute__c
	            WHERE IfFinished__c = 'Y' AND Case__c = :CaseID]);

	        Map<Id,Survey_Answers__c> surveyAnswersMap = new Map<Id,Survey_Answers__c>([SELECT Answer__c, Name, CreatedById, CreatedDate, CurrencyIsoCode, IsDeleted, If_rerender__c, LastModifiedById, LastModifiedDate, Id, Survey_Distribute__c, Survey_Questions__c, SystemModstamp, Case__c,Survey_Questions__r.Questions__c 
	            FROM Survey_Answers__c WHERE Survey_Distribute__c IN :surveyDistributeMap.keySet()]);

	        ansList.addAll(surveyAnswersMap.values());
		}

		return ansList;
    }
}