src/objects/Survey_Answers__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>个案</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Case_Survey_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Distribute__c</fullName>
        <label>Survey Distribute</label>
        <referenceTo>Survey_Distribute__c</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Distribute_Survey_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Answers</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Distribute__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>个案</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey Distribute</relationshipLabel>
        <relationshipName>Case_Survey_Distribute</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Distribute</label>
    <nameField>
        <displayFormat>SD-{000000}</displayFormat>
        <label>Survey Distribut名称</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_UpdateSurveyAnswerBatch.cls
global class CSC_UpdateSurveyAnswerBatch implements Database.Batchable<sObject> {
    public String query;

    global CSC_UpdateSurveyAnswerBatch() {
        if (!System.Test.isRunningTest()) {
            this.query = 'select id,Case__c,Survey_Distribute__r.Case__c from survey_answers__c where Case__c=null';
        }
        else {
            this.query = 'select id,Case__c,Survey_Distribute__r.Case__c from survey_answers__c where Case__c=null limit 20';
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        List<survey_answers__c> updateList = (List<survey_answers__c>)scope;
        for(survey_answers__c s: updateList) {
            s.case__c = s.Survey_Distribute__r.Case__c;
        }
        update updateList; 
    }

    global void finish(Database.BatchableContext BC) {
        Database.executeBatch(new CSC_CaseUpdateHplBatch(), 200);
    }
}