src/objects/Survey_Answers__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>个案</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Case_Survey_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Distribute__c</fullName>
        <label>Survey Distribute</label>
        <referenceTo>Survey_Distribute__c</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Distribute_Survey_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Answers</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Distribute__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>个案</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Survey Distribute</relationshipLabel>
        <relationshipName>Case_Survey_Distribute</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IfFinished__c</fullName>
        <label>IfFinished</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                    <default>true</default>
                    <label>N</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Survey Distribute</label>
    <nameField>
        <displayFormat>SD-{000000}</displayFormat>
        <label>Survey Distribut名称</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/EmailHpeConciegePQRComponentTest.cls
@isTest
public class EmailHpeConciegePQRComponentTest {
	
	public static Survey_Distribute__c getSurveyDistribute(String caseId){
		Survey_Distribute__c sd = new Survey_Distribute__c();
		sd.Case__c = caseId;
		sd.IfFinished__c = 'Y';
		insert sd;

		return sd;
	}

	static testmethod void testgetSurveyAnwswerList(){
		Test.startTest();
		List<Survey_Answers__c> sAList = new List<Survey_Answers__c>();
		EmailHpeConciegePQRComponent ehcp = new EmailHpeConciegePQRComponent();
		Case c = ElevationToHPEComponentTest.GetCase();
		ehcp.CaseID = c.Id;
		Survey_Distribute__c s = getSurveyDistribute(c.Id);
		ehcp.surveyAnwList = sAList;
		Boolean size = ehcp.getIsListEmpty();
		Test.stopTest();
	}
}