src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Intermediate</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workgroup__c</fullName>
        <label>Workgroup</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WG-CSC_DL_ALPHA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_Networking</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_CA_VA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_Pro1</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_HPSD_Com</fullName>
                </value>
                <value>
                    <fullName>WG-TSCO_DL_ISS_Trade</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_MA_ISSG</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_HPSD CA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_DP_ISS</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_L2_Storage</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_OPS</fullName>
                </value>
                <value>
                    <fullName>WG-H3C_HZ_RD_HW</fullName>
                </value>
                <value>
                    <fullName>WG-H3C_HZ_RD_SW</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_PCI</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_WWXD</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_Value_YIGAO</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_DIGITALCHINA</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_ASIACOM</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_Value_NJSISUO</fullName>
                </value>
                <value>
                    <fullName>WG-GSD_BJ_RASM</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_HPSD_Ent</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_MCRSS</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_Pro2</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_ESupport</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_BCS</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_BLD</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_MA_ADMIN</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_DP_VA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_L2_ISS</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_NJSISUO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_GSEM_GetUserInofoByEmail.cls
/**************************************************************************************************
* Name: CSC_GSEM_GetCasesByQueueName
* Object: Case
* Purpose: 
* 根据用户email,返回用户信息
* Author: Wang, Maccus Bo
* Create Date: 2016-06-13
***************************************************************************************************/
@RestResource(urlMapping='/GetUserInfoByEmail/*')
global with sharing class CSC_GSEM_GetUserInofoByEmail {
    //输入
	public class Appinput{

		public String email;
	}

	//输出
    global class AppOut {
        //true: Success; false:Error
        public Boolean rst;
        public String rstMsg;
        public List<String> queueName;
        public String userName;
        public String workGroup;
        public String level;
    }

    @HttpPost
    global static AppOut doPost() {
    	//取得request对象
    	RestRequest req = RestContext.request;
    	AppInput input = (CSC_GSEM_GetUserInofoByEmail.AppInput)JSON.deserialize(req.requestBody.tostring(), CSC_GSEM_GetUserInofoByEmail.AppInput.class);

    	AppOut out = new AppOut();
    	String retMsg = '';
    	out.rst = true;
        out.rstMsg = '';

    	try{

    		// 根据email查询user信息
    		User userInfo = [SELECT Id,Username,Workgroup__c,Level__c FROM User Where email = :input.email];
    		out.userName = userInfo.Username;
    		out.workGroup = userInfo.Workgroup__c;
    		out.level = userInfo.Level__c;

    		// 根据UserId查询该User下所有的queue信息
    		List<GroupMember> groupMemberList = [SELECT Group.Name FROM GroupMember Where Group.Type = 'Queue' and UserOrGroupId = :userInfo.Id];

    		List<String> queueList = new List<String>();
    		for (GroupMember item : groupMemberList){
    			queueList.add(item.Group.Name);
    		}

    		out.queueName = queueList;
    	}catch(Exception ex) {
            out.rst = false;
            out.rstMsg = ex.getMessage();

    	}
    	
    	return out;
    }
}