src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Subcase_Onsite_Fixed_Date__c</fullName>
        <label>WorkOrder Onsite Repair Fixed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Start_Date__c</fullName>
        <label>WorkOrder Onsite Repair Start Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_SPMS_WorkOrder.cls
public with sharing class CSC_SPMS_WorkOrder {

    public CSC_SPMS_WorkOrder(){
        spmsOrder = new CSC_SPMS_Order();
        owner     = new CSC_SPMS_Owner();
    }

    public List<CSC_SPMS_Order> spmsOrders;

    public String wkStatus; // workorder status
    public CSC_SPMS_Order spmsOrder;
    public String workorderNumer; // Sub case ID
    public String closeDate;
    public String problemDescription;
    // public String ownerId;
    public CSC_SPMS_Owner owner;
    //add by xutao 2018-02-02
    //Subcase_Onsite_Start_Date__c
    public String onSiteStartDate;
    //Subcase_Onsite_Fixed_Date__c
    public String onSiteFixedDate;

}