src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>HPEQueue__c</fullName>
        <description>技术升级使用的 HPE 那边的Queue List</description>
        <label>HPEQueue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>H3CElevation</fullName>
                </value>
                <value>
                    <fullName>SAPHANA</fullName>
                </value>
                <value>
                    <fullName>CLOUDSYSTEM</fullName>
                </value>
                <value>
                    <fullName>SDN_SOLUTION</fullName>
                </value>
                <value>
                    <fullName>NFV_SOLUTION</fullName>
                </value>
                <value>
                    <fullName>3PAR 3SC BreakFix</fullName>
                </value>
                <value>
                    <fullName>HPN Licensing</fullName>
                </value>
                <value>
                    <fullName>WWB_L2 BC OpenVMS</fullName>
                </value>
                <value>
                    <fullName>SIMPLIVITY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HPE_Case_Status__c</fullName>
        <description>技术升级使用的HPE Case Status</description>
        <label>HPE Case Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Level__c</fullName>
        <description>elevation flow, use it to identity this work order service Level to send to hpe</description>
        <label>Service Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Mission Critical</fullName>
                </value>
                <value>
                    <fullName>Warranty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_SendToHpe_Controller.cls
/**
     类名: CSC_SendToHpe_Controller
     功能说明: 技术升级，将创建的 WorkOrder 发送到GSEM 然后再到 HPE
     参数说明: 
     返回值: 
     作者: Hunter
     日期: 2016-11-16
    */
public class CSC_SendToHpe_Controller {
    public WorkOrder wo{get;set;}
    public Boolean SendDisabled{get;set;}
    public CSC_SendToHpe_Controller()
    {
        string id_str=ApexPages.currentPage().getParameters().get('id');
        wo=[Select Id,HPEQueue__c,HPE_Case_Status__c,Service_Level__c From WorkOrder Where Id = :id_str];   
        SendDisabled = String.isNotBlank(wo.HPE_Case_Status__c);
    }

    public void Send()
    {
        Try{
            if(String.isEmpty(wo.HPEQueue__c)){
                ApexPages.Message msg = new ApexPages.Message(ApexPages.severity.ERROR, 'you must select a HPEQueue');
                ApexPages.addMessage(msg);
                return;
            }

            string result = CSC_GSEM_ElevationCaller.CreateCase(wo.Id, wo.HPEQueue__c, wo.Service_Level__c);
            
            if(result == 'success'){
                SendDisabled = true;
                // update wo;
                ApexPages.Message msg = new ApexPages.Message(ApexPages.severity.Info, result);
                ApexPages.addMessage(msg);
            }
            else{
                ApexPages.Message msg = new ApexPages.Message(ApexPages.severity.ERROR, result);
                ApexPages.addMessage(msg);
            }
        }
        catch(Exception ex){
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.severity.ERROR, ex.getMessage());
            ApexPages.addMessage(errMsg);
        }
    }
}