src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_HPE_SubCase_ID__c</fullName>
        <externalId>true</externalId>
        <label>HPE WorkOrder ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CSC_Subcase_Repair_Class_Code__c</fullName>
        <label>WorkOrder Repair Class Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DEF</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>DG</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>HM</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IR</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NR</fullName>
                </value>
                <value>
                    <fullName>NS</fullName>
                </value>
                <value>
                    <fullName>NT</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>SV</fullName>
                </value>
                <value>
                    <fullName>SW</fullName>
                </value>
                <value>
                    <fullName>UC</fullName>
                </value>
                <value>
                    <fullName>WK</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>ML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Elevate_To_L3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Elevate To L3</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_Close_WorkOrder_Controller_Test.cls
@isTest
public class CSC_Close_WorkOrder_Controller_Test
{
    public static testMethod void CSC_Close_WorkOrder_Controller_Test1()
    {    
        //CSC_Assign_Controller_Test.GetHoliday();  
        WorkOrder wo=CSC_Assign_Controller_Test.GetWorkOrder();    
        User u_ASC=[Select Id From User Where Profile.Name = 'CSC&FST ASC' And IsActive=true limit 1];
        wo.ownerid=u_ASC.id;   
        wo.Elevate_To_L3__c=true;
        wo.CSC_HPE_SubCase_ID__c='';
        update wo;
        test.startTest();
        system.runas(u_ASC)
        {
            ApexPages.currentPage().getParameters().put('id', wo.Id);
            CSC_Close_WorkOrder_Controller c_Asc=new CSC_Close_WorkOrder_Controller();
            system.debug('ccccccccccccccccccccccccccccccccccccccccc');
        }
        ApexPages.currentPage().getParameters().put('id', wo.Id);
        CSC_Close_WorkOrder_Controller c=new CSC_Close_WorkOrder_Controller();
        CSC_Close_WorkOrder_Controller.Check_CloseWorkOrder(wo.Id);
        CSC_Close_WorkOrder_Controller.Save(wo.Id);
        CSC_Close_WorkOrder_Controller.Close_WorkOrder(wo.CaseId);
        c.Close();
        test.stopTest();
    }
    
    public static testMethod void CSC_Close_WorkOrder_Controller_Test2()
    {
        WorkOrder wo=CSC_Assign_Controller_Test.GetWorkOrder();    
        User u_DP=[Select Id From User Where Profile.Name = 'CSC&FST DP' And IsActive=true limit 1];
        wo.ownerid=u_DP.id; 
        wo.CSC_Subcase_Repair_Class_Code__c='';  
        wo.CSC_HPE_SubCase_ID__c='';
        update wo;
        test.startTest();
        system.runas(u_DP)
        {
            ApexPages.currentPage().getParameters().put('id', wo.Id);
            CSC_Close_WorkOrder_Controller c_Dp=new CSC_Close_WorkOrder_Controller();
            system.debug('ccccccccccccccccccccccccccccccccccccccccc');
        }
        test.stopTest();
    }
}