H3CIPMSJAVA-20180830/src/objects/BatchPeriod__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>batch执行取得case范围</description>
    <fields>
        <fullName>CSC_Manufactured_date__c</fullName>
        <label>CSC Manufactured date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Period</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>General_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SNR</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipLabel>个案</relationshipLabel>
        <relationshipName>CaseToGeneral_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/General_Product__c.object
<CustomObject>
    <label>General Product</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job_Error_log__c.object
<CustomObject>
    <description>Error log</description>
    <fields>
        <fullName>Job_Performance_Log__c</fullName>
        <label>Job Performance Log</label>
        <referenceTo>Job_Performance_Log__c</referenceTo>
        <relationshipLabel>Job Error log</relationshipLabel>
        <relationshipName>Job_Error_log_Per_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Error log</label>
    <nameField>
        <label>Error log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Performance_Log__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Number__c</fullName>
        <label>Batch Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Start_Time__c</fullName>
        <label>Job Start Time</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Success_Number__c</fullName>
        <label>Success Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job Performance Log</label>
    <nameField>
        <label>Job Performance Log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Parts__c.object
<CustomObject>
    <fields>
        <fullName>General_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>General Product</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipName>PartsToGeneral_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support BOM</label>
    <nameField>
        <label>Spare Part No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Product_Unit__c.object
<CustomObject>
    <fields>
        <fullName>General_Product__c</fullName>
        <label>General Product</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipName>Product_UnitToGeneral_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Manufactured BOM</label>
    <nameField>
        <label>Part number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_ManufacturedBatch.cls
global class CSC_ManufacturedBatch implements Database.Batchable<sObject> {
    public String query;
    public Job_Performance_Log__c Jp;
    public List<Job_Error_log__c> JellistError;
    public static final String CASE_STATUS = 'Closed';

    global CSC_ManufacturedBatch() {

        Integer numDays = BatchPeriod__c.getAll().get('BatchPeriod').CSC_Manufactured_date__c.intValue();
        Datetime filterDT = DateTime.now() - numDays;
        this.query = 'SELECT Id, CaseNumber, Status, General_Product__c '
                        + 'FROM Case WHERE General_Product__c != null and Status = \'' +  CASE_STATUS  + '\' AND ClosedDate > ' +  filterDT.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');

        //Insert log information.
        List<Job_Performance_Log__c> JpList = [select id,Job_Start_Time__c,Class_Name__c
                                               from Job_Performance_Log__c
                                               where Job_Start_Time__c = Today and Class_Name__c =: 'BOM'];
        if(JpList.size() == 0){
            Job_Performance_Log__c j = Factory.LogCreate('Manufactured BOM alert Messge ' + String.valueOf(System.today()), 0, 
                                                         'BOM', 'Manufactured BOM Delete Message.', '');
            Jp = j;
        } else{
            Jp = JpList.get(0);
        }
        JellistError = new list<Job_Error_log__c>();
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        
        List<Case> caseList = scope;
        Set<Id> generalId = new Set<Id>();
        Date currentDay = date.today();
        List<Job_Error_log__c> Jellist  = new List<Job_Error_log__c>();
        try{
            for (Case ca : caseList){
                generalId.add(ca.General_Product__c);
            }

            List<Product_Unit__c> generalList = [SELECT id FROM Product_Unit__c Where General_Product__c in :generalId limit 10001];

            // 大于10000条
            if (generalList.size() > 10000){

                List<Product_Unit__c> generalListTemp;

                do {
                    generalListTemp = [SELECT id FROM Product_Unit__c Where General_Product__c in :generalId limit 9999];
                    delete generalListTemp;
                }while (!generalListTemp.isEmpty());
            }else{

                // 小于10000条，直接删除
                delete generalList;    
            }

            List<Parts__c> pList = [SELECT id FROM Parts__c Where General_Product__c in :generalId limit 10001];

            if (pList.size() > 10000){

                List<Parts__c> productList;

                do {
                    productList = [SELECT id FROM Parts__c Where General_Product__c in :generalId limit 9999];
                    delete productList;
                }while (!productList.isEmpty());
                
            }else{
                delete pList;
            }

        }catch (Exception ex){
            Factory.ErrorLogCreate(Jellist, Jp.ID, 'Manufactured BOM Delete Message' + System.today(), 'Manufactured BOM Delete Message','Manufactured BOM', 
                                   ex.getStackTraceString(), String.valueOf(ex.getMessage()), String.valueOf(ex.getLineNumber()), 
                                   String.valueOf(ex.getCause()), 'Loop');
        }
        
    }

    global void finish(Database.BatchableContext BC) {
        
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                                 TotalJobItems, CreatedBy.Email
                          FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        Jp.Batch_Number__c                   = a.TotalJobItems;
        Jp.Success_Number__c                 = a.TotalJobItems - a.NumberOfErrors;
        update Jp;

        Factory.ErrorLogCreate(JellistError, Jp.ID, 'CSC_ManufacturedBatch ' + System.today(), 'CSC_ManufacturedBatch','BOM', 
                                   '', query, '', '', 'Loop');
        upsert JellistError;
    }
}