H3CIPMSJAVA-20180830/src/objects/BatchPeriod__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>batch执行取得case范围</description>
    <fields>
        <fullName>NumberDay__c</fullName>
        <label>NumberDay</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Period</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SLA_TYPE__c</fullName>
        <formula>Entitlement.SLA_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLA_TYPE</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Job_Error_log__c.object
<CustomObject>
    <description>Error log</description>
    <fields>
        <fullName>Job_Performance_Log__c</fullName>
        <label>Job Performance Log</label>
        <referenceTo>Job_Performance_Log__c</referenceTo>
        <relationshipLabel>Job Error log</relationshipLabel>
        <relationshipName>Job_Error_log_Per_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Error log</label>
    <nameField>
        <label>Error log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job_Performance_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Start_Time__c</fullName>
        <label>Job Start Time</label>
        <type>Date</type>
    </fields>
    <label>Job Performance Log</label>
    <nameField>
        <label>Job Performance Log Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_REPORT_DP_Dispatch_CE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DP Dispatch CE</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WoToDPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSC_Report_DP_Dispatch_CE_Employeeid__c</fullName>
        <label>DP Dispatch CE Employeeid</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Report_DP_Manager__c</fullName>
        <label>DP Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_Subcase_Repair_Class_Code__c</fullName>
        <label>WorkOrder Repair Class Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DEF</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CD</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>DG</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>HM</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IR</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NR</fullName>
                </value>
                <value>
                    <fullName>NS</fullName>
                </value>
                <value>
                    <fullName>NT</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>SV</fullName>
                </value>
                <value>
                    <fullName>SW</fullName>
                </value>
                <value>
                    <fullName>UC</fullName>
                </value>
                <value>
                    <fullName>WK</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>PO</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>ML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DP</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WoToDP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dispatch_User_Workgroup__c</fullName>
        <label>Dispatch User Workgroup</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispatch_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dispatch User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WorkOrderToUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resolution_Code__c</fullName>
        <label>Workorder Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Resolution_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Parts Shipped</fullName>
                </value>
                <value>
                    <fullName>SBD Counrier Assist</fullName>
                </value>
                <value>
                    <fullName>Onsite Repair</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>IRS and 3Par STaTS False Alarm</fullName>
                </value>
                <value>
                    <fullName>Customer Satisfaction</fullName>
                </value>
                <value>
                    <fullName>6XX End Call</fullName>
                </value>
                <value>
                    <fullName>Not Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Sub_Code__c</fullName>
        <label>Workorder Resolution Sub-Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Resolution_Code__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer self-solved without HPE assistance</fullName>
                </value>
                <value>
                    <fullName>Firmware/BIOS/Driver updates(except 3Par)</fullName>
                </value>
                <value>
                    <fullName>HW Issue</fullName>
                </value>
                <value>
                    <fullName>Implementation/Configuration/Setup questions</fullName>
                </value>
                <value>
                    <fullName>Non-Technical/Presales/Contract Coverage</fullName>
                </value>
                <value>
                    <fullName>SW Issue</fullName>
                </value>
                <value>
                    <fullName>Duplicate case logged</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Failed RPL</fullName>
                </value>
                <value>
                    <fullName>Unable to reach customer to begin diagnosis</fullName>
                </value>
                <value>
                    <fullName>Customer unwilling/Unable to perform remote diagnosis and/or implement action plan</fullName>
                </value>
                <value>
                    <fullName>Transferred out of HP EG</fullName>
                </value>
                <value>
                    <fullName>Customer declined billable service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Type__c</fullName>
        <label>Workorder Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSR</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Remote Other</fullName>
                </value>
                <value>
                    <fullName>Remote Resolve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA_Type__c</fullName>
        <label>SLA Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcase_Close_Date__c</fullName>
        <label>Close Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Delivery_Alternative__c</fullName>
        <label>WorkOrder Delivery Alternative</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>900</fullName>
                </value>
                <value>
                    <fullName>600</fullName>
                </value>
                <value>
                    <fullName>500</fullName>
                </value>
                <value>
                    <fullName>400</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
                <value>
                    <fullName>200</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_WorkOrderProcessQA_Batch.cls
global class CSC_WorkOrderProcessQA_Batch implements Database.Batchable<sObject> {
    public String query;
    public Job_Performance_Log__c Jp;
    public List<Job_Error_log__c> Jellist;

    global CSC_WorkOrderProcessQA_Batch() {

        //Insert log information.
        List<Job_Performance_Log__c> JpList = [select id,Job_Start_Time__c,Class_Name__c
                                               from Job_Performance_Log__c
                                               where Job_Start_Time__c = Today and Class_Name__c =: 'Case'];
        if(JpList.size() == 0){
            Job_Performance_Log__c J = Factory.LogCreate('CSC_WorkOrderProcessQA_Batch ' + String.valueOf(System.today()), 0, 
                                                         'Case', 'CSC_WorkOrderProcessQA_Batch.', 
                                                         '');
            Jp                       = j;
        }
        else{
            Jp                       = JpList.get(0);
        }

        Jellist = new list<Job_Error_log__c>();

        //从costum setting中取得天数
        Integer numDays = 0;
        if(System.test.isRunningTest()){
            numDays = 10;
        }else{
            numDays = BatchPeriod__c.getAll().get('BatchPeriod').NumberDay__c.intValue();
        }

        Datetime filterDT = DateTime.now() - numDays;
        /////////////////////////////////////////////////
        if (!Test.isRunningTest()) {
            this.query = 'SELECT Id, CSC_Subcase_Repair_Class_Code__c, Subcase_Delivery_Alternative__c, RecordType.DeveloperName, RecordTypeId, Dispatch_User_Workgroup__c,CSC_Report_DP_Dispatch_CE_Employeeid__c,CSC_Report_DP_Manager__c,Dispatch_User__c, CSC_REPORT_DP_Dispatch_CE__c, DP__c, Resolution_Type__c, Resolution_Code__c, Resolution_Sub_Code__c, case.SLA_TYPE__c, SLA_Type__c FROM WorkOrder WHERE Status=\'Closed\' and Subcase_Close_Date__c > ' +  filterDT.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        }
        else {
            this.query = 'SELECT Id, CSC_Subcase_Repair_Class_Code__c, Subcase_Delivery_Alternative__c, RecordType.DeveloperName, RecordTypeId, Dispatch_User_Workgroup__c,CSC_Report_DP_Dispatch_CE_Employeeid__c,CSC_Report_DP_Manager__c,Dispatch_User__c, CSC_REPORT_DP_Dispatch_CE__c, DP__c, Resolution_Type__c, Resolution_Code__c, Resolution_Sub_Code__c, case.SLA_TYPE__c, SLA_Type__c FROM WorkOrder WHERE Status=\'Closed\' LIMIT 200';
        }
        Factory.ErrorLogCreate(Jellist, Jp.ID, 'CSC_WorkOrderProcessQA_Batch ' + System.today(), 'CSC_WorkOrderProcessQA_Batch','Case', 
                                   '', query, '', '', 'Loop');
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) {
        List<Job_Error_log__c> Jelist = new List<Job_Error_log__c>();
        List<WorkOrder> newWorkOrderList = (List<WorkOrder>)scope;
        CSC_Case_SetData.CloseWorkOrderSetValueWithLog(newWorkOrderList, Jelist, Jp.ID);

        try {
            Database.SaveResult[] srList = Database.update(newWorkOrderList,False);
            for(Database.SaveResult sr : srList){
                if(Sr.isSuccess() == False){
                    Factory.ErrorLogCreate(Jelist, Jp.ID, 'CSC_WorkOrderProcessQA_Batch' + System.today(), 
                                           'CSC_WorkOrderProcessQA_Batch', 'Case', Sr.getId(), String.valueOf(Sr.getErrors()), 
                                           'DML',  '', 'DML');                   
                }
                else{
                    continue;
                }
            }

            Factory.ErrorLogCreate(Jelist, Jp.ID, 'CSC_WorkOrderProcessQA_Batch' + System.today(), 
                                           'CSC_WorkOrderProcessQA_Batch', 'Case', '', 'SaveResult size:' + srList.size(), 
                                           'DML',  '', 'DML');  
        }
        catch (Exception e) {
            Factory.ErrorLogCreate(Jelist, Jp.ID, 'CSC_WorkOrderProcessQA_Batch' + System.today(), 'CSC_WorkOrderProcessQA_Batch','Case', 
                                   e.getStackTraceString(), String.valueOf(e.getMessage()), String.valueOf(e.getLineNumber()), 
                                   '', 'Loop');            
        }

        insert Jelist;
    }

    global void finish(Database.BatchableContext BC) {
        
        insert Jellist;
        
        CaseFunction C = new CaseFunction();
        String q       = C.OrderUpdateQueryValue();

        if (!Test.isRunningTest()) {
            Database.executeBatch(new OrderUpdateBatchable(q), 200);
        }        
    }
}