H3CIPMSJAVA-20180830/src/objects/BatchPeriod__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>batch执行取得case范围</description>
    <fields>
        <fullName>Case_number__c</fullName>
        <label>Case number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Period</label>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/ManufacturedSchedule.cls
/**************************************************************************************************
 * Name:ManufacturedSchedule
 * Object: Case
 * Purpose:
 1.Delete Manufacture Bom when case is closed.
 * Author: Zhou, Xiong
 * Create Date: 2017-07-26
***************************************************************************************************/
global class ManufacturedSchedule implements Schedulable {
    global void execute(SchedulableContext sc) {

        Integer numDays = BatchPeriod__c.getAll().get('BatchPeriod').Case_number__c.intValue();
        Database.executeBatch(new CSC_ManufacturedBatch(), numDays);
    }
}