H3CIPMSJAVA-20180830/src/objects/Bundle_Information__c.object
<CustomObject>
    <fields>
        <fullName>General_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>General Product</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipLabel>Bundle Information</relationshipLabel>
        <relationshipName>Bundle_InformationToGeneral_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Description__c</fullName>
        <label>Parent Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Product Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Date__c</fullName>
        <label>Shipping Date</label>
        <type>Date</type>
    </fields>
    <label>Bundle Information</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSC_PN__c</fullName>
        <label>Product Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>General_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SNR</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipLabel>个案</relationshipLabel>
        <relationshipName>CaseToGeneral_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Child_Bundle_Information__c.object
<CustomObject>
    <fields>
        <fullName>Bundle_Information__c</fullName>
        <label>Bundle Information</label>
        <referenceTo>Bundle_Information__c</referenceTo>
        <relationshipLabel>Child Bundle Information</relationshipLabel>
        <relationshipName>Child_Bundle_InformationToBundle_Informa</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Child_Description__c</fullName>
        <label>Child Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Child_Product_Number__c</fullName>
        <label>Child Product Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Child Bundle Information</label>
    <nameField>
        <label>Child Serial Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/General_Product__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Marketing_Name__c</fullName>
        <label>Internal Marketing Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Localized_Product_Description__c</fullName>
        <label>Localized Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Manufactured_Date__c</fullName>
        <label>Manufactured Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plant_Code__c</fullName>
        <label>Plant Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Commercial_Name__c</fullName>
        <label>Product Commercial Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Product Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoHS_Code__c</fullName>
        <label>RoHS Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Date__c</fullName>
        <label>Shipment Date</label>
        <type>Date</type>
    </fields>
    <label>General Product</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Grandchild_Bundle_Information__c.object
<CustomObject>
    <fields>
        <fullName>Child_Bundle_Information__c</fullName>
        <label>Child Bundle Information</label>
        <referenceTo>Child_Bundle_Information__c</referenceTo>
        <relationshipLabel>Grandchild Bundle Information</relationshipLabel>
        <relationshipName>GrandchildBundleInformationToChildBundle</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grandchild_Description__c</fullName>
        <label>Grandchild Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Grandchild_Product_Number__c</fullName>
        <label>Grandchild Product Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Grandchild Bundle Information</label>
    <nameField>
        <label>Grandchild Serial Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <label>Work Order Name</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Order</relationshipLabel>
        <relationshipName>OrderToWorkOrder</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Parts__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Escalate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>General_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>General Product</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipName>PartsToGeneral_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoHS_Code__c</fullName>
        <label>RoHS Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Support BOM</label>
    <nameField>
        <label>Spare Part No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Product_Unit__c.object
<CustomObject>
    <fields>
        <fullName>General_Product__c</fullName>
        <label>General Product</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipName>Product_UnitToGeneral_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part_Description__c</fullName>
        <label>Part Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Part_Qty__c</fullName>
        <label>Part Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Manufactured BOM</label>
    <nameField>
        <label>Part number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_SN__c</fullName>
        <formula>Case.CSC_SN__c</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_View_Bom_Controller.cls
/**************************************************************************************************
* Name: CSC_View_Bom_Controller
* Object: General_Product__c
* Purpose: 
* CSC_View_Bom_Page页面后台控制类
* Author: Ben
* Create Date: 2016-05-26
***************************************************************************************************/
global with sharing class CSC_View_Bom_Controller
{
    public String type {get;set;}
    public String oId {get;set;}
    public String caseId {get;set;}
    public String strSN {get;set;}
    public String strPN {get;set;}
    public Order__c o{get;set;}
    public General_Product__c gp{get;set;}
    public List<Product_Unit__c> puList{get;set;}
    public List<Parts__c> pList{get;set;}
    public List<Bundle> bundleList{get;set;}

    public Boolean isShowGetGeneralProductBtn {get;set;}
    public Boolean isShowBundleInfoBtn {get;set;}
    public Boolean isShowReFreshBtn {get;set;}
    
    //Lily 2017-8-21 Start
    public Boolean isCaseClosed{get;set;} //当前case是否关单,用于前台disable GetBundleInfo按钮
    //Lily 2017-8-21 End
    
    public CSC_View_Bom_Controller()
    {
    
    }   
    
     //Lily 2017-8-21 Start
    public void init(){
      Case caze = [SELECT ID, Status FROM Case WHERE Id=:caseId];
      if (caze != null && caze.status == 'Closed'){isCaseClosed = true;}else{isCaseClosed = false;}
    }
    //Lily 2017-8-21 End
    
    public CSC_View_Bom_Controller(ApexPages.StandardController con)    
    {

        type = ApexPages.currentPage().getParameters().get('type');

        if (type != null && 'case'.equals(type)) {

            caseId = ApexPages.currentPage().getParameters().get('caseId');

            Case caze = [SELECT ID, CSC_SN__C, CSC_PN__C, General_Product__c FROM Case WHERE Id=:caseId];
            strSN = caze.CSC_SN__C;
            strPN = caze.CSC_PN__C;

            if (caze.General_Product__c != null) {
                oId = caze.General_Product__c;
                isShowGetGeneralProductBtn = false;
                isShowBundleInfoBtn = true;
                isShowReFreshBtn = true;
                GetInfo();
            } else {
                isShowGetGeneralProductBtn = true;
                isShowBundleInfoBtn = false;
                isShowReFreshBtn = false;
                strSN = caze.CSC_SN__C;
                strPN = caze.CSC_PN__C;
            }
            //Lily 2017-8-21 Start
            init();
            //Lily 2017-8-21 End
        
        } else {
            oId = ApexPages.currentPage().getParameters().get('id');
            isShowGetGeneralProductBtn = false;
            isShowBundleInfoBtn = false;
            isShowReFreshBtn = false;
            GetInfo();
        }
    }

    public void getBundleInfo(){
        Case caze = [SELECT ID, CSC_SN__C, CSC_PN__C, General_Product__c FROM Case WHERE Id=:caseId];

        if (caze != null && caze.General_Product__c != null) {
            gp = [Select Name,Product_Number__c From General_Product__c Where Id=:caze.General_Product__c ];

            if (gp != null) {
            if(!test.isrunningtest())
            {
                CSC_SearchEntitlementInfo.insertBundleInfo(gp.Name, gp.Product_Number__c, oId);
            }
                isShowBundleInfoBtn = false;
                isShowReFreshBtn = true;
            }
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'GeneralProduct Information Not Exist!'));
        }
    }

    public PageReference getGeneralProduct(){

        system.debug('strSN:' + strSN);
        if (strSN != null && strPN != null && caseId != null) {

            system.debug('Start getGeneralProduct****');
            CSC_SearchEntitlementInfo.insertSNRInfo(strSN,strPN,caseId);
            system.debug('Start getGeneralProduct2****');
            isShowGetGeneralProductBtn = false;
            isShowBundleInfoBtn = true;
            isShowReFreshBtn = true;
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Select GeneralProduct Information Failure !'));
        }
        
        return null;
    }

    public PageReference ReFresh(){

        Case caze = [SELECT ID, CSC_SN__C, CSC_PN__C, General_Product__c FROM Case WHERE Id=:caseId];

        if (caze != null && caze.General_Product__c != null) {
            oId = caze.General_Product__c;
            GetInfo();
        }

        return null;
    }

    public void GetInfo()
    {
        /*o = [Select Work_Order_Name__r.Case.General_Product__r.Name,Work_Order_Name__r.Case.General_Product__r.Internal_Marketing_Name__c,
                    Work_Order_Name__r.Case.General_Product__r.Localized_Product_Description__c,Work_Order_Name__r.Case.General_Product__r.Manufactured_Date__c,
                    Work_Order_Name__r.Case.General_Product__r.Plant_Code__c,Work_Order_Name__r.Case.General_Product__r.Product_Category__c,
                    Work_Order_Name__r.Case.General_Product__r.Product_Commercial_Name__c,Work_Order_Name__r.Case.General_Product__r.Product_Description__c,
                    Work_Order_Name__r.Case.General_Product__r.Product_Line__c,Work_Order_Name__r.Case.General_Product__r.Product_Number__c,
                    Work_Order_Name__r.Case.General_Product__r.RoHS_Code__c,Work_Order_Name__r.Case.General_Product__r.Shipment_Date__c,Work_Order_Name__r.Case.General_Product__c
                    From Order__c Where Id=:oId];*/
      
        gp = [Select Name,Internal_Marketing_Name__c,Localized_Product_Description__c,Manufactured_Date__c,
                    Plant_Code__c,Product_Category__c,Product_Commercial_Name__c,Product_Description__c,
                    Product_Line__c,Product_Number__c,RoHS_Code__c,Shipment_Date__c                    
                    From General_Product__c Where Id=:oId];  
        puList = [Select Name,General_Product__c,Part_Description__c,Part_Qty__c From Product_Unit__c Where General_Product__c=:oId];
        pList = [Select Name,Category__c,Description__c,Escalate__c,Part_Number__c,RoHS_Code__c,General_Product__c From Parts__c Where General_Product__c=:oId];
        List<Bundle_Information__c> biList = [Select Id,Name,Parent_Description__c,Product_Number__c,Shipping_Date__c From Bundle_Information__c Where General_Product__c=:oId];
        Map<string,Bundle_Information__c> biMap=new Map<string,Bundle_Information__c>();
        for(Bundle_Information__c bi:biList)
        {
            biMap.put(bi.Id,bi);
        }
        
        List<Child_Bundle_Information__c> cbiList = [Select Id,Bundle_Information__c,Name,Child_Description__c,Child_Product_Number__c From Child_Bundle_Information__c Where Bundle_Information__c in:biMap.keySet()];
        Set<string> cbids=new Set<string>();
        Map<string,List<Child_Bundle_Information__c>> bMap=new Map<string,List<Child_Bundle_Information__c>>();
        for(Child_Bundle_Information__c cbi:cbiList)
        {
            cbids.add(cbi.Id);
            if(bMap.containsKey(cbi.Bundle_Information__c))
            {
                bMap.get(cbi.Bundle_Information__c).add(cbi);  
                
            }
            else
            {
                List<Child_Bundle_Information__c> cbiL=new List<Child_Bundle_Information__c>();
                cbiL.add(cbi);
                bMap.put(cbi.Bundle_Information__c,cbiL);
            }
        }
        
        List<Grandchild_Bundle_Information__c> gbiList=[Select Id,Child_Bundle_Information__c,Name,Grandchild_Description__c,Grandchild_Product_Number__c From Grandchild_Bundle_Information__c Where Child_Bundle_Information__c in:cbids];
        Map<string,List<Grandchild_Bundle_Information__c>> cbMap=new Map<string,List<Grandchild_Bundle_Information__c>>();
        for(Grandchild_Bundle_Information__c gbi:gbiList)
        {
            if(cbMap.containsKey(gbi.Child_Bundle_Information__c))
            {
                cbMap.get(gbi.Child_Bundle_Information__c).add(gbi);      
            }
            else
            {
                List<Grandchild_Bundle_Information__c> gbiL=new List<Grandchild_Bundle_Information__c>();
                gbiL.add(gbi);
                cbMap.put(gbi.Child_Bundle_Information__c,gbiL);
            }
        }
        
        bundleList=new List<Bundle>();
        for(Bundle_Information__c bi:biList)
        {
            Bundle b=new Bundle();
            b.id=bi.Id;
            b.bi=bi;
            b.cbList=new List<ChildBundle>();
            
            if(bMap.get(bi.Id)!=null)
            {
                List<Child_Bundle_Information__c> cbL = bMap.get(bi.Id);
                for(Child_Bundle_Information__c cbi:cbL)
                {
                    ChildBundle cb=new ChildBundle();
                    cb.cbi=cbi;
                    cb.id=cbi.Id;
                    cb.gbiList=cbMap.get(cbi.Id);
                    b.cbList.add(cb);
                }
            }
            bundleList.add(b);
        }
        system.debug('bundleList:'+bundleList);
        for(Bundle b:bundleList)
        {
            for(ChildBundle c:b.cbList)
            {
                system.debug('c:'+c);
            }
        }
        /*for(string bId:bMap.keySet())
        {
            Bundle b=new Bundle();
            b.id=bId;
            b.bi=biMap.get(bId);
            b.cbiList=bMap.get(bId);
            bundleList.add(b);
        }*/  
    }
    
    public class Bundle
    {
        public Bundle_Information__c bi{get;set;}
        public String id{get;set;}
        //public List<Child_Bundle_Information__c> cbiList{get;set;}
        public List<ChildBundle> cbList{get;set;}
    }
    
    public class ChildBundle
    {
        public Child_Bundle_Information__c cbi{get;set;}
        public String id{get;set;}
        public List<Grandchild_Bundle_Information__c> gbiList{get;set;}
    }
}