H3CIPMSJAVA-20180830/src/objects/Bundle_Information__c.object
<CustomObject>
    <fields>
        <fullName>General_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>General Product</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipLabel>Bundle Information</relationshipLabel>
        <relationshipName>Bundle_InformationToGeneral_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Product Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Date__c</fullName>
        <label>Shipping Date</label>
        <type>Date</type>
    </fields>
    <label>Bundle Information</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>General_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SNR</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipLabel>个案</relationshipLabel>
        <relationshipName>CaseToGeneral_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Child_Bundle_Information__c.object
<CustomObject>
    <fields>
        <fullName>Bundle_Information__c</fullName>
        <label>Bundle Information</label>
        <referenceTo>Bundle_Information__c</referenceTo>
        <relationshipLabel>Child Bundle Information</relationshipLabel>
        <relationshipName>Child_Bundle_InformationToBundle_Informa</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Child_Product_Number__c</fullName>
        <label>Child Product Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Child Bundle Information</label>
    <nameField>
        <label>Child Serial Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/General_Product__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Marketing_Name__c</fullName>
        <label>Internal Marketing Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Localized_Product_Description__c</fullName>
        <label>Localized Product Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Manufactured_Date__c</fullName>
        <label>Manufactured Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plant_Code__c</fullName>
        <label>Plant Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Product Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>General Product</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Parts__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>General_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>General Product</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipName>PartsToGeneral_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Support BOM</label>
    <nameField>
        <label>Spare Part No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Product_Unit__c.object
<CustomObject>
    <fields>
        <fullName>General_Product__c</fullName>
        <label>General Product</label>
        <referenceTo>General_Product__c</referenceTo>
        <relationshipName>Product_UnitToGeneral_Product</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Part_Description__c</fullName>
        <label>Part Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Part_Qty__c</fullName>
        <label>Part Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Manufactured BOM</label>
    <nameField>
        <label>Part number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_View_Bom_WorkOrder_Controller_Test.cls
@isTest
private class CSC_View_Bom_WorkOrder_Controller_Test {
    static testMethod void testMethod1() {
        General_Product__c gp=new General_Product__c();
	    gp.Name='General_Product__c';
	    gp.Internal_Marketing_Name__c='General_Product__c';
	    gp.Localized_Product_Description__c='desc';
	    gp.Manufactured_Date__c=system.today();
	    gp.Plant_Code__c='Plant_Code__c';
	    insert gp;
	    Case cc=CSC_Assign_Controller_Test.GetCase();
	    cc.General_Product__c=gp.Id;
	    update cc;
	    test.startTest();
	    ApexPages.currentPage().getParameters().put('id', gp.Id);     
	    CSC_View_Bom_WorkOrder_Controller c=new  CSC_View_Bom_WorkOrder_Controller(null);
	    test.stopTest();
    }

    static testMethod void testMethod2() {
    	General_Product__c gp=new General_Product__c();
        gp.Name='General_Product__c';
        gp.Internal_Marketing_Name__c='General_Product__c';
        gp.Localized_Product_Description__c='desc';
        gp.Manufactured_Date__c=system.today();
        gp.Plant_Code__c='Plant_Code__c';
        insert gp;
         
        Product_Unit__c pu=new Product_Unit__c();
        pu.Name='Product_Unit__c';
        pu.General_Product__c=gp.Id;
        pu.Part_Qty__c=1;
        pu.Part_Description__c='desc';
        insert pu;
         
        Parts__c p=new Parts__c();
        p.Name='Parts__c';
        p.Category__c='Category__c';
        p.General_Product__c=gp.Id;
        p.Part_Number__c='PN';
        insert p;
         
        Bundle_Information__c bi=new Bundle_Information__c();
        bi.Name='bi';
        bi.General_Product__c=gp.Id;
        bi.Product_Number__c='PN';
        bi.Shipping_Date__c=system.today();
        insert bi;
         
        Child_Bundle_Information__c cbi=new Child_Bundle_Information__c();
        cbi.Name='cbi';
        cbi.Bundle_Information__c=bi.Id;
        cbi.Child_Product_Number__c='number';
        insert cbi;
         
        Case cc=CSC_Assign_Controller_Test.GetCase();
        cc.General_Product__c=gp.Id;
        update cc;
        test.startTest();   
        ApexPages.currentPage().getParameters().put('id', gp.Id);   
        CSC_View_Bom_WorkOrder_Controller c=new  CSC_View_Bom_WorkOrder_Controller(null);
        c.getBundleInfo();
        c.useSelectedData();
        test.stopTest();
    }
}