H3CIPMSJAVA-20180830/src/objects/City__c.object
<CustomObject>
    <fields>
        <fullName>Province_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Province</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>City</relationshipLabel>
        <relationshipName>CityToProvince</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Assign_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assign User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>WorkOrderToAssignUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City Lookup</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>City__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>City_RT</value>
            </filterItems>
            <filterItems>
                <field>$Source.Province_Lookup__c</field>
                <operation>equals</operation>
                <valueField>City__c.Province_Name__c</valueField>
            </filterItems>
            <infoMessage>请先选择省份再选择城市</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>工作订单 (City Lookup)</relationshipLabel>
        <relationshipName>WorkOrderToCity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>江苏-常熟</fullName>
                </value>
                <value>
                    <fullName>江苏-常州</fullName>
                </value>
                <value>
                    <fullName>江苏-东台</fullName>
                </value>
                <value>
                    <fullName>江苏-淮安</fullName>
                </value>
                <value>
                    <fullName>江苏-淮阴</fullName>
                </value>
                <value>
                    <fullName>江苏-江阴</fullName>
                </value>
                <value>
                    <fullName>江苏-昆山</fullName>
                </value>
                <value>
                    <fullName>江苏-连云港</fullName>
                </value>
                <value>
                    <fullName>江苏-南京</fullName>
                </value>
                <value>
                    <fullName>江苏-南通</fullName>
                </value>
                <value>
                    <fullName>江苏-邳州</fullName>
                </value>
                <value>
                    <fullName>江苏-苏州</fullName>
                </value>
                <value>
                    <fullName>江苏-太仓</fullName>
                </value>
                <value>
                    <fullName>北京市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Now__c</fullName>
        <label>Now</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Province_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Province Lookup</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>City__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Province_RT</value>
            </filterItems>
            <infoMessage>请选择省份</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>工作订单</relationshipLabel>
        <relationshipName>WorkOrderToProvince</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>shanxi</fullName>
                </value>
                <value>
                    <fullName>shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Repair_Level__c</fullName>
        <label>维修级别</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NBD</fullName>
                </value>
                <value>
                    <fullName>SBD</fullName>
                </value>
                <value>
                    <fullName>CTR</fullName>
                </value>
                <value>
                    <fullName>5*13*4</fullName>
                </value>
                <value>
                    <fullName>5*9*4</fullName>
                </value>
                <value>
                    <fullName>7*24*2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <label>Requested Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Estimated_Task_Duration__c</fullName>
        <label>WorkOrder Estimated Task Duration</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_Dispatch_Tool_ControllerTest.cls
/**************************************************************************************************
* Author: Hunter
* Create Date: 2016-11-28
*****************************************************************************************/
@isTest(seealldata=true)
private class CSC_Dispatch_Tool_ControllerTest{

	private static List<City__C> cityList = [select id,name,Province_Name__c from city__c where name='北京']; 
	private static List<City__C> spcityList = [select id,name,Province_Name__c from city__c where name='丹巴县']; 

	public static testMethod void Test1()
    {
        
    	CSC_Dispatch_Tool_Controller c = Init();

        test.startTest();
        c.GetAccountIndustry();
        c.GetBigAccount();
        c.GetAsc();
        c.GetRequestedDT();
        c.Assign();
        test.stopTest();
    }

    //需要有用户的City Area  '四川-成都市'的
    public static testMethod void GetAscTest()
    {
    	CSC_Dispatch_Tool_Controller c = Init();
    	c.wo.Province_Lookup__c = spcityList.get(0).Province_Name__c;
        c.wo.City_Lookup__c = spcityList.get(0).Id;
    	c.GetAsc();
    	System.debug('5:' + c.ascList.size());
    }

    //需要有用户的City Area 集合中的某一个的 '北京市-北京', '北京市-朝阳区', '北京市-海淀区', '北京市-西城区', '北京市-通州区', '天津市-天津市'的
    public static testMethod void GetAscTest2()
    {
    	CSC_Dispatch_Tool_Controller c = Init();
    	c.GetAsc();
    	System.debug('5:' + c.ascList.size());
    }

    public static void AssignTest()
    {
    	CSC_Dispatch_Tool_Controller c = Init();
    	c.wo.Subcase_Estimated_Task_Duration__c = 5;
    	c.Assign();
    	c.wo.Requested_Date__c = Datetime.newInstance(Date.newInstance(2017,2,14), Time.newInstance(15, 30, 0,0));
    	c.Assign();
    	c.GetAsc();
    	c.row = 0;
    	c.Assign();
    }

    public static testMethod void GetRequestedDTTest()
    {
    	CSC_Dispatch_Tool_Controller c = Init();
    	c.zone_value = '16h';
    	c.wo.Now__c = Datetime.newInstance(Date.newInstance(2017,2,12), Time.newInstance(15, 30, 0,0));
    	c.wo.Repair_Level__c = 'SBD';
    	c.GetRequestedDT();
    	c.wo.Repair_Level__c = 'NBD';
    	c.GetRequestedDT();
    	c.wo.Repair_Level__c = '5*13*4';
    	c.GetRequestedDT();
    	c.wo.Repair_Level__c = '5*9*4';
    	c.GetRequestedDT();
    	c.wo.Now__c = Datetime.newInstance(Date.newInstance(2017,2,14), Time.newInstance(15, 30, 0,0));
    	c.wo.Repair_Level__c = 'SBD';
    	c.GetRequestedDT();
    	c.wo.Repair_Level__c = 'NBD';
    	c.GetRequestedDT();
    	c.wo.Repair_Level__c = '5*13*4';
    	c.GetRequestedDT();
    	c.wo.Repair_Level__c = '5*9*4';
    	c.GetRequestedDT();
    }

    static CSC_Dispatch_Tool_Controller Init()
    {
    	WorkOrder wo=CSC_Assign_Controller_Test.GetWorkOrder();
        wo.Requested_Date__c=null;
        wo.Assign_User__c=userInfo.getUserId();
        wo.Subcase_Estimated_Task_Duration__c=null;
        wo.Province__c = 'Beijing';
        wo.City__c = '北京市';
        wo.Province_Lookup__c = cityList.get(0).Province_Name__c;
        wo.City_Lookup__c = cityList.get(0).Id;
        update wo;

        ApexPages.currentPage().getParameters().put('id', wo.Id);
        CSC_Dispatch_Tool_Controller c=new CSC_Dispatch_Tool_Controller();
        return c;
    }
}