H3CIPMSJAVA-20180830/src/objects/City__c.object
<CustomObject>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>江苏-常熟</fullName>
                </value>
                <value>
                    <fullName>江苏-常州</fullName>
                </value>
                <value>
                    <fullName>江苏-东台</fullName>
                </value>
                <value>
                    <fullName>江苏-淮安</fullName>
                </value>
                <value>
                    <fullName>江苏-淮阴</fullName>
                </value>
                <value>
                    <fullName>江苏-江阴</fullName>
                </value>
                <value>
                    <fullName>江苏-昆山</fullName>
                </value>
                <value>
                    <fullName>江苏-连云港</fullName>
                </value>
                <value>
                    <fullName>江苏-南京</fullName>
                </value>
                <value>
                    <fullName>江苏-南通</fullName>
                </value>
                <value>
                    <fullName>江苏-邳州</fullName>
                </value>
                <value>
                    <fullName>江苏-苏州</fullName>
                </value>
                <value>
                    <fullName>江苏-太仓</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>Province</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Chongqing</fullName>
                </value>
                <value>
                    <fullName>Fujian</fullName>
                </value>
                <value>
                    <fullName>Gansu</fullName>
                </value>
                <value>
                    <fullName>Guangdong</fullName>
                </value>
                <value>
                    <fullName>Guangxi</fullName>
                </value>
                <value>
                    <fullName>Guizhou</fullName>
                </value>
                <value>
                    <fullName>Hainan</fullName>
                </value>
                <value>
                    <fullName>Hebei</fullName>
                </value>
                <value>
                    <fullName>Heilongjiang</fullName>
                </value>
                <value>
                    <fullName>Henan</fullName>
                </value>
                <value>
                    <fullName>Hongkong</fullName>
                </value>
                <value>
                    <fullName>Hubei</fullName>
                </value>
                <value>
                    <fullName>Hunan</fullName>
                </value>
                <value>
                    <fullName>Jiangsu</fullName>
                </value>
                <value>
                    <fullName>Jiangxi</fullName>
                </value>
                <value>
                    <fullName>Jilin</fullName>
                </value>
                <value>
                    <fullName>Liaoning</fullName>
                </value>
                <value>
                    <fullName>Macao</fullName>
                </value>
                <value>
                    <fullName>Neimenggu</fullName>
                </value>
                <value>
                    <fullName>Ningxia</fullName>
                </value>
                <value>
                    <fullName>Qinghai</fullName>
                </value>
                <value>
                    <fullName>Shaanxi</fullName>
                </value>
                <value>
                    <fullName>Shandong</fullName>
                </value>
                <value>
                    <fullName>Shanghai</fullName>
                </value>
                <value>
                    <fullName>shanxi</fullName>
                </value>
                <value>
                    <fullName>shenzhen</fullName>
                </value>
                <value>
                    <fullName>Sichuan</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/UtilityTest.cls
/**************************************************************************************************
* Name: UtilityTest
* Object: 
* Purpose: 
* Utility 测试类
* Author: Hunter
* Create Date: 2016-11-21
***************************************************************************************************/
@istest
public class UtilityTest {
    public static testmethod void isMobileNoTest() {
		System.debug('result:'+Utility.isMobileNo('13436124669'));
		System.assertEquals(true, Utility.isMobileNo('13436124669'));
		System.assertEquals(true, Utility.isMobileNo('+86 13436124669'));
    }

	public static testmethod void ReturnPhoneTest() {
		System.debug('result:'+Utility.ReturnPhone('+86 13436124669', ''));
		System.assertEquals('+86 13436124669', Utility.ReturnPhone('13436124669',''));
		System.assertEquals('+86 13436124669', Utility.ReturnPhone('86 13436124669',''));
    }

    public static testmethod void getPicklistValuesTest() {
		test.startTest();
		Utility.getPicklistValues('WorkOrder','City__c');
		test.stopTest(); 
    }

    public static testmethod void getPicklistLabelValuesTest() {
		test.startTest();
		Utility.getPicklistLabelValues('WorkOrder','City__c');
		test.stopTest(); 
    }

    public static testmethod void getPicklistEntrysTest() {
		test.startTest();
		Utility.getPicklistEntrys('WorkOrder','City__c');
		test.stopTest(); 
    }

    public static testmethod void isPositiveEx0Test() {
		test.startTest();
		Utility.isPositiveEx0('55');
		test.stopTest(); 
    }

    public static testmethod void isPositiveTest() {
		test.startTest();
		Utility.isPositive('55');
		test.stopTest(); 
    }

    public static testmethod void ReturnPhoneTest1() {
		test.startTest();
		Utility.ReturnPhone('13432145551','abc');
		test.stopTest(); 
    }

    public static testmethod void ReturnPhoneTest2() {
		test.startTest();
		Utility.ReturnPhone('abc','+86 13432145551');
		test.stopTest(); 
    }

    public static testmethod void SlipWorkDaysTest() {
		test.startTest();
		Utility.SlipWorkDays(Date.newInstance(2017, 2, 10),4);
		test.stopTest(); 
    }

    public static testmethod void SlipWorkHoursTest() {
		test.startTest();
		Datetime initialTime = Datetime.newInstance(Date.newInstance(2017, 2, 10), Time.newInstance(14, 30, 0, 0));
		Time startTime = Time.newInstance(8, 30, 0, 0);
		Time endTime = Time.newInstance(17, 30, 0, 0);
		Utility.SlipWorkHours(initialTime, startTime, endTime,55);
		test.stopTest(); 
    }

    public static testmethod void GetPickListDependentOptionsTest() {
		test.startTest();
		Utility.GetPickListDependentOptions('WorkOrder','Province__c','City__c');
		test.stopTest(); 
    }


    public static testmethod void GetPickListControllingFiledValeTest() {
		test.startTest();
		Utility.GetPickListControllingFiledVale('WorkOrder','Province__c','City__c', '北京');
		test.stopTest(); 
    }

    public static testmethod void SubtractDateTest() {
		test.startTest();
		Datetime highDate = Datetime.newInstance(Date.newInstance(2017, 2, 10), Time.newInstance(14, 30, 0, 0));
		Datetime lowDate = Datetime.newInstance(Date.newInstance(2017, 1, 10), Time.newInstance(14, 30, 0, 0));
		Utility.SubtractDate(highDate, lowDate);
		test.stopTest(); 
    }

}