H3CIPMSJAVA-20180830/src/objects/Dispatch__c.object
<CustomObject>
    <fields>
        <fullName>EndDateTime__c</fullName>
        <label>EndDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <formula>DATEVALUE(EndDateTime__c)</formula>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <label>StartDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <formula>DATEVALUE(StartDateTime__c)</formula>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assign</fullName>
                </value>
                <value>
                    <fullName>Holiday</fullName>
                </value>
                <value>
                    <fullName>Accept</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DispatchToUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WorkOrder</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Dispatch</relationshipLabel>
        <relationshipName>DispatchToWorkOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dispatch</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Dispatch No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill_User__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Intermediate</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Blade Matrix</fullName>
                    <isActive>false</isActive>
                    <label>Blade Matrix</label>
                </value>
                <value>
                    <fullName>CCIE</fullName>
                    <isActive>false</isActive>
                    <label>CCIE</label>
                </value>
                <value>
                    <fullName>CCNA</fullName>
                    <isActive>false</isActive>
                    <label>CCNA</label>
                </value>
                <value>
                    <fullName>CCNP</fullName>
                    <isActive>false</isActive>
                    <label>CCNP</label>
                </value>
                <value>
                    <fullName>H3CNA</fullName>
                    <isActive>false</isActive>
                    <label>H3CNA</label>
                </value>
                <value>
                    <fullName>H3CNE</fullName>
                    <isActive>false</isActive>
                    <label>H3CNE</label>
                </value>
                <value>
                    <fullName>H3CSE-ROUTING &amp; SWITCHING</fullName>
                    <isActive>false</isActive>
                    <label>H3CSE-ROUTING &amp; SWITCHING</label>
                </value>
                <value>
                    <fullName>H3CSE-Storage</fullName>
                    <isActive>false</isActive>
                    <label>H3CSE-Storage</label>
                </value>
                <value>
                    <fullName>HP AIS-Network Infrastructure</fullName>
                    <isActive>false</isActive>
                    <label>HP AIS-Network Infrastructure</label>
                </value>
                <value>
                    <fullName>Trained</fullName>
                    <isActive>false</isActive>
                    <label>Trained</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Skill</label>
        <referenceTo>ProfileSkill</referenceTo>
        <relationshipLabel>Skill User</relationshipLabel>
        <relationshipName>SkillUserToSkill</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SkillUserToUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Skill User</label>
    <nameField>
        <displayFormat>SU-{00000}</displayFormat>
        <label>Skill User No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>City_Upper__c</fullName>
        <formula>UPPER(City)</formula>
        <label>City Upper</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Basic</fullName>
                </value>
                <value>
                    <fullName>Intermediate</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workgroup__c</fullName>
        <label>Workgroup</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WG-CSC_DL_ALPHA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_Networking</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_CA_VA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_Pro1</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_HPSD_Com</fullName>
                </value>
                <value>
                    <fullName>WG-TSCO_DL_ISS_Trade</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_MA_ISSG</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_HPSD CA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_DP_ISS</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_L2_Storage</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_OPS</fullName>
                </value>
                <value>
                    <fullName>WG-H3C_HZ_RD_HW</fullName>
                </value>
                <value>
                    <fullName>WG-H3C_HZ_RD_SW</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_PCI</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_WWXD</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_Value_YIGAO</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_DIGITALCHINA</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_ASIACOM</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_Value_NJSISUO</fullName>
                </value>
                <value>
                    <fullName>WG-GSD_BJ_RASM</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_HPSD_Ent</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_MCRSS</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_Pro2</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_ESupport</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_BCS</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_BLD</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_MA_ADMIN</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_DP_VA</fullName>
                </value>
                <value>
                    <fullName>WG-CSC_DL_L2_ISS</fullName>
                </value>
                <value>
                    <fullName>WG-FD_SO_ISS_NJSISUO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Province__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>安徽-安庆</fullName>
                </value>
                <value>
                    <fullName>安徽-蚌埠</fullName>
                </value>
                <value>
                    <fullName>安徽-亳州</fullName>
                </value>
                <value>
                    <fullName>安徽-巢湖</fullName>
                </value>
                <value>
                    <fullName>安徽-池州</fullName>
                </value>
                <value>
                    <fullName>安徽-滁州</fullName>
                </value>
                <value>
                    <fullName>安徽-阜阳</fullName>
                </value>
                <value>
                    <fullName>安徽-合肥</fullName>
                </value>
                <value>
                    <fullName>安徽-淮北</fullName>
                </value>
                <value>
                    <fullName>安徽-淮南</fullName>
                </value>
                <value>
                    <fullName>安徽-黄山</fullName>
                </value>
                <value>
                    <fullName>安徽-六安</fullName>
                </value>
                <value>
                    <fullName>安徽-马鞍山</fullName>
                </value>
                <value>
                    <fullName>安徽-其它城市</fullName>
                </value>
                <value>
                    <fullName>安徽-铜陵</fullName>
                </value>
                <value>
                    <fullName>安徽-芜湖</fullName>
                </value>
                <value>
                    <fullName>安徽-宣城</fullName>
                </value>
                <value>
                    <fullName>江苏-常熟</fullName>
                </value>
                <value>
                    <fullName>江苏-常州</fullName>
                </value>
                <value>
                    <fullName>江苏-东台</fullName>
                </value>
                <value>
                    <fullName>江苏-淮安</fullName>
                </value>
                <value>
                    <fullName>江苏-淮阴</fullName>
                </value>
                <value>
                    <fullName>江苏-江阴</fullName>
                </value>
                <value>
                    <fullName>江苏-昆山</fullName>
                </value>
                <value>
                    <fullName>江苏-连云港</fullName>
                </value>
                <value>
                    <fullName>江苏-南京</fullName>
                </value>
                <value>
                    <fullName>江苏-南通</fullName>
                </value>
                <value>
                    <fullName>江苏-邳州</fullName>
                </value>
                <value>
                    <fullName>江苏-苏州</fullName>
                </value>
                <value>
                    <fullName>江苏-太仓</fullName>
                </value>
                <value>
                    <fullName>深圳市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <label>Requested Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Skill</label>
        <referenceTo>ProfileSkill</referenceTo>
        <relationshipLabel>工作订单</relationshipLabel>
        <relationshipName>WorkOrderToSkill</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_Dispatch_ControllerTest.cls
/**************************************************************************************************
* Author: Hunter
* Create Date: 2016-11-28
*****************************************************************************************/
@isTest(seealldata=true)
private class CSC_Dispatch_ControllerTest{

	public static testMethod void Test1()
    {
    	CSC_Dispatch_Controller c = Init();
        test.startTest();
        c.Search();
        c.Assign();
        c.Close();
        test.stopTest();
    }

    public static testMethod void SearchTest()
    {
    	CSC_Dispatch_Controller c = Init();
    	c.allTimeIndicator = true;
    	c.searchType = true;
        test.startTest();
        c.Search();
        test.stopTest();
    }

    public static testMethod void ShowDispatchTest()
    {
    	CSC_Dispatch_Controller c = Init();
    	User u = [Select Id,Name,City_Upper__c From User Where IsActive=True
                            And (Profile.Name='CSC&FST CE') Limit 1];
    	Date dt = c.wo.Requested_Date__c.date();
    	initDispatch(c,u);
    	List<Dispatch__c> listD = [Select User__r.Name,User__r.Workgroup__c,User__r.City_Upper__c,StartDateTime__c,EndDateTime__c,Status__c,User__c,WorkOrder__c,WorkOrder__r.Work_Order_Name__c From Dispatch__c
                                    Where User__c =:u.Id And (StartDate__c=:dt Or EndDate__c=:dt) Order By User__c,StartDateTime__c];

        test.startTest();
        c.ShowDispatch(listD, dt);
        test.stopTest();
    }

    public static testMethod void GetEntityByUserTest()
    {
    	CSC_Dispatch_Controller c = Init();
    	User u = [Select Id From User Where IsActive=True
                            And (Profile.Name='CSC&FST CE') Limit 1];
        Date dt = c.wo.Requested_Date__c.date();
        Date qstart = dt.addDays(-5);
        Date qend = dt.addDays(5);
        initDispatch(c,u);
    	test.startTest();
        c.GetEntityByUser(u.Id, qstart, qend);
        test.stopTest();
    }

    public static testMethod void GetAllEntityTest()
    {
    	CSC_Dispatch_Controller c = Init();
    	c.allTimeIndicator = true;
    	c.searchType = true;
        test.startTest();
        c.GetAllEntity();
        c.wo.Requested_Date__c = null;
        c.GetAllEntity();
        c.wo.City__c='';
        c.GetAllEntity();
        test.stopTest();
    }

    public static testMethod void GetAllEntityTest2()
    {
    	CSC_Dispatch_Controller c = Init();
    	c.allTimeIndicator = true;
    	c.searchType = true;

    	User u = [Select City_Upper__c,Id,Name From User Where IsActive=True
                            And (Profile.Name='CSC&FST CE') And City_Upper__c =:c.wo.City__c limit 1];
    	initDispatchForGetEntity(c, u);
        test.startTest();
        c.GetAllEntity();
        test.stopTest();
    }

    public static testMethod void GetEntityTest()
    {
    	CSC_Dispatch_Controller c = Init();
    	//使用如下语句反查出库里有的skill
    	//Select User__c, Skill__r.name, Level__c From Skill_User__c where User__r.City_Upper__c='深圳市' and User__r.Profile.Name='CSC&FST CE'
    	c.wo.Skill_Name__c  = 'Blade - IA32';

        test.startTest();
        c.GetEntity();
        c.wo.Level__c = null;
        c.GetEntity();
        c.wo.Requested_Date__c = null;
        c.GetEntity();
        c.wo.City__c='';
        c.GetEntity();
        test.stopTest();
    }

	static CSC_Dispatch_Controller Init()
    {
    	WorkOrder wo=CSC_Assign_Controller_Test.GetWorkOrder();
        wo.Requested_Date__c= Datetime.newInstanceGmt(Date.newInstance(2017,2,15), Time.newInstance(15,0,0,0));
        wo.Assign_User__c=userInfo.getUserId();
        wo.Subcase_Estimated_Task_Duration__c=null;
        wo.Province__c = 'shenzhen';
        wo.City__c = '深圳市';
        wo.Level__c = 'Basic';
        update wo;

        ApexPages.currentPage().getParameters().put('id', wo.Id);
        CSC_Dispatch_Controller c=new CSC_Dispatch_Controller(null);
        c.allTimeIndicator = false;
        c.searchType = false;

        return c;
    }

    static void initDispatchForGetEntity(CSC_Dispatch_Controller c, User u)
    {
    	List<Dispatch__c> listD = new List<Dispatch__c>();
    	Date dt = c.wo.Requested_Date__c.date();

    	Dispatch__c d = new Dispatch__c();
    	d.Status__c = 'Assign';
    	d.User__c = u.Id;
    	d.WorkOrder__c = c.wo.Id;
    	d.StartDateTime__c = Datetime.newInstanceGmt(dt, Time.newInstance(10, 0, 0,0));
    	d.EndDateTime__c = Datetime.newInstanceGmt(dt, Time.newInstance(11, 0, 0,0));
    	listD.add(d);

    	insert ListD;
    }

    static void initDispatch(CSC_Dispatch_Controller c, User u)
    {
    	List<Dispatch__c> listD = new List<Dispatch__c>();
    	Date dt = c.wo.Requested_Date__c.date();
    	
    	Dispatch__c d = new Dispatch__c();
    	d.Status__c = 'Assign';
    	d.User__c = u.Id;
    	d.WorkOrder__c = c.wo.Id;
    	d.StartDateTime__c = Datetime.newInstanceGmt(dt, Time.newInstance(10, 0, 0,0));
    	d.EndDateTime__c = Datetime.newInstanceGmt(dt, Time.newInstance(11, 0, 0,0));
    	listD.add(d);

    	d = new Dispatch__c();
    	d.Status__c = 'Holiday';
    	d.User__c = u.Id;
    	d.WorkOrder__c = c.wo.Id;
    	d.StartDateTime__c = Datetime.newInstanceGmt(dt, Time.newInstance(12, 0, 0,0));
    	d.EndDateTime__c = Datetime.newInstanceGmt(dt, Time.newInstance(13, 0, 0,0));
    	listD.add(d);

    	d = new Dispatch__c();
    	d.Status__c = 'Accept';
    	d.User__c = u.Id;
    	d.WorkOrder__c = c.wo.Id;
    	d.StartDateTime__c = Datetime.newInstanceGmt(dt, Time.newInstance(13, 0, 0,0));
    	d.EndDateTime__c = Datetime.newInstanceGmt(dt, Time.newInstance(14, 0, 0,0));
    	listD.add(d);

    	d = new Dispatch__c();
    	d.Status__c = 'Reject';
    	d.User__c = u.Id;
    	d.WorkOrder__c = c.wo.Id;
    	d.StartDateTime__c = Datetime.newInstanceGmt(dt, Time.newInstance(14, 0, 0,0));
    	d.EndDateTime__c = Datetime.newInstanceGmt(dt, Time.newInstance(15, 0, 0,0));
    	listD.add(d);

    	insert ListD;
    }
}