H3CIPMSJAVA-20180830/src/objects/Dispatch__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assign</fullName>
                </value>
                <value>
                    <fullName>Holiday</fullName>
                </value>
                <value>
                    <fullName>Accept</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WorkOrder</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Dispatch</relationshipLabel>
        <relationshipName>DispatchToWorkOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dispatch</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Dispatch No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ref_Value__c.object
<CustomObject>
    <label>Reference Value</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>CSC_Action_Type__c</fullName>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DEF</fullName>
                </value>
                <value>
                    <fullName>HP Onsite</fullName>
                </value>
                <value>
                    <fullName>Partner Onsite</fullName>
                </value>
                <value>
                    <fullName>Callback</fullName>
                </value>
                <value>
                    <fullName>CPR-Elevation</fullName>
                </value>
                <value>
                    <fullName>CPR-ESC-CSM</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Ent Exception</fullName>
                </value>
                <value>
                    <fullName>FMN CSO</fullName>
                </value>
                <value>
                    <fullName>FMN CSO AutoRelease</fullName>
                </value>
                <value>
                    <fullName>Logistics Order</fullName>
                </value>
                <value>
                    <fullName>Transfer to CC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CSC_Subcase_Delay_Code__c</fullName>
        <label>WorkOrder Delay Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0-Response Met</fullName>
                </value>
                <value>
                    <fullName>1-Returned to office for resource</fullName>
                </value>
                <value>
                    <fullName>2-Parts Issue</fullName>
                </value>
                <value>
                    <fullName>3-No CE Resources Available</fullName>
                </value>
                <value>
                    <fullName>4-CSO sent to wrong CE</fullName>
                </value>
                <value>
                    <fullName>5-Travel Delay</fullName>
                </value>
                <value>
                    <fullName>6-No Trained/Qualified CE Available</fullName>
                </value>
                <value>
                    <fullName>7-Subcase recd Late from Call Center</fullName>
                </value>
                <value>
                    <fullName>8-Customer caused Delay</fullName>
                </value>
                <value>
                    <fullName>9-Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entitle_Guaranteed_DT__c</fullName>
        <formula>Case.CSC_Entitle_Guaranteed_DT__c</formula>
        <label>Entitle Guaranteed D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IsAccepted__c</fullName>
        <description>When CE clicked the accept button on the ice app, the flag change the value to Accepted.</description>
        <label>IsAccepted</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Refused</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Latested_DT__c</fullName>
        <formula>Case.CSC_Latested_DT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Latested D/T</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Ref_Resolution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WorkOrder Resolution</label>
        <referenceTo>Ref_Value__c</referenceTo>
        <relationshipLabel>Work Orders (Subcase Resolution)</relationshipLabel>
        <relationshipName>Work_Orders_Resolution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ref_Workorder_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Ref_Value__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Work Order Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ref_Value__c</referenceTo>
        <relationshipLabel>Work Orders (Workorder Type)</relationshipLabel>
        <relationshipName>Work_Orders_Work_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <label>Requested Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requested_Guaranteed_Date__c</fullName>
        <label>Requested Guaranteed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Close_Date__c</fullName>
        <label>Close Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Duration__c</fullName>
        <formula>Subcase_Onsite_Fixed_Date__c - Subcase_Onsite_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>WorkOrder Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subcase_Employee_Closer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WorkOrder Employee Closer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SUBCASE_USER_CLOSER</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcase_Enroute_Date__c</fullName>
        <label>WorkOrder Enroute Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Estimated_Task_Duration__c</fullName>
        <label>WorkOrder Estimated Task Duration</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Fixed_Date__c</fullName>
        <label>WorkOrder Onsite Repair Fixed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Start_Date__c</fullName>
        <label>WorkOrder Onsite Repair Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Onsite_Stop_Date__c</fullName>
        <label>WorkOrder Onsite Repair Stop Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subcase_Repair_Class_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WorkOrder Repair Class Code RCC</label>
        <referenceTo>Ref_Value__c</referenceTo>
        <relationshipLabel>工作订单</relationshipLabel>
        <relationshipName>WorkOrderToRepairClass</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcase_Service_Category__c</fullName>
        <formula>TEXT(Subcase_Repair_Class_Code__r.Srvc_Cat__c)</formula>
        <label>WorkOrder Service Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcase_Travel_Time__c</fullName>
        <description>Subcase_Onsite_Start_Date__c - Subcase_Enroute_Date__c</description>
        <formula>(Subcase_Onsite_Start_Date__c - Subcase_Enroute_Date__c)*24</formula>
        <label>WorkOrder Travel Time</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Order_Name__c</fullName>
        <externalId>true</externalId>
        <label>Work Order Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_App_IsCEAccepted.cls
/**************************************************************************************************
* Name: CSC_App_IsCEAccepted
* Object: WorkOrder
* Purpose: 
* APP获取WorkOrder数据.此接口用于手机获取新任务/待办任务列表/已办任务
* Author: Wang, Maccus Bo
* Create Date: 2016-04-22
***************************************************************************************************/

@RestResource(urlMapping='/IsCEAccepted/*')
global without sharing class CSC_App_IsCEAccepted {
    
    public class AppInput {
        public String WorkOrderId;
        //0: Accepted; 1:Refused
        public Integer IsAccepted;
        public String Description;
    }

    public class AppOut {
        //0: Success; 1:Error
        public Integer Result;
        public String WorkOrderId;
        public String WorkOrderStatus;
        public String Description;
    }

    @HttpPost
    global static String doPost() {
System.debug('User:' + UserInfo.getName());
        RestRequest req = RestContext.request;
system.debug('body : ' + req.requestBody.tostring());
        AppInput input = (CSC_App_IsCEAccepted.AppInput)JSON.deserialize(req.requestBody.tostring(), CSC_App_IsCEAccepted.AppInput.class);
        AppOut out = new AppOut();
        try {
            List<WorkOrder> orderList = [SELECT OwnerId,Work_Order_Name__c,Id, WorkOrderNumber, AccountId, Address, AssetId, CaseId,
                CreatedById, CreatedDate, Description, Discount, EndDate, status,
                EntitlementId,CSC_Action_Type__c, Entitle_Guaranteed_DT__c, IsAccepted__c, Latested_DT__c,
                Requested_Date__c, Requested_Guaranteed_Date__c, Subcase_Close_Date__c, CSC_Subcase_Delay_Code__c,
                Subcase_Duration__c, Subcase_Employee_Closer__c, Subcase_Enroute_Date__c, Subcase_Estimated_Task_Duration__c,
                Subcase_Onsite_Fixed_Date__c, Subcase_Onsite_Start_Date__c, Subcase_Onsite_Stop_Date__c,
                Subcase_Repair_Class_Code__c, Ref_Resolution__r.Name, Subcase_Service_Category__c,
                Subcase_Travel_Time__c, Ref_Workorder_Type__r.Name,UserRecordAccess.HasEditAccess
                FROM WorkOrder WHERE Id = :input.WorkOrderId];

            if (orderList.size() > 0) {
                if(!orderList[0].UserRecordAccess.HasEditAccess){
                    /*out.Result = 1;
                    out.WorkOrderId = input.workorderId;
                    out.Description = 'You cannot modify this record!';
                    String retMsg = JSON.serialize(out);
                    System.debug('retMsg:' + retMsg);
                    return retMsg;*/
                }
                else{
                    orderList[0].IsAccepted__c = input.IsAccepted == 0 ? 'Accepted' : 'Refused';
                    update orderList;
                    
                    /**************************************************************************************************
                    * Purpose: 
                    * 更新Dispatch数据，并插入Task提醒DP
                    * Author: Ben
                    * Create Date: 2016-11-22
                    ***************************************************************************************************/
                    //Start
                    List<Dispatch__c> dList=[Select Id,CreatedById From Dispatch__c Where WorkOrder__c=:orderList[0].Id];
                    if (dList !=null && !dList.isEmpty()){
                        for(Dispatch__c d:dList)
                        {
                            if(orderList[0].IsAccepted__c=='Accepted')
                            {
                                d.Status__c='Accept';
                            }
                            else if(orderList[0].IsAccepted__c=='Refused')
                            {
                                d.Status__c='Reject';
                            }
                        }
                        update dList;
                        
                        Task t=new Task();
                        t.OwnerId=dList[0].CreatedById;
                        system.debug('CreateByID' + dList[0].CreatedById);
                        t.ActivityDate=date.today();
                        t.WhatId=orderList[0].Id;
                        t.Internal__c = True;
                        t.status = 'open';
                        t.IsReminderSet = true;
                        t.ReminderDateTime = System.now();
                        Account a = [SELECT Name,Id From Account WHERE Id=:orderList[0].AccountId][0];
                        User u = [SELECT Name,Id From User WHERE Id=:orderList[0].OwnerId][0];
                        t.Subject='Workorder：'+orderList[0].Work_Order_Name__c+a.Name 
                                    +'状态被'+u.Name+'更新为：'+orderList[0].IsAccepted__c;
                        insert t;
                    }
                    //End 
                                       
                    out.Result = 0;
                    out.WorkOrderId = input.WorkOrderId;
                    out.WorkOrderStatus = orderList[0].IsAccepted__c;
                    out.Description = 'Success';
                }
            }
            else {
                out.Result = 1;
                out.WorkOrderId = input.WorkOrderId;
                out.Description = 'Fetch workorder error! WorkOrderId is wrong';
            }
        }
        catch(Exception ex) {
            out.Result = 1;
            out.WorkOrderId = input.WorkOrderId;
            out.Description = ex.getMessage();
        }

        String retMsg = JSON.serialize(out);
System.debug('retMsg:' + out);
        return retMsg;
    }
}