H3CIPMSJAVA-20180830/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Competitor__c</fullName>
        <label>Competitor</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/objects/Opportunity_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Competitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Competitor</relationshipLabel>
        <relationshipName>Opportunity_Competitor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Competitor</relationshipLabel>
        <relationshipName>Opportunity_Competitor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>业务机会竞争对手</label>
    <nameField>
        <displayFormat>OC-{000000}</displayFormat>
        <label>Opportunity Competitor No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/AddCompetitorsControllerTest.cls
@istest(seealldata=true)
public class AddCompetitorsControllerTest {
    public static testmethod void testAddCompetitorsController() {
    
        Opportunity o = [select id from Opportunity limit 1];
        Account a = [select id from Account limit 1];
        Opportunity_Competitor__c oc = new Opportunity_Competitor__c(); 
        oc.Competitor__c = a.id;
        oc.Opportunity__c = o.id;

        AddCompetitorsController acc = new AddCompetitorsController(new ApexPages.StandardController(oc));
        acc.oppId= o.id;
        acc.competitorList = new List<Opportunity_Competitor__c>();
        acc.competitorList.add(oc);
        acc.Save();
        acc.Cancel();
    }
}