H3CIPMSJAVA-20180830/src/objects/Parts__c.object
<CustomObject>
    <label>Support BOM</label>
    <nameField>
        <label>Spare Part No</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parts_Order__c.object
<CustomObject>
    <fields>
        <fullName>Offered_Parts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offered Parts</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Parts__c.General_Product__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Parts__c</referenceTo>
        <relationshipLabel>Parts Order (Offered Parts)</relationshipLabel>
        <relationshipName>Offered_To_Parts_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_Plant__c</fullName>
        <label>Ship Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Back Ordered</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>POD</fullName>
                </value>
                <value>
                    <fullName>Recommand</fullName>
                    <default>true</default>
                    <label>Recommand</label>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>Send Update</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tracking__c</fullName>
        <label>Tracking</label>
        <type>TextArea</type>
    </fields>
    <label>Parts Order</label>
    <nameField>
        <label>Parts Order Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/CSC_SPMS_UpdateOrderStatus.cls
/**************************************************************************************************
* Name: CSC_SPMS_UpdateOrderStatus
* Object: Case
* Purpose: 
* SPMS端，备件状态更新时，触发SFDC端的接口，更新SFDC的备件状态
* Return Msg:
*  <Bool,msg>
* Author: Chen, Xiaoqian
* Create Date: 2016-11-17
* *************************************************************************************************
* Edit Date: 2016-12-12 By Xiaoqian 
* Edit No: ed1
* 给方法添加异常处理
***************************************************************************************************/
@RestResource(urlMapping='/UpdateOrderStatus/*')
global with sharing class CSC_SPMS_UpdateOrderStatus {

    public class AppInput{
        public String SALES_ORDER;
        public String PART_NUMBER;
        public String PLANT;
        public String PART_STATUS;
        public String PART_ORDER_NUMBER;
        public String TRACKING;
        public Datetime ORDER_DATETIME;
    }

    //输出
    global class AppOut {
        //true: Success; false:Error
        public Boolean rst;
        public String rstMsg;

        public AppOut(){
            new AppOut(true,'');
        }

        public AppOut(Boolean rst, String rstMsg){
            this.rst = rst;
            this.rstMsg = rstMsg;
        }
    }

    public CSC_SPMS_UpdateOrderStatus() {
    }

    @HttpPost
    global static AppOut doPost() {

        RestRequest req = RestContext.request;

        //ed1 start
        AppInput input = null;

        String reqString = req.requestBody.tostring();
        System.debug('receive requsted string: '+ reqString);
        
        try{
            input = (CSC_SPMS_UpdateOrderStatus.AppInput)JSON.deserialize(reqString, CSC_SPMS_UpdateOrderStatus.AppInput.class);
        } catch(JSONException e){
            System.debug(e.getMessage());
            return new AppOut(false, e.getMessage());
        }
        //ed1 end
        

        try{
            if(String.isBlank(input.PART_NUMBER)){
                return new AppOut(false,'partNumber should not be empty!');
            }

            if(String.isBlank(input.PART_ORDER_NUMBER)){
                return new AppOut(false,'Part Order number should not be empty!');
            }

            // 备件号是否存在
            Parts__c part = [SELECT Id,Name FROM Parts__c WHERE Name =: input.PART_NUMBER limit 1];
            if (part ==null || String.isEmpty(part.Id)){
                return new AppOut(false,'The Parameter of part number is null!');
            }

            Parts_Order__c partOrder = [SELECT Ship_Plant__c, Name, Status__c, Tracking__c,Offered_Parts__r.Name,Offered_Parts__c FROM Parts_Order__c where Name =: input.PART_ORDER_NUMBER];

            partOrder.Offered_Parts__c = part.Id;

            if (!String.isEmpty(input.PART_STATUS)){
                partOrder.Status__c = input.PART_STATUS;
            }
            
            if (!String.isEmpty(input.PLANT)){
                partOrder.Ship_Plant__c = input.PLANT;
            }

            if (!String.isEmpty(input.TRACKING)){
                partOrder.Tracking__c = input.TRACKING;
            }

            update partOrder;

        }catch(Exception ex) {
            return new AppOut(false,ex.getMessage());
        }

        return new AppOut(true,'updated successfully!');
    }
}