H3CIPMSJAVA-20180830/src/objects/Related_Link__mdt.object
<CustomObject>
    <fields>
        <fullName>FileName__c</fullName>
        <label>FileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>IPMS Related Link</label>
</CustomObject>

H3CIPMSJAVA-20180830/src/classes/homeController.cls
/*
 * @Author:Chen
 * @Description:主页组件控制器（相关链接）
*/
public class homeController {
    @AuraEnabled
    public static List<Related_Link__mdt> queryURL(){
      List<Related_Link__mdt> rlList = [SELECT Id, MasterLabel,DeveloperName, URL__c, FileName__c FROM Related_Link__mdt Order By DeveloperName  LIMIT 8 ];
        if(rlList != NULL & rlList.size()>0){
            return rlList;
        }
        System.debug('****'+rlList);
        return NULL;
    }
}